### ISSUE TITLE
As a data editor, I want metadata from the geniza spreadsheet indexed into Solr so I can run more advanced searches to find geniza materials.

### ISSUE THREAD

**Issue by kmcelwee** [Princeton-CDH/geniza#1]
See `index_incipits.py` in `pemm-scripts`

**Comment by kmcelwee** [comment]
Geniza spreadsheet has ~5 Unnamed columns with various notes.
Columns and count of non-null items in each column
```
PGPID: 29404
Technical notes (optional): 11873
Library: 29283
Shelfmark - Current: 29404
Link to image: 1410
Shelfmark - Historical (optional): 312
Multifragment (optional): 16
Recto or verso (optional): 754
Text-block (optional): 82
Type: 14623
Tags: 19712
Joins: 731
Description: 29331
Editor(s): 10241
Translator (optional): 50
Notes2 (optional): 604
Input by (optional): 17505
Date entered (optional): 19077
Language (optional): 8479
Unnamed: 19: 59
Unnamed: 20: 7
Unnamed: 21: 10
Unnamed: 22: 5
Unnamed: 23: 0
Unnamed: 24: 1
```

**Comment by kmcelwee** [comment]
PGPID is unique except for one ID, `2771` which occurs twice

**Comment by kmcelwee** [comment]
Tags use a hashtag system, but whitespace is included, to appropriately get a tag for each entry, I recommend something along the lines of:
```python
tags_a = [tag.strip() for tag in tags_s.split('#') if x != '']
```

**Comment by kmcelwee** [comment]
### "Language (optional)"
Languages are mixed with notes (e.g. `'Yes.',`, `Image missing`), and separated by semicolon. The same script as for tags above can be used to separate them.

There are 135 unique items within this column

There are multiple versions of the same language: 
```
'Judaeo-Arabic',
 'Judaeo-Arabic (? )',
 'Judaeo-Arabic (?)',
 'Judaeo-Arabic (?) (Tiberian vocalisation)',
 'Judaeo-Arabic (Arabic vocalisation)',
 'Judaeo-Arabic (Tiberian vocalisation)',
 'Judaeo-Arabic (isolated Arabic vocalisation and diacritics)',
 'Judaeo-Arabic (isolated Arabic vocalisation)',
 'Judaeo-Arabic (isolated Tiberian vocalisation)',
 'Judaeo-Arabic (isolated vocalisation)',
 'Judaeo-Arabic (sporadic Arabic vocalisation)',
 'Judaeo-Arabic (sporadic Tiberian vocalisation)',
 'Judaeo-Arabic (with Arabic vocalisation)',
 'Judaeo-Arabic commentary on Isaiah 54:1 and 1 Samuel 1:11',
 'Judaeo-Arabic(?)',
```
We may want to collapse this column with tags.

**Comment by kmcelwee** [comment]
### "Shelfmark - Current"
There are 692 non-unique values in this column, presumably they are joins?

**Comment by kmcelwee** [comment]
### "Link to Image"
Looks good! Almost verything is a Cambridge link (e.g. https://cudl.lib.cam.ac.uk/view/MS-TS-NS-J-00029/1) Otherwise two google drive links: 
https://drive.google.com/file/d/0B2W9ljYaFP4mOUY0d01JYnFiYlE/view?usp=sharing
https://drive.google.com/file/d/0B2W9ljYaFP4mQzZBZmlsU2RwclE/view?usp=sharing

**Comment by kmcelwee** [comment]
### "Recto or verso (optional)"
Unique values
```
nan
recto
recto and verso
verso
unknown
```

**Comment by kmcelwee** [comment]
### Type
A very consistent column, especially considering its size! Semicolon delimited, here are all unique types:
```
Letter
Literary
Letter or Literary
List or table
State
Unknown
Legal
Paraliterary
```

**Comment by kmcelwee** [comment]
### "Unnamed: 19"

```python
df.groupby('Unnamed: 19')['Unnamed: 19'].count().sort_values(ascending=False)
```

outputs value and count:
```
Unnamed: 19
Post to PGP                                                     33
n                                                                6
y (v)                                                            2
Goitein card for this document is under 2739.12                  1
ENA 2727.11a                                                     1
ENA 2727.11d                                                     1
ENA 2727.23a                                                     1
Goitein Card ENA 4011.50                                         1
Goitein card ENA 4011.40                                         1
Goitein card ENA 4100.4                                          1
Goitein card for ENA 4011.47                                     1
Goitein card tothis number describing ena 4011.30                1
Goitein card to this number describes another document           1
oded                                                             1
NO SUCH NUMBER                                                   1
Partly transleted in Goitein, Letters under ENA 2739.16          1
SHOULD BE 9a                                                     1
We are not finding this in the the library's finding aid         1
We are not finding this in the the library's finding aid (?)     1
described in Goitein card ENA 4011.33 + 3a                       1
Addenda to IB IV                                                 1
```

**Comment by kmcelwee** [comment]
### Joins
A `+` delimited list of shelfmarks. We have the opportunity to link back to our own dataset: of the 785 unique shelfmarks listed in the Join column, only 77 do not match up to values in `Shelfmark - Current`.

**Comment by kmcelwee** [comment]
- [ ] Remove pandas. We'll separate out any kind of testing / cleaning.

**Comment by rlskoeser** [comment]
We have a script configured to update the search prototype index based on the PGP metadata spreadsheet. You're already testing this indirectly by testing the search on #7 , but please check the indexing a little more specifically:

- [ ] the total number of records match (if you can easily compare spreadsheet total from reported total on the search)
- [ ] data from the fields matches the spreadsheet (check a few records; make sure to check some with tags, some with mixed language in the descriptions)
- [ ] changes made in the spreadsheet appear in the search after ~1 hour (it's currently set to index at 5 minutes after every hour)

We're currently indexing from the production spreadsheet, and obviously you don't want to make changes just for testing this. If there is existing data work going on that you can use to test, that's great; otherwise, we could make a copy of the spreadsheet and configure the index to pull from that while we're testing. Let us know what would work best.

**Comment by sluescher** [comment]
Are all fields game now? For example, is language also included?

Testing for number of records match results a bit difficult as the search term could be in tags, description or editor/translator, or any of the combinations. I can write a python script for it, but would have to move it to Wednesday or Thursday.

Data from the fields matches the spreadsheet. Tags, description, library, shelf mark, type. Arabic and Hebrew are reflected as in the metadata sheet.

While checking the fields above, I noticed that in one description a word was in orange. In the metadata sheet it is written as "<em>instead</em>" which in the PGP is translated as _italics_.
<img width="1181" alt="OrangeWord" src="https://user-images.githubusercontent.com/30683720/97231204-8997a880-17b1-11eb-809b-89614c6a648d.png">


In terms of changes made in the spreadsheet. What's the best thing to do? Add a new line with a fake fragment? Change a description?

**Comment by rlskoeser** [comment]
@sluescher please don't write any python to test this! I just wanted a check of the total unfiltered results against what's in the spreadsheet to make sure we're not missing any records.

I can give you access to our test Solr index if you want to see what the indexed data looks like there.

Good to know about the possibility of formatting in descriptions! I don't know why it's showing up as orange. Are there other formatting conventions? 

Not sure what to do about changes — I don't think you should add fake data or make changes for testing. Maybe we can ignore that one for now and revisit if there's a problem.

**Comment by sluescher** [comment]
As long as I can't mess up anything, happy to see the indexed data in Solr.

Formatting: there are some words Alan formatted to be bold (for example, PGPID [30597](https://test-geniza.cdh.princeton.edu/?keywords=30597)). He added < b > and </ b >. I think that's all, but we can ask Alan.

**Comment by sluescher** [comment]
Can this issue be closed? I have checked out Solr (it looks very cool).

**Comment by rlskoeser** [comment]
@sluescher thanks for following up, and thanks for checking out Solr! Let's go ahead and close it.
