### ISSUE TITLE
As a content editor, I want new and revised transcriptions available for search immediately so that changes and new content are all available to all site users.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#1000]
## testing notes

- [x] add and edit a handful of transcriptions as described in #1002 and #913
- [x] go to the public site search and search for the text of the transcriptions you added/edited, and confirm it brings up the document(s) you transcribed successfully

## dev notes

- [x] revise document index data to pull transcription content from annotations 
- [x] add a new signal handler to reindex documents when annotations associated with them are changed or added (maybe via footnote / scholarship record?)
- [x] signal handler to reindex document when annotation changes but footnote does not

**Comment by richmanrachel** [comment]
@rlskoeser - we're both getting this weird pop up in the transcription editor (which we can close and work around), but just fyi:
<img width="1027" alt="image" src="https://user-images.githubusercontent.com/68028846/187286130-627ade57-0b48-41ec-a162-45984cdd8626.png">

**Comment by richmanrachel** [comment]
The auto zoom is also turned on, and so we're not seeing the boxes when we hold the shift key down to try to create regions.

**Comment by richmanrachel** [comment]
The search is working immediately and correctly! Only had time to test with one doc so far, but I think it's good.

**Comment by rlskoeser** [comment]
thanks for alerting me to the Tiny editor warning! I thought I had it configured with the correct API key and the domain listed, will investigate

**Comment by richmanrachel** [comment]
I would like to retest once it's easier for me to add new transcriptions. This is working for editing existing  transcriptions.

**Comment by richmanrachel** [comment]
@rlskoeser - I had the same trouble with drawing boxes at first. After a hard refresh it worked, but sometimes it kept wanting to move the box around as I zoomed in to try to see the text better. The search is still updating automatically!

**Comment by kseniaryzhova** [comment]
@rlskoeser I'm able to draw the boxes after a hard refresh and it doesn't move around when I zoom in. However, if I zoom in, the zoom bar at the top of the document disappears. I can still successfully zoom in and out with my mousepad. 
![image](https://user-images.githubusercontent.com/105385128/188002376-9a10482e-074f-4f6e-b884-7b31e322cb41.png)
https://test-geniza.cdh.princeton.edu/en/documents/8820/transcribe/933/

**Comment by richmanrachel** [comment]
@rlskoeser - should I close and create a new issue for the zoom problems?

**Comment by rlskoeser** [comment]
@richmanrachel yes, please do
