### ISSUE TITLE
As a content editor, I want to create a new transcription linked to new or existing scholarship records so I can document its source and authorship.

### ISSUE THREAD

**Issue by blms** [Princeton-CDH/geniza#1002]
## testing notes

From a document detail page, choose "add a new transcription".

- [x] you should be prompted to search for and select the source for the transcription you want to add
- [x] once you choose and submit the form, you should be on the transcription editor page and able to start adding transcription content
- [x] after adding the transcription, you should see "edit X's transcription" on the document details page above "add a new transcription" (may need a hard refresh)

## dev notes

Spun off from #913 

  - [x] prompt editor to choose an existing scholarship record to attach the annotations to; we should use existing django autocomplete functionality if at all possible (maybe use is a minimal admin model form?); link to source list in admin to create a new source if there is not already an appropriate one

**Comment by richmanrachel** [comment]
Sorry @rlskoeser - this needs to be reopened. This works for all the documents that have images and/or existing transcriptions. But there is no prompt to create a transcription for documents with neither image nor transcription:
https://test-geniza.cdh.princeton.edu/admin/corpus/document/26619/change/?_changelist_filters=textblock__fragment__iiif_url__isempty%3D1%26transcription%3Dno

**Comment by richmanrachel** [comment]
I'm not able to edit this transcription for a document without an image either (it lets me into the editor, but I can't edit): https://test-geniza.cdh.princeton.edu/en/documents/4744/transcribe/7/

**Comment by richmanrachel** [comment]
I'm also having trouble drawing boxes (I think because of the auto zoom as I mentioned somewhere else) so starting a new transcription is hard :(

**Comment by richmanrachel** [comment]
@rlskoeser - yes, that works for me! Do you have capacity to write the user story or should I?

**Comment by rlskoeser** [comment]
I'll write it — I have some notes somewhere on what needs to happen, if I can find or remember them.

question for you: is it ok if we show a placeholder image so that this will work as much like the other cases as possible, from a code perspective?

**Comment by richmanrachel** [comment]
> is it ok if we show a placeholder image so that this will work as much like the other cases as possible, from a code perspective?
@rlskoeser - yes, this works! Sorry, I thought I had responded to this already... my apologies fro keeping you waiting!

**Comment by blms** [comment]
Closing, superseded by #1039 and #1044.

**Comment by richmanrachel** [comment]
Yes, absolutely!
________________________________
