### ISSUE TITLE
As a content editor, I want an easy way to select the scholarship record for my unpublished transcriptions so I can add transcriptions to new documents more quickly.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#1010]
## dev notes
- [x] add optional 1-1 relationship between scholarship record `Creator` and django `User`
- [x] write a data migration to connect known creator/users in the db now
- [x] make the field available in django admin when editing `Creator` records
- [ ] revise `DocumentAddTranscription` view to find sources solely authored by the currently logged in user (maybe unpublished only? or limit the list of sources? could check what the max is once we know how many current users are also creators)
- [ ] revise template for `DocumentAddTranscription` to display source(s) by current author and link to the transcribe page for each source we include (whether one or multiple)

**Comment by kseniaryzhova** [comment]
@rlskoeser should we pass this on to Ben?

**Comment by rlskoeser** [comment]
@kseniaryzhova yes, if this is a priority please assign to Ben. I did already do some of the preparatory data work needed — I bundled it with the work to add github co-author emails for users. I just checked off the steps that I think I already completed.

**Comment by kseniaryzhova** [comment]
From RSK: "What we proposed is giving you a preset list of your own unpublished sources and/or (maybe?) recently used sources for transcriptions you've worked on (e.g., if an RA is working on entering a bunch from the same source, we list that source for them to make it a one-click)" I'll ask MR/RR how this correlates with #1275 and what we want to prioritize/how we want to attack this.

**Comment by kseniaryzhova** [comment]
@richmanrachel and I decided this isn't really an issue because we haven't experienced problems searching for sources using last names. Closing!
