### ISSUE TITLE
As a transcription editor, I want to reorder transcription blocks within a page so that I can make sure text content matches logical document order.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#1021]
## testing notes (QA)

Log in as an admin. On a document with images, and with or without transcriptions (try both!) visit the document details page and add or edit a transcription.
- [x] Reorder the existing transcription text blocks in the right column by dragging and dropping, within one page
- [x] Try the same with new transcription text blocks (create by making a selection on the page image in the left column)
- [x] Delete a block and confirm the order remains correct
- [x] Refresh and confirm the order remains correct

## dev notes
- [x] add drag/drop ~~handle~~ ability to annotation blocks (per Slack, handle discarded in favor of draggable blocks)
- [x] implement drag/drop behavior to reorder blocks within a page
- [x] after drag/drop completes, update position attribute on all annotations and save them if changed
  - position attribute should be 1-indexed `schema:position`
  - _only_ save changed ones, if possible
- [x] order tahqiq blocks by position attribute on load
- [x] on create new annotation (when saving), set its position attribute to the last index + 1 (or, if it's the first one, position 1)
  - saving should reload annotation list, as always, and thus display new annotation in the correct position
- [x] disable drag-and-drop when any TinyMCE editor is open
- [x] disable drag-and-drop during saving/loading

**Comment by kseniaryzhova** [comment]
@rlskoeser my transcription editor is launching very slowly - it takes several minutes for existing transcriptions to appear. Microsoft Edge, PC.

**Comment by kseniaryzhova** [comment]
@rlskoeser I cannot rearrange boxes which are not adjacent to each other in the transcription editor. For example, if I cannot move the first block below the third block in this screenshot - only below the second. 
![image](https://user-images.githubusercontent.com/105385128/189423399-f4b40708-7071-433f-890f-8b5449c334b6.png)
I think this will be crucial for rearranging joins with lots of text blocks.

**Comment by rlskoeser** [comment]
@kseniaryzhova would you test this in a browser other than Edge to see if it's something specific to Edge or if you have the same problem in other browsers? 

FYI I _think_ the slowness is some image processing I'm running on the test server, LMK if you want me to pause it while you're testing.

**Comment by kseniaryzhova** [comment]
@rlskoeser The issue above is fixed in Chrome. I tested over the weekend so hopefully nothing was running and it still sometimes takes minutes for existing transcriptions to appear in th edit window. For example, I'll click edit and wait for several minutes without it appearing. Once I refresh, it appears immediately.

**Comment by rlskoeser** [comment]
@kseniaryzhova I was running more image tiling over the weekend because it's going to take a while to get through all the images. Is this issue acceptable?

If you didn't accept because of the slowness, coordinate with me on slack and I can pause the image processing while you're testing.

**Comment by kseniaryzhova** [comment]
@rlskoeser once we paused tiling everything worked quickly!
