### ISSUE TITLE
As a transcription editor, I want to move transcription blocks to a different image so that I can easily correct content associated with the wrong image.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#1022]
## testing notes (QA)

Log in as an admin. On a document with multiple images, and with or without transcriptions (try both!) visit the document details page and add or edit a transcription.
- [x] Move an existing transcription text block in the right column from a page with transcription content to a page without any by dragging and dropping it to the "drop zone" that appears by the empty page
- [x] Move transcription text blocks from a page that has transcription content to another page that has transcription content by dragging and dropping onto a transcription block (in the same manner as reordering in #1021), and confirm it is added to the end of the list for the target page
- [x] Confirm none of these actions cause the order of existing transcription content on any page to change (i.e. only change should be adding/removing)
- [x] Refresh and confirm the order remains correct

## dev notes
- [x] use drag/drop handle from #1021 and make images drop targets
- [x] when an annotation is dropped onto a different image, update the target uri to the new canvas and save

to keep this simple, I suggest we order it after any existing annotations on the new image and let the user reorder as needed

**Comment by kseniaryzhova** [comment]
@rlskoeser Everything works well! The only thing is that the distance between images are kind of large, so it takes a while to scroll down to see the page (while keeping the transcription box selected). I don't expect many people to be using this feature (and we can explain it to those that do) - so not an issue, more of an inconvenience.
