### ISSUE TITLE
Quotation marks not working in Arabic script searches

### ISSUE THREAD

**Issue by richmanrachel** [Princeton-CDH/geniza#1034]
**Describe the bug**
As discussed in #789 and #948 , there is some problem with the frontend search and quotation marks around Arabic content. Even when a phrase is known to be in the Geniza, adding the quotation marks produces "0 results"

**To reproduce/expected behavior**
1. Go to test site.
2. Search for "ثوب دبيقي" and compare to results for Judaeo-Arabic "תוב דביקי" (a type of robe), there should be 11 results
3. See that Arabic search results are 0 when there are real entries with this phrase, despite without the quotation marks there are 145 results

**Comment by rlskoeser** [comment]
🤦‍♀️ it somehow only just occurred to me, this is almost certainly due to the way I'm modifying the query to put in the Judaeo-Arabic alternates – it's mangling the phrase somehow (still, even after my last revision). I think this is why it's only a problem for Arabic. Good news is, now I know where in the code I need to work on a fix. :-)

**Comment by richmanrachel** [comment]
@rlskoeser - great! Thanks so much!

**Comment by rlskoeser** [comment]
A fix for exact phrase searching in Arabic is on the test site now. I tested with the example in this issue and another Arabic phrase I found by searching and it looks like it's working, but it would be good to have someone familiar with the content and scripts confirm. Please try a variety of searches and different syntax to make sure they all work as expected.

**Comment by kseniaryzhova** [comment]
@rlskoeser works for me - 11 results for both Arabic search term and same search term in JA (also the same documents). Closing!
