### ISSUE TITLE
Search results not highlighting all matches in description

### ISSUE THREAD

**Issue by richmanrachel** [Princeton-CDH/geniza#1035]
**Describe the bug**
As discussed in #814, the search algorithm is correctly pulling some close matches but not displaying them with highlights on the search result page.

**To reproduce**
1. Search for:  مولاى 
2. See that first result does not highlight the term (PGPID 35813).
3. Click into 35813, see that description includes  مولاي

**Expected behavior**
 The term  مولاي and surrounding Arabic words show up in search results

**Screenshots**
Search results:
<img width="881" alt="image" src="https://user-images.githubusercontent.com/68028846/186515699-b9a64dc9-f33c-41df-b7cb-746941ae6dbf.png">

Doc. detail page:
<img width="645" alt="image" src="https://user-images.githubusercontent.com/68028846/186515660-fad88794-c076-446e-b877-40a320bebc69.png">

**Comment by rlskoeser** [comment]
Resolved by the changes for #1211 — there's now only one description field instead of two, so it's not possible to get a match that isn't highlighted as it was before. Did some testing and confirmed in QA.
