### ISSUE TITLE
As a content editor, I want database translation fields for Hebrew and Arabic content in the admin site to render text RTL, so that I can read and edit the content properly.

### ISSUE THREAD

**Issue by richmanrachel** [Princeton-CDH/geniza#1036]
## testing notes

Test RTL alignment for Hebrew and Arabic text inputs in the following places in django admin:
(may require a hard refresh to load the new styles)

- [x] document type name and label
- [x] document description
- [x] scholarship record source title
- [x] scholarship record creator first and last name

----- 
**Describe the bug**
When adding Hebrew/Arabic content for a document description, the text stays in a left-adjusted format and therefore it is difficult to add proper punctuation at the end of a line.

**To reproduce**
1. Go to admin site
2. Click on a document
3. Try to add Hebrew or Arabic descriptive text (ex. PGPID 8962)

**Expected behavior**
Text box automatically adjusts to RTL format when Hebrew/Arabic is typed or pasted in.

**Screenshots**
<img width="872" alt="image" src="https://user-images.githubusercontent.com/68028846/186516566-e3082cc8-7e19-4ee0-8ef5-9e8f9a24aabd.png">

**Device information**
 - Device: MacBook Air
 - OS and version: macOS 12.0.1
 - Browser and version: Chrome  104.0.5112.101 
 - Site version 4.7.0

**Comment by mrustow** [comment]
I only tested document description, and it was still justified left. I didn't understand document type name and label — should I be inputting a new type, but in He or Ar?

**Comment by kseniaryzhova** [comment]
@rlskoeser tried to add new creator and source title in Arabic and Hebrew - still justified left as well. (Same with document descriptions)

**Comment by rlskoeser** [comment]
@kseniaryzhova could you do a hard refresh just to be sure you're getting the new styles? And let me know what browser you're testing, in case that matters.

**Comment by kseniaryzhova** [comment]
@rlskoeser testing on the test admin, it all works with a few hard refreshes!
