### ISSUE TITLE
update annotation controller so deep zoom doesn't autoscroll the page when in edit mode

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#1037]
## testing notes (QA)

When navigating to the transcription editor for a document (QA public site document details page --> "edit X's transcription"/"add a new transcription", visible when logged into admin):
- [x] Confirm that the page does not immediately scroll itself down to the last image on the document

---
## dev notes

at minimum, we should disable the autoscroll behavior needed for the image+transcription panel viewer

if possible, it would be great if we could do some lazy-loading, maybe only initialize zoom and annotation editing when images are visible?

**Comment by rlskoeser** [comment]
@blms what if instead of enabling zoom on page load we activate it based on intersection observer?
https://stimulus-use.github.io/stimulus-use/#/use-intersection

**Comment by blms** [comment]
@rlskoeser That makes sense to me!

**Comment by kseniaryzhova** [comment]
@rlskoeser It does not immediately autoscroll to the bottom BUT it's still not immediately showing me the existing transcription. I have to refresh again after clicking on th Edit transcription button. Are you still tiling? Let me know how you want to proceed - the slow load time seems like a separate issue so happy to close this one and write a new bug report.

**Comment by blms** [comment]
@kseniaryzhova Yes, if this one is working then please close and create a new bug report for the slow load time. It might be (and this is my hunch) that they are not loading at all rather than loading slowly.

**Comment by kseniaryzhova** [comment]
@rlskoeser works for us!
