### ISSUE TITLE
As a user, I want to see all transcription content for a document even if it extends beyond the currently available iiif images.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#1039]
## testing notes (QA)

(these notes are similar to #1044, but they refer to the public viewer and not the transcription editor.)

Navigate to the QA public site document details page for one or more documents with: 
- no images, but transcription content (e.g. PGPID 6176)
  - [x] Confirm you see two gray blank rectangles as placeholder images for each block of transcription
- transcription content, and some but not all images (i.e. some transcription content extends past the images). (e.g. PGPID 1390)
  - [x] Confirm you see placeholder images for each block of transcription that extends past the number of images present

## dev notes
Transcription migration is creating placeholder canvases as needed for the content (either document has no images or document has not enough images), but we don't currently display them in the image + transcription viewer and we need to.

For documents with transcription but no image, we should not display the image panel on the public site (i.e., should remain disabled).

- [x] get unique set of canvas URIs from images + transcriptions in view
- [x] some but not all image URLs: display placeholder canvases; example PGPID 1390
- [x] canvas IDs, but no image URLs: no images, no image panel; ex PGPID 6176
  - [x] should be able to remove separate html section for transcription without images

see also: #1044 load editing for transcription with no iiif images

- [x] for the public site, make the placeholder completely transparent

**Comment by rlskoeser** [comment]
I had a thought about this — maybe we just gather the set of all canvas ids in the view first, based on any iiif images (with order override) and then any canvases referenced by annotations not in that set.

It occurred to me we need to make sure we handle something like reimporting iiif manifests with new canvas ids (as I think we will do with the JTS content after deskewing images and reingesting) without losing any transcription content — I think this implementation would display empty (or old/duplicate) canvases until we cleanup and reassociate, but all the content would be there.

**Comment by kseniaryzhova** [comment]
@rlskoeser I'm not sure I understand the second point. I went to PGPID 1390 but I don't see placeholders, just the images for the transcription (out of order because it's an unbound notebook). Are placeholder images supposed to be other Geniza documents or is it the same gray blank squares?

**Comment by blms** [comment]
@kseniaryzhova I got an email with your comment about PGPID 1390 but the comment seems to have been deleted!

My mistake; that PGPID was edited between my copy of the data and what's live on the test site. You're right that there are no placeholders for it now. Can you check the one you mentioned in the other issue, PGPID 3185, instead? (I see you checked it off in the list so maybe you already did.)

That said, please leave this issue open because I have one more task on it: to make those placeholders transparent instead of gray when viewing but not editing. Thanks!

**Comment by rlskoeser** [comment]
My fault! 🤦‍♀️  I edited that record when I was consulting with Gissoo on how to handle placeholder canvases, I forgot that we had listed that one as an example for testing. When we deliver again I'll refresh the data from production again before running the tei migration.

**Comment by rlskoeser** [comment]
confirmed that placeholders are now transparent on the public site
