### ISSUE TITLE
As a content editor, I want to add and edit transcriptions for records without all IIIF images available so that transcriptions aren't limited to records with all images.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#1044]
## testing notes (QA)

(these notes are similar to #1039, but refer to the transcription editor and not the public viewer)

Navigate to the QA public site document details page for one or more documents with: 
- no images, but transcription content (e.g. PGPID 6176)
- no images and no transcription content (e.g. PGPID 33472)
- both, with some but not all images (i.e. some transcription content extends past the images). (e.g. PGPID 1390)

In the transcription editor ("edit X's transcription"/"add a new transcription", visible when logged into admin):
- For a document with no images and no transcription:
  - [x] confirm that you see two gray blank rectangles as placeholder images where images would go
  - [x] shift+click on them to create new annotations on the image, should result in new transcription blocks in the right column
- For a document with transcription content but no images:
  - [x] Confirm you see placeholder images for each block of transcription
  - [x] Edit and save some transcription text
- For a document with transcription content and some but not all images:
  - [x] Confirm you see placeholder images for each block of transcription that extends past the number of images present

## dev notes
- [x] load transcription editor even if document has no images (ex. PGPID 6176)
- [x] display placeholder canvases in editor of document has no images (maybe recto/verso, canvas 1 and 2 ?)
- [x] use placeholder canvases for documents with some but not all images, ex. PGPID 1390

may have some overlap with #1039

**Comment by kseniaryzhova** [comment]
@rlskoeser PGPID 3185 is the better tester for incomplete images compared to the transcription - 1390 has all images (or at least does not have any gray squares)
