### ISSUE TITLE
regression on server error for documents associated with Heidelberg IIIF (PGPIDs 34016, 34017, 34018)

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#1046]
We seem to have a regression on #906 — we fixed this before, but it's broken again now. Getting a 500 error in production and staging both.

Based on the nginx logs in staging, there's a problem with getting the preferred label for the license (but could be the license uri itself that we're doing something wrong with)

https://test-geniza.cdh.princeton.edu/en/documents/34016/
https://test-geniza.cdh.princeton.edu/en/documents/34017/
https://test-geniza.cdh.princeton.edu/en/documents/34018/

**Comment by rlskoeser** [comment]
Looks like an rdflib change — no error running locally with 6.0, error in staging with 6.2, when I upgrade I can duplicate the problem. I don't see it in the rdflib changelog anywhere, but the `preferredLabel` doesn't seem to be available anymore. Need to update djiffy. (But we can pin rdflib to `<6.2` in the meantime as a quick fix.)

**Comment by kseniaryzhova** [comment]
@rlskoeser Rachel and I tested these PGPIDs in production and they load just fine, can we close?

**Comment by rlskoeser** [comment]
@kseniaryzhova they work because I have a temporary fix in place, but I still need to fix it properly — hope to address as part of the eventual work to upgrade to django 4

**Comment by richmanrachel** [comment]
@rlskoeser - the images are working. Is this the temporary fix or part of the permanent upgrade? https://geniza.princeton.edu/en/documents/34016/

**Comment by rlskoeser** [comment]
This specific issue was resolved by specifying the version of the rfdlib library; I think it's ok to close this issue and figure out how to address that problem as part of maintenance +upgrades
