### ISSUE TITLE
As a content editor, I want transcription formatting preserved in search result display but ignored for search text so that I can see where in the transcription matching terms are.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#1049]
## testing notes
- [x] transcription line numbers (when present) should display in the search results by default (no keyword search)
- [x] transcription line numbers (when present) should display with keywords in context if match is near the beginning of the document (won't always display if your match is from the middle of the text; is this acceptable?)
- [x] transcription keywords in context matches display the correct line number when the match is from the middle of the text

## dev notes
- [x] index html instead of plain text
- [x] update search result formatting for list instead of plain text with line breaks
- [x] calculate and add line number to html when indexing
  - [x] [parse the HTML](https://stackoverflow.com/questions/14694482/converting-html-to-text-with-python/55825140#55825140) to look for `ol > li` and use "start" attribute if present
  - [x] add either a data attribute or value attribute to each `li`, doesn't matter which
- [x] revise css to display pseudo-marker based on line number attribute for search only
- [x] update styles in admin that are suppressing line numbers

**Comment by richmanrachel** [comment]
>transcription line numbers (when present) should display with keywords in context if match is near the beginning of the document (won't always display if your match is from the middle of the text; is this acceptable?)
- I'm afraid this isn't acceptable -- it's really helpful as a researcher to have all the line numbers on the search page so that I can quickly jot down where to find the term in my spreadsheet/notes without having to go into the full document.

Also, it looks a bit messy and confusing to have a mixture of numbered and un-numbered entries:
transcription line numbers (when present) should display with keywords in context if match is near the beginning of the document (won't always display if your match is from the middle of the text; is this acceptable?)

**Comment by rlskoeser** [comment]
ok! I wondered if it might not be sufficient, but wanted to know for sure before doing more work. Now that we're using proper ordered lists, we don't have the sequence number on each line by default, so we'll have to do a little bit of extra work to put it in so we can display it on the search version.

**Comment by richmanrachel** [comment]
Okay, thanks so much!

Also, just an oddity that's happening now with the formatting for results that are too far into the text for line numbers - there's a first line and then an indentation:
<img width="764" alt="image" src="https://user-images.githubusercontent.com/68028846/188005113-a995876c-1a0a-4b9e-ad91-5208e1100787.png">
https://test-geniza.cdh.princeton.edu/en/documents/?q=%D7%9E%D7%9E%D7%9C%D7%95%D7%9B%D7%9A&docdate_0=&docdate_1=&sort=relevance

**Comment by kseniaryzhova** [comment]
@rlskoeser transcriptions which have numbered lines on the public site do not have them on the admin site. None of the documents with transcriptions on the public site (I've clicked through about 10) have numbered transcription lines.
![image](https://user-images.githubusercontent.com/105385128/188005327-504b11f9-66ae-4d11-b13c-cda365254704.png)
![image](https://user-images.githubusercontent.com/105385128/188005499-c9b9fee8-dad0-432a-817e-e1aff62491cb.png)
PGPID 9044

**Comment by rlskoeser** [comment]
ah, good catch, we forgot to update some styles in admin that are suppressing the numbers

**Comment by kseniaryzhova** [comment]
@rlskoeser transcription keywords in context do not display the line number when the match is from the middle of the text - I took the following example from the middle of line 10 but the correct line number does not appear in the search results (for the same document):
![image](https://user-images.githubusercontent.com/105385128/190936189-4eb886dd-c659-4d6c-ad37-bf9a6b383aa4.png)

**Comment by blms** [comment]
@kseniaryzhova Could you comment with the PGPID and the search query you used so I can test this and try to figure out why it's wrong? Thanks!

**Comment by kseniaryzhova** [comment]
@blms sorry I only just saw this! It's PGPID 1223 and I used the name "הנכבד בן כגק"

**Comment by kseniaryzhova** [comment]
@rlskoeser works for me!
