### ISSUE TITLE
As a content editor, I want to cut and paste transcription content from a Google Doc or similar and have it display properly with site styles so that I can easily add existing transcription content.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#1055]
## testing notes (qa)

In the transcription editor for a document (QA public site document details page --> "edit X's transcription"/"add a new transcription", visible when logged into admin):
- [ ] Edit or create a transcription block. Paste in some content with formatting, such as bold, italic, tables, images, etc (such as the unpublished edition by Marina in the scholarship records for PGPID 646). Click "save" and confirm the extraneous formatting is removed, but list numbering remains.

## dev notes
- [x] use bleach or similar to sanitize body html content on `Annotation.save` (maybe make use of a clean method? but make sure it's called on save)

PGPID 646 is a good test case, there's an unpublished edition by Marina in a google doc linked in an existing footnote; cutting and pasting from the google doc looks like it works, but when I tried it, it introduced a bunch of in-line styles.

**Comment by kseniaryzhova** [comment]
@rlskoeser extraneous formatting is removed and the list numbering remains BUT the numbers move to the ends of the lines like so: 
![image](https://user-images.githubusercontent.com/105385128/190935771-522b64f6-b094-4bca-b86d-3db3b988c74c.png)

**Comment by blms** [comment]
@kseniaryzhova Odd, that suggests the list formatting got stripped out. Can you pass along the source that you copied from? I want to see how it's structured to see if there's anything we can do to preserve the list formatting.

**Comment by rlskoeser** [comment]
@kseniaryzhova was it formatted as a numbered list in the version you copied from, or were the numbers just text?

**Comment by kseniaryzhova** [comment]
@rlskoeser works for me - other issues discussed on Slack!
