### ISSUE TITLE
Image viewer in transcription editor acting improperly

### ISSUE THREAD

**Issue by richmanrachel** [Princeton-CDH/geniza#1057]
retesting notes:

- [ ] confirm the editor box is added next to the top of the image or under the last text section (no empty space above it forcing you to scroll down)

**Describe the bug**
While testing #1000, Ksenia and I ran into different issues with the image on the transcription editor. I had issues of the box I dragged being moved around as I tried to navigate the image (in Google Chrome). Ksenia lost her zoom/rotation bar once she zoomed in (Microsoft Edge, I think?). I am not losing my zoom/rotation bar on Chrome and she did not seem to have issues with navigating around her region box.

**To reproduce**
1. Go to test site and "add/edit transcription"
2. Try to use the region box and the zoom feature

**Expected behavior**
Ksenia should have maintained her ability to use the zoom/rotation tool. I should have been able to zoom into the region box and move around to view words as I transcribed them without moving the box itself. 

**Screenshots**
Screenshot from RR where trying to move within a zoomed screen moved the box edge:
<img width="1258" alt="image" src="https://user-images.githubusercontent.com/68028846/188014116-7fa6689f-0de3-409a-a9df-328fdbf935b5.png">
 [Ksenia's screenshot in #1000]

**Comment by kseniaryzhova** [comment]
@rlskoeser both work for me now - I do not lose the zoom bar when I zoom in and the transcription block I selected was not moved around when I zoomed (but this was not an issue for me before). I can close now, or ask Marina to test herself, just to get more eyes on it given how it behaved differently for Rachel and I.

**Comment by richmanrachel** [comment]
As Marina was testing (on Vivaldi 5.4, Mac OS Monterray 12.5.1):
- She did not run into any zoom traps!
- The shift create a box worked!
- But when the transcription box was created (at the top of the image), the editor box was a long scroll down from where the selected image section was :(

**Comment by blms** [comment]
@richmanrachel Ah, I think I know what happened: the "drag target" for moving annotations from another image was still present after the new annotation was initiated, and caused the editor box to shift down. Thanks to you and Marina for the testing!

**Comment by kseniaryzhova** [comment]
@rlskoeser testing with @mrustow today and the editor box was appearing right next to the document as it should, but she had the following issues (see attached video from Marina):
- when zoomed in, after zooming out the text box had shifted
- when zoomed in, Marina could not drag the zoom window to another part of the document

**Comment by mrustow** [comment]
Here's the [screen recording](url)

**Comment by kseniaryzhova** [comment]
@rlskoeser we tested with Bodleian images and we could move the window around the document when zoomed in but without selecting a text box. Once we created a text box, we could no longer move the window around the document when zoomed in.

**Comment by rlskoeser** [comment]
@mrustow the link to your screen recording isn't working, could you share again?

Is that problem specific to Bodleian images and not happening on others? If so, then maybe it's a limitation of the static iiif images implementation (which we aren't going to be using, I just haven't removed the initial set of static Bodleian content I loaded).

**Comment by kseniaryzhova** [comment]
@rlskoeser no, we specifically tested with CUDL images first (the video is CUDL image) but the same issue happened with Bodleian https://www.dropbox.com/s/bn4weoprhxlks13/Screen%20Recording%20for%20issue%20%231057.mov?dl=0

**Comment by blms** [comment]
Based on meeting discussion, closing this as acceptable behavior that passes testing.

Remaining work is in #1129 (help text to clarify behavior noted above) and #1131 (an unrelated issue with the editor).
