### ISSUE TITLE
Pass tiny API key to, and use it in, tahqiq

### ISSUE THREAD

**Issue by blms** [Princeton-CDH/geniza#1065]
## testing notes (QA)

In the transcription editor for a document (QA public site document details page --> "edit X's transcription"/"add a new transcription", visible when logged into admin):
- [x] Create or edit a block of transcription text. Confirm there is no warning message about "This domain is not registered with Tiny Cloud" or about an API key.

## dev notes
- [x] Pass API key along in config via geniza
- [x] Add line during tiny instantiation to set the `api-key` attribute
- [x] Remove extraneous instantiation in HTML head

**Comment by kseniaryzhova** [comment]
@rlskoeser has not appeared for me while I've been testing with transcriptions today!
