### ISSUE TITLE
As a user, I want to see updates and changes made in the new database in the current pgp site while the new website is still in development so that I can reference current information. 

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/geniza#107]
**Is your feature request related to a problem? Please describe.**
During the transition period after the data has been imported to the new database, changes won't be manifested on the current PGP site unless the metadata google sheet is also updated.

**Describe the solution you'd like**
The existing PGP site should be updated to automatically pull a new CSV or JSON feed with data from the database that matches the fields used from the existing spreadsheet. 

We should create a new view that returns CSV as a streaming response so that data can be consumed before the full result is generated.  Use https://github.com/LibraryOfCongress/django-tabular-export and integrate into a view instead of django admin

**Additional context**
Details provided by Ben:

> It can be CSV or JSON, whichever you prefer. I can also test the ingest from your data at any time with a local copy of the database, not a problem.
> The following are the bits of info I getting from the spreadsheet and the corresponding column in the spreadsheet (starting with 0 for the first)

pgpid    column 0
~notes    column 1~
library    column 2
shelfmark    column 3
shelfmark_alt    column 5
recto_verso     column 7
type    column 9
tags    column 10
joins    column 11
description    column 12
editor    column 13

## dev notes
- [x] create new corpus view and configure a url
- [x] use `document` queryset to get a list of public documents
- [x] use the queryset to create a generator with the needed fields
- [x] use `tabular_export.core.export_to_csv_response` to render
 
open questions / suggestions:
- current pgp models documents and joins slightly differently; propose we return the first shelfmark only in the shelfmark column and the full shelfmark in the join
- suggest we create a footnote method to output edition information in a similar form to what was in the spreadsheet; does not have to match exactly.

**Comment by rlskoeser** [comment]
@mrustow The list of fields Ben says he uses from the current spreadsheet includes the **Technical Notes** column, which as far as I know we were not planning to import into the database. Please advise.

**Comment by mrustow** [comment]
Technical notes is a mess, but contains valuable info on action items. Would be easier to get these sorted out in the spreadsheet, I would think — not sure.

**Comment by rlskoeser** [comment]
Confirmed with Ben we can drop the technical notes field from the new version of the data export.

**Comment by richmanrachel** [comment]
@rlskoeser - just to clarify, this is for Ben to test, not me?

**Comment by rlskoeser** [comment]
@richmanrachel yes! working on getting him access, sorry if adding the label was confusing

**Comment by rlskoeser** [comment]
Apparently this is working, since Ben J has switched the site over to the new feed (and current missing editor display on the site is not a problem with the data feed).

Considering this tested and accepted.
