### ISSUE TITLE
As a content editor, I want to override the orientation of images displayed for a document so I can rotate images to display in logical orientation for readability/useability.

### ISSUE THREAD

**Issue by kseniaryzhova** [Princeton-CDH/geniza#1070]
### testing notes (QA)

On the [QA admin site](https://test-geniza.cdh.princeton.edu/admin):
- [x] Navigate to a document with images. Rotate one or more of the images using the new rotation controls (may require a hard refresh to appear). The buttons should rotate the images in place
- [x] You should also be able to reorder the images freely
- [x] On save, the rotations should persist, and appear in the transcription/translation viewer in the admin
- [x] Rotations should also be reflected in the public site document detail page (may require a refresh)
- [x] Rotations should also be reflected in the search results thumbnails on the public site

---

**Is your feature request related to a problem? Please describe.**
There are some images (newest Bodleian batch) which display the document sideways. This is confusing and makes it hard to read documents and edit/add new transcriptions. See Additional context for a screenshot. 

**Describe the solution you'd like**
Just like the image order override, I would like for there to be an option in the admin site to rotate the displayed images to their logical positions. I would like for it to be intuitive and preferably linked to the image order override section (in my mind the two features go together as image display manipulation). 

**Additional context**
![image](https://user-images.githubusercontent.com/105385128/189538836-e3ef5892-a8be-4f7c-a157-f33c7c262188.png)

**Comment by rlskoeser** [comment]
@kseniaryzhova is it reasonable to only allow increments of 90 degree rotations? And do you have any sense of which direction would be more logical or most common, rotate to the right or to the left first?

**Comment by kseniaryzhova** [comment]
@rlskoeser 90 increment rotations at a time right? So I would turn twice to get an 180 degree turn right? (There's at least one instance where it need a 180 turn). As for which would be more common, right or left, I have no idea. The above example should be rotated 90 degrees to the left, but a quick search turned up equal instances of it needing to be rotated right or left. If it helps, this solution does not need to be user friendly - it's enough that the management team can do it, I don't envision this being of use to content admins/editors since it's an infrequent permanent fix to help with the display.

**Comment by blms** [comment]
From @kseniaryzhova over slack:

> Oh yes only 90 degree turns is good. It's really just to turn an image permanently. Anything else people can use the little knob that does rotations already. This is just for like the Bodleian manuscripts that are published on the Bodleian site as sideways. Or sometimes another collection will have the verso with the main text upside down.

**Comment by kseniaryzhova** [comment]
@blms works really well, thank you! My OCD soul can now fix all these incorrectly rotated images!
