### ISSUE TITLE
Image order override does not work consistently on the admin site

### ISSUE THREAD

**Issue by kseniaryzhova** [Princeton-CDH/geniza#1077]
**Describe the bug**
Performing the same action doesn't always yield the same results - MR (Mac, Vivaldi) tried to reorder an image with one that was not adjacent - it worked the first time but the other times it did not.  For me (KR, PC, Chrome), the field for dragging images to rearrange is very small and it is hard to preview whether I'm doing the right thing (no yellow border appears to indicate which image I am switching when I drag another image to rearrange; a red circle appears if I've exceeded the confines of the dragging field).

**To reproduce**
1. Go to the admin site and search for [any document with joins and an image](https://geniza.princeton.edu/admin/corpus/document/?textblock__fragment__iiif_url__isempty=0&transcription=yes) (Cannot filter by joins yet)
2. Click on any one of these join documents with images.
3. Scroll down to image order override.
4. Try to rearrange thumbnails, especially those that are not adjacent.

**Expected behavior**
I expect identical actions to yield identical results - if I drag an image and move it to a non-adjacent position, I expect that to work each time. I also expect a clearer preview of what I am about to do (i.e. yellow border around the other image to indicate new placement of image).

**Screenshots**
KR (PC, Chrome): https://princetongeniza.slack.com/files/U026R91M8BE/F041SM2M7TR/change_document___princeton_geniza_project_site_admin_-_google_chrome_2022-09-13_12-01-24.mp4
MR (Mac, Vivaldi): https://capture.dropbox.com/fkdo5pk43JTFjm5A

---
## dev notes
- [ ] drag and drop stimulus component
- [ ] the js should be a separate file, referenced explicitly in the media for the form or model admin

**Comment by blms** [comment]
@kseniaryzhova I think the component that Rebecca posted would help. If the [demo for that component](https://stimulus-sortable.stimulus-components.com/) seems to work better for you, it may be worth doing. Would likely be a handful hours to swap them out.

**Comment by kseniaryzhova** [comment]
@blms I haven't heard anyone else complain about this, and I haven't had any issue with in regularly. Let me close this, and if this issues pops up again we can reopen and invest the hours. Thanks so much!
