### ISSUE TITLE
Determine (and possibly mitigate) impact of indexing on annotation editing

### ISSUE THREAD

**Issue by blms** [Princeton-CDH/geniza#1084]
> It occurred to me from watching the logging that there may be some slowness with updating annotations due to the fact that we're reindexing documents on every change. We may want to add some time stamp / duration logging to our annotation signal handler to get a better sense of how much of an impact this is. It would be nice if we could delay the indexing or wait until a batch of edits is complete, but I'm not sure how we could do that without a queue manager or something like that.

Originally posted by @rlskoeser in https://github.com/Princeton-CDH/annotorious-tahqiq/pull/15#issuecomment-1245838012

**Comment by rlskoeser** [comment]
@blms resolved by #1329  ?
