### ISSUE TITLE
As a content admin, I want TEI contributors documented in the new GitHub annotation and transcription backups so that there is a record of everyone who has contributed to the transcription structure and content.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#1093]
## testing notes

Use this branch of our test transcription backup to test:
https://github.com/Princeton-CDH/test-pgp-annotations/tree/test-tei-migration

Maybe easiest to look at the [list of recent commits](https://github.com/Princeton-CDH/test-pgp-annotations/commits/test-tei-migration)

- [x] there are transcription export files in this branch of the repository created by the migration (this branch was empty until I ran the migration script)
- [x] commit message includes TEI filename
- [x] commit message / credit is based on who contributed to the bitbucket file (click in to see "co-authored-by" text in the full commit message; I only have a github co-author email for myself right now, so only my commits are linked to my github account)

FYI: got a weird error and the tei to annotation script didn't finish running; I will need to re-run it and investigate, but I think it got far enough for you to test that it's correctly exporting to github at migration time and preserving contributor information.

## dev notes

Revise tei to annotation migration script to add a backup step. As each document is converted, determine the contributors, generate a co-author list, and run the github export. Should commit but not push until all content has been migrated.

**Comment by kseniaryzhova** [comment]
@rlskoeser works for me!
