### ISSUE TITLE
As a content admin, I want to add content editor user's github coauthor emails and link their account to scholarship records so that their contributions will be properly documented.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#1094]
## testing notes
- [x] in django admin, when editing `user` there is now a section with a field for github co-author email and linking to scholarship record creator/author
- [x] github co-author field has help text with link to github documentation
- [x] creators are populated for existing user account where first and last names match exactly (e.g., Marina, Alan) 

Question: instead of the GitHub documentation link, should we include the text in the blue box on that page? What would be most useful?
> To find your GitHub-provided no-reply email, navigate to your email settings page under "Keep my email address private."
> To find the email you used to configure Git on your computer, run git config user.email on the command line.

## dev notes
- [x] create a new user profile model with a 1-1 relation to django user model; reverse name `profile`
- [x] add optional github co-author email with link to instructions
- [x] add optional 1-1 to creator model in footnotes
- [x] include the new profile fields on the admin user change form

**Comment by kseniaryzhova** [comment]
@rlskoeser looks good!
