### ISSUE TITLE
As a content admin, I want transcription backups to include information about who made edits when possible, so that I can track changes in versioned transcription content.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#1095]
## testing notes

1. Eit your user profile on the test site and add your github co-author commit email
2. Edit transcription content as in #1096 
3. Check that the [update pushed to the GitHub test data repository](https://github.com/Princeton-CDH/test-pgp-annotations/commits/main) includes  "co-authored-by: " language in the commit message and is linked to your github account

(I made a test change to confirm it was configured the way I expected; you should be able to see in the commit list that there's a test change I contributed)

## dev notes

revise transcription backup signal handler to generate a co-author string based on the user who makes the edit, if they have a github co-author email associated with their account

**Comment by kseniaryzhova** [comment]
@rlskoeser I think I need more guidance, I tried to follow the steps in the Github documentation but fell apart at Git Bash.

**Comment by rlskoeser** [comment]
Well, at least one of the commits is showing up as co-authored by you! https://github.com/Princeton-CDH/test-pgp-annotations/commit/ddca43e9a495f99b2a141e617f8bc2f314d626c6

But I'm not sure why the others aren't...

Happy to look at this with you and get your input on revising the help text to make it more helpful.

**Comment by kseniaryzhova** [comment]
@rlskoeser my recent changes worked. I think the reason some of them were not showing up with the co-authorship line was because I was only deleting text blocks while testing and not actually adding or changing the transcription content. Not sure if this is by design.

**Comment by rlskoeser** [comment]
@kseniaryzhova I do expect deletions and changing order or image association to get a co-author commit. I'd like to test this a little more and see if we can figure out what's going on, in case I need to adjust the logic some.

**Comment by kseniaryzhova** [comment]
@rlskoeser tested a bit more today, the co-author co-commits work fine with editing existing transcriptions and deleting transcriptions. Creating new transcriptions does not list me as a co-author and I tried editing from my own source and from others'.

**Comment by kseniaryzhova** [comment]
@rlskoeser works for me, even with deletions (I retested with everything though, all over again - all works)
