### ISSUE TITLE
As a content admin, I want transcription content backups to be regularly updated as edits are made, so that the backup is up to date, version history is more granular, and I can compare changes.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#1096]
## testing notes

Test the transcription backup by editing transcription content on the test PGP site and then checking for corresponding changes in the test export repository.  Simplest solution right now is to look at the commit history and check for changes based on your edits.  https://github.com/Princeton-CDH/test-pgp-annotations/commits/main 

Right now I have it configured to push changes every 2 minutes, so there may be a slight delay before you see your changes

test a few different cases:
- [x] edit an existing transcription and make a few text changes
- [x] edit an existing transcription that has content on more than one image; remove blocks of content so there is only content on image (one of the annotation list files should be removed; 
- [x] add a new transcription
- [x] remove an existing transcription entirely — the corresponding exports should be removed from github

## dev notes
- [x] update transcription backup as a signal handler on annotation save
- [x] remove outdated transcriptions when the last annotation for a footnote is removed
- [x] cron job to regularly sync local with remote (avoid waiting on push/pull in the signal handler)

**Comment by kseniaryzhova** [comment]
@rlskoeser testing on Sunday, and it is not updating every 2 minutes - it's been half an hour and I still don't see an update about me creating or deleting transcriptions. It was working fine on Friday.

**Comment by rlskoeser** [comment]
@kseniaryzhova I don't see any errors in the log for the sync script; I do see activity in the django log and I see that some  changes were pushed on Sunday: https://github.com/Princeton-CDH/test-pgp-annotations/commits/test-tei-migration

I think this is my fault! It looks like I gave you a link to a different branch; I switched to a different branch to test exporting to github when we migrate the TEI and forgot that I had a different branch linked here.

**Comment by kseniaryzhova** [comment]
@rlskoeser I see it now, thank you! It works!
