### ISSUE TITLE
As a content admin, I want fragment data exports synchronized to github so that there is a publicly accessible, versioned copy of project data available for researchers

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#1099]
## testing notes
In django admin on the test site, go to the [fragments list](https://test-geniza.cdh.princeton.edu/admin/corpus/fragment/)
- [x] should be able to  "download all as CSV" using the link/button on the top right
- [x] should be able to select a subset of entries and download as CSV using the action menu and "go" button
- [x] CSV should include shelfmark, old shelfmark, collection details, url and iiif urls, dates created and last modified, and admin url link
- [x] CSV should include the PGPIDs associated with the fragment

## dev notes
- [x] implement an export for fragments that can be used with the documents export 
- [x] make an admin version and set up in django admin as action and convenience link
- [x] make a public version for data export manage command

**Comment by kseniaryzhova** [comment]
@rlskoeser it all works, closing and thank you!
