### ISSUE TITLE
As a content admin, I want data exports to include information about who made edits when possible, so that I see who contributed to changes in project data.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#1102]
## testing notes
for testing you should be looking at commits on the test metadata repository here: https://github.com/Princeton-CDH/test-geniza-metadata/commits/main
- [x] metadata exports should now only generate commits when there are changes
- [x] commits should include co-author information 

## dev notes
- [x] add functionality to manage command that syncs data exports to github to track when it was last run
- [x] query django admin log entries to get the list of users who have contributed to the changes since last run (limit to appropriate content types)
- [x] generate a co-author commit message including all contributors since the last time the script was run

**Comment by kseniaryzhova** [comment]
@rlskoeser works for me, closing!
