### ISSUE TITLE
review problem transcriptions in the tei migration & transcription editor

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#1107]
for the unresolved cases in the [transcription cleanup worksheet](https://docs.google.com/spreadsheets/d/1S8eorROnapeEl3Xlqk352SFwrLkuHbTgL69r94IMo88/edit#gid=286636463), 
please check how they are being handled by the migration from tei to the new annotation format. (don't need to check all, but would be good to review at least one case of the different types of problems)

- is the migration handling the content reasonably appropriately ? 
- can you do the remaining cleanup and resolve any problems in the new transcription editor?

e.g., in the case of transcriptions split across two TEI files, are both sets of content aggregated in one source, and can you drag the blocks of text to the appropriate images and edit as needed?

**Comment by richmanrachel** [comment]
Closing per conversation in meeting 9/20/22!
