### ISSUE TITLE
As a frontend user, I want keyword search for Seleucid dates to give me complete matches first so that I can browse by decreasing relevancy in the date field. 

### ISSUE THREAD

**Issue by kseniaryzhova** [Princeton-CDH/geniza#1151]
**Is your feature request related to a problem? Please describe.**
Syntax search for Seleucid dates (document_date: 1450 seleucid) brings back 5 exact matches. [https://test-geniza.cdh.princeton.edu/en/documents/?q=document_date%3A+%221450+seleucid%22&docdate_0=&docdate_1=&sort=relevance](https://test-geniza.cdh.princeton.edu/en/documents/?q=document_date%3A+%221450+seleucid%22&docdate_0=&docdate_1=&sort=relevance) Keyword search for 1450 Seleucid brings back 1,364 results (and the first two are actually shelfmark matches - the 1450 is part of the shelfmark and not in the date field). [https://test-geniza.cdh.princeton.edu/en/documents/?q=1450+seleucid&docdate_0=&docdate_1=&sort=relevance](https://test-geniza.cdh.princeton.edu/en/documents/?q=1450+seleucid&docdate_0=&docdate_1=&sort=relevance) 

**Describe the solution you'd like**
I want keyword searches for Seleucid dates (when I use Seleucid dates as a phrase "1450 seleucid") to give me exact date matches first, followed by other partial matches. 

**Describe alternatives you've considered**
@rlskoeser suggested we tweak phrase boosting to make terms together more important in the search results.

**Comment by richmanrachel** [comment]
@rlskoeser - I'm still getting the same results as Ksenia did :(

**Comment by kseniaryzhova** [comment]
@rlskoeser keyword search is giving me exact matches first, followed by the shelfmark matches and then partial matches everywhere else. Works for me!
