### ISSUE TITLE
Exempt IIIF URLs from i18n patterns

### ISSUE THREAD

**Issue by blms** [Princeton-CDH/geniza#1164]
> maybe we need to define separately and include in our main urls.py differently? might mean the urls will have a different namespace, but once we get the url config right I think everything else should work

Originally posted by @rlskoeser on Slack

**Comment by rlskoeser** [comment]
@blms I checked an annotation created by the tei migration after this fix was pushed to the test site, and the document and source uris in the annotation both look good to me. Is there any other checking you want to do on this?

**Comment by blms** [comment]
@rlskoeser Great, thanks! I also just checked the `/iiif/annotations/` endpoints for a few documents with transcriptions and they all look fine. I think we're good to close.
