### ISSUE TITLE
As a frontend user, I want search results to include partial matches of words in transcriptions, so that I can search by substrings of words.

### ISSUE THREAD

**Issue by blms** [Princeton-CDH/geniza#1174]
## testing notes

Try searching for transcription content without using full words; you should get matches where the word contains your partial word, and phrases should be most relevant. This should work with or without quotes. Two details to be aware of:
- I have the ngram filter configured with two letters as a minimum, so two letters will be enough to match a word but one letter will not. LMK if this is not sufficient.
- Right now Solr is highlighting the entire word instead of just the part of the word that matched, which is frustrating. I did a little investigating into this and found examples of other people wrestling with this problem. None of their solutions worked immediately for me, and I thought it was more important to get the partial search functionality out.  (We should probably make a separate issue for that.)

Here's one of my test searches to get you started:
- [search documents for partial transcription text (test site)](https://test-geniza.cdh.princeton.edu/en/documents/?q=%D7%A2%D7%A9%D7%94+%D7%91%D7%99%D7%AA+%D7%99%D7%A2%D7%96%D7%A8+%D7%9C%D7%94&docdate_0=&docdate_1=&has_transcription=on&sort=relevance)
- [same partial search, but as an exact phrase](https://test-geniza.cdh.princeton.edu/en/documents/?q=%22%D7%A2%D7%A9%D7%94+%D7%91%D7%99%D7%AA+%D7%99%D7%A2%D7%96%D7%A8+%D7%9C%D7%94%22&docdate_0=&docdate_1=&has_transcription=on&sort=relevance)

**Comment by richmanrachel** [comment]
The search for דלאל (and other terms in Ju-Ar) is much better than before! I'm getting more variations on the word without having to use the *.

**Comment by kseniaryzhova** [comment]
@rlskoeser all good for transcription search!
