### ISSUE TITLE
Transcriptions are failing to save in the editor

### ISSUE THREAD

**Issue by blms** [Princeton-CDH/geniza#1176]
## Testing notes (QA)

In the transcription editor for a document:
- [x] Create and save a new annotation and confirm it persists in the editor
- [x] Edit and save an existing annotation and confirm the change persists in the editor
- [x] Delete an existing annotation and confirm it is deleted successfully

## dev notes

- [x] Fix save failure condition
- [x] raise events on save/delete failure
- [x] raise events on save/delete success
- [x] display errors/success messages in frontend

**Comment by blms** [comment]
About to jump into a meeting, so before I forget: I think the save failure is another Annotorious/async race condition.

First we `await` the [Annotorious promise](https://github.com/Princeton-CDH/annotorious-tahqiq/blob/e208fd859002052c7bb2e260fba6b0ca547b7f96/src/index.ts#L349-L350), which raises the following event:

https://github.com/Princeton-CDH/annotorious-tahqiq/blob/e208fd859002052c7bb2e260fba6b0ca547b7f96/src/storage.ts#L36-L39

That event handler `await`s [saving the annotation](https://github.com/Princeton-CDH/annotorious-tahqiq/blob/e208fd859002052c7bb2e260fba6b0ca547b7f96/src/storage.ts#L133) to storage.

Back in the original function, we [fetch all annotations](https://github.com/Princeton-CDH/annotorious-tahqiq/blob/e208fd859002052c7bb2e260fba6b0ca547b7f96/src/index.ts#L354-L355) from storage after the Annotorious promise resolves.

But there's no guarantee that our event handler has itself resolved. It's entirely possible (and indeed, it appears to be the case) that we are calling `this.storage.loadAnnotations()` before it has been saved to the storage). Should be as simple as calling that method in `storage.ts` `handleUpdateAnnotation` instead.

**Comment by kseniaryzhova** [comment]
@rlskoeser works for me, thank you!
