### ISSUE TITLE
Clicking outside the current annotation zone and/or into another zone in the transcription editor cancels unsaved changes without warning

### ISSUE THREAD

**Issue by blms** [Princeton-CDH/geniza#1177]
## testing notes

in the transcription editor [on the QA site](https://test-geniza.cdh.princeton.edu/admin/)
- [x] select an existing transcription, don't make any changes, then click on the image outside the selected zone; it should do nothing
- [x] select an existing transcription, don't make any changes, then click the "Cancel" button; it should cancel without prompting
- [x] on a record with multiple transcription boxes on the same image, select one for editing; if you click on the other transcription text box by the same image, nothing should happen — you should still be editing the same transcription
- [x] select an existing transcription, make some changes to the text content, then click on the image outside the selected zone; it should do nothing
- [x] select an existing transcription, make some changes to the text content, then click the "Cancel" button; it should prompt you to confirm if you want to cancel
- [x] when you are prompted, if you choose to cancel, it should cancel and editor should no longer be active
- [x] when you are prompted, if you want to keep editing, it should keep the editor open; confirm you can save your changes
- [x] create a new transcription block
  - [x] confirm there's no issue with drawing or resizing the box, making it larger and smaller
  - [x] confirm clicking on anything outside of the box on the image, such as another annotation or the image itself, does nothing
  - [x] enter some content, click the "cancel" button, and confirm you're prompted to confirm the cancel
  - [x] when you are prompted, if you choose to cancel, it should cancel and editor should no longer be active
  - [x] when you are prompted, if you want to keep editing, it should keep the editor open; confirm you can save your changes
- [x] while editing a transcription block, create or edit one on another image on the same document. confirm you can have both open at the same time, and edit and save them independently of each other.

<details>
<summary>old testing notes</summary>

## testing notes
in the transcription editor
- [x] select an existing transcription, don't make any changes, then click on the image outside the selected zone; it should cancel without prompting
- [x] select an existing transcription, don't make any changes, click on the page outside the editor, hit escape; it should cancel without prompting
- [ ] on a record with multiple transcription boxes on the same image, select one for editing; if you click on the other transcription text box by the same image, nothing should happen — you should still be editing the same transcription
- [x] select an existing transcription, make some changes to the text content, click on the page outside the editor, hit escape; it should prompt you to confirm if you want to cancel
- [x] select an existing transcription, make some changes to the text content,  then click on the image outside the selected zone; it should prompt you to confirm if you want to cancel
- [x] when you are prompted, if you choose to cancel, it should cancel and editor should no longer be active
- [ ] when you are prompted, if you want to keep editing, it should keep the editor open; confirm you can save your changes

</details>

## dev notes

- [x] prompt the user before cancelling

**Comment by rlskoeser** [comment]
@mrustow @kseniaryzhova I have work in progress to prompt you before canceling the active annotation you are editing if there are changes in the text editor. Ben raised a question when he reviewed the changes: would you also want to be prompted like this when you click the "cancel" button? Or can we assume if you cancel by clicking the button you want to discard any changes you've made?

**Comment by rlskoeser** [comment]
Ok, thanks.

**Comment by kseniaryzhova** [comment]
@rlskoeser @blms when I click outside the annotation box on the image, it does bring up the "do you want to continue editing?" window and if I say ok, then it keeps the transcription editor open BUT then I can no longer save my changes. If I hit save it just gives me the "saving..." popup but doesn't actually close the transcription editor NOR does it save my changes (when I finally hit refresh). This does not happen when I click outside the editor page and hit escape, I'm able to successfully save changes then,

**Comment by kseniaryzhova** [comment]
@blms works great, and thanks especially for the notes you wrote! I want to run this by Marina to see if this is an acceptable exchange for the auto save. I think it is, but we'll see what she thinks!

**Comment by richmanrachel** [comment]
The test site is redirecting to the production site again! So I thought it wasn't working until I looked back at the urls.... It is in fact working for me on the test site :)

**Comment by blms** [comment]
Glad to hear it's working! Going to go ahead and close this one based on the above feedback and add the "question" tag to the autosave one.
