### ISSUE TITLE
clean up after v4.9 release & tei migration

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#1179]
- [x] add more content to readme for pgp-text repo
- [x] remove content field from footnotes
- [x] remove sync transcription and tei migration code
- [x] remove iiif-bodleian-a repo in geniza lab github org

**Comment by rlskoeser** [comment]
I'm reverting this cleanup — I did it too quickly, it looks like we need the tei migration code to stick around a little longer to help with cleaning up some problems found after migration (we have at least one case where the TEI had the wrong id, and it seems easiest to just rename the file and migrate it so it gets attached to the correct PGPID)

**Comment by richmanrachel** [comment]
@blms - should this be closed?

**Comment by blms** [comment]
Not sure @richmanrachel, I'm not using the TEI migration script anymore so maybe it can be removed and the issue closed. Thoughts @rlskoeser?

**Comment by rlskoeser** [comment]
I hope we're not still using it at this point! based on my notes I removed and then put it back? so let's remove the old code and then close this. @blms is that appropriate for you to handle?

**Comment by blms** [comment]
Yes I can do that @rlskoeser!

**Comment by blms** [comment]
Done!
