### ISSUE TITLE
As a content editor, I want commit messages for transcription export data on GitHub to include PGPID so that I can more easily find the changes I'm interested in.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#1187]
## testing notes

Modify a transcription on the test site, wait ~5 minutes, then check that the commit on the test github export includes the PGPID of the document you were working on:
https://github.com/Princeton-CDH/test-pgp-annotations/commits/migration-test-run

question: is the repeated PGP - PGPID redundant? any suggestions for revising?

**Comment by mrustow** [comment]
It worked! 
<img width="458" alt="image" src="https://user-images.githubusercontent.com/73319225/195229707-5a53bee9-8bfb-43dc-9d23-d5aa8dd904c1.png">
The PGP - PGPID redundancy doesn't bother me at all.
