### ISSUE TITLE
OpenSeadragon navigator should not be visible on placeholder images

### ISSUE THREAD

**Issue by blms** [Princeton-CDH/geniza#1191]
## testing notes (QA)

- [x] In the transcription editor in the QA site, for a document (such as PGPID 1390) with more transcription blocks than images, confirm there is no "navigator" (the mini zoom position indicator with the red outline) in the top left of the gray placeholder rectangles.
- [x] Confirm the navigator is still present on the actual images.

**Comment by kseniaryzhova** [comment]
@rlskoeser @blms works for me! Closing!
