### ISSUE TITLE
generate a CSV of JTS IIIF manifests and DPUL view URLs from Figgy for import with new fragment url import script

### ISSUE THREAD

**Issue by richmanrachel** [Princeton-CDH/geniza#120]
## dev notes
This is the IIIF collection manifest for JTS Geniza images in figgy: https://figgy.princeton.edu/collections/d878ac93-2237-4731-a815-79ff46450e32/manifest

However, that doesn't give us the view urls on DPUL without reading individual manifests. Alternate solution, per slack conversation with Esmé:
> instead of having to resolve 2500 manifests, you could pull the ARKs from the Blacklight response:
https://figgy.princeton.edu/?f[member_of_collection_titles_ssim][]=Cairo+Geniza&per_page=100&format=json&page=1 (through page=26)

The last portion of the ark identifier can be used to generate the DPUL link like this:
`https://dpul.princeton.edu/[collection_slug]/catalog/[last_part_of_ARK]`

And the id can be used to generate the manifest in figgy like this: `https://figgy.princeton.edu/concern/scanned_resources/[figgy_id]/manifest`

Collection slug in this case is cairo_geniza — although the DPUL site is still not published, so testing the view urls may require either publishing the site or someone with access to the unpublished version.

Need to generate a csv file with headings `shelfmark,url,iiif_url`

**Comment by rlskoeser** [comment]
Changing this to a chore — we just need to generate a csv file that can be used with the same script we've implemented for the cambridge image urls.

**Comment by rlskoeser** [comment]
Closing this since we don't have to do it: PUL has agreed to generate a CSV for us when they have the files merged, published, and ARKs generated.
