### ISSUE TITLE
Digital edition switcher not present in admin

### ISSUE THREAD

**Issue by blms** [Princeton-CDH/geniza#1202]
## Testing notes (QA)

- [x] In the QA site admin for a document with multiple digitized transcriptions, such as PGPID 646, confirm you can click on "Edition: [Name]" (directly above the transcription text) and see a dropdown.
- [x] Confirm you can choose a different editor, and that it changes the visible transcription text to show the different editions.

## dev notes

In the admin ITT panel, for documents with multiple digital editions, the dropdown to switch between different digital editions does not appear.

- [x] Include in `iiif` bundle

**Comment by kseniaryzhova** [comment]
@rlskoeser @blms works for me! Closing!
