### ISSUE TITLE
As a Content Editor, I want to download a CSV version of all or a filtered list of documents in the backend, in order to data work or facilitate my own research.

### ISSUE THREAD

**Issue by richmanrachel** [Princeton-CDH/geniza#121]
## Testing Notes
There are two ways of downloading a document CSV in the document admin view, either by ticking the document checkboxes and selecting "Download as CSV" from the actions dropdown or by clicking the "Download all as CSV" in the top right corner of the page.

**Test the site:**
- [ ] Test the "Download all as CSV" button works.
- [x] Select a few documents and ensure that the actions dropdown works.

**Test the CSV**
- [x] Test the links in the CSV and ensure that they lead to the correct pages
- [ ] Confirm that all fields and header names are as expected.

---

**Fields**
Fields and field order as approved by PGP team

 - PGPID
 - link to public site (column name: url_public; or just url?)
 - fragment IIIF link* (column name: iiif_url)
 - link to view fragment on library site* (column name: fragment_url? view_fragment?)
 - shelfmark*
 - multifragment*
 - side*
 - extent_label* (rename to region?)
 - type
 - tags* (suggest displaying #tag1 #tag2 for consistency/familiarity; but could use semicolons)
 - description
 - footnotes (i.e editions & translations; include source, location, notes, and document relationship; pending data import)
 - historic shelfmarks* (column name: shelfmarks_historic)
 - languages*
 - probable languages* (column name: languages_probable)
 - language_note
 - notes (document only, not fragment notes)
 - needs_review (document only, not fragment)
 - link to admin change view (column name: url_admin)
 - input_by* (list all unique names of people who edited the record)
 - date_entered (first log entry date)
 - last_modified
 - status (i.e., public or suppressed — use display value, not code)
 - library abbreviation* (column name: library)
 - collection abbreviation* (column name: collection)

*multivalued or possibly multivalued fields; delimit with semicolons unless otherwise noted

**Default sort**
Which field should be used for initial sorting?

-----

## dev notes

We've used https://github.com/LibraryOfCongress/django-tabular-export in the past, and it does exactly what we need. It looks like it hasn't been updated in a while, but let's see if still works.  (I could ask on twitter if they're still using it or recommend something else; if appropriate, might be easy & nice to contribute an update for newer versions of django...)

fixes after first round testing:
- [x] for all multivalued fields (iiif urls, fragment url, subfragment): only generate if at least one fragment has a value (get rid of ";")
- [x] input by: output user fullname instead of user id
- [x] add deploy notes to remind us to set the site url in the database

**Comment by richmanrachel** [comment]
I'm not sure if this will work for fragments as well? But ideally we can use this from the languages/scripts section of the backend to, once you click into the document list.

Once we have the bibliography section up and running, I'll write a separate list of fields for that CSV download as well.

**Comment by rlskoeser** [comment]
@richmanrachel @mrustow I revised the user story slightly — to my mind this data export is important to support data curation work. It certainly can and should support research work as well, at least in the short term, but remember we plan to have a public-facing researcher download that will be more specific to researcher needs.

If you want to include fragment information in the documents download list, please include that in the list of fields (e.g., do you want to include library/collection in addition to shelfmark?). If you want a separate download of fragment data, please add another story for that.

With data curation needs in mind, I have questions about other fields you might want to consider including:
- What about text block information? (multifragment, text block / region, recto/verso)
- What about links to view the item, iiif urls?
- What about record/database edit information, date created / last modified in the database?

And a question about sorting — does it matter what order documents are listed in the export? Should we sort by PGID, by shelfmark?

**Comment by richmanrachel** [comment]
@rlskoeser - Marina and I think we need to have this conversation with you live rather than asynchronously. I'll add it to our Thursday agenda.

**Comment by rlskoeser** [comment]
Discussed in 4/15 meeting and determined that we want to include as much information as possible in the download. CDH team should propose the list of fields, but we do have permission to push back if there is anything we think is unreasonable/excessive to include. Where possible, we should follow the order of the current metadata spreadsheet, with the exception of urls — all urls (view, iiif, admin link, site link) should be included last.

**Comment by rlskoeser** [comment]
Here's what I propose for the list of fields, in this order:


- PGPID
- library abbreviation* (column name: library)
- collection abbreviation* (column name: collection)
- shelfmark*
- type
- tags* (suggest displaying #tag1 #tag2 for consistency/familiarity; but could use semicolons)
- description
- editions (from footnotes, pending data import)
- translations (from footnotes, pending data import)
- historic shelfmarks* (column name: shelfmarks_historic)
- side*
- extent_label* (rename to region?)
- multifragment*
- languages*
- probable languages* (column name: languages_probable)
- language_note
- notes (document only, not fragment notes)
- needs_review (document only, not fragment)
- status (i.e., public or suppressed — use display value, not code)
- input_by* (list all unique names of people who edited the record)
- date_entered (first log entry date)
- last_modified
- link to view fragment on library site* (column name: fragment_url? view_fragment?)
- fragment IIIF link* (column name: iiif_url)
- link to admin change view (column name: url_admin)
- link to public site (column name: url_public; or just url?)

* multivalued or possibly multivalued fields; delimit with semicolons unless otherwise noted

**Comment by richmanrachel** [comment]
@rlskoeser - That looks good to me! Thanks for putting time and thought into pushing us on this.

My only stylistic preference would be for languages to be displayed earlier, perhaps before the description. @mrustow: does this list look good to you?

**Comment by rlskoeser** [comment]
@richmanrachel thanks for the feedback! I put language information later because the are listed later in the current spreadsheet (I actually didn't put them as far back as the current spreadsheet has them).

I do wonder if editions and translations should continue to be separate fields; from what I understand of the data we have now, all translations are all also editions and the separate columns are a result of the way the data was added. Is there a more meaningful way to include this information? Could we include all scholarly sources in one field with indicators for what is available (edition, translation, discussion)?

**Comment by richmanrachel** [comment]
@rlskoeser - Got it!

I think that scholarly sources as we're developing that category is definitely more helpful than just the edition/translation columns. I would be in favor of shifting to the new system. I guess the question is how easy that is to do with the existing metadata?

**Comment by rlskoeser** [comment]
@richmanrachel scholarly sources would be easier for us to generate, since that's how we're modeling it in the database. Let's go with that unless you can think of any problems.

**Comment by richmanrachel** [comment]
@rlskoeser - perfect!

**Comment by mrustow** [comment]
I've reordered the fields and queried some here: https://docs.google.com/spreadsheets/d/1WnvqLQe-tt7WU_8TOV6FOkRUHrheKuNrfjoInieQzJQ/edit?usp=sharing

**Comment by rlskoeser** [comment]
Thank you @mrustow  — I'm glad you took the time to reorder the way you want them, my proposed order was very different!

I've added comments on the linked doc to try to answer your questions — let us know if you have further questions and/or when you're happy with the list and order of fields.

**Comment by rlskoeser** [comment]
@kmcelwee did we make this harder than it needed to be? or should it be a 3 instead of a 2?

**Comment by rlskoeser** [comment]
@richmanrachel CSV download for documents is available in the admin now, but we haven't written up test notes yet.

**Comment by richmanrachel** [comment]
@rlskoeser - I did a targeted search in the Documents section for "broker" and it came up with 18 entries. I dowloaded the CSV and it worked, though it was a little slow (almost as slow as downloading the whole metadata sheet).

Looking through the CSV, however, only one of the documents actually has the word "broker" in it. This is in contrast to the search page, where broker does appear in all the descriptions. 

The CSV downloaded 660 consecutive PGPIDs (444-1155) rather than the list pulled up on the website.

**Comment by richmanrachel** [comment]
And do you know what all these semi-colons mean?
![image](https://user-images.githubusercontent.com/68028846/118700160-5c0f5c80-b7e0-11eb-9b16-e8898bcfff81.png)

**Comment by richmanrachel** [comment]
I went back to check if this was an issue because I didn't formally hit the checkboxes, but I got the same download when I did check them:
![image](https://user-images.githubusercontent.com/68028846/118700617-dc35c200-b7e0-11eb-8457-cd0eba6999ba.png)

**Comment by richmanrachel** [comment]
When I used the action button it was successful at downloading the correct report.

**Comment by richmanrachel** [comment]
I'm a bit concerned about how the "Input_by" field is showing up:
![image](https://user-images.githubusercontent.com/68028846/118701670-fa4ff200-b7e1-11eb-9f86-5d36365ae33a.png)

**Comment by richmanrachel** [comment]
And just to clarify - did you want all the URLs for the admin and frontend to be example.com links rather than the test site?

**Comment by kmcelwee** [comment]
Hi @richmanrachel !

* Input by now has names, not numbers
* Semicolons were removed
* Example.com was changed to the correct address

We were unable to replicate your problem with the filtered download. The "Download all as CSV" button will always download all 30k documents, but if you want filtered results, you'll need to check all boxes and use the actions dropdown. Did you do both? I'm happy to quickly get on a zoom call with you if it's easier.

**Comment by richmanrachel** [comment]
> Test the "Download all as CSV" button works.
- It initiates a download (and when the download is small enough, like the one that just got cut off due to dev work) it works. But neither Marina nor I could download it yesterday, I think because the file was too big?
- The changes @kmcelwee made are great (yay, live links!). 

> Confirm that all fields and header names are as expected.
- I think it fits what Marina asked for. 
- I'm concerned that the file is too big and will only get bigger. What kinds of deletions or changes could we make/consider to make the CSV a more manageable download/size?

**Comment by rlskoeser** [comment]
@richmanrachel we may be able to optimize the download to some extent, but you make a good point about adjusting the fields. What if we separate fragment and footnote/source information into separate downloads and minimize that information in this download? What is the minimum amount of fragment information needed in the documents download for it to be useful?

**Comment by richmanrachel** [comment]
@rlskoeser - which fields are you thinking of in terms of fragment separation? I only see shelfmark (necessary) and fragment url (nice but hopefully already integrated into the public site view). 

I agree that footnotes could probably be moved into a separate download.

**Comment by rlskoeser** [comment]
Just excluding the footnotes would probably make a noticeable difference.

here are some fields pulled from fragment data that we could consider dropping:
- library abbreviation
- collection abbreviation
- historic shelfmarks
- fragment IIIF link
- fragment view link

**Comment by richmanrachel** [comment]
historic shelfmark needs to stay, but I'm happy to drop the rest.

**Comment by richmanrachel** [comment]
@rlskoeser - did you adjust the logic for download? Should I try it again?

**Comment by rlskoeser** [comment]
@richmanrachel I have been working on it and figured out some improvements, but they aren't on the test site yet

**Comment by richmanrachel** [comment]
@rlskoeser - the full download worked! It took 2 minutes in the browser to download, and then another 3 to open on my computer (which is just fine). The only thing that's confusing me is that it has 30,124 rows, despite the backend saying that there are 29,879 documents total...

Fields all look good! 

Full selection of searched-documents both on and off current page also a hit. (And for 300 docs took about 30 sec start to finish)

HOORAY! Closing :)

**Comment by rlskoeser** [comment]
Hooray, wonderful! We can look into the total rows / total documents issue — what did you open with? Excel / Numbers / ?

**Comment by richmanrachel** [comment]
@rlskoeser - Numbers
