### ISSUE TITLE
transcription labels in search results are RTL

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#1216]
transcription labels in search results are inheriting the RTL text direction we have set on the transcription block; we should exempt them (which we already do on the document detail view)

![Screen Shot 2022-10-26 at 4 20 23 PM](https://user-images.githubusercontent.com/691231/198128929-b95a0e9e-c027-4bff-bb38-eebf529114ff.png)

**Comment by kseniaryzhova** [comment]
@rlskoeser transcription labels seem LTR aligned to me - punctuation is where it should be, etc. Closing!
