### ISSUE TITLE
write a manage command that can generate the public export and sync to a configured github repo

### ISSUE THREAD

**Issue by quadrismegistus** [Princeton-CDH/geniza#1218]

**Comment by quadrismegistus** [comment]
Do we want the manage.py command to use PublicDocumentExporter by default, and AdminDocumentExporter if an argument set?

Do we want this command to use the SourceExporter you've just written?

**Comment by quadrismegistus** [comment]
Figured out an issue with relying solely on DictWriter to separate Public and AdminDocumentExporter: the same csv fields will appear in both exports even if the contents of say url_admin are empty. Working on that now

**Comment by rlskoeser** [comment]
My plan is that the new script will generate something like the pemm-data repository we had for PEMM, which you can look at here: https://github.com/Princeton-CDH/pemm-data  (now archived)

We should have data files and a datapackage for validation.

Once the repo exists, we can link to the flat github view of the data; here's an example from PEMM: https://flatgithub.com/princeton-cdh/pemm-data?filename=data%2Fmanuscript.csv&sha=6af68882a30832d7efca92ab807926b3d9488a29
(although it may be a little slow to load our documents file...)

In terms of the git logic, we're doing something similar in the `sync_annotation_export` manage command; I think the git logic is `geniza.corpus.annotation_export` — if it's simple, we could move the git logic into a base class that we use for annotation and metadata exports.  (First version of this script doesn't need to include log entry & co-author commit logic, I think we have a separate issue for that.)

Here's the production data repo for transcriptions: https://github.com/princetongenizalab/pgp-text 
And here's the one I setup for testing the sync annotation functionality: https://github.com/Princeton-CDH/test-pgp-annotations.

I added local settings config options for the annotation repo and path; I imagine we'll need something similar for this one.

**Comment by rlskoeser** [comment]
tested and completed as part of #1097
