### ISSUE TITLE
documents in admin should be sorted by shelfmark by default

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#1219]
reported by Alan on Slack — I think this is a regression in v4.10 related to the changes we made for the document export

the `ArrayAgg` annotation is still present  (included in `metadata_prefetch` and probably shouldn't be, I think we only need for admin) but we lost the default sort for the admin queryset

## dev notes
- [x] move shelfmark query aggregation from `metadata_prefetch` to the document admin queryset method
- [x] sort by shelfmark by default in document admin queryset
- [x] revise `shelfmark_display` property on `Document` class to use the aggregation property `shelfmk_all` for admin sorting — should be able to add it to the existing `admin.display` decorator (this should make the column clickable in admin for combining / reversing sort)

**Comment by quadrismegistus** [comment]
Should we close this?

**Comment by rlskoeser** [comment]
Tested in admin on qa site — there's a long join showing up first and I'm not sure exactly why (my guess: aggregated shelfmark doesn't follow document / textblock order; this one doesn't show in my local dev instance, but my data is out of date). Otherwise it looks like records are sorted by shelfmark, and shelfmark is clickable to adjust sort order. This should address the immediate regression.
