### ISSUE TITLE
Include two placeholder images for each fragment associated with a document

### ISSUE THREAD

**Issue by kseniaryzhova** [Princeton-CDH/geniza#1229]
## Testing notes

On the [QA site](https://test-geniza.cdh.princeton.edu/), find a few documents that include fragments with missing images: documents with no images whatsoever, and joins where only some of the fragments have images. For each of these types:

- [x] There should now be two placeholder images for each fragment that does not have any images.

(see also #1230)

---

**Is your feature request related to a problem? Please describe.**
When a join has fragments that both do and do not have IIIF images, there are no placeholder images for the fragments without IIIF images. This makes it impossible to attach transcriptions to the correct fragment (we have had to attach to the fragments with IIIF images). Ex: [https://geniza.princeton.edu/en/documents/35279/](https://geniza.princeton.edu/en/documents/35279/)

**Describe the solution you'd like**
I would like for two placeholder images to be generated for every fragment associated with a document (so for a fragment that has transcription but no image)

**Additional context**
We have placeholder images for documents without images but with existing transcriptions, the issue is when the document contains some but not all IIIF images (like joins).

**Comment by richmanrachel** [comment]
One additional detail I had in mind to prevent clutter: Is it possible for the two placeholder images to appear on the backend, but not the frontend unless actively selected?

I imagine the logic for this might be challenging, so feel free to disregard if it's too much of a barrier.

**Comment by kseniaryzhova** [comment]
@blms and they have the shelfmark name with the recto and verso indicated - woo! Closing, thank you!
