### ISSUE TITLE
Design mobile and tablet wireframes of the cluster view browse results page to communicate the content structure, page layout, and content variations to the project team

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/geniza#123]
- [x] content structure 
- [x] content structure variations depending on what element(s) in the network is/are being browsed
- [ ] language and labeling of content and functionalities 
- [x] page layout
- [x] page layout when any field is missing, e.g. images

**Comment by gissoo** [comment]
The designs [here](https://www.figma.com/file/HpGBOZi9lO8B3nCAx3d4Fj/Princeton-Geniza-Project-team?node-id=739%3A199) have been reviewed by the dev team and the project team. 
The designs for this issue consist of the following for mobile and tablet: 
1. list of of documents that are shown when a term that belongs to one cluster/region has been selected 
2. list of documents that are shown when a term that belongs to multiple clusters/regions has been selected
3. list of documents that are shown when a cluster/region has been selected 
4. pagination 
5. cluster information, however its position on the page and the types of information that it consists of may be changed depending on our approach. 
6. list of documents consist of:
- terms that are associated with the document 
- cluster names/regions (this is pending and may not be valid if we decide to not name clusters and rather rely on a more visual approach on the visualization to show topical regions) 
- shelfmark number
- document date original
- document date converted
- input date 
- description excerpt
- transcription excerpt 
- whether a document has discussions and translations as part of its scholarship records (discussion and translation) - agreed to not show transcription here
- fragment image thumbnail
- whether the document has more than one image thumbnail through a visual cue (layered image effect)
- variations are shown when there is no image, transcription, description, and scholarship records

Note: on this issue the visualization needs to be ignored, they are shown just to help communicate the variations in the list of results. 

@richmanrachel @mrustow Please read the above and let me know if you think of anything that is missing here – I will close this issue for now.

**Comment by richmanrachel** [comment]
@gissoo - Looks good to me!
