### ISSUE TITLE
Design mobile wireframes of the search results page to communicate the content structure, page layout, and content variations to the project team

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/geniza#124]
- [x] content structure 
- [ ] language and labeling of content and functionalities 
- [x] page layout
- [x] page layout when any field is missing, e.g. images

**Comment by gissoo** [comment]
The designs here have been reviewed by the dev team and the project team.
The designs for this issue consist of the following for mobile and tablet:
1. list of of documents when a term has been searched for 
2. highlighted searched term in the results (can be in description, transcription, and the document terms)
3. pagination 
4. list of documents consist of:
- result number
- terms that are associated with the document
- shelfmark number (will show designs for this in a different issue – needs to be experimented with based on our discussions last week) 
- document date original
- document date converted
- input date
- description excerpt
- transcription excerpt
- whether a document has discussions and translations as part of its scholarship records (discussion and translation) - agreed to not show transcription here
- fragment image thumbnail
- whether the document has more than one image thumbnail through a visual cue (layered image effect)
    variations are shown when there is no image, transcription, description, and scholarship records

@richmanrachel @mrustow Please read the above and let me know if you think of anything that is missing here – I will close this issue for now.

**Comment by richmanrachel** [comment]
@gissoo - I love the layered images to indicate multiple photos!

Curious to see how the shelfmark/PGP ID developments go.

I don't know whether it would help or hurt, but it seems like having 3 lines of dates is excessive. Could we do: Converted date (Original Date) ?

**Comment by gissoo** [comment]
@richmanrachel credits to Nick for bringing up that idea about the layered images! I had used it at some point for the document detail view but totally forgot that we can use it here!! 

- Re: shelfmark/PGP ID – I will create another issue so we can discuss variations/options design-wise. 
- Re: dates for lines – I agree that they seem excessive right now, I forgot to say above, with data such as dates, and location once we have some actual data and all the possible varieties with it the dev team will open issues for me to get back to the design in more detail – right now the designs are acting more as placeholders and in the case of the dates: just to show that there will be a original date field and a converted date field.
