### ISSUE TITLE
Design wireframes of the filters and sort options on mobile, tablet, and desktop to communicate the ways in which content can be curated when searching 

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/geniza#125]
Here are the filters for [mobile](https://www.figma.com/file/HpGBOZi9lO8B3nCAx3d4Fj/Princeton-Geniza-Project-team?node-id=756%3A1326), [tablet](https://www.figma.com/file/HpGBOZi9lO8B3nCAx3d4Fj/Princeton-Geniza-Project-team?node-id=756%3A1516), and [desktop](https://www.figma.com/file/HpGBOZi9lO8B3nCAx3d4Fj/Princeton-Geniza-Project-team?node-id=758%3A460) 

- [x] content structure 
- [x] content structure variations depending on whether cluster view is on or off
- [ ] language and labeling of content and functionalities 
- [x] page layout
- [x] interaction with filters + states + sort

Note: The filters that are provided in search and for cluster view are exactly the same.

**Comment by gissoo** [comment]
The designs for [mobile](https://www.figma.com/file/HpGBOZi9lO8B3nCAx3d4Fj/Princeton-Geniza-Project-team?node-id=756%3A1326), [tablet](https://www.figma.com/file/HpGBOZi9lO8B3nCAx3d4Fj/Princeton-Geniza-Project-team?node-id=756%3A1516) and [desktop](https://www.figma.com/file/HpGBOZi9lO8B3nCAx3d4Fj/Princeton-Geniza-Project-team?node-id=758%3A460) have been reviewed by the dev team and the project team.
The designs for this issue consist of the following primarily based on the sitemap:
1. input fields for document date (as range)
2. transcription filter (whether a document has it, as options to be checked or unchecked) – with number of documents that have it
3. translation filter (whether a document has it, as options to be checked or unchecked) – with number of documents that have it
4. discussion filter (whether a document has it, as options to be checked or unchecked) – with number of documents that have it
5. document type drop down options – with number of documents for each type
6. geographical locations drop down options – with number of documents for each location
7. toggle to turn the cluster view on and off **(I will need to experiment with this further in another issue)**

Sort options to show the list of results by:
1. Document date
2. Input date
3. Scholarship records (highest-lowest)
4. Scholarship records (lowest-highest) 

note: 
- the need for seeing documents that have no scholarship records and those that have many was brought up by Marina, RSK suggested the sort options #3 and #4 for this need. 
- the need for a more specific filter for "from" and "to" location input for letters was brought up by Rachel, we think this is too specific to be a filter at this point – we would like to make sure that what is built will be useful to researchers and to make sure we focus on the data we have for right now. However, I will document this idea. 

Note: 
- We are trying to avoid implementing reactive search, where the results will change as soon as you hit a filter or as soon as you begin typing in a keyword, and rather have a "search" and "apply" button for the search and the filters. Because of this, next to the search box there will be a icon button on desktop that needs to be selected in order for results to show up (or the user can select enter on their keyboard) – on tablet and mobile the keyboard will have a "search" button that the user will select.  

- Based on all the conversations with the dev team and the project team and after trying a few variations I have decided to keep the filters more consistent across screen sizes and have a filter icon below the search box which opens up a modal when selected where all the filters reside. There will be an "apply" button along with the filters that the user will need to select in order for the results to be shown and/or updated. 


@richmanrachel @mrustow Please read the above and let me know if you think of anything that is missing here – Question for you and for @rlskoeser: the "document date" and the "input date" sort options, do we want to have:  
"most recent - least recent" or "least recent - most recent"? what order do we want to offer for these sort options?

**Comment by richmanrachel** [comment]
@gissoo - Overall, looks good! One question I have around dates, is if we want/if it's feasible to have an option to search only for documents with internal dating (i.e. written on the document, not via scholarly deduction)? This could potentially be achieved by searching only for "original dates" without a converted date.

> the need for a more specific filter for "from" and "to" location input for letters was brought up by Rachel, we think this is too specific to be a filter at this point – we would like to make sure that what is built will be useful to researchers and to make sure we focus on the data we have for right now. However, I will document this idea.
- I guess the question that remains for me is whether we're including the mention of any geographic location versus where the document is from? If the former, than letters can simply be marked with both locations.

> "most recent - least recent" or "least recent - most recent"? what order do we want to offer for these sort options?
- Can we have both?

**Comment by gissoo** [comment]
> @gissoo - Overall, looks good! One question I have around dates, is if we want/if it's feasible to have an option to search only for documents with internal dating (i.e. written on the document, not via scholarly deduction)? This could potentially be achieved by searching only for "original dates" without a converted date.
> 

- @richmanrachel I think this makes sense as keyword search not as a separate date filter, as long as the internal dating would appear on the results list as part of the description excerpt (maybe as part of its notes?) where it would be highlighted if I understand you correctly – but I would defer to @rlskoeser – I'm not sure this would make sense as its own filter. Otherwise, can we incorporate it to the filters we have already discussed?

> > the need for a more specific filter for "from" and "to" location input for letters was brought up by Rachel, we think this is too specific to be a filter at this point – we would like to make sure that what is built will be useful to researchers and to make sure we focus on the data we have for right now. However, I will document this idea.
> 
>     * I guess the question that remains for me is whether we're including the mention of any geographic location versus where the document is from? If the former, than letters can simply be marked with both locations.
> 

- Let's discuss this at one of our meetings – it depends on what it is more important and consistent across more document types 

> 
> > "most recent - least recent" or "least recent - most recent"? what order do we want to offer for these sort options?
> 
>     * Can we have both?
>
- I think both will make sense to me but would like to hear @rlskoeser 's thoughts on this too.

**Comment by rlskoeser** [comment]
I agree that original/unconverted date should be included in the keyword search fields.  (Right now I'm not sure how this could work anywhere else, but maybe we'll know more when we've actually modeled this and have examples).

I'm not sure about the geographic questions either, also because I'm not sure we've decided how to structure locations yet. I do think we should avoid adding filters that are specific to particular types, but would make sense to me to allow searching on any associated locations.

I'm ok with having both sort options (most recent / oldest) for document date — although I do wonder how well sorting on document date will work when we know we will have variable date precision. I'm not sure we should have both for input date, though — it seems like that could start to clutter the sort options. Do we have a use case for this? If it's to find the most recently added items, can we just offer most recent first?

**Comment by gissoo** [comment]
I have revised the sort options [on this page](https://www.figma.com/file/HpGBOZi9lO8B3nCAx3d4Fj/Princeton-Geniza-Project-team?node-id=721%3A134) so that now there are: 

- scholarship records (highest–lowest)
- scholarship records (lowest–highest)
- document date (latest–earliest)
- document date (earliest–latest)
- input date (latest–earliest)
- input date (earliest–latest)

I'll close this issue for now.

**Comment by rlskoeser** [comment]
@gissoo I apologize that I didn't catch this before! What does "scholarship records (highest-lowest)" and "(lowest-highest)" mean? Is it the number of scholarship records for each item? I have questions about wording and also about how you would propose we "count" this for sorting purposes — should we discuss those now?

Also, if we're sorting on the "amount" of scholarship (however quantified), then I think we need to show that (in some way) on the search results — the check mark in your current design isn't enough information.
