### ISSUE TITLE
Searching descriptions for words/phrases in quotations works unpredictably

### ISSUE THREAD

**Issue by kseniaryzhova** [Princeton-CDH/geniza#1255]
## testing notes

In the [QA site search](https://test-geniza.cdh.princeton.edu/en/documents/):
- [ ] Try the two searches mentioned in the bug report below, as well as some other exact phrases, and confirm results are as expected
  - Note that while only exact matches will appear, the actual text "Abū l-Munā" won't be highlighted in results. This is due to the "l-". Let me know if it's worth investing the additional ~3-5 hours to address this.
- [ ] Try some searches with both quoted and not quoted phrases, such as `"he decided" buy` and `"he decided" AND buy`

---

**Describe the bug**
Searching for phrases such as "he divorced" in quotations yields 12 results, none are precise matches but are very close. Searching for full names such as "Abu l-Muna" or even "Abū l-Munā" (both attested in the descriptions) yields 0 results

**To reproduce**
1. Go to [public site search](https://geniza.princeton.edu/en/documents/)
2. Search for "Abū l-Munā" (with quotations)
3. [See results ](https://geniza.princeton.edu/en/documents/?q=%22Ab%C5%AB+l-Mun%C4%81%22&docdate_0=&docdate_1=&sort=relevance)
4. Repeat with a non-name phrase such as "he divorced". [See results.](https://geniza.princeton.edu/en/documents/?q=%22he+divorced%22&docdate_0=&docdate_1=&sort=relevance)

**Expected behavior**
I want search terms in quotations to give precise results (while still ignoring diacritics) no matter what Latin script word or phrase I'm searching for. Searches for "Abu l-Muna" or "Abū l-Munā" should pull up at least a dozen (if not more) exact matches.

**Comment by kseniaryzhova** [comment]
@blms Searching "Abū l-Munā" brings back 117 precise results with diacritics. Searching "Abu l-Muna" brings back 117 of the same exact results.

**Comment by blms** [comment]
Marking as closed based on meeting discussion 3/1/2023. We agreed that:
- The comments above (searching without diacritics bringing up diacritic results, and vice versa) is the desired behavior
- Further work will be tracked in #1335, and further issues as they arise
