### ISSUE TITLE
Spreadsheet of all the existing fuzzy or uncertain dates in the PGP (marked by the word "dating") 

### ISSUE THREAD

**Issue by kseniaryzhova** [Princeton-CDH/geniza#1262]
**Is your feature request related to a problem? Please describe.**
We are currently designing for an event model and we know we have a lot of fuzzy and uncertain dates. We need to know what those fuzzy and uncertain dates are and how they are represented in the description fields so we know how they should be captured in the event model.

**Describe the solution you'd like**
We would like @blms to use his magic and find all instances of the word "dating" (indicating uncertain or fuzzy dates) in the document descriptions, as well as the dating information that comes after this word. We would like the results to be in a spreadsheet. Thank you!

**Comment by blms** [comment]
Done using the following Django shell script:

```py

from geniza.corpus.models import Document
from django.db.models import Q
import csv

docs = Document.objects.filter(Q(description__contains="Dating")|Q(description__contains="dating")).order_by("pk")
with open("dating.csv", "w", newline="") as csvfile:
    fieldnames = ["PGPID", "Dating", "Description"]
    writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
    writer.writeheader()
    for d in docs:
        splitstr = "Dating" if "Dating" in d.description else "dating"
        # some additional processing can be done before splitting by "." to ensure "ca." and "c." are captured
        dating = d.description.split(splitstr, 1)[1].split(".", 1)[0]
        writer.writerow({"PGPID": d.pk, "Dating": dating, "Description": d.description})
```

and shared on Google Sheets.
