### ISSUE TITLE
Transcription search results not always formatted correctly 

### ISSUE THREAD

**Issue by kseniaryzhova** [Princeton-CDH/geniza#1269]
### testing notes

On the [QA public site search](https://test-geniza.cdh.princeton.edu/en/documents):
- [x] Transcription snippets should not have wrongly aligned lines (at least in the cases where the lines are numbered in the actual transcription)
  - [x] Try the below search `אסאל אללה` 
- [x] Line numbers should generally be present (when numbered in the actual transcription), even for lines that only partially appear in the search result, in which case there should be an ellipsis to indicate incompleteness (for example, line 4 in the transcription snippet for the search `pgpid:3567`)
  - This won't work 100% of the time, since it's just trying to guess whether a line is incomplete and needs a number, but should be generally fairly accurate

---

**Describe the bug**
Transcription search results sometimes have text or other characters above the result that are not formatted like a line in a transcription and thus look random/out of place. This is LOW priority. 

**To reproduce**
1. Go to public site search.
2. Search for אסאל אללה
3. [See results](https://geniza.princeton.edu/en/documents/?q=%D7%90%D7%A1%D7%90%D7%9C+%D7%90%D7%9C%D7%9C%D7%94&docdate_0=&docdate_1=&sort=relevance)

For other search results for transcription content this is not as common but still occurs. 

**Expected behavior**
I expect transcription content to appear with a line item beside it (so we can find the exact line when we click into the document detail page). If the text/other characters are not part of the transcription, they should either not appear (if they do not contain the results) or should appear somewhere else in the correct format (if part of the description, should appear in the description, not right above the transcription content)

**Screenshots**
![image](https://user-images.githubusercontent.com/105385128/206483277-a684c2fb-d0b9-434a-8253-6124d2c4cd5c.png)

**Comment by kseniaryzhova** [comment]
@blms is this related to the issue of transcriptions of varying lengths showing up when we have a specific transcription keyword [search[](url)](
Uploading Search Documents - Google Chrome 2024-02-05 15-35-52.mp4…
)

**Comment by kseniaryzhova** [comment]
@blms is this related to the issue of transcriptions of varying lengths showing up when we have a specific transcription keyword
Uploading Search Documents - Google Chrome 2024-02-05 15-35-52.mp4…

**Comment by blms** [comment]
@kseniaryzhova Looks like your video didn't go through, but I don't think it's related. This is happening because it's pulling a few words of context from the end of a line, so it doesn't include the opening tag from that line. Something like this in the HTML:
```html
... of line 1</li>
<li>Text of line 2</li>
<li>Text of line 3</li>
```

**Comment by kseniaryzhova** [comment]
@blms 
<img width="1171" alt="image" src="https://github.com/Princeton-CDH/geniza/assets/105385128/40fa880c-84fa-4101-ad99-812705219236">
See above, when the lines are incomplete, there is often no line number shown (even when it exists in the transcription)

**Comment by kseniaryzhova** [comment]
@blms works as it should, thanks! Closing!
