### ISSUE TITLE
As a global admin, I want new documents created in the database after data import to receive PGPIDs higher than the highest imported PGPID, so that identifiers will be unique and semi-sequential.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#127]
## testing notes
Create a new document record in the system after the data import has run and existing documents have been imported. Confirm that you can save the document, and the PGPID for the new record is a high number (it should be one higher than the highest PGPID imported, but it's ok if you don't have a way to test that — without this update it was a very low number, likely based on many test records have been manually added to the system.)

## dev notes
- data import script needs to update the auto-increment sequence after all documents are imported

**Comment by richmanrachel** [comment]
It works! Yay, closed :)

**Comment by richmanrachel** [comment]
Wait - @rlskoeser - we couldn't add a shelfmark...

**Comment by rlskoeser** [comment]
Documents get their shelfmark by association with fragments — try adding a fragment via text block

**Comment by richmanrachel** [comment]
> Documents get their shelfmark by association with fragments — try adding a fragment via text block
- Yes, this worked. I'm not sure I like how it works though... When we experiment on Tuesday with complex docs, we might come up with some suggestions. 

But the PGP ID generation works, so I'll close for real :)
