### ISSUE TITLE
Autofill for source search (when inputting a transcription source) not functioning properly

### ISSUE THREAD

**Issue by kseniaryzhova** [Princeton-CDH/geniza#1275]
### testing notes

On the [QA site](https://test-geniza.cdh.princeton.edu/), add a new transcription or translation. On the page where you choose a source, entering any of the following should bring up the expected results for each:
- [x] `Goitein, the Renewal`
- [x] `Goitein CUL`
- [ ] `S. D. Goitein`
- [x] `Marina Rustow`
- [x] `Rustow, Marina`

---

**Describe the bug**
When choosing a source for a transcription in the editor, search functionality in the drop down is not intuitive and difficult to navigate especially for transcription authors with a lot of different sources (like Goitein). 

If you type in Goitein you get dozens of his sources and have to scroll for a long time to get to the one you want. If you type in Goitein CUL (to reference the specific unpublished edition volume), you get no results. If you type in S. D. Goitein (which is how the sources are formatted for Goitein), you get nothing. Likewise, typing in Marina to get Marina Rustow unpublished editions gets you nothing, but Rustow gets you to the right results. 

Per Alan, "Goitein, the Renewal" not working but just "Renewal" is.

**To reproduce**
1. Go to any PGPID with an image.
2. Click "Add transcription"
3. In the source page, type in the following order: Goitein, S. D. Goitein, Goitein CUL, Rustow, Marina 
4. See behavior for each of the terms (delineated by commas)

**Expected behavior**
I want any key terms present in a source (ex: author first and last names as well as collection names, etc) to bring up the relevant source when it's typed into the search bar. 

**Additional context**
[Video demonstrating issue.
](https://princeton.zoom.us/rec/share/3mEfhR1XFQ4rrYnnOyDZmeyDYnFILinkI-li6aYxeI9x6cQBfbHc1TXbcGxa8CM.39R4OvWQrukF9VVS?startTime=1671034046000)

**Comment by kseniaryzhova** [comment]
@blms S.D. Goitein only shows up if you add a space after each of the first two letters, S. D. Is there an easy fix for this? So that typing in S.D. gives you the correct results as well? If it's too complicated, I can live without.

**Comment by blms** [comment]
@kseniaryzhova I don't think so, since without writing a search backend with relevance scores, we can only really search for exactly how it's formatted on the source. Ok to close as completed?

**Comment by kseniaryzhova** [comment]
@blms yeah definitely, thanks!
