### ISSUE TITLE
As a content editor working on transcriptions, I want to be able to move transcriptions from one document to another, so that I can fix a mistake if a transcription was associated incorrectly.

### ISSUE THREAD

**Issue by blms** [Princeton-CDH/geniza#1280]
## Testing notes

In the QA site admin, in the Footnotes section, find a Digital Edition footnote. In the "object id" field, change the PGPID to another (valid) document PGPID. 

- [x] Confirm that the transcription is no longer on the old document.
- [x] Confirm that it is present on the new document, but attached to placeholder images, and can be moved onto the correct images using the transcription editor.

**Comment by kseniaryzhova** [comment]
@blms works well for me! Thank you, closing!
