### ISSUE TITLE
Prevent content editors from clicking more than one option for a digital edition, and explain to them the difference between edition and digital edition.

### ISSUE THREAD

**Issue by kseniaryzhova** [Princeton-CDH/geniza#1285]
## Testing notes

In the [QA admin site](https://test-geniza.cdh.princeton.edu/admin/), open a Document for editing. (Do a hard refresh just in case.)
- [x] In the "Footnotes" section, hover over the question mark icon next to the "doc relation" column header. You should see the full help text here.
- [x] You should be prevented from selecting both "edition" and "digital edition" at the same time for a footnote.
- [x] If you click the "Add another Footnote" link at the bottom of the footnotes list to add more footnotes, you should not be able to select both "edition" and "digital edition" simultaneously for any one of the new footnotes in the list.

Go to the Sources section in the admin, and click on a source to edit it.
- [x] All of the above should be true for the "Footnotes" section there as well.

Go to the Footnotes section in the admin and create a new footnote.
- [x] You should not be able to select both "edition" and "digital edition" here either.
- [x] The help text should be written out beneath the doc relations options.

---

**Is your feature request related to a problem? Please describe.**
Because we use the term footnote for both edition and digital edition, content editors are confused as to why these are kept separate and often try to merge the two (and this creates other problems).

**Describe the solution you'd like**
We would like two things:
1. Help text to help explain the difference between a digital edition and an edition (even if they come from the same source). It should live in two places: (a) the Document edit pages in the admin at the top of the section where you edit footnotes, and (b) in the individual Footnote edit pages in the admin.
2. When adding a footnote, you should not be able to click both digital edition and edition for the same footnote, even if the source is identical.

---

## dev notes

script to find the footnotes that have both relations currently:
```py
Footnote.objects.filter(
    Q(doc_relation__contains="X") & Q(doc_relation__contains="E")
)
```

right now there are only ~9 of them, so cleanup manually.

- [ ] split existing records manually
- [x] JS in admin to disallow clicking both checkboxes
- [x] update help text

see also #1212

**Comment by kseniaryzhova** [comment]
@blms For the footnotes, the help text is cut off 
![image](https://user-images.githubusercontent.com/105385128/212401573-2a3cbeba-9f3f-4408-99d8-11eafa971b2c.png)
PGPID 448, but it's the same on a few others I clicked randomly.

**Comment by blms** [comment]
@kseniaryzhova Can you try a hard refresh and see if that fixes it?

**Comment by kseniaryzhova** [comment]
@blms I just attempted - it does not fix the issue, still cut off.

**Comment by kseniaryzhova** [comment]
@blms just tested on Chrome (was on Edge before) and the text displays in full. Closing, thank you!
