### ISSUE TITLE
Bracket and other character search is functioning unpredictably 

### ISSUE THREAD

**Issue by kseniaryzhova** [Princeton-CDH/geniza#1286]
### testing notes (round 2)

On the [QA public search](https://test-geniza.cdh.princeton.edu/en/documents/):
- [x] All of the below should still work
- [x] Now when searching for words _without_ the sigla in your search query, they should be highlighted in the search results, even when the result contains sigla
- [x] Searching _with_ sigla should still work as long as you use double quotes (it will not work unquoted) and should still highlight

### testing notes

On the [QA public search](https://test-geniza.cdh.princeton.edu/en/documents/):
- [x] Searching exactly for terms with sigla in them, like [`"وسـ[ـعرهـ]ـم"`](https://test-geniza.cdh.princeton.edu/en/documents/?q=%22%D9%88%D8%B3%D9%80%5B%D9%80%D8%B9%D8%B1%D9%87%D9%80%5D%D9%80%D9%85%22&docdate_0=&docdate_1=&sort=relevance), in double quotes should bring up the correct transcription(s) containing only results with those exact sigla in them
  - [x] The terms, with the sigla, should be highlighted in the result
- [x] Searching for the word [`وسعرهم`](https://test-geniza.cdh.princeton.edu/en/documents/?q=%D9%88%D8%B3%D8%B9%D8%B1%D9%87%D9%85&docdate_0=&docdate_1=&sort=relevance) without sigla or connectors, without double quotes, should bring up PGPID 9157 again, but ranked lower in relevance than those already containing that word without sigla
  - [x] The term with the sigla should NOT be highlighted in that result ~~(unfortunately not feasible with the current approach)~~
- [ ] The same general behavior should be true for other sigla, and work for Hebrew script as well

---

**Describe the bug**
Some of our transcription content is incomplete and there are often lacunae in words that are represented in the transcriptions via brackets and other chracters such as  < { ⟦ . ـ). Currently, adding brackets to search terms adds irrelevant results that are not the actual word but are just other texts with brackets/lacunae.

**To reproduce**
See video. But also (on the public search):
 1539 results for كتاب 
 4522 results for كت[ا]ب
 4454 results for كتـ[ـا]ب
1 result for just the connector ـ

**Expected behavior**
In a simple search (without quotations or boolean operators, etc), we want search results to include brackets and other characters such as  < { ⟦ . ـ if they're relevant. So كتاب should bring up searches for كتـ[ـا]ب as well and so on.

In a search with quotations or other specifications, we want search terms which include brackets to bring back brackets and we want search terms which exclude brackets and other characters to bring back results without brackets and other chracters.

**Screenshots**
Video of issue here: [https://princeton.zoom.us/rec/share/r84y45cKQSh3YzIUXMknd8iWDtff1cBQVnyUunr34bwmRqk-oEt3fdq16eh11Ck.UatunUGgPeBoINXJ?startTime=1671033531000](https://princeton.zoom.us/rec/share/r84y45cKQSh3YzIUXMknd8iWDtff1cBQVnyUunr34bwmRqk-oEt3fdq16eh11Ck.UatunUGgPeBoINXJ?startTime=1671033531000)

**Comment by blms** [comment]
Interesting note here. The issue encountered with using Cmd-F and searching for the connector in the body of a page seems to be a Chrome browser limitation, not related to PGP. It works fine in Safari and Firefox on [PGPID 8314](http://localhost:8000/en/documents/8314/) but not on Chrome! (You can even see that such a search fails on [this Wikipedia article](https://en.wikipedia.org/wiki/Kashida) in Chrome only.)

As for brackets: Working on a fix now that will at least let you search `"كت[ا]ب"` in double quotes and it will bring up the correct document. We likely won't be able to get it to work such that searching `كت[ا]ب` without double quotes will bring up the right content. 

What I might be able to do is, as described in the video, allow a search that "ignores" those brackets. In this case, we would populate a separate index where `كت[ا]ب` gets indexed as `كتاب`, and searching for the latter will bring up the correct transcription. (Though it might not be possible to highlight it.)

Question: can you provide the full list of characters that should be treated like brackets? It needs to include both opening and closing characters for any applicable (i.e. both `[` and `]`). That way, we can tell the indexer exactly what to "ignore" for this second index.

**Comment by blms** [comment]
Another question: Is it ok if using double quotes turns off matching Judaeo-Arabic results when searching in Arabic ([this feature](https://github.com/Princeton-CDH/geniza/issues/706))? It breaks queries with brackets like `"كت[ا]ب"`.

**Comment by blms** [comment]
Note from Slack: when searching for complete words, we don't want to ignore the Arabic connector when it actually appears in a word. However, we do want to ignore it in the following two cases:
  - Appearance at the very beginning or end of a word.
  - Appearance immediately before or after sigla. At least `[]`, `〚〛`, and `\\//` may have connectors before or after them.

**Comment by kseniaryzhova** [comment]
@blms So the non-sigla search does bring up the correct result, but it does not even show the correct line so there's no way to tell at a glance if it's the right result without clicking into the transcription.
<img width="918" alt="image" src="https://github.com/Princeton-CDH/geniza/assets/105385128/c21a176a-cbf2-490c-8aaa-98ee92d392c6">

**Comment by kseniaryzhova** [comment]
@blms Searching some other sigla gives weird results as well, I tried كتـ[ـا]ب, with quotations I got 0 results, without quotations I got 1.624 but as far as I could tell they were irrelevant (the second result only had a discussion so there was no transcription content at all).
<img width="881" alt="image" src="https://github.com/Princeton-CDH/geniza/assets/105385128/61042056-7c98-4feb-ab82-ff7b2df2079c">

**Comment by blms** [comment]
@kseniaryzhova 

>  but it does not even show the correct line so there's no way to tell at a glance if it's the right result without clicking into the transcription

Right, unfortunately there's no way (as far as I can work out) to highlight the result with the sigla, when the search term doesn't include the sigla. Highlighting, in this case, includes being able to tell where in the transcription it appears. Is it sufficient that the document matches in this case, or is it necessary to know where in the transcription it appears?

>  I tried كتـ[ـا]ب, with quotations I got 0 results

Can you let me know which document should come up for this query? That way I can troubleshoot why its transcription isn't being indexed properly. If that exact sigla pattern shows up in a transcription, it should show up when you use the double quotes.

> without quotations I got 1.624 but as far as I could tell they were irrelevant

Yes, unfortunately we can't really handle that since without double quotes the query will be broken up by any special characters. So what that search actually is saying is `كتـ OR ـا OR ب`. If you wanted to search without quotes you'd also need to remove the sigla. I would recommend [documenting that in "how to search"](https://github.com/Princeton-CDH/geniza/issues/1547) so people aren't confused by it.

**Comment by kseniaryzhova** [comment]
@blms it's perfect, thank you! Closing!
