### ISSUE TITLE
De-selected images display yellow border in viewer and editor when no image on TextBlock is selected

### ISSUE THREAD

**Issue by kseniaryzhova** [Princeton-CDH/geniza#1295]
## Testing notes

In the [QA site admin](https://test-geniza.cdh.princeton.edu/admin), edit a document that joins multiple fragments. On one of the joined fragments, deselect _all_ images and save. The document should no longer show the yellow border for the deselected images. The same should be true if you only deselect _some_ of the images on the fragment.

---

**Describe the bug**
Deselected images in the related fragments section still have a yellow border around them in both the viewer and the transcription editor (indicating they are part of the PGPID). 

**To reproduce**
1. Go to [Halper 389 ](https://geniza.princeton.edu/admin/corpus/document/2587/change/?_changelist_filters=q%3DHalper%2B389%26textblock__fragment__iiif_url__isempty%3D0%26transcription%3Dyes)or [Halper 414](https://geniza.princeton.edu/admin/corpus/document/35364/change/?_changelist_filters=q%3DHalper%2B389).
2. In the related fragments section, select the correct fragment and de-select the other fragment.
3. See error.

**Expected behavior**
When I purposefully deselect fragment images, I want the yellow border to be removed in both the viewer and the editor, to serve as a visual clue that those images do not belong with this PGPID.

**Comment by blms** [comment]
Closing as `wontfix` per meeting on 2/1/2023. Current behavior is acceptable.
