### ISSUE TITLE
As a content admin, I want to be able to enter uncertain dates with descriptors (exact year unknown but year range is known)

### ISSUE THREAD

**Issue by kseniaryzhova** [Princeton-CDH/geniza#1297]
**Is your feature request related to a problem? Please describe.**
Many Geniza documents are dated inferrentially - there is no year on the document itself but other clues allow researchers to pinpoint a range of years (end of the 11th century, 1120s, mid-14th century) and we want this information to be reflected in the database/document detail page (both the date range and WHY we think it's this range).

**Describe the solution you'd like**
I want the document detail page to have a section where a content admin can enter inferred dates with less precision (date range, century, etc). I want it to be clear that this is an inferred date and I want the content admin to have to choose precise dates for the range (end of the 11th century could be registered as 1080-1099)

**Comment by blms** [comment]
Closing as duplicate of #870
