### ISSUE TITLE
Please merge the JTS and JTS, ENA collections in admin

### ISSUE THREAD

**Issue by kseniaryzhova** [Princeton-CDH/geniza#1299]
## testing notes

On the [QA site](https://test-geniza.cdh.princeton.edu/), there should no longer be a JTS ENA collection, and the JTS collection should contain all the ENA fragments.

---

**Is your feature request related to a problem? Please describe.**
Initially, we wanted to separate out the ENA collection from the rest of the JTS collections. However, most of the ENA documents are under JTS, only about 450 are under JTS, ENA. This is confusing and unhelpful.

**Describe the solution you'd like**
Please merge JTS, ENA into JTS so that all the ENA shelfmarks appear under JTS, mixed in with all the other non-ENA JTS documents.

**Comment by kseniaryzhova** [comment]
@blms in QA the collections have merged, in the merged site there's 7065 fragments,
 but in production JTS has 7065 fragments and JTS ENA has 473 fragments.

**Comment by blms** [comment]
Should be fixed after running replicate playbook and re-running migrations

**Comment by kseniaryzhova** [comment]
@blms works well! Closing!
