### ISSUE TITLE
As a content editor, I want to view and search on PGPID so I can distinguish documents on the same shelfmark and refer to the same documents in the spreadsheet and database.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#131]
## testing notes
- [x] confirm you can see PGPID in admin document list view
- [x] confirm you can search by PGPID

## dev notes
- [x] add pgpid to admin list view (make it the first element)
- [x] included pgpid in admin search for document

**Comment by richmanrachel** [comment]
@rlskoeser and @kmcelwee - thanks for making this work so quickly! And it does work!

My only question is whether it should be the privileged category in the list view for clicking over shelfmark. @mrustow - Do you have a minute to look at this?

**Comment by rlskoeser** [comment]
The reason I put it first is because it's actually the only guaranteed unique identifier — but it's easy for us to adjust if you all prefer a different order.

**Comment by richmanrachel** [comment]
I see we're bringing up the more existential question about the PGP ID tomorrow, so closing!
