### ISSUE TITLE
Add polygon annotation boxes to the transcription editor 

### ISSUE THREAD

**Issue by kseniaryzhova** [Princeton-CDH/geniza#1311]
### testing notes (QA -- round 2)

On the [QA site](https://test-geniza.cdh.princeton.edu/), go to add/edit a transcription or translation
- [x] The icons should now match the designs from Chelsea, and it should be clear which tool is selected
- [x] The help text should now mention clicking and dragging to create polygon annotations
  - I think I was able to reproduce the bug you mentioned, which is actually an underlying bug with Annotorious. I'm not sure there is much we can do there, but there is an [issue on Annotorious](https://github.com/annotorious/annotorious-openseadragon/issues/178) for it already.
  - It is caused when you hold shift and click once without dragging. It makes it impossible to use either of the tools. 
  - The fix is to simply refresh the page (no hard refresh needed). Then you will be able to click and drag again.
  - Hopefully, the updated help text will prevent people from encountering this, since it explicitly says to click _and drag_ now.

---

### testing notes (QA)

On the [QA site](https://test-geniza.cdh.princeton.edu/), go to add/edit a transcription or translation
- [x] There should now be two additional icons, one for a rectangle tool and one for a polygon tool, above each image, between the pin icon and the zoom control (may take a second to load)
- [x] The rectangle tool should be selected by default, and should work as usual
- [x] When the polygon tool is clicked, it should appear selected
- [x] The instructions on the right should be updated to explain how to use the polygon tool
- [x] Following the instructions (including a double-click at the end of drawing) should allow one to draw polygons that behave similarly to the rectangular annotations
- [x] You should be able to write a label and transcription/translation text for that polygonal region
- [x] Saving it should persist and show publicly, as with rectangular annotations
- [x] Leaving the page and returning to the editor should not cause the shape of the polygon to change or disappear

---

**Is your feature request related to a problem? Please describe.**
Text layout in Geniza documents is non-standard - there is diagonal text in the margins for example, and other non-rectangular shaped text. We want to draw polygonal annotation boxes to better map transcription text to image.

**Describe the solution you'd like**
I want to be able to reformat the annotation box on an image from a rectangle to a polygon to better fit non-standard text layouts. This should be a marked choice - the default should be the rectangular box. 

**Additional context**
Just one example: 
![image](https://user-images.githubusercontent.com/105385128/217596398-a456bbc7-4ecf-481f-922a-2844835606c7.png)

**Comment by rlskoeser** [comment]
was planning to eventually enable annotorious toolbar plugin and polygon, perhaps also tilted box (but was not compatible with toolbar last I tried it); can see these in my glitch transcription prototypes for selection tools https://pgp-transcription-prototype.glitch.me/

**Comment by kseniaryzhova** [comment]
@blms 
![image](https://github.com/Princeton-CDH/geniza/assets/105385128/1c8bf084-8a24-43bb-99af-5d645d349fb7)
any way we can make the selection more visible? Now it's like a dark gray versus black which is really hard to spot. Maybe make it green when selected? Chelsea question?

**Comment by kseniaryzhova** [comment]
@blms So I was able to draw a polygon at first, but then I clicked cancel and the annotation box disappeared. When I went to draw another polygonal box, it wouldn't let me, not even after a hard refresh.

**Comment by blms** [comment]
> any way we can make the selection more visible? Now it's like a dark gray versus black which is really hard to spot. Maybe make it green when selected? Chelsea question?

@kseniaryzhova Good point, I see what you mean! It actually is green, it's using the "primary" color for Geniza, but it's such a thin line that it's hard to tell. Let's get Chelsea's input here.

> @blms So I was able to draw a polygon at first, but then I clicked cancel and the annotation box disappeared. When I went to draw another polygonal box, it wouldn't let me, not even after a hard refresh.

Ooh, sounds like a bug. Let's mark this tested needs attention. Thanks!

**Comment by kseniaryzhova** [comment]
@blms Works! If people read the instructions then should be good to go! Closing, thank you!
