### ISSUE TITLE
As a front end user who speaks Hebrew or Arabic, I want search form options and filters in my native language, so that I understand the options.

### ISSUE THREAD

**Issue by blms** [Princeton-CDH/geniza#1316]
## Testing notes

- [x] After a hard refresh, the [Hebrew public QA site search](https://test-geniza.cdh.princeton.edu/he/documents/) should show have translated Hebrew for all the English labels in the screenshot below.

---

Just need to use `gettext_lazy`.

![image](https://user-images.githubusercontent.com/7234006/218853038-7de97538-f4af-41a1-b3f0-0027b7f6b71f.png)

**Comment by kseniaryzhova** [comment]
@blms works for me! Thank you!
