### ISSUE TITLE
Please fix digital edition sources in the PGP (spreadsheet re-ingest)

### ISSUE THREAD

**Issue by kseniaryzhova** [Princeton-CDH/geniza#1318]
**Is your feature request related to a problem? Please describe.**
We'd like to update bibliographic information on existing digital edition footnotes. Some reflect older practices which we have updated to include more information, others just need more information so we could accurately find the published source or give credit to the authors of unpublished editions.

**Describe the solution you'd like**
Please use [this spreadsheet](https://docs.google.com/spreadsheets/d/1rxUQfASXNpIuUbs-hmvkyo1k98OEPHI8C1T3PH2rIA4/edit?usp=sharing) (look under the "For Ben to fix" tab) to update the source names for the digital edition footnotes. The old sources should be deleted after the replacement has been concluded.

**Comment by richmanrachel** [comment]
@blms and @kseniaryzhova - is this still relevant?

**Comment by kseniaryzhova** [comment]
@richmanrachel @blms no, I was able to update on my own, taking off Ben's plate, closing!
