### ISSUE TITLE
On tag change, document indexing is one revision behind

### ISSUE THREAD

**Issue by blms** [Princeton-CDH/geniza#1331]
### Testing notes (QA)

In the [QA site admin](https://test-geniza.cdh.princeton.edu/admin):

- [x] Add a tag to a document—can be a new or existing tag (try both!)—and save the document. Then, on the public site search, search for the document by pgpid (i.e. `pgpid:1234`)
- [x] In the results, the tags list should reflect the new tag(s) added
- [x] Try the same with removing a tag from a document, and modifying and saving a tag's name

---

### dev notes
Similar to https://github.com/Princeton-CDH/geniza/issues/1308, document index lags one revision behind after modifying tags.

To reproduce:
1. Add a tag to a document
2. Search for it on the search page by pgpid; tags will not have changed
3. Add another tag to the document
4. On search, tags will now reflect the revision made in step 1, but not the revision made in step 3

**Comment by kseniaryzhova** [comment]
@blms works as it should, thank you! Closing!
