### ISSUE TITLE
Tags may be saved with identical names, case-insensitive

### ISSUE THREAD

**Issue by blms** [Princeton-CDH/geniza#1333]
## testing notes

In the [QA admin site](https://test-geniza.cdh.princeton.edu/admin/taggit/tag/), find an existing tag.

- [x] Using the "Add tag" button, try to add a new tag with the same name. You should receive an error on save.
- [x] Try the same name, but use different capitalization from the original tag. You should still receive an error on save.
- [x] Create a tag with a completely different name and save it. It should save successfully. Now, on the edit page for your new tag, rename it to be the same name as a different existing tag, but with different capitalization. You should again receive an error on save.

## dev notes

It is currently possible to save two tags with the same name, with the only difference being that different letters are capitalized. Since Taggit uses the query `tag = manager.get(name__iexact=name)` when `TAGGIT_CASE_INSENSITIVE=True`, saving a document with one of these tags results in a `MultipleObjectsReturned` error. Simplest solution is to use case-insensitive uniqueness validation.

example: https://geniza.princeton.edu/admin/taggit/tag/?q=judaeo-arabic+poetry

**Comment by kseniaryzhova** [comment]
@blms works as expected! Closing, thank you!
