### ISSUE TITLE
As a content editor, I would like a tool somewhere to convert alternate calendar dates automatically, so that I can make these conversions without using the document date field.

### ISSUE THREAD

**Issue by blms** [Princeton-CDH/geniza#1342]
## dev notes

- Should use existing logic from the document date field conversions

**Comment by blms** [comment]
From @richmanrachel via Slack:
> could we add a converter for Hebrew dates in Hebrew characters? I’m always worried I’m going to mess up the math as I add up the letters myself

**Comment by kseniaryzhova** [comment]
@blms @richmanrachel We actually have this information linked in the [Glossary on the public site](https://geniza.princeton.edu/en/about/glossary/) so we're closing!
