### ISSUE TITLE
Create wireframes of sitemap-v2 so we can review order and placement of content and capabilities on each page and identify any gaps in our mental models

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/geniza#1343]

**Comment by gissoo** [comment]
The [wireframes](https://www.figma.com/file/anZFStv7zBaVWnFxr95nKt/Work-in-Progress-%2F-WIP?node-id=2910%3A66019&t=KW3ctJAmDcDHbNKa-1) created based on sitemap-v2 (copied on to the figma page) were reviewed by the team and the need for minor adjustments were identified before a second round of review.

**Comment by gissoo** [comment]
@blms, [the wireframes](https://www.figma.com/file/anZFStv7zBaVWnFxr95nKt/Work-in-Progress-%2F-WIP?node-id=2910%3A66019&t=npp66HhFNt2WGhB2-1) have been partially revised based on feedback from two weeks ago and this week: 

- The wireframes cover the homepage, the search form and search result formats, and the person detail page. 
- The header and footer of the site (seen on the homepage) will have "documents" and "people" instead of just "Search" 
- The search form on the people page has a "dates of appearance", along with "Relation to doc" and "related doc type" – I had included "professions" and "geographical locations", which are both very unlikely to exist as filters because the list in both are huge and potentially not suitable as drop-down filters. 
- In the search results and in the person detail metadata we might put a person's occupation/profession in a field called "known as/known for" – because many people don't have professions including many women, this might be a safer and more inclusive option. 
- on the person detail page we have discussed displaying the documents that relate to the person, as well as people who related to the person – I have three proposals for the related document portion – [please review and let me know what you think](https://www.figma.com/file/anZFStv7zBaVWnFxr95nKt/Work-in-Progress-%2F-WIP?node-id=2910%3A64813&t=npp66HhFNt2WGhB2-1), I have included descriptions next to each – I'll need to work more on this, none of the proposals are quite there yet – the team wants to see the relationship of the person with each document (whether they wrote it, were an addressee, etc) so I've not resolved that part yet. 
- Note: these are not as rough as wireframes usually are, since we already have our visual styles it would have been harder to be rough/go back to wireframe styles.

**Comment by blms** [comment]
Thanks very much @gissoo! This all looks really good, and, I think, not a large amount of new things that were not originally written in the plans. I will pass along some estimates to the team.

As far as the person detail page, the simplest from a dev perspective (and maybe most consistent design-wise) is v2. It's the closest to "related documents" on the existing document details page. v3 should also be very simple, since we're already planning a feature to filter documents by people. That said, I don't think v1 would be all that complicated anyway, only a small amount of extra design implementation work. All look great!

**Comment by gissoo** [comment]
@blms thank you for the feedback! Do we have a plan to filter documents by people? How would that work?

**Comment by gissoo** [comment]
@blms that makes sense, thank you. Yes, my understanding is that we would have the people search instead of any people filters on the document search

**Comment by gissoo** [comment]
@blms I think we have been addressing the continuation of this issue through other design issues. I'll go ahead and close this issue.
