### ISSUE TITLE
As a front end user, I want a translation module added to the image/transcription viewer so I can see translations of documents into my native language.

### ISSUE THREAD

**Issue by blms** [Princeton-CDH/geniza#1350]
## testing notes

On the [QA public site](https://test-geniza.cdh.princeton.edu/) (and admin):

- [x] The following three documents should now have an active translation toggle (rightmost button should now be clickable in the image/transcription/translation viewer on the document details page):
  - [PGPID 9235](https://test-geniza.cdh.princeton.edu/en/documents/9235)
  - [PGPID 18932](https://test-geniza.cdh.princeton.edu/en/documents/18932)
  - [PGPID 23030](https://test-geniza.cdh.princeton.edu/en/documents/23030)
- [x] Translation content in English should be visible in all three when that button is clicked, and the large label beneath the toggle should include "(in English)"
- [x] You should be able to expand and collapse the different toggles in such a way that you can view any two of the three options side by side
- [x] When both are open, transcription and translation lines should generally be aligned with each other, except for cases where 1 line of text takes up 3 lines vertically due to wrapping, in which case alignment will be off. (intention is to address those cases in #1358)

Additional tasks (such as the editor and searching) tracked in #1355

---
## dev notes 

Decoupling this from the editor issue (#1337) so it can be tracked and tested separately.

on deploy to QA, load translations using script

**Comment by kseniaryzhova** [comment]
@blms works great! My only comment is that collapsing the toggles isn't intuitive. You have to click twice on a toggle to minimize it, whereas I tend to expect that the toggle would automatically minimize if I click on a second toggle (if two fields are already open). Is this an easy fix? If it's not, then I think we can deal.
