### ISSUE TITLE
Design public search results to display inferred dates when searching by date

### ISSUE THREAD

**Issue by kseniaryzhova** [Princeton-CDH/geniza#1354]
**Description:**
We now have an inferred date field in the admin and we want to be able to search using inferred dates while also making it clear whether a date is inferred or on the document. We want this distinction between inferred and precise dates to be visible in the search results when searching by date.

This entails also displaying the inferred dates on the individual document detail pages.

**Comment by gissoo** [comment]
@blms [here are the designs](https://www.figma.com/file/anZFStv7zBaVWnFxr95nKt/PGP?type=design&node-id=3231%3A81459&mode=design&t=nhPDpyvLiPlPp4Lw-1) that display the inferred dating field in the results right below the document title

**Comment by blms** [comment]
Looks good, thanks @gissoo!
