### ISSUE TITLE
As a content admin, I want translation backups to populate automatically in GitHub, alongside but differentiated from transcriptions, so that I can track changes in versioned translation content.

### ISSUE THREAD

**Issue by blms** [Princeton-CDH/geniza#1357]
## Testing notes (QA)

(this text is copied verbatim from https://github.com/Princeton-CDH/geniza/issues/1096 and edited to say "translation" and give you fresh unchecked checkboxes)

Test the translation backup by editing translation content on the test PGP site and then checking for corresponding changes in the test export repository.  Simplest solution right now is to look at the commit history and check for changes based on your edits.  https://github.com/Princeton-CDH/test-pgp-annotations/commits/main 

Right now I have it configured to push changes every 5 minutes, so there may be a slight delay before you see your changes

test a few different cases:
- [x] edit an existing translation and make a few text changes
- [x] edit an existing translation that has content on more than one image; remove blocks of content so there is only content on image (one of the annotation list files should be removed; 
- [x] add a new translation
- [x] remove an existing translation entirely — the corresponding exports should be removed from github

Also,
- [x] in the HTML export of a translation, the `<title>` tag contents should include the language of the translation

**Comment by kseniaryzhova** [comment]
@blms Only the creation of a new translation is registered, the others still haven't appeared in half an hour, and I can see the changes displayed on the QA site.

**Comment by kseniaryzhova** [comment]
@blms all working now, closing! Thanks!
