### ISSUE TITLE
As a front-end user, I want transcription lines always aligned with translation lines when I view both, so that I can compare the two texts line-by-line.

### ISSUE THREAD

**Issue by blms** [Princeton-CDH/geniza#1358]
## testing notes

On the [QA public site](https://test-geniza.cdh.princeton.edu/en/documents/), visit a handful of documents with both transcription and translation.

- [x] After a hard refresh, open both transcription and translation side by side, and all lines should be aligned
- [x] Click "edit X's edition", then click to open the translation, and all lines should be aligned 
- [x] Do the same for "edit Y's translation" and opening transcription; all lines should be aligned, and the fonts should be correct
- [x] Click on a translation block in the open editor. It should switch to text editor fonts/spacing, and the alignment should not become visible again until you click "cancel" or "save" on the text you're editing
- [x] In the viewer (i.e. not the rich text editor), there should be no periods after line numbers (see MR's comment below) on either side
- [x] Confirm all of the above is also true on the [QA admin site](https://test-geniza.cdh.princeton.edu/admin/) (don't forget to hard refresh!)

## dev notes

First pass of this is working when all lines are <= 2 lines tall.

RSK suggestion for handling 3+ line heights:

> Trying to think of a simple way you might implement something; might not be too hard to add a stimulus controller that compares side by side ordered lists for sections in the itt view and adjusts the height of corresponding line numbers based on whichever is longer. (But still only when they are displayed together and only on desktop!)

**Comment by mrustow** [comment]
One other small thing: with the translation editor open, the headers aren't aligning. Two fixes might help here: the bold header font is bigger on the translation side; and I think I can shave some words off the help text. 
![Untitled](https://github.com/Princeton-CDH/geniza/assets/73319225/39913564-eb7a-47b6-9109-f7d755194b7b)

**Comment by mrustow** [comment]
And now really last comment: in the screenshot just above there are periods on the translation side, but none on the transcription side. There shouldn't be periods on either side.

**Comment by mrustow** [comment]
oy just thought of something else, sorry! Looks like the font isn't yet styled inside the translation editor field? Or it's too big, or something.

**Comment by kseniaryzhova** [comment]
@blms on a PC, periods exist after line numbers in both the open editor and in the viewer
![image](https://github.com/Princeton-CDH/geniza/assets/105385128/5b91112b-f4c0-47ce-8718-8dab886d7034)

**Comment by kseniaryzhova** [comment]
@blms after cancelling my changes to a translation block, the alignment with the transcription was out of sorts
![image](https://github.com/Princeton-CDH/geniza/assets/105385128/806420b0-541b-4a58-b246-7f00bd72d01e)

**Comment by kseniaryzhova** [comment]
@blms a hard refresh does fix the above problem.

**Comment by kseniaryzhova** [comment]
@blms alignment is also off in the admin site (even after multiple hard refreshes)
![image](https://github.com/Princeton-CDH/geniza/assets/105385128/ca2c13aa-3ac4-4610-bd7d-bfb427566789)

**Comment by blms** [comment]
@kseniaryzhova Thanks for the thorough testing! All should now be fixed, with the following exceptions:

1. We cannot remove dots inside the rich text editor itself, unfortunately. The acceptance criteria is just for display in Geniza fonts. (In fact removal of dots is cosmetic, so really only applies to public display, not things that are admin-only.)
2. I don't have a way of testing on Windows, so I'm not sure if the dots will be completely covered. If you can link me to failing examples I can see if they fail on Mac; otherwise I think we would need to open a new issue for further investigation (i.e. some way for me to develop this on windows).

**Comment by kseniaryzhova** [comment]
@blms works as it should, closing and thank you! Re: the dots on Windows. We had this discussion before about how this is Windows specific. They're very small (like maybe a quarter of the size of actual periods like so .) and if they're not visible on Mac to bother MR, I say we just move on.
