### ISSUE TITLE
Dropdown header menu partially hidden behind search filters (z-index)

### ISSUE THREAD

**Issue by blms** [Princeton-CDH/geniza#1360]
## Testing notes (QA)

On the QA [public site search](https://test-geniza.cdh.princeton.edu/en/documents/), with filters expanded, open the About dropdown. The below issue should not occur.

---

![image](https://user-images.githubusercontent.com/7234006/233093372-2c63fb63-f8f7-49cc-913c-b519dfc2b991.png)

**Comment by richmanrachel** [comment]
Yes, @blms - I think you fixed it! First screenshot from production site, second screenshot from test site: <img width="1170" alt="image" src="https://github.com/Princeton-CDH/geniza/assets/68028846/297b6549-97e2-4671-9df8-79a8ec7e1ec4">

<img width="969" alt="image" src="https://github.com/Princeton-CDH/geniza/assets/68028846/7fc7b1f0-2644-45e3-bfe9-dedb000e2719">
