### ISSUE TITLE
As a public site user, I want people's names in the document detail page descriptions to be hyperlinks, so I can navigate to their person page and get more context/information about them.

### ISSUE THREAD

**Issue by kseniaryzhova** [Princeton-CDH/geniza#1364]
**Describe the solution you'd like**
When we build out our people modules and have people pages, I want to be able to navigate to those people pages from the document detail page where relevant. So if a description names Nahray b. Nissim as a letter-writer, then I want his name to be clickable in the description field so I can navigate to his person page and get more context/information about him.

**Comment by blms** [comment]
Closing as wontfix per @kseniaryzhova.
