### ISSUE TITLE
Design the document detail page on the public site so that there is field to display people mentioned in the documents

### ISSUE THREAD

**Issue by kseniaryzhova** [Princeton-CDH/geniza#1365]
**Description:**
Building out the people module, we want to tag documents with the people mentioned in them or involved in their production. The details will be recorded on the admin site (each person's specific role in the document, i.e. addressee, writer, mentioned in, signatory) but on the front-end we just want to show a list of the people mentioned/somehow involved with the document. The particular role of each person in a document will be shown publically on the respective people pages.

**Comment by gissoo** [comment]
@blms [Here are the designs for desktop and mobile](https://www.figma.com/file/anZFStv7zBaVWnFxr95nKt/PGP?type=design&node-id=3121%3A67352&mode=design&t=nhPDpyvLiPlPp4Lw-1), please let me know if you have any questions – note: the field for mentioned people comes after the description field.

**Comment by gissoo** [comment]
@blms yes! I think they would be included but won't be linked. [I have added an example just in case in the designs](https://www.figma.com/file/anZFStv7zBaVWnFxr95nKt/PGP?type=design&node-id=3410%3A26603&mode=design&t=C6bMYXVVQjID8DQ0-1)
