### ISSUE TITLE
As a content editor, I want a separate field to record people's names and roles in each document, so that I can build a structured dataset of all people across the PGP.

### ISSUE THREAD

**Issue by kseniaryzhova** [Princeton-CDH/geniza#1366]
### testing notes (round 3)

On the QA site admin:

- Edit an existing person and save. If there are no person records, create one, hit save, and then (this is important!) edit it and save it again.
- [x] Create a new person. Before hitting save, try to add a relationship with the previously edited person. If you begin typing that person's name, they should show up in the autocomplete list of people.

---

### testing notes (round 2)

Visit the [QA site admin](https://test-geniza.cdh.princeton.edu/admin) and add a new Person entry.

- [x] Start by adding a name for the person. The help text for the language should read: "Please indicate the language of most components of the person's name as you've indicated it here"
  - [x] The check box for the name should now read "display name" (instead of "primary")
- [x] Social roles should be listed alphabetically
- [x] The check box below that should read "Person page," and then for help-text, "Check box if this person should have a dedicated, public Person page on the PGP. If checked, please draft a public description below."
- [x] Under "Related People", the list of relationship types under the Relations field should be listed alphabetically

Next, edit or create a Document in the admin.

- [x] Related Fragments, Footnotes, and Related People sections should all be below transcription viewer

---

### testing notes

Visit the [QA site admin](https://test-geniza.cdh.princeton.edu/admin).

- [x] There should be a new section called "Entities" with subsections called People, Person social roles, Person-Document relationships, and Person-Person relationships
- [x] All of those except People should be pre-populated with the [lists from here](https://docs.google.com/spreadsheets/d/1RwdV_qMsXo1L-UOplU77ps2J1DSvKb6OKAFq4wOwCRo/edit?pli=1#gid=0)
- [x] You should be able to add a new person, with names in different languages, gender, social role, description, and footnotes
- [x] You should be able to add/edit social roles, Person-Document relationships and Person-Person relationships
  - [x] You should be able to add Hebrew and Arabic translations for each
  - [x] For social roles, there should also be a "display label" field in case you want to provide a slightly different label for public display
- [x] When editing or adding a Document, there should be a new section at the bottom of the "Change document" page called "Related People". You should be able to pick the person you created there.
  - [x] Once you save this relationship, the document should also show up on the Person's "Change person" page.
- [x] If you create a second person, on the "Add person" page, there should be a section called "Related People". you should be able to select the first person you created from there and specify the relationship between the two people.
  - [x] Once you save this relationship, both of the people should show up on each other's "Change person" page.

---

**Describe the solution you'd like**
On each document detail page in the admin, I want a space to record the people mentioned in documents/involved in their production and their relationship to the document (recipient, witness, legal party, etc). 

**Additional context**
This information (people's role in each document) will be linked to the relevant individual people pages as well.

**Comment by kseniaryzhova** [comment]
@blms took a few minutes for my first person entry to pop up in the related people dropdown on the document detail page but it did eventually. Works beautifully, thank you!

**Comment by blms** [comment]
Reopening to track revisions:

**Comment by kseniaryzhova** [comment]
@blms Related Fragments, Related People and Footnotes are still listed below the transcription editor in my viewer (Chrome, PC)
![Uploading image.png…]()

**Comment by kseniaryzhova** [comment]
@blms related name lists are not alphabetized and I noticed that the last person entry to be edited does not show up in the related people of the following person page. You have to save the new entry and refresh the page for it to appear in the dropdown. Is there an easy solution or do we just deal with it?
![image](https://github.com/Princeton-CDH/geniza/assets/105385128/c12ec76a-9240-497b-935f-5e2965527f2d)

**Comment by blms** [comment]
> Related Fragments, Related People and Footnotes are still listed below the transcription editor in my viewer (Chrome, PC)

@kseniaryzhova I think that is the intended behavior! Unless I misunderstood, the original problem you'd reported was that footnotes were appearing above the transcription editor, so I moved them back below.

> related name lists are not alphabetized

It's the "Relation" field we're alphabetizing here, not the list of names. But maybe it's a good idea to alphabetize names too! The only problem is that we'd need to alphabetize them by the first letter, regardless of whether that is a surname or a given name. Would that still be worth doing?

> I noticed that the last person entry to be edited does not show up in the related people of the following person page

Good catch, that's a bug! Marking this as "tested needs attention" for that bug.

**Comment by kseniaryzhova** [comment]
@blms sorry I misread above for below when testing; I do indeed like the footnotes below and that's where they are! Thanks! The relations are alphabetized so that is also checked off! As for the names, I don't think there's a good way to alphabetize as you mentioned, but the keyword search should allow us to find specific people quickly (assuming we end up with over 100 people pages). The keyword search works for me (If I type in "J" it brings up only the people with J in their name, so on).

**Comment by blms** [comment]
Thanks so much @kseniaryzhova, glad everything there is as it should be! Reopening just to track the bug with the last edited person not showing up in the list.

**Comment by kseniaryzhova** [comment]
@blms Works as it should! Thank you!
