### ISSUE TITLE
As a content editor, I want a separate field in the document detail page so that I can record place information mentioned in the document.

### ISSUE THREAD

**Issue by kseniaryzhova** [Princeton-CDH/geniza#1373]
### testing notes (QA)

- [x] On the [QA site admin](https://test-geniza.cdh.princeton.edu/admin), there should now be a section called Places.
- [x] There should also be sections for "Document-Place relationships" and "Person-Place relationships", and these should be filled out with the agreed-upon place relationship types.
- [x] Visit the "Places" section and you should be able to add new Places: name(s), lat/long coordinates, related people, and footnotes for tracking the source of the information.
- [x] Add or edit a Document. You should see a new section, Related Places, and be able to search for and add related places with the dropdown(s).
- [x] Add or edit a Person. Again there should be a Related Places section that allows you to add Places to a Person.
- [x] When you add related places to documents and people, and go back to the Place page to edit, you should now see those documents and people show up under Related Documents and Related People on the Place page.
- Note that #1453 is a separate user story and not being tested here.
- Note that #1461 also applies to Places and can be added later to add documents directly to a Place page, but is not being tested here.

---

**Describe the solution you'd like**
I want a way to record the places mentioned in a document and to qualify this data, i.e. by specifying where a letter was written and to where it was delivered as well as the itineraries described in the letter. This will help us later track the movements of people and materials and record this data for use in visualization approaches.

**Comment by kseniaryzhova** [comment]
@blms 
Finalized language for document + place relations: 
- Origin (written in (legal document), written from (letter))
- Destination (generally for letters)
- Places mentioned (excluding origin and destination) 
- Possibly the same as a place that appears in
- Was once believed to appear in but in fact doesn’t

**Comment by blms** [comment]
@kseniaryzhova Could I suggest these simplifications? We could make these display labels if you need more information for data entry purposes in the admin.

- Origin
- Destination
- Mentioned
- Possibly mentioned
- Formerly believed to be mentioned

**Comment by kseniaryzhova** [comment]
@blms works as it should! My one quip is the same as the people page, the fact that I can't add documents from the places page. This may be less relevant actually than it is for people since we'll mostly be browsing places.
