### ISSUE TITLE
Design the document detail page in the public site so that there is a separate field for recording places mentioned in the document.

### ISSUE THREAD

**Issue by kseniaryzhova** [Princeton-CDH/geniza#1374]
_This issue tracks design work through the [CDH design review workflow](https://princeton-cdh.github.io/docs/workflows/#workflow-5)._

**Description:**
We decided to record place name information in a separate field on the document detail page. This will link to the places module/map and will record information such as the geographical origin and final destination of a document, as well as any places mentioned therein. This will need to be somehow displayed on the public site for each document detail page which has relevant information about places.

**How the proposal/idea can fail:** 

**Questions:** 
  1. Does the idea and/or the design make sense to you? If not, please say why
  2. Is there anything that you expected to see and is missing? 
  
  
**Additional context**
Add any other context or screenshots about the design here.

**Comment by gissoo** [comment]
@blms [here are the designs for mentioned places](https://www.figma.com/file/anZFStv7zBaVWnFxr95nKt/PGP?type=design&node-id=3121%3A67352&mode=design&t=nhPDpyvLiPlPp4Lw-1). Note: this field would come after the mentioned people.

**Comment by blms** [comment]
@gissoo Looks good, just same question as on #1365.

**Comment by gissoo** [comment]
@blms yes! [added an example for this one too](https://www.figma.com/file/anZFStv7zBaVWnFxr95nKt/PGP?type=design&node-id=3410%3A26603&mode=design&t=C6bMYXVVQjID8DQ0-1)
