### ISSUE TITLE
As a content editor, I want clear help text when adding a source to explain how to select the source language, so that it is done consistently for translations and transcriptions.

### ISSUE THREAD

**Issue by kseniaryzhova** [Princeton-CDH/geniza#1375]
### testing notes (QA) round two

On the [QA site admin](https://test-geniza.cdh.princeton.edu/admin), navigate to the Sources section. Add or edit a Source.
- [x] Now, under "Languages", the help text should refer to "the Unspecified language option" for unpublished transcriptions, instead of instructing users to choose the language of the transcription text.

### testing notes (QA)

On the [QA site admin](https://test-geniza.cdh.princeton.edu/admin), navigate to the Sources section. Add or edit a Source.

- [x] Under "Source type", the help text should clearly communicate the need for different sources for unpublished transcriptions and translations.
- [x] Under "Languages", the help text should clearly communicate that only sources consisting entirely of transcription content should include transcription language.

---

### dev notes

Revised solution: Help text when adding a source to make it clear that unpublished translations and unpublished editions are two separate sources, and that the unpublished translation sources need to be set with the language of the translation.

---

**Is your feature request related to a problem? Please describe.**
Right now there is an undifferentiated unpublished source option, which means editions and translations are being tagged with this option. It's a requirement to select a source language, but for editions, we track the source language through the language tagging option on the document itself. For translations, however, we do want to know the language of scholarship.

**Describe the solution you'd like**
We want two separate source type options: unpublished translations and unpublished editions, to replaced the current "unpublished" option. For unpublished editions, there is no need to select a source language and it should not display in the footnote. However, for unpublished translations, the language of scholarship should be selected and should display in a footnote.

**Comment by kseniaryzhova** [comment]
@blms so even if the translation and edition are on the same Google Doc, they would still be two different sources (with the same author, etc)?

**Comment by blms** [comment]
@kseniaryzhova Yes, that’s the idea! Though, I think that would be the case either way; the difference is just that in my view, they should both have the “unpublished” source type, rather than one having “unpublished edition” and one having “unpublished translation”.

**Comment by mrustow** [comment]
@kseniaryzhova I agree with Ben: "unpublished" refers to the nature of the scholarship, not what's inside the scholarship or its content. So we would want to create two separate sources for each author (or author group): "transcription" or "translation." We pretty much have to do this anyway when we enter the TE, so it's not really extra work beyond the initial investment in creating a 'translation' source when a 'transcription' one already exists. Also, I find the process of creating a new source to be very streamlined and lightweight on the data entry side!

**Comment by blms** [comment]
Great, thanks @mrustow!

So @kseniaryzhova, does this resolve the issue?
- Always select the language of the translation for the "unpublished" sources with only translation content
- The language for "unpublished" sources with only transcription content is irrelevant, since transcription language always = Document language, and those sources should never have Footnotes tagged "digital translation"

We could also disable the forced requirement to select a source language, if that's helpful for the latter case.

**Comment by kseniaryzhova** [comment]
@blms I think we'll need help text outlining all of this, to make it clear that unpublished translations and unpublished editions are two separate sources even if they have the same author(s) and are often on the same Google Doc. Essentially we just need to tell people that if they're inputting unpublished editions, to not touch the language selector. But for translations it's necessary. And the entries will look identical, you're just distinguishing by the name

**Comment by blms** [comment]
That makes sense, thank you @kseniaryzhova! I'll track the help text addition here, then.

**Comment by kseniaryzhova** [comment]
@blms Works as it should, just a quick question about the language help text. "The language(s) the source is written in. Note: Sources should never include transcription language **unless the entire source consists of a transcription**. Hold down “Control”, or “Command” on a Mac, to select more than one." I thought we decided if it's the transcription language we're not going to add the language at all since it'll be registered as the language of the document itself.

**Comment by kseniaryzhova** [comment]
@blms works as it should, thank you! Closing!
