### ISSUE TITLE
Design the public transcription search filter so that there is an option to select search results with no transcriptions.

### ISSUE THREAD

**Issue by kseniaryzhova** [Princeton-CDH/geniza#1376]
_This issue tracks design work through the [CDH design review workflow](https://princeton-cdh.github.io/docs/workflows/#workflow-5)._

**Description:**
Right now the transcription filter on the public site allows users to choose results that only have transcriptions or everything. We need an option that allows for results without transcriptions, in part because this will make it easier to search image thumbnails in the public site search results to find documents with images that do not yet have transcriptions in the PGP. 

**How the proposal/idea can fail:** 

**Questions:** 
  1. Does the idea and/or the design make sense to you? If not, please say why
  2. Is there anything that you expected to see and is missing? 
  
  
**Additional context**
Add any other context or screenshots about the design here.

**Comment by gissoo** [comment]
The design for desktop has been executed and reviewed. [here is the link to the design on Figma](https://www.figma.com/file/anZFStv7zBaVWnFxr95nKt/Work-in-Progress-%2F-WIP?type=design&node-id=3116%3A65810&t=W0K6mZY1WoztWqtJ-1). However we have decided to resolve this issue in the admin interface and the design solution will not be applied. The figma page is archived and remains in the file in case it will be needed in the future for other cases.
