### ISSUE TITLE
As a content admin, I want a person with 10+ associated documents to automatically generate a front-end People Page, so that content editors do not have to manually make significant people pages live. 

### ISSUE THREAD

**Issue by richmanrachel** [Princeton-CDH/geniza#1381]
### testing notes (QA)

Forgot to ever deliver this one for testing! It should continue to be true that a person record will only get a public person page if it has 10 related documents or the "person page" checkbox is checked on their edit page.

---

### dev notes
> can mitigate with help text and maybe also an admin filter to see who does/does not have a page so they could easily override those who wouldn't otherwise. + make the override field `list_editable`

---

**Is your feature request related to a problem? Please describe.**
We don't know how quickly/consistently data will be added related to people. So by building an automatic feature to make a person's page public if they cross a certain threshold, we will prevent artificial bottlenecks and get important people (who we may not even realize were important!) onto the front end.

**Describe the solution you'd like**
In addition to a manual boolean checkmark (or something equivalent) for turning on public pages for figures that may not reach the arbitrary 10 document threshold, we would like the association of people and documents to automatically trigger a public page publication.

**Additional context**
Perhaps we can write the code in such a way that if 10 ends up being too low of a number, we can change it? Or at least know how to find and access this feature?

**Comment by kseniaryzhova** [comment]
@blms works as it should! Thank you, closing!
