### ISSUE TITLE
As a content editor, I want to add and edit all footnotes associated with a single source to make bulk data entry easy and efficient.

### ISSUE THREAD

**Issue by richmanrachel** [Princeton-CDH/geniza#139]
## testing notes
On source edit page, confirm:
- [x] can view existing footnotes
- [x] can link to associated document
- [x] can edit existing footnotes
- [x] can add new footnote

---
Context: we would like to be able to hire RAs to go through an entire book and add all of the relevant document/footnote connections. I imagine this could be done by mirroring the footnote entry that currently exists in the Document View but from the Source page, to allow bulk data entry of: shelfmark, page range, document relation. 

Question: if there are multiple PGP IDs for the entered shelfmark, would it be possible to prompt the user to pick one? Ideally with the document type information visible to facilitate making the correct choice?

**Comment by rlskoeser** [comment]
@richmanrachel a version of this is available for testing now. It's a little clunkier than I'd like, but I couldn't justify spending more time on it when we need to complete the data import. Hopefully it's better than nothing.

The source edit page now includes associated footnotes. Each one should have a preview & edit link for the document a footnote is associated with. To add new ones, you have to select the content type and the object id (this is the clunky part). If you click the search icon it will bring up a window where you can pick a document, but you could also enter a PGP ID if you're linking to a document.

Pretty sure there will be a limit in how many footnotes you can save at once; you could test this with some of the sources that have more references loaded and see what happens.

**Comment by richmanrachel** [comment]
@rlskoeser - Feeling immediately intimidated by this:
![image](https://user-images.githubusercontent.com/68028846/118704205-df32b180-b7e4-11eb-9085-04dff9b6c751.png)
Is "corpus I document" always going to be the way we're supposed to show the footnote's relation to a document?

**Comment by richmanrachel** [comment]
I practiced adding a footnote and it went pretty smoothly, though it's a little inconvenient to have to find the PGP ID in a separate window, since all the sources will only cite by shelfmark. Is there a way to type in the shelfmark instead and be given a window to click and open a new tab if you have to choose between disaggregated pgpids?

**Comment by richmanrachel** [comment]
If we could perhaps change the titles of the columns to be slightly clearer, that would also be helpful for new RAs. 
![image](https://user-images.githubusercontent.com/68028846/118705429-37b67e80-b7e6-11eb-815f-a35f4bf7837b.png)
[Ex. change Object ID to PGP ID, Location to Page Number(s)]

**Comment by richmanrachel** [comment]
And what does the Digitized Transcription field handle? Is that just indicating if it's this source that provides the transcription for the website?

In sum: this feature works, but could use some improvement for useability/clarity :)

**Comment by rlskoeser** [comment]
@richmanrachel thanks for the feedback. Yes, I recognize it's not ideal — as I said, it's a little clunky.

I've updated so that footnotes can only be added to models in the `corpus` app, so the list of choices aren't as long. I don't want to change the labels because footnotes are a generic relationship that can be connected to other types of records, so it won't always be a pgpid. We originally had "location" as page number, but that wasn't accurate because many sources provide a document # instead of or in addition to pages.

We could make this work better in future, but I'm not comfortable spending more time on it now when we still have a lot to do to finish the data import work.

Would you also test what happens when you try to edit a source that has a lot of footnotes associated? I think it will fail at some point when there are too many but I don't know what point that is. I'm not sure it should hold up accepting this issue but it would be good to be aware.

**Comment by rlskoeser** [comment]
@richmanrachel Actually, I see that we have 2201 footnotes associated with the source for Goitein's typed texts. I'm certain that will be unusable. I think we need to disable this feature.

**Comment by richmanrachel** [comment]
@rlskoeser - thank you for limiting the options for the relationship, that definitely helps! Maybe you can describe what each of them are to me (now or when we have the final version) so I can write up a manual for RAs.

I don't think we should have anything as high as Goitein's typed texts... they are so numerous because they're a type of source rather than a single source. I think it's okay to disable for now, if we need to, and focus on import. But there might be some other way we can treat Goitein's material to avoid this problem?

**Comment by rlskoeser** [comment]
@richmanrachel I think we'll have to do something different with the Goitein materials anyway — maybe can address it whenever we tackle attachments.  

Would you look at this briefly with @mrustow tomorrow and decide together whether you'd rather have this feature and not be able to edit the source for Goitein's typed texts or have the feature turned off?  FWIW, it's been useful for me in testing to be able to easily see the footnotes associated with a source, and it seems like we could probably get by with not editing the typed texts source for a while — but I defer to you two.

**Comment by richmanrachel** [comment]
With approval from @rlskoeser we came to a decision that we can split Goitein's typed texts into "volumes" by shelfmark collection (T-S, CUL, etc). We can do this post-import.

**Comment by rlskoeser** [comment]
Great. Shall we close this one @richmanrachel ?

**Comment by richmanrachel** [comment]
@rlskoeser - close permanently or put on hold to perfect later?

**Comment by rlskoeser** [comment]
@richmanrachel close it, since the preliminary version is working and you've decided you want to keep the features vs turning it off. Later enhancements should be tracked as a new story or stories and be prioritized against other development work.
