### ISSUE TITLE
csv of all undated documents that have Seleucid/Sel. in the description

### ISSUE THREAD

**Issue by kseniaryzhova** [Princeton-CDH/geniza#1392]
**Describe the solution you'd like**
LOW PRIORITY (to be done after Seleucid conversion feature is live). We would like a csv of all PGPIDs that are undated and have the words Sel. or Seleucid in the description. This is so we can go through and start inputting Seleucid dates into the converter once that feature goes live.

**Comment by rlskoeser** [comment]
@kseniaryzhova fwiw you should be able to use the dataset exports and colab notebooks to generate lists like this; some of the data exploration I started doing with colab might be a helpful starting point, if you have anyone on the team who can work with that

**Comment by kseniaryzhova** [comment]
@rlskoeser that is good to know! We don't have anyone with that kind of skillset right now, but we're trying to arrange for a workshop where we can learn this (among other things)

**Comment by blms** [comment]
I just accomplished this using document exporter via Django shell for now.

```py
from django.db.models import Q

from geniza.corpus.metadata_export import AdminDocumentExporter
from geniza.corpus.models import Document

# doc_date_standard can't be null, but can be blank
docs = Document.objects.filter(
    Q(description__icontains="Seleucid") | Q(description__icontains="Sel.")
).filter(doc_date_standard="")

exporter = AdminDocumentExporter(queryset=docs)
exporter.write_export_data_csv(fn="/tmp/undated_seleucid_export.csv")
```
