### ISSUE TITLE
As a content admin, I want CSV export document dates (on document and inferred) to be in one column so that I can sort by a single date column.

### ISSUE THREAD

**Issue by kseniaryzhova** [Princeton-CDH/geniza#1398]
**Describe the solution you'd like**
We want date on document and inferred dates to appear in the same column so we can sort by dates in csv exports. Fortunately, the two are mutually exclusive - a document with a date on it will never have an inferred date and vice versa.

**Comment by mrustow** [comment]
Just a note on why we're not moving forward with this: "date on doc" and "inferred date" are different levels of data, one certain, the other uncertain, so merging them by default would mean losing information. To get them all in one column doesn't take much effort — a simple copy-paste from column to column should do it — whereas merging them by default would potentially put the researcher in the position of untangling them later, which would be somewhere between painful and virtually impossible.

**Comment by blms** [comment]
Thanks for the clear explanation! Closing as `wontfix`.
