### ISSUE TITLE
Update ansible deploy so we can use PUL Solr 8 for search

### ISSUE THREAD

**Issue by kmcelwee** [Princeton-CDH/geniza#14]
Ideally, we'll be using PUL's Solr infrastructure, which requires Solr 8.  `parasolr`, our Solr python wrapper, is currently tested against Solr 6.6.5.

Updates to parasolr for Solr 8 will be tracked on parsolr's [solr-8 branch ](https://github.com/Princeton-CDH/parasolr/tree/feature/solr-8)

See https://github.com/Princeton-CDH/parasolr/issues/48 ~and https://github.com/Princeton-CDH/parasolr/issues/49~ (parasolr/issue/49 is unique to docker, not Solr8) for existing issues concerning the Solr 8 update.

**Comment by rlskoeser** [comment]
Closing, since the ansible role for solr handling is implemented and working in qa.
