### ISSUE TITLE
Alignment between Arabic transcriptions and English translations is slightly off

### ISSUE THREAD

**Issue by blms** [Princeton-CDH/geniza#1409]
### testing notes (qa)

On the [QA public site](https://test-geniza.cdh.princeton.edu/):
- [x] Visit a handful (5-10) of documents with both transcription and translation content, including both JA and Arabic documents. Open both the transcription and the translation. Numbered lines in the transcription and translation should be aligned side-by-side.

(Note that in some cases, such as PGPID 1018, one or the other side may contain content that is not matching, such as a paragraph on one side and numbered lines on the other. Alignment can only occur when both sides contain matching numbered lines.)

---

### testing notes (QA)

On the [QA public site](https://test-geniza.cdh.princeton.edu/):
- [x] Find a few documents with a transcription in Arabic and translation in English, such as PGPID 38281. Transcription and translation lines should be aligned properly.
- [x] Try the same on the QA site admin.

---

### dev notes

![Screenshot 2023-06-27 at 11 25 01 AM](https://github.com/Princeton-CDH/geniza/assets/7234006/008b66f3-d5e7-4b74-9005-1a30f688dadc)

It may not be possible to fix this without affecting the other languages, but worth investigating.

Example doc: https://geniza.princeton.edu/en/documents/38281/
Example doc on QA: https://test-geniza.cdh.princeton.edu/en/documents/38281/

**Comment by kseniaryzhova** [comment]
@blms alignment was great for the admin site but not public for some reason, same document, 38281.
![image](https://github.com/Princeton-CDH/geniza/assets/105385128/e7451ae3-43e0-466e-83de-1ece6739a618)
![image](https://github.com/Princeton-CDH/geniza/assets/105385128/cff6633d-20d9-428f-b072-ea6ae96c93ee)

**Comment by kseniaryzhova** [comment]
@blms It works for me, I think I should have @mrustow test on her Mac since there were differences before.

**Comment by blms** [comment]
@mrustow before we reopen, can you give this one a try on Safari [on QA](https://test-geniza.cdh.princeton.edu/en/documents/38281/) after a hard refresh? (Cmd+Opt+R) Here's what I'm seeing there now:

![Screenshot 2023-08-16 at 11 34 37 AM](https://github.com/Princeton-CDH/geniza/assets/7234006/56c713bc-63f7-4caa-95a5-aca1429ce6be)

**Comment by mrustow** [comment]
Yeah it's sooooo close, like a mm off — 

<img width="1628" alt="image" src="https://github.com/Princeton-CDH/geniza/assets/73319225/65461114-84ef-42dc-8aec-f8dd2c7ae20a">

**Comment by blms** [comment]
Reopening to fix that, and I also am seeing some other problems (PGPID 1018, PGPID 2649)

**Comment by amelbensalim** [comment]
Hello! I'm working on a PC and noticed that the alignment works great for the first text block, but that blocks for margins/second and third text blocks don't align. I tried re-doing the text formatting, to no avail. 
![image](https://github.com/Princeton-CDH/geniza/assets/139090834/9e95a881-aec2-4167-9eb1-9dd0dc17cad4)

**Comment by blms** [comment]
Confirmed fixed by Marina during 9/13 meeting, closing.
