### ISSUE TITLE
Design desktop wireframes of the cluster view browse results page to communicate the content structure, page layout, and content variations to the project team

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/geniza#142]
Here are the designs [for desktop](https://www.figma.com/file/HpGBOZi9lO8B3nCAx3d4Fj/Princeton-Geniza-Project-team?node-id=713%3A533)

- [x] content structure 
- [x] content structure variations depending on what element(s) in the network is/are being browsed
- [ ] language and labeling of content and functionalities (will be creating a site content google doc to resolve this point)
- [x] page layout
- [x] page layout when any field is missing, e.g. images

**Comment by gissoo** [comment]
Here are the designs [for desktop](https://www.figma.com/file/HpGBOZi9lO8B3nCAx3d4Fj/Princeton-Geniza-Project-team?node-id=713%3A533)

The context here is exactly the same as what I have written for issue #123, [here. ](https://github.com/Princeton-CDH/geniza/issues/123#issuecomment-825267214)

@richmanrachel @mrustow Please read the above and let me know if you think of anything that is missing here – I will close this issue for now.

**Comment by richmanrachel** [comment]
@gissoo - looks good! I assume once it's live and not in Figma play mode, the font will be able to adjust when the window size shifts?

**Comment by gissoo** [comment]
@richmanrachel so the play mode is just shown when I have made some parts clickable so that it looks more like what it's supposed to in the browser for different devices – but in general in Figma we communicate the font sizes for different screen sizes by showing designs for mobile, tablet, and desktop (using 3 breakpoints) – right now the font sizes on mobile and tablet are the same and larger for desktop – maybe it's worth that we have a 30-minute meeting just about Figma and some design conventions that will remain consistent throughout our collaboration.
