### ISSUE TITLE
As a content editor, I want the location field for digital edition/translations to automatically populate from an existing edition/translation on the same source, so that I can save time manually re-entering it.

### ISSUE THREAD

**Issue by blms** [Princeton-CDH/geniza#1420]
### testing notes (qa)

In the [QA admin site](https://test-geniza.cdh.princeton.edu/admin), navigate to a document.

- Add an Edition footnote with some value in the "location" field
- Add a new transcription with the transcription editor on the same source as the Edition footnote you created
- In the transcription editor, create some annotation blocks on the images
- [x] On the document, there should now be a new Digital Edition footnote with the same location as the Edition footnote
- [x] Try the same with a Translation footnote with a location, adding a translation on the same source in the translation editor. The newly created Digital Translation footnote should get the same location as the Translation footnote
- [x] Try this on a document with more than one Edition footnote on the same source, each having different locations. Using the transcription editor to create a new transcription on that source should _not_ populate the new Digital Edition footnote with a location, since it is ambiguous which Edition footnote should be used.

---

Requested by @mrustow over Slack. This should include:
- [x] A one-time migration to copy all `Footnote.location` values from edition to digital edition, and translation to digital translation, on the same Source
- [x] Logic to populate this automatically when users are creating digital content via annotations in the transcription/translation editor

**Comment by kseniaryzhova** [comment]
@blms works as it should, thank you! Closing!
