### ISSUE TITLE
Revise the document detail page so that tags are placed below the mentioned places field below the description 

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/geniza#1424]
@blms this change is the result of adding the people and places fields. Please let me know if you have thoughts on this. [Here are the designs](https://www.figma.com/file/anZFStv7zBaVWnFxr95nKt/PGP?type=design&node-id=3121%3A67352&mode=design&t=nhPDpyvLiPlPp4Lw-1).

**Comment by blms** [comment]
@gissoo Is this a duplicate of #1365 or is there something different here?

**Comment by gissoo** [comment]
@blms this one is about reordering the tags so they appear below the people and places fields
