### ISSUE TITLE
Transcription and translation may become misaligned when resizing window

### ISSUE THREAD

**Issue by blms** [Princeton-CDH/geniza#1431]
### testing notes (qa)

On the [QA public site](https://test-geniza.cdh.princeton.edu/):
- [x] Visit a document with both transcription and translation content. Open both of these side by side. Ordered lines should be aligned side-by-side, and resizing the window should retain the alignment, despite some lines wrapping differently.

---

Workaround is to collapse and re-expand one of the open panels.

https://github.com/Princeton-CDH/geniza/assets/7234006/d2449b0d-191d-4d2a-85a6-3a585f2fb057

**Comment by kseniaryzhova** [comment]
@blms works as it should! Closing, thank you!
