### ISSUE TITLE
Annotations on the document detail page do not respect reordering

### ISSUE THREAD

**Issue by blms** [Princeton-CDH/geniza#1438]
### testing notes (qa)

On the [QA site](https://test-geniza.cdh.princeton.edu/):

- [x] Edit a document transcription or translation, and reorder some annotations by dragging and dropping text blocks in the right column. You should see a small confirmation message appear at the bottom of the screen indicating that the reorder was successful.
- [x] Visit that document's entry on the public site and hard refresh. The new order of annotations in that particular transcription/translation should persist.

---

The `content_html` property of a footnote is missing the `order_by` step.

**Comment by kseniaryzhova** [comment]
@blms Works as it should, closing, thank you!
