### ISSUE TITLE
check demerge spreadsheet against original metadata and data import

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#144]
- check demerged against originals for fields that may have changed since the demerge spreadsheet was generated (in particular I'm thinking of the input by date cleanup; not sure how to identify expected changes from unexpected ones)
- check demerged ids against data import logic (multiple types) — are we skipping the same ids? Is every skipped id addressed?

**Comment by kmcelwee** [comment]
There were 19 PGPIDs found in the metadata spreadsheet that I could not find in the records spreadsheet of https://docs.google.com/spreadsheets/d/18zt4yvuheuurBgb4qJrqKOBfEwszvj5aT7lBllUKaVE/edit#gid=1697128067:

```
32188
32262
19420
19430
32483
32484
31783
31800
32460
9376
32291
32292
32297
32298
31716
32075
32107
32108
23465
```

**Comment by rlskoeser** [comment]
@kmcelwee were there any PGPIDs in the demerge spreadsheet that we are _not_ ignoring in the current import?

**Comment by kmcelwee** [comment]
@rlskoeser Yes! sorry for that oversight. There is one PGPID 27846. If we look for the word "disaggregate" in Technical Notes we'd pick it up, but not sure if you'd want to implement that.
