### ISSUE TITLE
Digital translation footnote in scholarship records behaving incorrectly, excluding other footnotes on source

### ISSUE THREAD

**Issue by blms** [Princeton-CDH/geniza#1446]
### testing notes (qa)

- [x] On the QA public site, [PGPID 6955's scholarship records page](https://test-geniza.cdh.princeton.edu/en/documents/6955/scholarship/) should no longer display the below behavior, and should instead say "includes Digital Translation, Edition, Translation"
- [x] Check a handful of other documents with many scholarship records, including digital transcriptions/translations. The scholarship records page should never say "for X see" without further information below the word "see", and it should always list all document relations for a particular source, even if they are split across multiple footnotes.

---

On PGPID 6955, this record has no location or URL, yet says "for digital translation see" instead of "includes digital translation". Also, it is causing other footnotes on the source to be excluded entirely from the scholarship records.

![image](https://github.com/Princeton-CDH/geniza/assets/7234006/580adf58-4694-4b56-b49f-b734ec6cd269)

In admin:

![Screenshot 2023-08-21 at 10 10 45 AM](https://github.com/Princeton-CDH/geniza/assets/7234006/a7368c25-dd81-46f4-a639-4686ca18faf2)

**Comment by kseniaryzhova** [comment]
@blms Works well, thank you! Closing!
