### ISSUE TITLE
As a content editor, I want an option to include inferred dates in the admin date filter, so that they are included in CSV exports from filtered results.

### ISSUE THREAD

**Issue by blms** [Princeton-CDH/geniza#1452]
### testing notes (QA)

In the [QA site admin](https://test-geniza.cdh.princeton.edu/admin):

- [x] Navigate to the list of Documents. You should be able to filter by dates as before
- [x] There should be a new filter called "By date type (if at least one date filter active)", with "Document and inferred dates" selected by default. While this is selected, results of a date filter _should_ take inferred dates into account.
- [x] Select "Document dates only". Now, only documents with document dates (that fall within the filtered range) should appear in the list; documents with only inferred dates should not.

---

Splitting this off from #1371 because it's significantly more complex, and the other half has already been implemented.

**Comment by kseniaryzhova** [comment]
@blms works as it should! So exciting! Closing, thank you!
