### ISSUE TITLE
As a content admin, when viewing people-to-people relationships in person pages, I want reverse relationships to be visible, so that I don't inadvertently add a relationship twice.

### ISSUE THREAD

**Issue by blms** [Princeton-CDH/geniza#1458]
### testing notes (QA)

on the [QA site admin](https://test-geniza.cdh.princeton.edu/admin/):

- [x] If you select one of the entries in the list of [Person-Person relationship types](https://test-geniza.cdh.princeton.edu/admin/entities/personpersonrelationtype/), you should be able to view and edit the converse relationship type name. All the ones from the spreadsheet should now be populated here.
- Add some Person entries and some Person-Person relationships between them
- [x] After adding a single relationship between people, both people should have the relationship represented on their page
  - [x] The first person should show the relationship you entered in the "Related People (input manually)" section, with the relationship type you selected
  - [x] When you go to the other person's Person page, you should see the "converse" relationship type in the "Related People (automatically populated)"

### dev notes 

- from discussion on https://github.com/Princeton-CDH/geniza/issues/1390
- need a new field on RelationshipType for reverse of relationship (probably come up with better nomenclature?)
  - reverse relationships listed [here](https://docs.google.com/spreadsheets/d/1RwdV_qMsXo1L-UOplU77ps2J1DSvKb6OKAFq4wOwCRo/edit?usp=sharing)
  - can do this in a data migration for these

**Comment by blms** [comment]
@kseniaryzhova A handful of questions that have come up in the process of implementing this:

1. Should the reciprocal relations for “Maternal cousin” and “Paternal cousin” just be “Cousin”? 
   - Example: if Jane is my maternal cousin because she’s my mother’s sister’s daughter, then the relationship is identical on both sides—I’m also her maternal cousin. But if Jane is my mother’s brother’s daughter, then while she’s still my maternal cousin, I’m actually her _paternal_ cousin. In other words, if I add Jane in the DB as my maternal cousin, it’s ambiguous whether I’m Jane's maternal or paternal cousin.
2. For the nephew and niece relations, is there a reason why we only have aunt and uncle relations as actual relationship types, and nephew/niece only appear as reciprocal relations?
3. Is "Reverse name" and the following help text a good description for what we're talking about here? "Reciprocal" seems inaccurate (since it implies something done or given in return for something else, rather than a semantic complement)
   -  I'm using the term "[semantic converse](https://en.wikipedia.org/wiki/Converse_(semantics))" here after some research on wikipedia 😆 
   - Does "symmetrical" convey enough information for what we mean when the relationship is the same in both directions?
   ![Screenshot 2023-09-12 at 4 12 31 PM](https://github.com/Princeton-CDH/geniza/assets/7234006/963b0652-54d5-47e3-81ef-68e29ec05a5e)
4. Do these header names make sense for separating the related people from the reverse read-only display? "People related to" seems confusing since it is semantically the same thing as "related people", but I'm struggling with the proper terminology here.
   ![Screenshot 2023-09-12 at 4 16 16 PM](https://github.com/Princeton-CDH/geniza/assets/7234006/f7bd249d-24ad-4794-88c1-be0e20dc557a)

   fwiw, here's what it looks like if I click that link to "Other person" and look at their related people section:
   ![Screenshot 2023-09-12 at 4 16 27 PM](https://github.com/Princeton-CDH/geniza/assets/7234006/5e1903ba-514b-487a-a83e-871ae229d913)

**Comment by blms** [comment]
Answers from 9/13 meeting:
1. Yes
2. Should all appear individually, though "maternal niece/nephew" and "paternal niece/nephew" should be changed to  "niece/nephew on sister's side" and "niece/nephew on brother's side"
3. Change to "converse relationship," example is good, "Leave blank if the converse is identical"
4. Change to "Related People (Input Manually)" and "Related People (Populated Automatically)"

**Comment by kseniaryzhova** [comment]
@blms works as it should, thank you! Closing!
