### ISSUE TITLE
As a content admin, I want to be able to merge two (identical) people pages without losing any data

### ISSUE THREAD

**Issue by kseniaryzhova** [Princeton-CDH/geniza#1459]
### testing notes (QA)

In the [QA site admin](https://test-geniza.cdh.princeton.edu/admin):
- [x] Visit the list of People. You should be able to select multiple people, then in the dropdown, choose "merge selected people"
- [x] You should be brought to a view showing a comparison between the people you selected, listing all the properties of both
- [x] If any relations are not present for a record (for example, document-person) this should also be indicated
- [x] You should be able to choose a primary person for the merge
- [x] When you merge them, you should be redirected to the merged record
- [x] On merge, descriptions should be combined; all names (except duplicates), relations (docs/people/places), and footnotes should appear on the merged record
  - [x] The display name of the primary person should be the display name of the merged record
- [x] Merging two people with different genders, or different social roles, should cause an error visible to the user
  - [x] The exception is when one of the genders is "Unknown" and the other(s) is/are identical, since unknown is treated as blank

---

**Describe the solution you'd like**
I want to be able to merge duplicate people pages in the same way we merge documents now (side-by-side comparison of entires, no data loss, choosing the main display name).

**Comment by kseniaryzhova** [comment]
@blms testings works as it should. I did see a potential issue. When I merge two records, the display name becomes the associated name for every related document, even if some of them were under the other name pre-merge. Is there an easy way to maintain that difference? Just so you can see which names were associated with which documents? If it's too much of an investment, we can deal.

**Comment by blms** [comment]
@kseniaryzhova Definitely possible, we could keep track of which name is the display name when the document-person association is created, then ensure that doesn't get modified when things are merged. I would estimate about 6 hours for it. Want to create a new user story for it and close this one if complete otherwise?

**Comment by kseniaryzhova** [comment]
@blms We decided not to keep track of which name displays on the related documents page after the merge. Closing, thank you!
