### ISSUE TITLE
As a content editor, I want a preliminary version of transcription text linked to a scholarly source so that I know which documents have available transcriptions.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#146]
# testing notes
**this implementation is provisional!** the actual way in which we handle transcriptions will likely be quite different, and the transcription text that you will see was generated by an experimental script. no content is expected to be correct – we're testing that things show up in the right places.

- there should now be a boolean filter on the document admin list that allows you to filter by documents with a digitized transcription, along with a check mark indicator for those that have one.
- if you check the admin edit page for any of these documents, you should see a section labeled "transcription" below the main metadata area that displays the (experimental) transcription text with very light formatting (the text is assumed to be a right-to-left script and aligned accordingly). it is not intended to be editable; the content is not stored as editable text.
- in the list of footnotes for the document further down the page, you should also see a checkmark indicator showing which of the footnotes is the edition from which the transcription is taken.
- if you go to the footnotes admin list, you should also have the ability to see and filter on which footnotes provide a digitized transcription.
- if you edit a footnote, you should see the same transcription display as you would on the document edit page.

**Comment by richmanrachel** [comment]
@rlskoeser - I love it! This looks great (and answers one of the questions I had on #139)!
