### ISSUE TITLE
As a content admin, I want to add related documents directly from people pages to facilitate data entry.

### ISSUE THREAD

**Issue by kseniaryzhova** [Princeton-CDH/geniza#1461]
### testing notes (QA - round two)

On the [QA site admin](https://test-geniza.cdh.princeton.edu/admin/):
- [x] On a Person page, when adding Related Documents, the autocomplete search should now function much more as expected. (It won't be perfect and there will probably be a small number of irrelevant entries, but it should be reasonably easy to find the relevant ones.)

### testing notes (QA)

On the [QA site admin](https://test-geniza.cdh.princeton.edu/admin/):
- [x] Visit a Person page and scroll down to the "Related documents" section. You should now be able to search for documents by shelfmark or PGPID and pick the correct document to add
- [x] You should be able to choose the relation type and successfully add the relationship
- [x] After saving, visit the document page in the admin; the relationship should show up there too

---

**Describe the solution you'd like**
I want to be able to add related documents directly from people pages (and not just from the document page) and I want there to be an autocomplete function where any fragment I type in (provided it is already in the PGP) will pop up with all the PGPIDs associated with the fragment so I can choose the correct document. This will facilitate data entry because there will be researchers focused specifically on people who will already have associated dossiers and so the data entry will occur from the people, not the documents page.

**Comment by kseniaryzhova** [comment]
@blms Everything works as it should but the shelfmark search is very slow and you have to put in basically the full shelfmark for it to show results. But when I start typing ENA or CUL, it doesn't automatically update the dropdown. Is this expected behavior?

**Comment by blms** [comment]
Yes, except I'm not sure what's going on with ENA or CUL. When you type the full shelfmarks for those are you able to find them? It's up to you whether this and the slowness are acceptable; if not we can revise.

**Comment by blms** [comment]
@kseniaryzhova I'm not sure what's going on with ENA or CUL. When you type the full shelfmarks for those are you able to find them? It's up to you whether this and the slowness are acceptable; if not we can revise.

**Comment by kseniaryzhova** [comment]
@blms tested this some more, played around with it. And the speed is fine, people can deal. But I'm running into an alphabetization issue. I typed in Moss. II and only about 7 entries down did I start to get Moss. II fragments. 
![image](https://github.com/Princeton-CDH/geniza/assets/105385128/d08e1b35-0ceb-44db-8ece-c470fd115ff9)

**Comment by richmanrachel** [comment]
The speed looks good to me too. I agree the results are still a little different than what I would expect. See here this example of "Ena 21" where the results all have 21 in them, but the first ones that show up are not from the first part of the shelfmark:
<img width="312" alt="image" src="https://github.com/Princeton-CDH/geniza/assets/68028846/a0b66b56-1f37-4f05-b558-196f74bced1e">

If I type in more, the right docs come up, so I'm not sure it needs fixing, it's just different than anticipated.

**Comment by kseniaryzhova** [comment]
@blms I think we'll close then! Thank you!
