### ISSUE TITLE
As a public site user, I would like to see date ranges separated with an en-dash (–) instead of an em-dash (—).

### ISSUE THREAD

**Issue by mrustow** [Princeton-CDH/geniza#1467]
### testing notes

On the QA public site:
- [x] Documents such as PGPID 4020 should use the en dash (–) to separate dates in ranges, in both [search results](https://test-geniza.cdh.princeton.edu/en/documents/?q=pgpid%3A4020&docdate_0=&docdate_1=&sort=relevance) and on the public [document detail page](https://test-geniza.cdh.princeton.edu/en/documents/4020/)

---

The highlighted character is an em-dash — (on Mac, option-shift-hyphen) but per CMS should be an en-dash – (option-hyphen), without spaces on either side. 

Admittedly not our biggest problem! Hopefully won't take up much of your time.

Love, 
Your friendly Chicago Manual of Style enforcer

**Comment by richmanrachel** [comment]
@blms - is this something for you or @cblissg?

**Comment by kseniaryzhova** [comment]
@blms checked a few others, en-dashes everywhere! Thanks, closing!
