### ISSUE TITLE
As a front end user, I want old shelfmarks to show up in search results and on the individual document pages (alongside the new shelfmark names) 

### ISSUE THREAD

**Issue by kseniaryzhova** [Princeton-CDH/geniza#1469]
### testing notes (round two, qa)

(general search only, not regex)

- [x] You should be able to find documents by historical shelfmark using the syntax `shelfmark:"historical shelfmark"`
- [x] It should show which historical shelfmark matched in the result

### testing notes

On the [QA site public search](https://test-geniza.cdh.princeton.edu/en/documents), try searching for some documents by historical shelfmark:

- [ ] It should generally find the correct document if the historical shelfmark is there in the admin
  - There might be some problems with historical shelfmarks that have single character words in them; we don't index this in exact match fields, so using double quotes won't help. You also may run into matches in the description that take precedence over the historical shelfmark field.
- [x] The matching historical shelfmark should appear in the search result, as an additional metadata field
- [x] All historical shelfmarks should appear on the document detail page, above "Input date"

---

**Is your feature request related to a problem? Please describe.**
There's a few shelfmarks that have new names but may still be referred to by their old names in older literature. We want to help users see the correspondence between old and new shelfmarks on the site. We already have a field for historical shelfmarks but it relies on manual entry and is incomplete. It also doesn't show up in search or on the public document detail pages.

**Describe the solution you'd like**
Whenever relevant, I want a search of the old shelfmarks to show the old shelfmark names in the result page so I can see the connections between the old and new names. I also want the old shelfmark names to show up in the individual document detail pages for the relevant PGPIDs.

**Additional context**
[PGP Shelfmark Guide - incomplete, needs MR to finalize/go over](https://docs.google.com/spreadsheets/d/1YuRUX5L_cqPvhUJtyyp9kDOpQsXYa18Q9alqznUAl8c/edit?usp=sharing)

**Comment by kseniaryzhova** [comment]
#271 is essentially the same thing, linking here but I'm closing that one.

**Comment by blms** [comment]
@kseniaryzhova Is this roughly what you had in mind for document details? I'm noticing it can get pretty long, especially with some of these ones we populated automatically for search purposes. Same issue could end up happening on the search results. Maybe a design concern?

![Screenshot 2024-03-08 at 12 46 06 PM](https://github.com/Princeton-CDH/geniza/assets/7234006/a2890f30-23b8-41fc-8bdf-96ea626846e7)
![Screenshot 2024-03-08 at 12 46 00 PM](https://github.com/Princeton-CDH/geniza/assets/7234006/1e9892ca-cfea-49e4-9672-79798e3d2842)

**Comment by kseniaryzhova** [comment]
@blms Historical shelfmark is not showing up when we search for historic shelfmarks more generally: https://test-geniza.cdh.princeton.edu/en/documents/?q=shelfmark%3AULC+1080&docdate_0=&docdate_1=&sort=relevance. First result gives me just a "U" under historical shelfmark, and other results search transcriptions and descriptions and highlight those first. https://test-geniza.cdh.princeton.edu/en/documents/?q=shelfmark%3A%22ULC+OR+1080%22&docdate_0=&docdate_1=&sort=relevance

**Comment by kseniaryzhova** [comment]
@blms precise search with quotations gives me 0 entries, but if I type without quotations (but still using shelfmark:) then the entry pops up as the first of thousands so the boosting is working.

**Comment by kseniaryzhova** [comment]
@blms suddenly working fine now, glad that works! Closing!
