### ISSUE TITLE
Issues with shelfmark scoped search

### ISSUE THREAD

**Issue by blms** [Princeton-CDH/geniza#1476]
### testing notes

On the [QA site](https://test-geniza.cdh.princeton.edu/en/documents):
- [x] Searching for most shelfmarks using the syntax `shelfmark:"T-S 12.302"`, `shelfmark:"AIU II.A.73"`, etc should bring up the correct results
- [x] There should not be a bunch of irrelevant results containing the word "type" highlighted (this is what was happening before—and what this issue was intended to fix)
- [x] Both on the public site and admin, it should work roughly the same way (though the admin search is not ordered by relevance)

---

- Shelfmark scoped search brings up irrelevant results after the relevant ones. This was happening before the solr 9 upgrade, but since then, it seems to highlight the word "type" in each additional result. More here: https://github.com/Princeton-CDH/geniza/issues/1359#issuecomment-1719972954
- Searching for `shelfmark:"T-S 12.30"`, the relevance score seems like it may be wrong, since all the partial matches like "T-S 12.304" come up before "T-S 12.30 + JRL SERIES B 2367". Maybe it's a problem with joins. (confirmed, it is a problem with joins, unrelated.)
- Does not work at all in admin search

**Comment by kseniaryzhova** [comment]
@blms works as it should, closing, thanks!
