### ISSUE TITLE
Last chosen person not populating in person-document relations dropdown

### ISSUE THREAD

**Issue by mrustow** [Princeton-CDH/geniza#1477]
### testing notes (QA)

In the [QA site admin](https://test-geniza.cdh.princeton.edu/admin):
- [ ] Edit an existing person record. Navigate to a Document record, you should be able to add that person as a related person
- [ ] Navigate to a different Document record and try to add that person as a related person, they should still appear in the dropdown of people you can add

---

Made a [screen recording](https://princeton.zoom.us/rec/share/t0NIJl7Z_VRu6r7NSbmTvTJPNiyVK_hTL2IxZ4Z-ruWVxvYP1FDKXc45oGOTuQDN.SNusImbWB1ob65qa) — lmk if you have questions. 

I should add: the dude does seem to have been populated correctly in People.

<img width="1300" alt="image" src="https://github.com/Princeton-CDH/geniza/assets/73319225/93d0e020-6f97-44bb-baf4-fcd36e3c8d2e">

Was working on Safari.

**Comment by blms** [comment]
@mrustow Thanks for catching this! Just applied a fix directly to production. Can you check if it's behaving as expected now?

**Comment by mrustow** [comment]
All better now!
