### ISSUE TITLE
Invalid lat/long coordinates are allowed for Places, but don't persist

### ISSUE THREAD

**Issue by blms** [Princeton-CDH/geniza#1478]
### testing notes (round 2)

In the [QA site admin](https://test-geniza.cdh.princeton.edu/admin), create a new Place record. Then:
- [x] don't enter any coordinates and try to save. you should see a warning asking if you're certain you want to do this
  - [x] confirming should save the record without coordinates; cancelling should not save and should let you add them
  - [x] same should be true for entering invalid coordinates, instead of no coordinates, in Firefox or Safari

### testing notes

In the [QA site admin](https://test-geniza.cdh.princeton.edu/admin), create a new Place record. Then:
- [x] Using Chrome, you should NOT be able to enter latitude and longitude in degrees, minutes, seconds (38° 53′ 23″ N, 77° 00′ 32″ W) at all—it should strip the non-numeric characters
- [x] Using Safari and Firefox, you should be able to enter it, but it should give you a tooltip that says something like "please enter a number"
  - [x] If you click out of the text box in Safari or Firefox, it should be red to indicate it is invalid
- [x] There should be help text with a link to convert the latitude and longitude to decimal
- [x] Once converted to decimal, you should be able to enter the latitude and longitude normally
- [x] Entering a number with more than 4 decimal places, such as `41.9561342823`, should not be possible manually; pasting in that value should automatically round it to 4 decimal places

### dev notes

- [x] should show a validation error on wrong format
- [x] should also add help text explaining the correct format and the way to convert them
- [x] should also automatically round to the correct number of decimal places instead of raising a validation error for precision
- cross ref with S&Co code

**Comment by kseniaryzhova** [comment]
@blms In Firefox I am still allowed to save a place with the non-numeric characters. Like I just ignored the warnings (the red is very faint) and then saved to see what would happen, and there was no issue saving. The latitude and longitude do not appear in the saved entry but the place entry still exists.

**Comment by kseniaryzhova** [comment]
@blms is there a way to say, “Are you sure you want to save without adding coordinates?” if someone tries to save without coordinates? We could still allow it, but then remind people that they haven't put in coordinates (if they try to input non-numeric things)

**Comment by kseniaryzhova** [comment]
@blms works as it should, thank you! Closing!
