### ISSUE TITLE
People names are not diacritic neutral when adding them from Document Detail page

### ISSUE THREAD

**Issue by richmanrachel** [Princeton-CDH/geniza#1479]
### testing notes (QA) -- round two

In the [QA site admin](https://test-geniza.cdh.princeton.edu/admin):
- [x] Go to the People section. In the list view, use the search bar to search for people's names who have diacritics in them. Try searching both with and without diacritics. Both should bring up the expected person.
- [x] The same should be true for the Places section.
- [x] Now try to edit a Place. Go to the section where you attach related people and places. In these autocomplete dropdowns, the searches should work the same way—both diacritic and non-diacritic searches should bring up the right results.

### testing notes (QA)

In the [QA site admin](https://test-geniza.cdh.princeton.edu/admin):
- [x] Try adding Related People to a Document. You should be able to successfully search their names without diacritics and case-insensitive
  - [x] try the same when adding Related People to People and Places entries
  - note that this does not include `'` and `ʿ` being treated the same—just diacritics
- [x] Try adding Related Places to Documents, People, and Places. Again, you should be able to search without diacritics and pull up the correct places

---

**Describe the bug**
While we've made the search results of the website diacritc-mark neutral (i.e. you can search for "Masliah" to get "Maṣliaḥ") the same is not currently true when adding People in the Document Detail page. This will create problems and potentially duplicates of People by making it harder for RAs to attach the correct people to documents. 

**Screenshots/To produce bug**
If I type in "Ma" I get the following results, but if I type in "Mas" without the underdot, the results don't populate:
<img width="318" alt="image" src="https://github.com/Princeton-CDH/geniza/assets/68028846/a8655baa-6c2c-4af8-b199-5af4eb052508">

<img width="314" alt="image" src="https://github.com/Princeton-CDH/geniza/assets/68028846/1ca63ec2-eb93-4dfe-907f-5afb3dc5c5ad">

**Expected behavior**
Underdots, macrons, and the hamza/ayin notations should be ignored when typing a name to pull up an existing person (i.e. use the same logic developed for the frontend).

**Comment by richmanrachel** [comment]
#1499 is the same; I'll copy Ksenia's comment here and close:

Is your feature request related to a problem? Please describe.
Finding people with diacritics as part of the first letter of any of their names is hard. I cannot type "H" and get Ḥayyim b. 'Ammār al-Madīnī. For those working on PCs, this makes quick data entry a pain because we have to copy and paste the diacritics separately (there is no way to create them via a keyboard shortcut).

Describe the solution you'd like
I want to be able to type in an H and get names that start with the diacritic and the diacritic-less version of this letter (Ḥ). This would apply to other such letters (Ṣ, Ḍ, Ṭ, Ẓ and ʾ)

**Comment by kseniaryzhova** [comment]
@blms works well, thank you! Closing!

**Comment by blms** [comment]
Reopening as it works from autocomplete, but not on admin search pages.

**Comment by kseniaryzhova** [comment]
@blms weirdness noted, searching "Elhanan" (no diacritics) gives me 3 results, but searching "Elḥanan" only gives me 2 even though all 3 of those results have Elḥanan in them.

**Comment by blms** [comment]
@kseniaryzhova Actually, I think that is a data issue; there is something different about the way those two names are spelled with diacritics. Try copying these two and trying them separately:
1. `Elḥanan` (first two results)
2.`Elḥanan` (third result)

**Comment by blms** [comment]
On the plus side, that means that the diacritic-less search will find even tiny unnoticeable variants like this :)

**Comment by kseniaryzhova** [comment]
@blms data entry problem, as you said! Closing and thank you!
