### ISSUE TITLE
As a content admin, I want to be able to upload related documents in bulk to the relevant field of an individual person page, to speed up data entry when a person has a lot of associated documents 

### ISSUE THREAD

**Issue by kseniaryzhova** [Princeton-CDH/geniza#1481]
**Describe the solution you'd like**
We want a way to do bulk uploads of related documents for people pages. Some of our people are associated with hundreds of documents and most who merit a people page will have 30+. Bulk uploads from the person page in admin would speed up data entry.

**Comment by richmanrachel** [comment]
Decided as a team that this won't be worth the effort on our end or Ben's. Closing.
