### ISSUE TITLE
[PGPID] OR [PGPID] search does not work in the admin

### ISSUE THREAD

**Issue by blms** [Princeton-CDH/geniza#1483]
### Testing notes (QA)

In the [QA site admin](https://test-geniza.cdh.princeton.edu/admin):
- [x] Navigate to the list of documents. Make a search like [`3424 OR 34032`](https://test-geniza.cdh.princeton.edu/admin/corpus/document/?q=3424+OR+34032). It should pull up the documents for both PGPIDs. Try with a few other PGPID pairs as well just to be sure.

---

Reported by Alan on Slack, it seems the boolean search when entering only PGPIDs no longer works (for example, `34034 OR 30718`). This makes merging more difficult, as it was the main way admins were pulling up two documents in the admin.

![image](https://github.com/Princeton-CDH/geniza/assets/7234006/3955f626-3c7b-40f9-ab2d-e1ab076652f0)

It seems that other fields queried in boolean searches are not affected, for example, [`bronze OR metal`](https://geniza.princeton.edu/en/documents/?q=bronze+OR+metal) works as expected.

@rlskoeser wondering if this may be a case we missed in the solr upgrade! Investigating now…

**Comment by rlskoeser** [comment]
@blms sorry we missed that! 

It looks like it behaves properly in the public search: https://geniza.princeton.edu/en/documents/?q=34034+OR+30718

Is there a change we made in the public search that we didn't apply to the admin search? I remember there was something about the way we specify edismax syntax but I forget the specifics

**Comment by blms** [comment]
@rlskoeser Ooh, good catch. And my `bronze OR metal` search [doesn't work in the admin](https://geniza.princeton.edu/admin/corpus/document/?q=bronze+OR+metal). That's a helpful lead, I'll take a look!

**Comment by blms** [comment]
@rlskoeser I'm wondering if maybe `mm=100%` was broken before, and is actually working now, but isn't desired. Removing it fixes the issue. Do you remember why it was there in the first place?

https://github.com/Princeton-CDH/geniza/blob/e0881afa15385c16c58ca13c3f1f2984f6d0ef23/geniza/corpus/solr_queryset.py#L137-L138

**Comment by rlskoeser** [comment]
@blms I think the `mm` was to make it an all match instead of an any; because we don't have relevance sorting in the admin, it's more important for the searches to be more precise rather than more capacious. Can you check if there's a different way to do that in solr 9?

**Comment by rlskoeser** [comment]
it looks like `mm` should still be supported, as long as we are properly setting the edismax query type: https://solr.apache.org/guide/solr/9_2/query-guide/edismax-query-parser.html#extended-dismax-parameters

there's an `mm.autoRelax` parameter we  could try

**Comment by blms** [comment]
That's what I'm seeing too! It seems like we want default `AND` behavior unless `OR` is written, but it looks like the way to do that is exactly setting `q.op` to `AND`. I wonder why it wasn't working and when this admin search actually broke (maybe not the solr 9 upgrade). I'll try the `q.op` thing again!

**Comment by kseniaryzhova** [comment]
@blms works well! Closing, thank you!
