### ISSUE TITLE
Empty lines cause line number display issues in search results

### ISSUE THREAD

**Issue by blms** [Princeton-CDH/geniza#1486]
### Testing notes (QA)

On the [QA public site](https://test-geniza.cdh.princeton.edu/):
- [x] Transcriptions/translations with empty lines should display the empty lines correctly in search results. For example, searching for [`linen`](https://test-geniza.cdh.princeton.edu/en/documents/?q=linen&docdate_0=&docdate_1=&has_translation=on&sort=relevance) should show empty lines in the translations for PGPID 576 and 1316, and searching for [`3424 AND שנטלתי`](https://test-geniza.cdh.princeton.edu/en/documents/?q=3424+AND+שנטלתי) should show an empty line in the transcription for PGPID 3424. The below line numbering error should not occur

---

From [this search](https://geniza.princeton.edu/en/documents/?q=linen&docdate_0=&docdate_1=&has_translation=on&sort=relevance):

![Screenshot 2023-10-24 at 2 13 27 PM](https://github.com/Princeton-CDH/geniza/assets/7234006/e3e12dc0-c031-4641-b931-e27118b6c0f2)

**Comment by kseniaryzhova** [comment]
@blms works as it should! Closing!
