### ISSUE TITLE
Highlighting context shows entire transcription or translation in search result

### ISSUE THREAD

**Issue by blms** [Princeton-CDH/geniza#1487]
### testing notes

In the [QA public site search](https://test-geniza.cdh.princeton.edu/en/documents):
- [x] Searching [`פכראבהא`](https://test-geniza.cdh.princeton.edu/en/documents/?q=%D7%A4%D7%9B%D7%A8%D7%90%D7%91%D7%94%D7%90&docdate_0=&docdate_1=&has_translation=on&sort=relevance) should only show a snippet of the transcription surrounding the keyword. Not the entire transcription
- [x] Other searches for words/phrases within the transcriptions/translations also should not show the entire transcription or translation in the search result

### dev notes

For example, searching [`פכראבהא`](https://geniza.princeton.edu/en/documents/?q=%D7%A4%D7%9B%D7%A8%D7%90%D7%91%D7%94%D7%90&docdate_0=&docdate_1=&has_translation=on&sort=relevance) produces exactly one match within the transcription, but shows the whole transcription instead of a small amount of context.

![Screenshot 2023-10-24 at 4 51 29 PM](https://github.com/Princeton-CDH/geniza/assets/7234006/e7f077a0-944c-4043-816a-fb82b5c47752)

Not sure if this is a new thing from solr 9 or if it's been like this the whole time

**Comment by kseniaryzhova** [comment]
@blms works well, thank you! Closing!
