### ISSUE TITLE
As an admin, I’d like the autocomplete for people to be diacritic-independent, so that I can find people and add relations more quickly

### ISSUE THREAD

**Issue by kseniaryzhova** [Princeton-CDH/geniza#1499]
**Is your feature request related to a problem? Please describe.**
Finding people with diacritics as part of the first letter of any of their names is hard. I cannot type "H" and get Ḥayyim b. 'Ammār al-Madīnī. For those working on PCs, this makes quick data entry a pain because we have to copy and paste the diacritics separately (there is no way to create them via a keyboard shortcut).

**Describe the solution you'd like**
I want to be able to type in an H and get names that start with the diacritic and the diacritic-less version of this letter (Ḥ). This would apply to other such letters (Ṣ, Ḍ, Ṭ, Ẓ and ʾ)

**Comment by richmanrachel** [comment]
Duplicate issue. See #1479. Closing
