### ISSUE TITLE
Alignment issues with translations in editor display when zooming in and out

### ISSUE THREAD

**Issue by kseniaryzhova** [Princeton-CDH/geniza#1501]
**Describe the bug**
Misalignment of the English translation when side-by-side with the transcription. It appears as though the lines are doubled up, so the text from the line below is just superimposed over the first line, making it illegible.

**To reproduce**
1. Go to public search.
2. Search for documents with a digital transcription and a digital translation.
3. In the module, open up the transcription and translation side by side.

**Expected behavior**

**Screenshots**

![image (7)](https://github.com/Princeton-CDH/geniza/assets/105385128/6c8f9e28-3e1a-4ac3-af34-70b9afc04b24)

**Device information**
 - MR is using Safari 17.1. KR had no issues on PC. Ben could not reproduce initially.

**Comment by blms** [comment]
It's surprisingly difficult to get an accurate height for an element when the browser has been zoomed in.

This might help, but it's not yet supported in Safari:
https://web.dev/articles/device-pixel-content-box
https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserverEntry/devicePixelContentBoxSize

We'll stick with the workaround for now, until/unless this becomes higher priority.

**Comment by richmanrachel** [comment]
Annoying but not the highest priority. Closing.
