### ISSUE TITLE
Cannot merge a document into a primary that does not have a description

### ISSUE THREAD

**Issue by blms** [Princeton-CDH/geniza#1506]
### Testing notes

On the [QA site admin](https://test-geniza.cdh.princeton.edu/admin/):
- [ ] Find or create a document with no description. Attempt to merge with a different document, choosing the no-description document as the primary. This should not cause an error.

### dev notes
`if doc_description and doc_description not in current_description:` results in `TypeError: argument of type 'NoneType' is not iterable`

**Comment by kseniaryzhova** [comment]
@blms works as it should, closing! Thank you!
