### ISSUE TITLE
Indexing issues with creating documents in Hebrew or Arabic admin

### ISSUE THREAD

**Issue by blms** [Princeton-CDH/geniza#1507]
### testing notes (QA)

In the [QA site admin](https://test-geniza.cdh.princeton.edu/admin):
- Set your browser's preferred language to Hebrew or Arabic so that you can visit the admin page in that language. (Settings -> Languages -> Preferred Language in Google Chrome; Settings -> General -> Language in Firefox.) Navigate to the page to create a new document.
- [x] When creating the document, you should be able to choose a document type in the selected language (note that one or more of them may not be translated to all languages).
- Choose a fragment and save the document (perhaps with a shelfmark override to make it easy to search for). 
- [x] Change your preferred language back to English and visit the public search page. There should not be any extra "unknown type" facets in the Document Type dropdown. In addition, when you search for the document, it should be listed under the facet for the type you selected (but in English).

---

A new DocumentType record was added, and some documents moved to it. The list of document types now looks like this:

![Screenshot 2023-12-12 at 9 53 46 AM](https://github.com/Princeton-CDH/geniza/assets/7234006/3b9c0bcb-8233-429c-9196-97ae3c397315)

In the public site, the list of types first appeared like this:

![image](https://github.com/Princeton-CDH/geniza/assets/7234006/edc327cc-dc89-4d1c-95d8-fde9807153d6)

Then, after a reindex, like this:

![Screenshot 2023-12-12 at 9 53 11 AM](https://github.com/Princeton-CDH/geniza/assets/7234006/57fa8c5c-e275-45d1-9725-907c66ec25a0)

**Comment by blms** [comment]
I was temporarily able to resolve this by restarting nginx and then reindexing again. However, I think it's not a sustainable solution. Probably related to #1189. Moving to backlog for now.

**Comment by blms** [comment]
Seems this isn't related to the new doctype at all. Rather, it happens when a user is using the Hebrew or Arabic version of the admin and saves a new document or changes a document's doc type.

**Comment by kseniaryzhova** [comment]
@blms works in both Hebrew and Arabic, thank you! Closing!
