### ISSUE TITLE
Translation annotation box gets stuck (even when open) and will not allow edits

### ISSUE THREAD

**Issue by kseniaryzhova** [Princeton-CDH/geniza#1516]
**Describe the bug**
The translation annotation window gets "stuck" and nothing will type inside it. To bypass the problem, I save and click back in and that resets it. 

**To reproduce**
See video

**Expected behavior**
When an annotation box is open or active, we always want to be able to type in it.

**Screenshots**
[Marina's screenshare](https://share.icloud.com/photos/0d2IyVcjmmd0dPOy_CyewUJfw)

**Device information**
 - Safari

**Comment by kseniaryzhova** [comment]
Additional info from MR: This seems to happen when I encounter superscript text (I'm pasting text into the box from another file and there are footnote callouts). I can't un-superscript it (button greyed out) and I can't delete it.

**Comment by blms** [comment]
@mrustow Very odd! I can't seem to replicate this even with superscript and callouts to footnotes in the original document. That kind of formatting doesn't seem to copy over at all, and I can't get it to gray out any buttons or stop letting me type. (Safari 16.6, Chrome 120.0.6099.199, or Firefox 121.0.1; Mac OS 13.5.2).

A few questions:

1. Does this happen when creating a new annotation, or only when editing an existing one?
2. Does it only happen when pasting in from another source? If so, where does the source come from? A google doc, a PDF? And can you provide a link to it?
3. How often does this happen? Are there any documents where it happens consistently?
4. Does a hard refresh fix it?

**Comment by mrustow** [comment]
I was able to reproduce the issue (Safari 17.3) editing an existing annotation. See, for instance, [this one](https://geniza.princeton.edu/admin/corpus/document/9044/change/?_changelist_filters=q%3DCUL%2BAdd.3340). In the recto, right margin, annotation box, there are numbers next to the words. Those are the footnote callouts I meant: for this particular source, India Book vol. 4, the footnote callouts got included in the transcriptions and I have been gradually removing them. I can delete a few at a time, but then the screen gets stuck. I'll find a few more examples.

What has fixed it for me temporarily is to save and then click back into the box. I haven't tried hard refresh yet.

**Comment by mrustow** [comment]
These are the [transcriptions](https://geniza.princeton.edu/admin/footnotes/source/141/change/?_changelist_filters=q%3Dalfon) to look at for footnote callouts. Pretty sure the original source of these transcriptions was: they were MS Word files, then they got imported into the old Db, then migrated to the new one.

**Comment by blms** [comment]
Thanks @mrustow! That's really weird, I still can't replicate it in Safari 17.3. 

I'm also not seeing superscript here, so maybe the condition that causes the freezing isn't present.

https://github.com/Princeton-CDH/geniza/assets/7234006/7c5852a2-bd5c-4028-aafa-f4d56a448ecb

**Comment by blms** [comment]
@mrustow After you try a hard refresh, can you also list any browser extensions you have enabled currently? Wondering if one of them might be interfering. And does it only happen in Safari or other browsers too?

**Comment by richmanrachel** [comment]
Unable to replicate. Closing.
