### ISSUE TITLE
Dark mode styles are broken for new transcription/translation source input

### ISSUE THREAD

**Issue by blms** [Princeton-CDH/geniza#1517]
### testing notes (QA)

On the [QA site](https://test-geniza.cdh.princeton.edu/), sign in and visit the page to add a new transcription/translation, with the dropdown to choose the source. After a hard refresh,
- [x] the text in the dropdown should be readable in both light and dark mode
- [x] the button below should appear centered

---

![image](https://github.com/Princeton-CDH/geniza/assets/7234006/3ca8689e-b4f2-46e1-9214-56a24184e4b3)

## dev notes

- Working for me locally but not on QA or prod, suspect some django dependency got an update that broke this. needs more investigation

**Comment by kseniaryzhova** [comment]
@blms works really well, thank you! Closing!
