### ISSUE TITLE
As a user, I want documents that span fragments with consecutive shelfmarks to have their shelfmark displayed using a range, so that it's easier for me to read.

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/geniza#154]
## testing notes
- in the admin site:
 - [x] open a document for editing and confirm the new shelfmark override field is displayed
 - [x] confirm shelfmark override field is optional (save changes without adding one)
 - [x] confirm you can add a custom shelfmark 
 - [x] check that the shelfmark override value you added is displayed in the document list view
- on the public site:
 - [x] on the document details page, check that the shelfmark override value you set is displayed for the title and and the shelfmark metadata
 - on the document search
  - [x] confirm you can find your document by searching for your shelfmark override value (keyword search)
  - [x] confirm you can find your document by searching for individual shelfmarks for the fragments associated with the document (keyword search)
  - [x] confirm you can search on shelfmark override in the shelfmark field `shelfmark:...`
  - [x] confirm you can search on individual shelfmark in the shelfmark field `shelfmark:...`

**Is your feature request related to a problem? Please describe.**
As raised by alan in [the april 29th meeting](https://docs.google.com/document/d/1ZzoZJBqsseFCROEtFnP26G3baeZYT4vJGFDucYB3-nw/edit#heading=h.w8r3weqyj6tk), we have some documents that occur on fragments that have consecutive shelfmarks. Aan example is `Bodl. MS Heb. d 66/49–50`, which is a join between `Bodl. MS Heb. d 66/49` and `Bodl. MS Heb. d 66/50`.

Currently, the data import will be creating a single fragment with a shelfmark of `Bodl. MS Heb. d 66/49–50`, based on what's in the spreadsheet. However, we want to more accurately model this as a document that occurs across multiple distinct fragments, since there's technically no single object with the shelfmark `Bodl. MS Heb. d 66/49–50`. The team has agreed to handle this problem by "demerging" these fragments with dashes in the shelfmark after the data import (see [corresponding asana task](https://app.asana.com/0/187294619140624/1200267553437360)).

On the display side, however, it's better to show the document shelfmark _with_ the dash, because it's easier to read and to see that the fragments are in fact consecutive. Otherwise, these documents may have shelfmarks that are quite long and difficult to read.

**Describe the solution you'd like**
~The method that calculates `Document.shelfmark` should take account of whether the document's fragments have consecutive shelfmarks. For any consecutive ranges, we should display them using an en-dash, which is the convention for noting a numeric range.~

**Additional context**
Alan mentioned that some of these ranges will include fragments with shelfmarks that end in non-numeric identifiers like `13bis`. Once we know what nonstandard identifiers are out there, we can develop a solution that ignores them in favor of the numeric content in the identifier.

## dev notes
- [x] add an optional shelfmark display override field on the Document model and make available in the admin edit form; display directly below the shelfmark fields. Should have help text to indicate it is for this use case: "Override default shelfmark display, e.g. to indicate a range of shelfmarks."
- [x] update shelfmark display method to use the override value if set, otherwise current logic
- [x] index shelfmark display in solr as a single keyword field (we will want to use this for sorting by shelfmark too)
- [x] display new shelfmark display field in search results
- [x] include shelfmark display field in both public and admin solr search query fields
- [x] add unit tests to confirm searching on shelfmark override label and individual shelfmarks included in a range

revisions after testing:
- [ ] on admin change form, shelfmark should display combined fragment shelfmarks, not override
- [ ] on document detail, metadata shelfmark should display combined fragment shelfmarks, not override

**Comment by thatbudakguy** [comment]
Further investigation reveals that there are also shelfmarks where the range is indicated with a regular dash (-) not an en-dash (–). This is unfortunate, because it's not simple to search for such shelfmarks: doing [a regular search for the dash](https://test-geniza.cdh.princeton.edu/admin/corpus/fragment/?q=-) turns up many fragments with a dash in a different part of the shelfmark (e.g. `L-G Ar. I.93`).

We probably need to do a slightly more advanced query for numeric ranges with a dash (using a regex or similar) and generate a list of shelfmarks with these ranges to give to the team as part of the asana task mentioned above.

**Comment by richmanrachel** [comment]
Noting here a decision made that we should treat these documents as joins, but have a **display name that shows the range** (that way, if you search for an individual shelfmark in the middle of the range you'll still find the right document, and we don't have to merge/demerge as many documents).

**Comment by richmanrachel** [comment]
On the front end too... I'm more confident now that "shelfmark" needs to stay the same and show the proper join:
<img width="616" alt="image" src="https://user-images.githubusercontent.com/68028846/165366725-41c8082b-c047-4f3e-bea4-b3a8a566a833.png">

**Comment by richmanrachel** [comment]
The override name isn't working on the document list on the admin side.

I need to find another example (ideally one that isn't merged yet) to keep testing. But in the meantime, I think we do need to ensure that the override name does NOT actually override the shelfmark information and is only a title and searchable field.

**Comment by rlskoeser** [comment]
@richmanrachel I wondered about that when I was working on it!  Would you please list out the places you would like to see the override and where you want to see the list of actual shelfmarks, just so I can be clear what I need to change?

**Comment by richmanrachel** [comment]
@rlskoeser - I think that "shelfmark" should always refer to what the library has (and therefore joins should be listed with each shelfmark separately). But the display name for the document detail view on both frontend and admin site can use the override/display name.

@alanelbaum - is this what you were hoping for too?

**Comment by rlskoeser** [comment]
@richmanrachel this is ready for retesting

**Comment by richmanrachel** [comment]
@rlskoeser - I'm getting a server error when I try to do it!

**Comment by rlskoeser** [comment]
oh no! same db problem, I bet. ugh, sorry

**Comment by richmanrachel** [comment]
Yay, it works now! Closing!
