### ISSUE TITLE
As a public site user, I want a page to view details about an individual person, so that I can learn more about their life and presence in documents.

### ISSUE THREAD

**Issue by blms** [Princeton-CDH/geniza#1566]
### testing notes (QA)

On the QA site, navigate to the [list of people](https://test-geniza.cdh.princeton.edu/en/people).
- [x] Click on a person with a link. It should navigate to a Person Detail page.
- [x] This page should match the design below. (No life events, bibliography, citation, or permalink yet.)
- [x] The tabs for related documents, people, and places should be disabled, but they should show accurate counts.

---

Design here: https://www.figma.com/file/mPu59EJcveUnltjlll3twI/Princeton-Geniza-Project?type=design&node-id=768-10996&mode=design&t=d1QOs8BP588SiFnE-4

**Comment by kseniaryzhova** [comment]
@blms looks great, thank you, closing!
