### ISSUE TITLE
As a public site user, I want a way to browse all the people in the database, so that I can find a specific person I am looking for, or get an overview of all people

### ISSUE THREAD

**Issue by blms** [Princeton-CDH/geniza#1568]
### testing notes (QA)

- [x] Visit [this page on the QA site](https://test-geniza.cdh.princeton.edu/en/people). It should bring you to a list of people in the database.
- [x] This list should match the design (linked below). It should be missing the date range filter, and the filter "bubbles" that appear when filters are applied.
- [x] People with "Person page" checked, or at least 10 related documents, should appear as links in the list.
- See also:
    - #1566
    - #1571 
    - #1578

---

Design here: https://www.figma.com/file/mPu59EJcveUnltjlll3twI/Princeton-Geniza-Project?type=design&node-id=776-80765&mode=design&t=G94VYkwBxY12RovA-4

**Comment by kseniaryzhova** [comment]
@blms wait why are the filter bubbles and date range filter missing?

**Comment by kseniaryzhova** [comment]
@blms answering my own question based on your notes from other issues, it's just because not everything has been implemented yet, right? Anyway, everything in the checklist works as it should, closing!
