### ISSUE TITLE
As a public site user, I want to be able to filter people in the browse page by gender, social role, and relation to documents, so that I can narrow down my browse results

### ISSUE THREAD

**Issue by blms** [Princeton-CDH/geniza#1571]
### testing notes (QA)

On the QA site, navigate to the [list of people](https://test-geniza.cdh.princeton.edu/en/people).
- [x] Click "Filters". The filter button should change colors and open a panel of filters.
- [x] There should be filters for gender, social role, and document relations. Each option should have counts.
- [x] Clicking filters should narrow down the results.
- [x] Clicking multiple options within the same filter should broaden the results to "people matching any of the selected criteria" for that filter.

---

Design here: https://www.figma.com/file/mPu59EJcveUnltjlll3twI/Princeton-Geniza-Project?type=design&node-id=776-80765&mode=design&t=G94VYkwBxY12RovA-4

**Comment by kseniaryzhova** [comment]
@blms works as it should! Closing!
