### ISSUE TITLE
As a public site user, I want to be able to sort people in the browse page by date, name, and other criteria so that I can quickly find the most relevant result

### ISSUE THREAD

**Issue by blms** [Princeton-CDH/geniza#1578]
### testing notes (QA - round two)

On the QA site, navigate to the [list of people](https://test-geniza.cdh.princeton.edu/en/people).
- [x] Sorting by name should now behave as expected.

---

### testing notes (QA)

On the QA site, navigate to the [list of people](https://test-geniza.cdh.princeton.edu/en/people).
- [x] Above the list, on the right, there should be text that says "Sort by:" and a dropdown next to it (by default reading "Name").
- [x] Clicking the different options should sort the list by the selected field.
- [x] Switching between ascending and descending should reverse the order of the list.

---

Design here: https://www.figma.com/file/mPu59EJcveUnltjlll3twI/Princeton-Geniza-Project?type=design&node-id=776-80765&mode=design&t=G94VYkwBxY12RovA-4

**Comment by kseniaryzhova** [comment]
@blms what is the sorting logic? What does it mean to go ascending versus descending for something non-numerical like names or social roles (I don't get the sense that it's alphabetized, which is what I would expect)

**Comment by blms** [comment]
@kseniaryzhova It is meant to be alphabetized for non-numeric fields. The only one where I'm seeing unexpected behavior is Name, where we have a number of entries that begin with `ʿ` and thus get sorted to the end of the list. I think I have an idea for how to fix this (secretly sorting by slug, i.e. the name as it appears in a URL such as `yehuda-b-isma-il-al-andalusi`). Social role is alphabetized correctly though!

**Comment by kseniaryzhova** [comment]
@blms works as it should, thank you, closing!
