### ISSUE TITLE
When searching in Hebrew, search results are excluded when the keyword searched is longer than the word that appears in transcriptions

### ISSUE THREAD

**Issue by blms** [Princeton-CDH/geniza#1582]
### testing notes (QA)

On the [QA site](https://test-geniza.cdh.princeton.edu/en/documents/):
- [x] Searching the below word אלמרכב should bring up entries with אלמרכב itself, as well as entries with מרכב
- [x] Same should be true for words starting with the other Hebrew prefixes

---

Moving this conversation over from #1335 since this isn't related to relevance scoring.

The problem is that `אלמרכב` is searched when `מרכב` appears in a transcription. The expected behavior is that this transcription should match and appear in the results, but it does not, because the word in the transcription is shorter than the word searched.

Unclear if this is fixable without implementing Hebrew language support in Solr. One possible solution is implementing n-gram filtering on queries, but it appears this was deliberately prevented.

**Comment by blms** [comment]
Additional comments from the other issue:

>  @blms מרכב אלצלטאן does not show up at all even though it appears four times https://test-geniza.cdh.princeton.edu/en/documents/?q=%D7%9E%D7%A8%D7%9B%D7%91+%D7%90%D7%9C%D7%A6%D7%9C%D7%98%D7%90%D7%9F&docdate_0=&docdate_1=&sort=relevance

_Originally posted by @kseniaryzhova in https://github.com/Princeton-CDH/geniza/issues/1335#issuecomment-2070871565_
            

> [Searching `מרכב AND אלצ` does] bring up the correct search results, I just think this is very confusing for users, when to add in the definite article and when not to add it. The word remains the same (with some implications for grammar, one is "a small ship" and the other is "the ship of the sultan" so there is a grammatical difference), so partial search results should capture it, right? Would this be something that could be helped with tagging this as Hebrew/JA?
> 
> I mean, when I search in English, I don't expect grammar to always be followed, just word order. Although with English word order is grammar, so that may not even be a helpful comparison.

_Originally posted by @kseniaryzhova in https://github.com/Princeton-CDH/geniza/issues/1335#issuecomment-2070889653_
            

> @kseniaryzhova To give a little explanation about how the partial matching works right now:
> 
> - the word `מרכב` appears in the transcription to be indexed
> - in indexing, solr tokenizes it as `מר`, `מרכ`, `מרכב`
> - you search `אלמרכב` and solr tries to match it against one of those tokens exactly: no match
> - you search `מרכב` and it matches the first of three tokens exactly
> 
> If the system knew your search term were Hebrew, it could try to separate `מרכב` as a stem for the word, and consider that as the actual token to match. But since we don't have that capability right now, it's only capable of matching the word itself as entered, or smaller.

_Originally posted by @blms in https://github.com/Princeton-CDH/geniza/issues/1335#issuecomment-2070908301_

**Comment by blms** [comment]
Additional context regarding ngram filtering:

>  > @rlskoeser I see in the indexing code that we are only applying edge ngram filtering on index, but not on query. Could this be related? And what was the reasoning behind that?
> 
> The goal was for search terms that are partial matches of the contents to return results without the user having to add wildcards. I think in most cases applying the edge ngram filtering on the query would have very confusing results.
> 
> It does sound like the best solution for this particular use case would be to move towards language-specific indexing.

_Originally posted by @rlskoeser in https://github.com/Princeton-CDH/geniza/issues/1335#issuecomment-2073368635_

**Comment by blms** [comment]
Decision: only check for each of the prefix characters `"ו","ל","ב","כ","מ","ה","שׁ"` at the beginning of each entered keyword. If one appears, search for that word both with and without it.

**Comment by kseniaryzhova** [comment]
@blms works as it should, closing, thank you!
