### ISSUE TITLE
As a public site user, I want a page to view details about an individual place, so that I can learn more about it and its presence in geniza documents.

### ISSUE THREAD

**Issue by blms** [Princeton-CDH/geniza#1584]
### testing notes (QA)

On the [QA admin site](https://test-geniza.cdh.princeton.edu/admin), navigate to the Places section.
- [x] Click on a Place and click "View on site" in the top right corner. This should navigate you to the Place Detail page for that place.
- [x] The page should match the design, linked below.
- [x] It should include a map with a pin, and metadata for lat/long coordinates, other names, and notes. (Assuming it's a place with all of that information filled out)
- [x] Links to related documents and related people should be disabled for now. But they should show the counts accurately.
- [x] Check this for a handful of places.

---

Designs here: https://www.figma.com/file/mPu59EJcveUnltjlll3twI/Princeton-Geniza-Project?type=design&node-id=968-78184&mode=design&t=wBlXyRcPbAr9Lie3-4

**Comment by kseniaryzhova** [comment]
@blms works as it should, thank you, closing!
