### ISSUE TITLE
As a public site user, I want a tab where I can list and sort documents related to a person or place, so I can see where they actually appear in the PGP.

### ISSUE THREAD

**Issue by blms** [Princeton-CDH/geniza#1586]
### testing notes (QA)

On the QA site:
- [x] Visit a handful of person pages from the [list of people](https://test-geniza.cdh.princeton.edu/en/people) (or [sorted by related documents, descending](https://test-geniza.cdh.princeton.edu/en/people/?date_range_0=&date_range_1=&sort=documents&sort_dir=desc)). Each should have a tab called "Related documents" with a count
   - [x] Counts should be accurate, and counts > 1 should be linked to the related documents page
   - [x] The related documents page should list all related documents entered in the admin
   - [x] The page should match the design
   - [x] It should be sortable by shelfmark, type, relation, and date
   - [x] Each document should be linked to its document details page
- [x] The same should be true for places, which you can currently access from the [QA site admin](https://test-geniza.cdh.princeton.edu/admin/entities/place/), by clicking on a place and clicking "View on site"

---

Designs here: https://www.figma.com/file/mPu59EJcveUnltjlll3twI/Princeton-Geniza-Project?type=design&node-id=768-11118&mode=design&t=kkNZCwBdruSsuqYV-4

**Comment by kseniaryzhova** [comment]
@blms works as it should, closing! Thanks!
