### ISSUE TITLE
As a public site user, I want the image/transcription/translation viewer on the document detail page to have a 3-up display, and default to this display when possible, so that I can see image, transcription, AND translation together.

### ISSUE THREAD

**Issue by blms** [Princeton-CDH/geniza#1591]
### testing notes

On the QA site, navigate to the [documents search page](https://test-geniza.cdh.princeton.edu/en/documents/). Find some documents with image/transcription/translation.
- [x] A document with all three of those should have all three open by default now
- [x] The image/transcription/translation viewer should be redesigned and match Chelsea's new designs
  - [x] Check this in light and dark mode, and with many different screen sizes / page widths, and many different documents
- [x] Redesigned image zoom/rotate controls should work as expected
- [x] Header labels should now read "Editor(s)" and "Translator(s)" instead of "Edition" and "Translation"
- [x] Click "Edit X's transcription" and/or "Edit X's translation". The editor should also have the redesign
  - [x] To save dev time, I made the drawing tools a toggle switch instead of a dropdown. Try using this; comment here if it is a problem and we can consider spending the time for the dropdown
  - [x] The pin icon should still work as expected
  - [x] You should now be able to open all three image, transcription, and translation even in the editor
- See also: #1592

---

Designs here: https://www.figma.com/design/mPu59EJcveUnltjlll3twI/Princeton-Geniza-Project?node-id=1213-78335&t=SN5AwaPMWCqB4bZI-4

**Comment by kseniaryzhova** [comment]
@blms works really well, thank you! I actually prefer the toggle and not the dropdown for the drawing tools, so I think no need to change it.
