### ISSUE TITLE
As a public site user, I want the image/transcription/translation viewer on the document detail page to use buttons instead of headers to open and close sections, so that it is less confusing how to interact with them.

### ISSUE THREAD

**Issue by blms** [Princeton-CDH/geniza#1592]
### testing notes

On the QA site, navigate to the [documents search page](https://test-geniza.cdh.princeton.edu/en/documents/). Find some documents with image/transcription/translation.
- [x] New design should use buttons to open and close image, transcription, translation instead of the headers, and these should work as expected
- See also: #1591

---

Designs here: https://www.figma.com/design/mPu59EJcveUnltjlll3twI/Princeton-Geniza-Project?node-id=1052-112559&t=SN5AwaPMWCqB4bZI-4

**Comment by kseniaryzhova** [comment]
@blms works well, thank you! Closing!
