### ISSUE TITLE
As a public site user, I want to be able to sort and filter people in the browse page by dates active in geniza documents, so that I can narrow down my browse results.

### ISSUE THREAD

**Issue by blms** [Princeton-CDH/geniza#1597]
### testing notes (QA)

On the [QA site list of people](https://test-geniza.cdh.princeton.edu/en/people/):
- [x] There should now be a date range filter under filters
- [x] It should allow you to enter start and/or end years
- [x] Those dates should have placeholder text for the min and max years
- [x] Entering those years should filter the list, and add a filter "chip" to the top of the screen, which can be clicked to unapply it
- [x] There should also be a sort option for dates, desc and asc, and it should work as expected
- [x] People in the list should show a human-readable date range that matches either their automatic date range, or override if one is present

---

Design here: https://www.figma.com/design/mPu59EJcveUnltjlll3twI/Princeton-Geniza-Project?node-id=776-79649&t=VPz32HXpOsQZv7ho-4

**Comment by kseniaryzhova** [comment]
@blms works as it should, thank you, closing!
