### ISSUE TITLE
Can't save, can't cancel

### ISSUE THREAD

**Issue by mrustow** [Princeton-CDH/geniza#1599]
<img width="1708" alt="image" src="https://github.com/Princeton-CDH/geniza/assets/73319225/a33feff6-201b-4e29-9162-87410c449560">

Running Chrome 125.0.6422.142 

Had multiple annotation boxes open at the same time. Got a scary message (image above). Couldn't click or scroll. Went to Chrome > About to find Chrome version number and it hard refreshed, solving the problem — and apparently also not losing my unsaved annotations.

**Comment by kseniaryzhova** [comment]
Marking wontfix because Ben was unable to recreate (and no one else seemed to have this issue)

**Comment by kseniaryzhova** [comment]
@blms Closing because we weren't able to replicate and this issue has not come up again.
