### ISSUE TITLE
As a data editor, I want to access links to external records where available so that I can view other versions of the item more easily.

### ISSUE THREAD

**Issue by kmcelwee** [Princeton-CDH/geniza#16]
- [x] Index `Link to image` column from metadata into solr
- [x] Add "View external record" link to record in search.
- [x] Index IIIF manifest for Cambridge records

**Comment by rlskoeser** [comment]
Records that have a "link to image" in the google sheet should now have a "view external record" in the search prototype.

Please test with a handful of records to confirm:
- [ ] records with links in the sheets have them in the search results
- [ ] the links match what is in google sheets and go to the correct location
- [ ] records without links do not display an external link in search results

**Comment by sluescher** [comment]
I have tested 10 with links, 6 without. 
[LinkTesting.txt](https://github.com/Princeton-CDH/geniza/files/5441454/LinkTesting.txt)

All ten records with image links had them in the search result, matched the google sheet link and took me to the correct location.

All six records without image links had no links in the search result.

A small point: would it be possible to have the link open in a new tab? 

> Records that have a "link to image" in the google sheet should now have a "view external record" in the search prototype.
> 
> Please test with a handful of records to confirm:
> 
>     * [ ]  records with links in the sheets have them in the search results
> 
>     * [ ]  the links match what is in google sheets and go to the correct location
> 
>     * [ ]  records without links do not display an external link in search results

**Comment by rlskoeser** [comment]
@sluescher you know, I thought about having them open another tab... I'm against that generally on principle, but this might be one of the cases where it makes sense. Does this matter for you while you're testing the prototype?

**Comment by sluescher** [comment]
It's fine. I am reversing my position. 

Generally, if I have search results, I prefer being able to open multiple tabs each with one record without leaving the search results, because inevitably the results page will move up or down and I have to double check where I left off. However that's perfectly doable with right-click.

**Comment by rlskoeser** [comment]
@sluescher maybe we should start a list of ideas and questions that the search prototype are prompting. Would it make sense to put them in our "future log" ?

@sluescher based on your testing and changing your mind about the links opening a new window, are you ready to sign off on this one now?

**Comment by sluescher** [comment]
Yes, happy to sign off.
