### ISSUE TITLE
As a content editor, I want to easily get from document editing to fragment editing, to easily make changes and contextualize the work.

### ISSUE THREAD

**Issue by richmanrachel** [Princeton-CDH/geniza#160]
Perhaps there can be a link to the fragment view next to the shelfmark? Or it can be a button alongside the History and View on Site?

![image](https://user-images.githubusercontent.com/68028846/117334649-3f7e3680-ae68-11eb-9bd4-6e32f26561e0.png)

## dev notes
add read only fragment edit link property to textblock and display in inline edit

**Comment by richmanrachel** [comment]
@rlskoeser and @thatbudakguy - Is this an easy issue that could be done quickly? I'm realizing it will help facilitate the meeting Nick and I have planned on Tuesday for complex documents. Thanks!

**Comment by thatbudakguy** [comment]
@richmanrachel it doesn't seem too difficult, but it's not looking like we'll have time before then. in the meantime, you can always click this button in the textblock list at the bottom of the document page:
<img width="374" alt="Screen Shot 2021-05-11 at 9 03 04 AM" src="https://user-images.githubusercontent.com/4924494/117819655-c2700a00-b237-11eb-9191-c8ac0530229d.png">
which will open a popup window showing the fragment on which the textblock appears.

**Comment by rlskoeser** [comment]
@thatbudakguy I thought we were thinking of adding something similar to that — if this is already here, do we still need that? What would be different?

**Comment by rlskoeser** [comment]
@richmanrachel the pencil and plus icons are django conventions that are used throughout the admin. I don't think we can customize the help text for it.

Maybe you (or someone!) could start working on a data editors guide/manual that includes this?

I think the built in functionality does what we need in this case, and we need to prioritize work to complete the data import, so I'm going to close this as a "won't fix".
