### ISSUE TITLE
As a public site user, I want a way to browse all the places in the database, so that I can find a specific place I am looking for, or get an overview of all places.

### ISSUE THREAD

**Issue by blms** [Princeton-CDH/geniza#1600]
### testing notes (QA -- round two)

On the QA public site, navigate to the [Places page](https://test-geniza.cdh.princeton.edu/en/places/).

- [x] The map and list should now show all places on initial load (up to 300)

### testing notes (QA)

On the QA public site, navigate to the [Places page](https://test-geniza.cdh.princeton.edu/en/places/).

- [x] You should see a map and a list
- [x] You should be able to zoom in and out, and pan around the map
- [x] You should be able to click a pin on the map and it should take you to the place entry in the list
- [x] Clicking on a place name should take you to the associated place page
- [x] You should be able to sort places by name, # relations to people, # relations to docs
- [x] There should be pagination at the bottom of the places list, which will show the remaining places on the map

---

Designs here: https://www.figma.com/design/mPu59EJcveUnltjlll3twI/Princeton-Geniza-Project?node-id=1296-74156&t=j2lDD6JvYKtq9Mqx-4

**Comment by kseniaryzhova** [comment]
@blms Everything looks good, except when we zoom in to the Egypt map, all the Arabic letters that should be connected are not.
![image](https://github.com/user-attachments/assets/f295a205-131d-4dcc-bda4-36bb4faa5867)

**Comment by kseniaryzhova** [comment]
@blms when we first open the places page, we do not actually see all of the places entered into the database, only the first 50 that appear in the list on the right. Could we show all of the places on the map, even if they're not in the 50 results shown in the list on the right?

**Comment by blms** [comment]
@kseniaryzhova Arabic letters: Unfortunately we don't have control over that, at least as long as we are using the supplied styles from MapTiler Cloud. If you would like, I can spend some hours (I would guess around 3) to see if self-hosting it and using a different font would be possible.

First 50 results: we can only ever show the same number of results on the map as those that appear on the right side of the page. But if you would like, we can increase that number beyond 50.

**Comment by kseniaryzhova** [comment]
@blms adding this here - based on the 8/29 Performant/PGP meeting, we decided to expand the places immediately shown on the map to 300.

**Comment by kseniaryzhova** [comment]
@blms shows all 61 so far (we'd need more place names to test further so that's on the PGP to do), and I wrote to MapTiler to see if they can fix the map issue and I may need your help on the technical bit.
