### ISSUE TITLE
As a public site user, I want a tab where I can list and sort places related to a person, so I can understand their geographical movement throughout the PGP

### ISSUE THREAD

**Issue by blms** [Princeton-CDH/geniza#1601]
### testing notes (QA)

On the QA site [list of people](https://test-geniza.cdh.princeton.edu/en/people):
- [x] Visit some people with pages and related places. There should be a tab for related places on the top of the detail page
- [x] The tab should include a count, and if greater than 0, should link to the related places page
- [x] The related places page should match Chelsea's design
- [x] There should be a map showing pins for all the places that have coordinates, and should automatically resize to show the group of pins on load
- [x] The list should be sortable by place name and relation
- [x] The list should include links to the places' detail pages

---

Designs here: https://www.figma.com/design/mPu59EJcveUnltjlll3twI/Princeton-Geniza-Project?node-id=768-11447&t=pOPcTgiwqgpHzWK7-4

**Comment by kseniaryzhova** [comment]
@blms works well, thank you, closing!
