### ISSUE TITLE
As a public site user, I want a tab where I can list and sort people related to a place, so I can understand geographical groupings of people in the PGP.

### ISSUE THREAD

**Issue by blms** [Princeton-CDH/geniza#1604]
### testing notes

In the [QA site admin places list](https://test-geniza.cdh.princeton.edu/admin/entities/place/), navigate to a place with related people. Click "View on site".
- [x] There should be a tab for "Related people" with a count next to it
- [x] The count should be accurate and, if greater than 0, should link to a page
- [x] This page should match the design for the places related people page (light and dark mode)
- [x] The list should be sortable by name and relation
- [x] People with person detail pages enabled (i.e. > 10 docs or manual override) should be linked in this list
- [x] Try this for a handful of places

---

Designs here: https://www.figma.com/design/mPu59EJcveUnltjlll3twI/Princeton-Geniza-Project?node-id=968-79318&t=2nIKfHE6uabmgB11-4

**Comment by kseniaryzhova** [comment]
@blms works as it should, thanks, closing!
