### ISSUE TITLE
As a public site user, I want applied filters to appear above the browse results at all time, without having the filters menu open, so that I can quickly tell which filters are applied and remove them one by one

### ISSUE THREAD

**Issue by blms** [Princeton-CDH/geniza#1606]
### testing notes (QA -- round two)

On the QA site [list of people](https://test-geniza.cdh.princeton.edu/en/people):
- [x] Applying date filters should no longer remove other filters

### testing notes (QA)

On the QA site [list of people](https://test-geniza.cdh.princeton.edu/en/people):
- [x] Applying filters should add "chips" (buttons) to the top of the page that show the applied filters
- [x] Clicking one should remove the clicked filter
- [x] These should remain on the page even when the filter panel is closed
- [x] There should also be a "clear all" button that should remove all filters

---

Designs here: https://www.figma.com/design/mPu59EJcveUnltjlll3twI/Princeton-Geniza-Project?node-id=1536-140618&t=2nIKfHE6uabmgB11-4

**Comment by kseniaryzhova** [comment]
@blms mostly works, but putting in start and end dates resets the gender filter.

**Comment by kseniaryzhova** [comment]
@blms applying date filters still removes the gender filter

**Comment by kseniaryzhova** [comment]
@blms Fixed! Thank you, closing!
