### ISSUE TITLE
Description snippets in search results appear inaccurately continuous when joined

### ISSUE THREAD

**Issue by blms** [Princeton-CDH/geniza#1607]
### testing notes (QA)

On the [QA site public search](https://test-geniza.cdh.princeton.edu/en/documents/):

- [x] Highlighted descriptions in search results should show [...] between incomplete snippets, such as the below.

---

Joining of description snippets without indication can be misleading, especially as solr returns incomplete sentences as snippets sometimes. For example:

![Screenshot 2024-06-24 at 2 43 38 PM](https://github.com/Princeton-CDH/geniza/assets/7234006/f911ab56-c04c-447c-a6fd-950864cddc32)

Proposed solution:

![Screenshot 2024-06-24 at 2 43 11 PM](https://github.com/Princeton-CDH/geniza/assets/7234006/44b4a86a-840c-4849-9960-2f4433e2f13a)

**Comment by kseniaryzhova** [comment]
@blms works well, thank you! Closing!
