### ISSUE TITLE
As a content editor, when editor and translator information is imported I want urls associated with the footnote so I can get to the resource if available.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#161]
## testing notes
footnotes now have a url field, and urls from the editor/translator field should be populated on import
- [x] url indicator on footnote list view
- [x] url filter on footnote list view
- [x] url visible/editable on footnote change form
- [x] url populated for editor/translator fields that have associated url (check a few of each)

----
split from remaining work on #108 

## dev notes
- move url from source to footnote (or possibly leave url on source but add url to footnote)
- revise editor parsing logic to set url on the footnote instead of in the source

**Comment by richmanrachel** [comment]
Would it be possible to make the "Source" column more narrow? I had to make my window full screen to see the "Has URL" checkbox:
![image](https://user-images.githubusercontent.com/68028846/119391887-f2d69000-bc9c-11eb-88bb-dd790bf0948f.png)

**Comment by richmanrachel** [comment]
>  url populated for editor/translator fields that have associated url (check a few of each)
@rlskoeser - what do you mean by this?

**Comment by rlskoeser** [comment]
@richmanrachel sorry, that was unclear! Some of the editor/translator entries have a link, like some of the google docs we were working on in the editor cleanup spreadsheet — this is just to confirm that the url is getting picked up and put into the new url field on the footnote.  (You can probably use the urls from the cleanup spreadsheet for testing if you can't load the full metadata sheet.)

**Comment by richmanrachel** [comment]
@rlskoeser - I'm not sure this last bit is working right. When I go to PGP ID 3504, for example, I see that Perry did a digitized transcription, but I have no way of getting to the URL. Plus, in this case, the transcription is showing up twice, as a side-by-side... https://test-geniza.cdh.princeton.edu/admin/corpus/document/3504/change/?_changelist_filters=q%3D3504
![image](https://user-images.githubusercontent.com/68028846/119513358-261f2a80-bd42-11eb-9e40-fbbb0585e08c.png)

**Comment by rlskoeser** [comment]
I noticed a few of those side-by-side transcriptions in passing! @thatbudakguy any idea what's going on? Is it something to do with the transcription data?

**Comment by rlskoeser** [comment]
@richmanrachel digitized transcription is different from url right now (which I recognize now might be a bit non-obvious...). I'm hoping that the url access will be a temporary solution, but wanted to preserve the information that's currently available.

Here's the footnotes list filtered by has url: https://test-geniza.cdh.princeton.edu/admin/footnotes/footnote/?url__isempty=0

If you click in to edit, you should see a url field that's populated with a link (almost always a google docs / google drive link, I think) — I just wanted you to check a few of those links.

Should the footnote url be available in the document edit view? I didn't think of including it there

**Comment by thatbudakguy** [comment]
The double transcription is because both the Perry and Goitein footnotes for that document have a `content` set to the transcription, so both are being included. That shouldn't happen during import, since we only attach the transcription to the first of the editions:
https://github.com/Princeton-CDH/geniza/blob/603fbb7c30a9939acc762e046922b45dd2cbfdf9/geniza/corpus/management/commands/import_data.py#L805-L809

**Comment by richmanrachel** [comment]
@rlskoeser  - URL does need to be viewable on document view as well (just in notes field is fine). Thanks!

**Comment by rlskoeser** [comment]
@richmanrachel footnote URL field is available now when editing footnotes inline on the document and source edit pages. Could you confirm and close?

**Comment by richmanrachel** [comment]
All good!
