### ISSUE TITLE
Use self-hosted TinyMCE

### ISSUE THREAD

**Issue by blms** [Princeton-CDH/geniza#1615]
### testing notes

On the [QA site](https://test-geniza.cdh.princeton.edu/):

- [x] Try adding and editing some transcriptions and translations. Should work the same as before; just testing to make sure the self-hosting didn't break anything.

---

Tiny.cloud now has a limit of 1,000 loads per month, which is too low for us, so we need to self-host.

- [x] Prevent loading css from absolute paths on the server
- [x] Include css as text into the correct override property 
- [x] Resolve issues with bundling css
- ~~Deploy hotfix~~

**Comment by kseniaryzhova** [comment]
@blms works for me, thanks! Closing!
