### ISSUE TITLE
As a content editor, I want to be able to view what a single document editor has edited, so that I can learn more about documentary geniza scholarship and help solve metadata problems.

### ISSUE THREAD

**Issue by mrustow** [Princeton-CDH/geniza#162]
Today Abigail figured out that some editions were by A. L. Udovitch by looking at the scans attached to the record and recognizing his typewriter. But she wanted confirmation. I noted that ALU usually edited trade letters related to Nahray b. Nissim. It would be great to have access to information like that at a glance. 

Another use-case would be wanting to know what Goitein chose to edit, since that determined the footprint of much geniza scholarship for a generation.

This may be tangentially related to another scenario we discussed in our meeting today: wanting to see records introduced into the database during certain time-ranges — except in this case, I'd want to see documentary texts published in certain time-ranges, for instance before 1954, so I know which edited texts Goitein had available when he started out.

**Comment by richmanrachel** [comment]
Decided as a team that there are workarounds in the backend and therefore we won't build this feature. Closing.
