### ISSUE TITLE
As a public site user, I want to see a section on the document detail page telling me "what's in the PGP", so that at a glance I can tell whether there is a transcription or translation without scrolling down.

### ISSUE THREAD

**Issue by blms** [Princeton-CDH/geniza#1623]
### testing notes (QA)

On the [QA public site](https://test-geniza.cdh.princeton.edu/), navigate to a handful of document detail pages.
- [x] Documents with images, transcriptions, or translations should have a section called "What's in the PGP" that should match the design below and accurately communicate what's digitally available

---

Design here: https://www.figma.com/design/mPu59EJcveUnltjlll3twI/Princeton-Geniza-Project?node-id=1476-63869&t=Vgr8PqU5E3CNYWih-4

**Comment by kseniaryzhova** [comment]
@blms works well, closing! Thank you!
