### ISSUE TITLE
As a public site user, I want lists of related people and places, by category of relation, with links, on the document detail page, so that I can get an overview of all relations.

### ISSUE THREAD

**Issue by blms** [Princeton-CDH/geniza#1625]
### testing notes (QA)

On the [QA public site](https://test-geniza.cdh.princeton.edu/), navigate to a handful of document detail pages that you know to have related people and/or places.
- [x] Those people and places should show up in lists on the doc details page, formatted according to the below designs

---

Designs here: https://www.figma.com/design/mPu59EJcveUnltjlll3twI/Princeton-Geniza-Project?node-id=1476-63869&t=PJRwKOh3vyNuEeT1-4

**Comment by kseniaryzhova** [comment]
@blms looks good, thank you! Closing!
