### ISSUE TITLE
Design all the design components for all the content pages that go under the "About" section to meet the needs of users

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/geniza#163]
[Here is a link to content styles](https://www.figma.com/file/HpGBOZi9lO8B3nCAx3d4Fj/Princeton-Geniza-Project-team?node-id=899%3A856) on Figma using sample pages from the Geniza Lab site. 

takes into account what is needed on Credits, How to Cite, Data Exports, Technical, and FAQ, and potentially the editorial pages. 

- [ ] Page titles 
- [ ] Section titles (h2 and h3)
- [ ] Paragraph style
- [ ] links
- [ ] bulleted lists
- [ ] numbered lists
- [ ] contextual notes (these would functionally act like the contextual notes in Startwords, [here is an example](https://startwords.cdh.princeton.edu/issues/1/data-beyond-vision/#fn:1) – design of the pop up box will be in another issue (for when we get to the editorial section)
- [ ] indented lines (e.g. for citation and pull quotes)
- [ ] images (including side-by-side images on desktop)
- [ ] image captions
- [ ] footer

**Comment by gissoo** [comment]
@thatbudakguy @rlskoeser 
I fixed the auto layout issue [here,](https://www.figma.com/file/HpGBOZi9lO8B3nCAx3d4Fj/Princeton-Geniza-Project-team?node-id=913%3A0) please let me know if there is anything else you would like me to do here.

@mrustow @richmanrachel [Here are the styles for content pages on mobile, tablet, and desktop](https://www.figma.com/file/HpGBOZi9lO8B3nCAx3d4Fj/Princeton-Geniza-Project-team?node-id=903%3A830) 
These would be for content that go under the "About" section of the site, and most probably used in the editorial section as well. 

The styles included are for: 
- Page titles 
- Section titles (h2 and h3)
- Paragraph style
- links
- bulleted lists
- numbered lists
- contextual notes (these would functionally act like the contextual notes in Startwords, [here is an example](https://startwords.cdh.princeton.edu/issues/1/data-beyond-vision/#fn:1) – design of the pop up box will be in another issue (for when we get to the editorial section)
- indented lines (e.g. for citation and pull quotes)
- images (including side-by-side images on desktop)
- image captions
- footer

@mrustow @richmanrachel please let me know if you have any questions and would like to discuss together, what you think, and if there is anything that we need that's missing here.

**Comment by richmanrachel** [comment]
@gissoo - This is too hard for us to understand on our own. Could we set up a time to meet, please?

**Comment by gissoo** [comment]
@richmanrachel Sure! I'll message you on Slack

**Comment by richmanrachel** [comment]
Sample texts that will be close to what we want on the site:

Credits: https://genizalab.princeton.edu/people/current-team

How to cite: https://genizalab.princeton.edu/pgp-database/citing-pgp

Data Export: https://genizalab.princeton.edu/resources/datasets 

Technical: https://genizalab.princeton.edu/pgp-database/technical-history

[And we don't have a good FAQ yet]

**Comment by gissoo** [comment]
@richmanrachel @mrustow Please review the revised designs – the new link is above, in the description section of the issue

**Comment by richmanrachel** [comment]
@gissoo - looks good to me! I'll make sure @mrustow reviews and gives the final go ahead by Thursday :)
