### ISSUE TITLE
Remove edition information from the top of the doc detail page

### ISSUE THREAD

**Issue by kseniaryzhova** [Princeton-CDH/geniza#1632]
**Describe the solution you'd like**
In the new designs, we decided not to include editor information at the top of the document detail page. This information will appear in the transcription/translation viewer and on the second tab (select bibliography)

**Comment by richmanrachel** [comment]
@blms - is this already done?

**Comment by blms** [comment]
@richmanrachel Yes! I guess we technically never tested it, but it's live on production already. Whoops 😅
