### ISSUE TITLE
As a public site user, I want a grid view for the people browse page, so that I can visualize the information differently.

### ISSUE THREAD

**Issue by blms** [Princeton-CDH/geniza#1646]
### testing notes (QA)

Navigate to the [QA site people browse page](https://test-geniza.cdh.princeton.edu/en/people).
- [x] It should be in grid mode by default, matching the below designs
- [x] Pressing the toggle switch in the upper right corner should change it to list mode
- [x] Your choice of list or grid mode should persist between pages
- [ ] The sorting and filtering should still work as expected

---

Design: https://www.figma.com/design/mPu59EJcveUnltjlll3twI/Princeton-Geniza-Project?node-id=1536-137025&t=j6IdWn59MJn2WOWB-4

**Comment by kseniaryzhova** [comment]
@blms everything works well, but the filtering is very slow for me. It takes at least 5 seconds for the results to show up after I've made my selections and this occurs when I'm applying multiple filters at once or just one. I'm not sure if it's just my device or if this is a broader issue.
