### ISSUE TITLE
As a public site user, I want content pages to match the style of the rest of the website, so that I am not confused by the inconsistency.

### ISSUE THREAD

**Issue by blms** [Princeton-CDH/geniza#1656]
### testing notes

On the [QA site](https://test-geniza.cdh.princeton.edu/):
- [x] Visit a content page. The new navigation and page margins should be present
  - [x] The navigation should take you to sibling pages, e.g. all other pages in the About section
  - [x] It should look OK at all desktop screen resolutions
  - [x] New feature added as part of this—Smaller desktop screen sizes should collapse the _top_ navigation menu into a hamburger menu in the top right, which should function similar to the mobile menu but on the side of the screen
- [x] Edit a content page. When editing the text of the page, there should be a + button, which gives you the option to add blocks such as paragraphs or images
- [x] There should be a new option here called "collapsible paragraph (accordion)"
- [x] Selecting that option should let you enter a label and content for the collapsible section
- [x] Once you preview or publish the page, you should see these collapsible sections and they should match the designs
  - [x] They should all be collapsed by default, but you should be able to open them to see their contents
  - [x] Multiple collapsible paragraphs should look OK when adjacent, and when separated by paragraph or image blocks

---

Designs here: https://www.figma.com/design/mPu59EJcveUnltjlll3twI/Princeton-Geniza-Project?node-id=2300-48972&node-type=canvas&t=ETBrhEF9D1FmoqrC-0

**Comment by kseniaryzhova** [comment]
@blms I was not able to use the accordion in wagtail. I see the plus sign but not the "collapsible paragraph" option.

**Comment by kseniaryzhova** [comment]
@blms On the test wagtail it works well, thank you! Closing!
