### ISSUE TITLE
As a public site user, I want an interactive network graph of related people, so that I can visually comprehend a person's interpersonal relationships.

### ISSUE THREAD

**Issue by blms** [Princeton-CDH/geniza#1660]
### testing notes

On the [test site](https://test-geniza.cdh.princeton.edu/), visit a person page (with at least 1 related person) and click "related people"
- [x] The people network graph should appear there
- [x] Closer relationships should be closer in proximity to the center person
- [x] You should be able to zoom (scroll) and pan (click and drag)
- [x] It should be more or less clear that all relationships are with the central person, and not between two other people in the graph

**Comment by kseniaryzhova** [comment]
@blms closing, thank you! I'll do the line thickness enhancement on a separate story!
