### ISSUE TITLE
Collections on document detail page sometimes listed in the wrong order for joins

### ISSUE THREAD

**Issue by blms** [Princeton-CDH/geniza#1674]
### testing notes (QA)

On the [QA public site](https://test-geniza.cdh.princeton.edu/):
- [x] For joins, "Collections" on public doc detail pages should always be listed in the order of shelfmark
- [x] Try joins with 3 or more collections

---

They should be listed in the same order as the shelfmark.

![image](https://github.com/user-attachments/assets/bbee3541-9577-475a-8fc6-9d0cc0a567c2)

**Comment by kseniaryzhova** [comment]
@blms for joins of multiple fragments with only two collections, they are not listed in order: https://test-geniza.cdh.princeton.edu/en/documents/30817/. But others work fine. Is it just that there are multiple fragments from the same collection on a join?

**Comment by richmanrachel** [comment]
@blms and @kseniaryzhova - tested on four different joins and it works! Closing :)
