### ISSUE TITLE
As a frontend user, I want to search in Judaeo-Arabic (Hebrew script) and get search results from both Arabic and Judaeo-Arabic transcriptions so that I can find more content that matches my search.

### ISSUE THREAD

**Issue by blms** [Princeton-CDH/geniza#1679]
### testing notes (qa -- round three)

On the [QA site](https://test-geniza.cdh.princeton.edu/):
- [x] Searching in Judaeo Arabic should generally result in the Hebrew script results coming up first, then Arabic script results afterwards
  - Sometimes this might not be the case, such as when an Arabic result is a 1:1 match and a Hebrew result is a fuzzy match—that could result in the Arabic showing up first. The presence of Hebrew prefixes in the search query will also impact this ordering. But it should generally be true.
- [x] The search `كتابي` should result in _fewer_ hits than `כתאבי`, due to there being more options going from JA to Arabic than vice versa, and the presence of a Hebrew prefix in the JA search.
  - note: the full expansions performed automatically by the search engine are
     - Arabic search: `كتابي OR כתאבי`
     - JA search: `(כתאבי OR كتابى OR كتابي OR ختابى OR ختابي OR كثابى OR كثابي OR خثابى OR خثابي) OR (תאבי OR تابى OR تابي OR ثابى OR ثابي)`
  - [x] Not only should it have fewer results, but all results from searching in Arabic `كتابي` should also be present in the search for the same term in Judaeo Arabic `כתאבי`

---

### testing notes (QA)

On the [QA site](https://test-geniza.cdh.princeton.edu/):
- [x] Searching in Judaeo-Arabic should bring up results in both Judaeo-Arabic and Arabic

---

Essentially the inverse of #706—search Hebrew script, get results in Arabic as well.

According to the team, it won't be a problem when the Hebrew language is searched instead of Judaeo-Arabic, as direct cognates _should_ be included, and the rest will produce nonsense that will almost certainly never match in an Arabic transcription.

Using Marina's guide here to create translation table: [Marina's Arabic to Judaeo-Arabic conversion chart](https://docs.google.com/document/d/1hcwWwBuPEmxc_FHpSk1JWoBZvs5Y1LOn8v6PIqaP9mA/edit)

**Comment by kseniaryzhova** [comment]
@blms works as it should, but it does now mix the Arabic and Hebrew script results, whereas for Arabic searches, the Hebrew is at the very end. Is there a way to prioritize the results where for Hebrew script searches the Hebrew script results come first?

**Comment by kseniaryzhova** [comment]
@blms searching a word in Arabic brings up 970 results, some of which are in Hebrew (كتابي). Searching the same word in JA gives me only 963 results and I can't find any Arabic (but I didn't check every single record, just 5 out of the 20 pages)

**Comment by richmanrachel** [comment]
I don't want to close this without @kseniaryzhova's approval, but I think it is working as expected!

**Comment by kseniaryzhova** [comment]
@blms I've tested a few words and it works! Maybe Alan or someone will find a bug or a case that this doesn't cover later on but I think it's good to close now! Thank you!
