### ISSUE TITLE
As a content editor, I want scholarship records from known journals imported as articles even if no title is present, so I can identify the resources and augment them later.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#172]
## testing notes
- check journal field is editable/usable in admin
  - [x] included on the source list page
  - [x] included on source edit page
  - [x] searchable
- check import of editor/translator records from known journals (working from Marina's original list)
   - [x] journal should be set
   - [x] volume should be set, when recognized
   - [x] should work for references with and without titles
   - [x] source type should be article

## dev notes
- [x] add journal field to source
- [x] revise editor parsing to identify articles based on list of known journals, even without title
- [x] import title if set, but import as article without title if necessary
- [x] adjust admin listing to include journal
- [x] include journal in str output

list of journals provided by @mrustow :
- Tarbiz
- Zion
- Ginzei Qedem
- Kiryat Sefer
- (The) Jewish Quarterly Review (also JQR)
- Shalem
- Bulletin of the School of Oriental and African Studies
- Jewish History
- Leshonenu
- Eretz Israel
- Qoveṣ al Yad (or Kovetz al Yad)
- Te’udah or Te’uda
- Sefunot (or Sfunoth)

**Comment by rlskoeser** [comment]
@richmanrachel @mrustow question about some other journal and/or book titles for the sources in the editor field:

I also found these — I think some are journal titles and some may be books, can you confirm/clarify?
- Otzar yehudey Sfarad
- Aretz Israel
- Yehoshua Finkel Festschrift / Joshua Finkel Festschrift
- Gratz College Anniversary volume
- AJS Review
- Studies in Judaica, Karaitica and Islamica
- Studi Orientalistic in onore di Levi Della Vida
- Mas'at Moshe
- Studies in Judaica, Karaitica and Islamica
- Dine Israel
- Journal of Semitic Studies

We don't currently have a book chapter / book section type; it looks like we need one to handle some of these entries. I'm thinking about how to generalize the journal field to be journal title for article or book title for book section.

I added another tab to the [editor/translator cleanup sheet](https://docs.google.com/spreadsheets/d/1v8uaX9a4cxXVW5oFUHOr9lVP4JFU_ej8voJtf_d3CkQ/edit?ts=608b768e#gid=1637835899) with a list of entries that have quotes but don't match any of the journal titles that I'm looking for currently (based on the list Marina gave me). Some of them have the sources listed above, but not all. What's the best way to handle reviewing these, should I make an asana task?

**Comment by rlskoeser** [comment]
@mrustow @richmanrachel one more question, about PGPID 730. The editor text includes "Goitein, JQR ns 66". What is "ns" here? Is 66 the volume of JQR?

**Comment by richmanrachel** [comment]
@rlskoeser - the correct bibliographic data for PGPID 730 is:
![image](https://user-images.githubusercontent.com/68028846/118872345-7582d800-b8b6-11eb-8cd5-a408911044b7.png)

**Comment by rlskoeser** [comment]
great, thank you @richmanrachel ! I've edited so 66 will be picked up as the volume

**Comment by richmanrachel** [comment]
Doing a quick search through the library website and JSTOR:
Otzar yehudey Sfarad [Can't find]
Aretz Israel [Probably misspelling of Eretz Israel in your other list]
Yehoshua Finkel Festschrift / Joshua Finkel Festschrift [Book: https://catalog.princeton.edu/catalog/2284769] 
Gratz College Anniversary volume [Book: https://catalog.princeton.edu/catalog/1703499] 
AJS Review [Journal]
Studies in Judaica, Karaitica and Islamica [Book: https://catalog.princeton.edu/catalog/652237]
Studi Orientalistic in onore di Levi Della Vida [Book: https://catalog.princeton.edu/catalog/3434723]
Mas'at Moshe [Book: https://catalog.princeton.edu/catalog/2428340] 
Dine Israel [Journal. Also sometimes spelled Dine Yiśraʼel on the library website]
Journal of Semitic Studies [Journal]
Sinai [Journal]

**Comment by richmanrachel** [comment]
@rlskoeser - the Journal does come up in the Source View page but not the Source Edit page, and it wasn't searchable.

**Comment by rlskoeser** [comment]
Drat. I see that now. I remember making the change somewhere, maybe it's in code that hasn't been delivered for testing yet. Sorry!

Any feedback from Marina on how she wants to handle book sections?

**Comment by mrustow** [comment]
A small request: in this window 
<img width="913" alt="Screen Shot 2021-05-20 at 11 36 34 AM" src="https://user-images.githubusercontent.com/73319225/119007936-b08d1600-b95f-11eb-811e-29ccc3259f76.png"> could we instead have this? 

Created from PGPID 5304
Peamim 78 (1999)

(Also, in the screenshot there is an apostrophe before Peamim that shouldn't be there)

**Comment by rlskoeser** [comment]
@mrustow I was thinking to clean those notes field up and not include them — they are extraneous parts of the source information that were not parsed. I created an `other_info` where I thought other parts of the citation could go (like for the dissertations). There are variations between versions that may otherwise be lost. Is this information useful?

**Comment by mrustow** [comment]
ah ok, sounds like the problem should go away when we clean up the scholarship records?

**Comment by rlskoeser** [comment]
@mrustow we're nearing the limits of how much more cleaning and refining we can do on the scholarship records before we import! I hope to improve it a bit more, but the notes might still be a bit messy. Do you prefer to have the extra information in case it is useful, or prefer not to have messy notes?

**Comment by rlskoeser** [comment]
@mrustow I'm glad you shared the screenshot, Peamim is another journal that wasn't on my list! It also helped me in my thinking about how best to clean up the notes.

**Comment by rlskoeser** [comment]
journal field on source is now journal/book, and should be searchable and editable

**Comment by richmanrachel** [comment]
@rlskoeser - Beautiful! Closing :)
