### ISSUE TITLE
As a content admin, I want book sections, unknown sources, translation language, and other information included in editor import so that more of the scholarship records are handled automatically.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#173]
## testing notes
- [x] confirm that sources from book sections from the list of books we identified on #172 are imported with type book section and the book title set in the journal/book field
- [x] look at the "source unknown" record in the source list and associated footnotes, and check a few footnotes to see that they have a transcription — this is how I'm handling documents where the editor field has text we're ignoring (like awaiting transcription, or similar) but we actually _have_ transcription content from the TEI
- [x] check language handling for editor/translator import; should be set when it's specified in the spreadsheet (Hebrew, German, and English)
- [x] check that extra citation information is included in the "other info" field (look at a dissertation for an example of this)
- [ ] check that source notes are not as messy as before (should not have the same text repeated as before)

## dev notes
- [x] handle translation language (combine with existing language detection)
- ~disambiguate the two Weiss authors~ (will handle manually)
- [x] for "Source of transcription not noted in original PGP database." — ignore if only that text; if that text plus anything else, put in document notes — _unless_ there is a transcription; in which case, create an anonymous unpublished entry (?) so we can associate it
- [x] put unparsed source information in `other_info` field; enable in admin edit and search
- [x] handle book sections from known book titles

**Comment by richmanrachel** [comment]
@rlskoeser - overall looks great! There was some repetition in the Other and Notes field, but I'm not too concerned about it for now:
![image](https://user-images.githubusercontent.com/68028846/119390863-a0e13a80-bc9b-11eb-90ee-3274b6e8d6a7.png)

**Comment by richmanrachel** [comment]
I guess the parsing is a bit more messed up in cases like this where the source accidentally went with Alan's revision date rather than the date of the dissertation:
![image](https://user-images.githubusercontent.com/68028846/119391022-d4bc6000-bc9b-11eb-8bd2-8333236d0045.png)

But I don't know if I should close this for now and we can just add an Asana task for clean up later?

**Comment by rlskoeser** [comment]
Yes, I've seen a few of those as well :-/ 

I think at this point we probably need to do the cleanup in the database — should we make a task specifically for reviewing and correcting dates in sources?

**Comment by richmanrachel** [comment]
@rlskoeser - I'll do that now. Closing this issue :)
