### ISSUE TITLE
As a content admin, I want notes and technical notes parsed and optionally imported into the database so I can preserve and act on important information included in those fields.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#179]
## Testing notes
- [x] Find a document in the metadata spreadsheet that contains "Old PGPID: ##" in the notes field and confirm that it has been properly placed in the document admin.
- [x] Ensure that notes (that aren't ignored) have been added to the "notes" field. 
- [ ] confirm that "FGP stub" is copied from technical notes to document notes in the database
- [x] Find a document that mentions Goitein scans and confirm that the notes have been properly formatted.

## dev notes
- for content in **notes2** field:
  - [x] if note contains an old PGPID, id should be parsed and added to old pgpid field. Possible variants:
    - `Old PGPID: 9563`
    - `Old PGPIDs: 9382, 16089`
    - `India; old PGPID: 16829`
  - [x] If note matches any of the following, ignore it:
     - India
     - India; unsure of date entered by Geniza Lab team (historical, before 2015)
     - India: addendum to IB IV
     - Rustow, Lost Archive
     - DISAGGREGATE
  - [x] all other content should be imported to notes field
- for content in **technical notes** field:
  -  [x] if content includes "?scanned in drive", insert this text into notes: "Look for Goitein scan in this folder: https://drive.google.com/drive/folders/1ZAWSK3ILoRyll0FafU61V5zdccx0CgaP?usp=sharing"
  - [x] if content matches "not in Gil", insert this text into notes: "Not published by Gil, pace FGP."
  - [x] if content matches any of these, then add to notes "There is a [transcription/translation] in Goitein's notes that should be digitized." 
     -  scanned in drive (TRANSCRIPTION + TRANSLATION)
     - scanned in drive (TRANSCRIPTION)
     - scanned in drive (TRANSLATION)

**Comment by rlskoeser** [comment]
@mrustow @richmanrachel I wrote up this issue based on what I'm seeing in the technical notes document. Could you review the list above and let me know what I've missed?  I do have some specific questions:
 - I wasn't sure what (if anything), we should do based on your notes for these two:  
    - TEI file is empty
    - DISAGGREGATE
- Is there anything you need done with technical notes? I can't tell from what's in the spreadsheet

**Comment by richmanrachel** [comment]
@rlskoeser - “DISAGGREGATE” is how Alan marked the shelfmarks that need demerging (and how Abigail is finding them, so please don't delete yet). This should be ignorable as all the relevant docs will hopefully be overwritten by the demerge sheet where this note will be deleted.

I'm afraid I don't know the answer to your other two questions. Your write up makes sense to me!

@mrustow - could you weigh in, please?

**Comment by richmanrachel** [comment]
@rlskoeser - reviewing our meeting notes from last week, and am still a little confused about what we decided regarding duplicates. This affects this technical notes section because "Merge idX and idY" appears. Did we confirm with Ben that he's doing this on his end?

**Comment by rlskoeser** [comment]
@richmanrachel To clarify — I'm not deleting anything in the metadata spreadsheet! But content in technical notes and notes2 won't be imported into the database unless we're directed to do so.

I don't think I was involved in the conversation on the "Merge idX and idY" notes! I see them in the older version of the list of notes, but they aren't in the new one. Looking at the spreadsheet, the notes about merging have been removed and I think most of the merges have been done (7214 is still in the spreadsheet, but the second id for all the others I checked was not). However, I don't see any "old PGPID" notes added to the remaining records to document the merge.

**Comment by richmanrachel** [comment]
@rlskoeser - oops! I didn't see the newest sheet on the spreadsheet. Thanks for the clarification.

**Comment by richmanrachel** [comment]
@rlskoeser - Marina has changed her mind about what should be imported to notes. Please continue to parse out the old PGPIDs, but she wants all other notes to stay as notes.

**Comment by rlskoeser** [comment]
@richmanrachel @mrustow  ok, thanks. So, to confirm/clarify: parse old pgpids and store them, but everything else in notes2 goes into the document notes in the database. Do we need to do anything with technical notes? If a note includes additional content besides the old pgpid, should that go into the notes in the database?

**Comment by rlskoeser** [comment]
@mrustow I've updated the instructions in the issue description based on your revisions to the technical notes & notes spreadsheet. Can you review to confirm I haven't missed anything for the technical notes?

**Comment by richmanrachel** [comment]
@rlskoeser - It all looks good to me, but @mrustow should be the one to sign off on the technical notes list.

**Comment by rlskoeser** [comment]
@richmanrachel ok, that makes sense. I see you've confirmed that it's working as intended, as far as you can — thanks.

**Comment by mrustow** [comment]
As far as I can tell there's only one note type on the technical notes list that still requires confirmation, and I'm checking on it now. The others are either crossed out on the list (because they no longer exist), or highlighted in turquoise (because they require action on import).

**Comment by rlskoeser** [comment]
Thanks for flagging this, I see there's one more action item flagged in turquoise since I wrote up the instructions for this issue!

@mrustow I checked and there are 5765 rows in the spreadsheet with "FGP stub" in the technical notes. Of these, there are 52 where the description does not include the text "Documentary per FGP - needs examination" — some of them look like actual descriptions, but a handful have only "Image not available?" for the description.

@mrustow please confirm, do you want all of these stubs (identified by either "image not available" or "documentary per FGP" text in the description) processed as you described, set to suppressed and have the note added that you have in the technical notes spreadsheet? 

Here is a list of the unique values that occur in the description for those that include the "documentary per FGP" text. Let us know if any of these should be treated any differently:
- Documentary per FGP - needs examination.    (5524)
- Documentary per FGP - needs examination. Image not available?  (160)
- Documentary per FGP - needs examination. Not digitized?  (6)
- Documentary per FGP - needs examination. Image not available.  (5)
- Documentary per FGP - needs examination. Very faded.  (2)
- Documentary per FGP - needs examination. Image not available. Apparently a book list in Ladino, per FGP.                                                                                                                                                                             - Documentary per FGP - needs examination. Image not available? Apparently a letter in Ladino, per FGP.                                                                                                                                                                                - Documentary per FGP - needs examination. Not digitized? Catalogued as scans of the Dead Sea Scrolls.                                                                                                                                                                                 - Documentary per FGP - needs examination. Current: T-S 8J31.3.                                                                                                                                                                                                                        - Documentary per FGP - needs examination. Includes 6 different shelfmarks. All look literary.                                                                                                                                                                                         - Documentary per FGP - needs examination. May in fact be literary.                                                                                                                                                                                                                    - Documentary per FGP - needs examination. Current: T-S 10J22.4.                                                                                                                                                                                                                       - Documentary per FGP - needs examination. Apparently a letter in Ladino, per FGP.                                                                                                                                                                                                     - Documentary per FGP - needs examination. Current: T-S 8J31.7.                                                                                                                                                                                                                        - Documentary per FGP - needs examination. Current: T-S 8J31.4.                                                                                                                                                                                                                        - Documentary per FGP - needs examination.*                                                                                                                                                                                                                                            - Documentary per FGP - needs examination. Not digitized? Catalogued as a document from Yemen.                                                                                                                                                                                         - Documentary per FGP - needs examination. It is unclear which shelfmark is meant. The only current shelfmark that might be documentary is M53 (alt: 19), which does not have images on FGP. If XIX is intended, see instead DK 230.3 (alt: XIX) or DK 228.3 (alt: 228/B, XIX).        
- Documentary per FGP - needs examination. Includes 15 different shelfmarks. There are several documentary ones, but all may be Ashkenazi/non-Geniza.                                                                                                                                  
- Documentary per FGP - needs examination. Image not available. Apparently a letter addressed to Yom Tov b. Eliyyahu Yisrael, in Ladino, dated 1876 CE, per FGP.                                                                                                                       
- Documentary per FGP - needs examination. Join by Elinoar Bareket.

**Comment by rlskoeser** [comment]
I've created a new issue to track the FGP stub suppression work; the only thing remaining to test on this one is that the "FGP stub" technical note is copied into the database.

**Comment by rlskoeser** [comment]
Confirmed that FGP stub technical note was included in the notes field on import
