### ISSUE TITLE
As a user, I want to search documents by keyword or phrase so that I can find materials related to my interests.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#182]
## testing notes

Test at https://test-geniza.cdh.princeton.edu/documents/ 

This is a preliminary version of the keyword search, and is missing a lot of functionality (see below for some of the many things that are out of scope). Also, be aware that not all edits in the database will immediately propagate to the search index (notably, changes to scholarship records currently do not); we will set up a cron job to reindex nightly until we're able to get on-demand indexing implemented for footnote/source edits.

You should be able to search across content in all of the following fields:
- [x] description
- [x] pgpid
- [x]  type
- [x] library / collection
- [x] shelfmark (including join notation  — the + should be ignored)
- [x] tags
- [x] scholarship record (source/footnote, including notes; try searching a scholar like Udovitch not mentioned in description)
- [x] old pgpid. Here are a few you can test with: 6160 (5575);  9382 or 16089 (2752), 9626 (9220)

Search result information should include:
- [x] document type + shelfmark (this is preliminary, does not look exactly like the final display in the design)
- [x] input date if known
- [x] pgp id
- [x] description excerpt
- [x] indicator and count if document has transcription, translation, discussion (AFAIK there are no footnotes in the db currently marked discussion; if you want to test this, you can edit one to change it and ask me to reindex)
- [x] link to document detail page

--- 

## dev notes

Preliminary implementation for public keyword search

Intentionally keeping this limited to try to keep it manageable. Out of scope functionality includes: pagination, sorting, image display, transcription search, keywords in context

**Comment by richmanrachel** [comment]
@rlskoeser 
- Type isn't working. ("Legal" produces a bunch of documents because it's used in descriptions and tags, but "paraliterary" produces zero results.)
- Shelfmark doesn't work. I got way too many results for a solitary shelfmark and no results for a shelfmark join that I copy-pasted from that previous results list:

![image](https://user-images.githubusercontent.com/68028846/120532778-0a54fd80-c3ae-11eb-9af4-31316763899b.png)


![image](https://user-images.githubusercontent.com/68028846/120532713-f5786a00-c3ad-11eb-806e-7a194fe14b8b.png)

**Comment by richmanrachel** [comment]
Everything else works!

**Comment by rlskoeser** [comment]
@richmanrachel 

> * Type isn't working. ("Legal" produces a bunch of documents because it's used in descriptions and tags, but "paraliterary" produces zero results.)

Good catch — it's case sensitive right now, so Paraliterary works but paraliterary doesn't. I'll fix that.

> * Shelfmark doesn't work. I got way too many results for a solitary shelfmark and no results for a shelfmark join that I copy-pasted from that previous results list:

I think shelfmark is working, it's just not working very well because we haven't done any relevance tuning yet, and Solr treats each part of a shelfmark as a "word" — which doesn't work particularly well for shelfmarks. In the examples you shared, it's matching on "T-S" and "Misc" in those other records, and we haven't configured it to care about matches in some fields (i.e. shelfmark) more than others. Similar for searching on join shelfmarks — I'd expect it to return every document that matches any one or portion of the shelfmarks included in the join (relevance ranking should help here too, though). 

Searching on this one seemed like it gave fairly reasonable results to me: T-S NS 184.55 + T-S NS 184.52 + T-S NS 184.56

When I tried searching on just 8.16 I didn't find the T-S Misc shelfmark you were testing with — should it be there?

Searching with quotes around the full join won't work because it isn't indexed as a phrase like that — the shelfmarks are indexed individually. It should work if you put quotes around individual shelfmarks (but we should tune it so that's not necessary).

Do you want to test a few more shelfmarks and see if there's something more going on? Or is the current functioality workable enough for a preliminary search?

**Comment by richmanrachel** [comment]
@rlskoeser - ah yes, I can see most of this is my bad... The shelfmark I had in mind was T-S Misc. 8.18 and it does come up, especially if I use quotes. 

I think that changing case sensitivity is high priority (and presumably an easy fix?). But I think it's okay to close for now? It's hard going back to such a bare-bones search after getting spoiled by all the filters in the back end :)

**Comment by rlskoeser** [comment]
Yes, changing case sensitivity is an easy fix — I'll can do that today or tomorrow.

I agree it's a very bare bones search! Just a starting point...

**Comment by rlskoeser** [comment]
confirmed that "paraliterary" search in lower case works in qa now
