### ISSUE TITLE
Add number for each scholarship record in the results on the browse and search results pages so the user can see how many scholarship records exist per result

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/geniza#186]
this was caught by RSK in #125 (look at the last two comments on the issue) – I have now included the number in parentheses next to each scholarship record in the results  – Including them in parentheses after each scholarship record is more consistent with how they appear in the search filters as well.  

We especially need to show the number of scholarship records for each result on these pages because we are offering sorting options for "highest-lowest" and "lowest-highest" scholarship records. 

Feel free to let me know if we want to use a different language for the sort since it's quantifiable "lowest" is probably not the right language.

I have included the sorting options in the designs as well, if you would like to see again what we had agreed on as far as sorting options in #125. @mrustow @richmanrachel 

Here are the [designs on Figma](https://www.figma.com/file/HpGBOZi9lO8B3nCAx3d4Fj/Princeton-Geniza-Project-team?node-id=953%3A523)

**Comment by gissoo** [comment]
@rlskoeser does this address what you had asked? Thanks for catching this! 

@mrustow @richmanrachel Please let me know your thoughts based on the description above, or we can also talk about this at our Tuesday meeting

**Comment by richmanrachel** [comment]
@gissoo - looks fine to me!

**Comment by rlskoeser** [comment]
@gissoo the numbers look great, thank you for adding. I think the wording for the sort should be most/least.

**Comment by richmanrachel** [comment]
@gissoo - We agree with Rebecca that most/least is perfect. Closing!
