### ISSUE TITLE
As a content editor, I want to import fragment view and IIIF urls from a csv file into the database so that I can provide access to images for fragments.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#187]
## testing notes
- [x] confirm that view and iiif urls have been added that weren't previously there (can check the totals when filtering and compare test/qa; not sure a good way to find specific examples)
- [x] confirm that fragments that already had urls were not overwritten (use sample script output)
- [ ] confirm that fragments that were updated also got a log entry to document it (here's [one example](https://test-geniza.cdh.princeton.edu/admin/corpus/fragment/453837/history/?_changelist_filters=url__isempty%3D0))

**Comment by rlskoeser** [comment]
## dev notes
New manage command to take a csv file with fragments and view or iiif urls to import into the database.

**Comment by rlskoeser** [comment]
Just ran this in qa with the spreadsheet of Cambridge shelfmarks + urls that Marina provided. Here's the end of the script output to help with testing:
```
....
Fragment T-S NS J230 url differs: https://cudl.lib.cam.ac.uk/view/MS-TS-NS-J-00230/1 https://cudl.lib.cam.ac.uk/view/MS-TS-NS-J-00230
Fragment T-S NS J249 url differs: https://cudl.lib.cam.ac.uk/view/MS-TS-NS-J-00249/1 https://cudl.lib.cam.ac.uk/view/MS-TS-NS-J-00249
Fragment T-S NS J251 url differs: https://cudl.lib.cam.ac.uk/view/MS-TS-NS-J-00251/1 https://cudl.lib.cam.ac.uk/view/MS-TS-NS-J-00251
Fragment T-S NS J262 url differs: https://cudl.lib.cam.ac.uk/view/MS-TS-NS-J-00262/1 https://cudl.lib.cam.ac.uk/view/MS-TS-NS-J-00262
Fragment T-S NS J268 url differs: https://cudl.lib.cam.ac.uk/view/MS-TS-NS-J-00268/1 https://cudl.lib.cam.ac.uk/view/MS-TS-NS-J-00268
Fragment T-S NS J269 url differs: https://cudl.lib.cam.ac.uk/view/MS-TS-NS-J-00269/1 https://cudl.lib.cam.ac.uk/view/MS-TS-NS-J-00269
Fragment T-S NS J270 url differs: https://cudl.lib.cam.ac.uk/view/MS-TS-NS-J-00270/1 https://cudl.lib.cam.ac.uk/view/MS-TS-NS-J-00270
Fragment T-S NS J282 url differs: https://cudl.lib.cam.ac.uk/view/MS-TS-NS-J-00282/1 https://cudl.lib.cam.ac.uk/view/MS-TS-NS-J-00282
Fragment T-S NS J283 url differs: https://cudl.lib.cam.ac.uk/view/MS-TS-NS-J-00283/1 https://cudl.lib.cam.ac.uk/view/MS-TS-NS-J-00283
Fragment T-S NS J292 url differs: https://cudl.lib.cam.ac.uk/view/MS-TS-NS-J-00292/2 https://cudl.lib.cam.ac.uk/view/MS-TS-NS-J-00292
Fragment T-S NS J295 url differs: https://cudl.lib.cam.ac.uk/view/MS-TS-NS-J-00295/1 https://cudl.lib.cam.ac.uk/view/MS-TS-NS-J-00295
Fragment T-S NS J296 url differs: https://cudl.lib.cam.ac.uk/view/MS-TS-NS-J-00296/1 https://cudl.lib.cam.ac.uk/view/MS-TS-NS-J-00296
Fragment T-S NS J305 url differs: https://cudl.lib.cam.ac.uk/view/MS-TS-NS-J-00305/1 https://cudl.lib.cam.ac.uk/view/MS-TS-NS-J-00305
Fragment T-S NS J342 url differs: https://cudl.lib.cam.ac.uk/view/MS-TS-NS-J-00342/1 https://cudl.lib.cam.ac.uk/view/MS-TS-NS-J-00342
Fragment T-S NS J344 url differs: https://cudl.lib.cam.ac.uk/view/MS-TS-NS-J-00344/1 https://cudl.lib.cam.ac.uk/view/MS-TS-NS-J-00344
Fragment T-S NS J375 url differs: https://cudl.lib.cam.ac.uk/view/MS-TS-NS-J-00375/1 https://cudl.lib.cam.ac.uk/view/MS-TS-NS-J-00375
Fragment T-S NS J376 url differs: https://cudl.lib.cam.ac.uk/view/MS-TS-NS-J-00376/1 https://cudl.lib.cam.ac.uk/view/MS-TS-NS-J-00376
Fragment T-S NS J380 url differs: https://cudl.lib.cam.ac.uk/view/MS-TS-NS-J-00380/1 https://cudl.lib.cam.ac.uk/view/MS-TS-NS-J-00380
Fragment T-S NS J382 url differs: https://cudl.lib.cam.ac.uk/view/MS-TS-NS-J-00382/1 https://cudl.lib.cam.ac.uk/view/MS-TS-NS-J-00382
Fragment T-S NS J388 url differs: https://cudl.lib.cam.ac.uk/view/MS-TS-NS-J-00388/1 https://cudl.lib.cam.ac.uk/view/MS-TS-NS-J-00388
Fragment T-S NS J389 url differs: https://cudl.lib.cam.ac.uk/view/MS-TS-NS-J-00389/1 https://cudl.lib.cam.ac.uk/view/MS-TS-NS-J-00389
URLs added: 5980
URLs updated: 0
IIIF URLs added: 5981
IIIF URLs updated: 0
Fragments not found: 14854
Fragments skipped: 1540
```

**Comment by richmanrachel** [comment]
@rlskoeser - do you have recommendations for how to test this? I didn't notice a problem before so I'm not sure what to check.

**Comment by rlskoeser** [comment]
@richmanrachel oh! I forgot that I need to run the script after I fixed the database earlier today, since we restored it with a copy of production data. I will do that now.

I did add some testing notes, but they may not be as helpful as they could be — I think it would be easiest if you compare cambridge fragments (or documents) in production with what's in test. Let me know if you want me to help you find specific records to test with.

**Comment by rlskoeser** [comment]
@richmanrachel ok, reran the script in test. Summary numbers are exactly the same as what I reported before.

**Comment by richmanrachel** [comment]
@rlskoeser - Does that mean I don't have to test the first part? I'm still confused about what to do, sorry!

**Comment by rlskoeser** [comment]
@richmanrachel I apologize! my fault for writing bad testing instructions (I was being lazy 🙄).

For the first test, I wanted you to see that the total number of fragments with iiif urls has changed after running this script. You can see this by comparing on the test site and production: if you go to the admin list of fragments and filter by "has image", the total of matching fragments is displayed near the search box. In production we currently have **1694**; on the test site, after running this script we have **7674**.

For the second test: check a few of the fragments that were reported by the script as already having urls. They should still have the url they had before, and not the url from the CSV file. Examples:
- T-S NS J389
- T-S NS J382
- T-S NS J251

For the third test: check a fragment that had url added by the script. See that view url and IIIF url are set and the IIIF viewer displays, and check that there is a log entry documenting that the image urls were added by script (use the "history" button on the top right of the edit form). Here are some example fragments you can check:
- T-S NS J400
- T-S NS J396
- T-S NS J392

**Comment by richmanrachel** [comment]
> In production we currently have 1694; on the test site, after running this script we have 7674.
- My numbers are slightly different, but show the same trend (1762 vs. 7926).

The History didn't work:
![image](https://user-images.githubusercontent.com/68028846/121918415-0311e600-cd04-11eb-834f-02bb4ecce552.png)

But this is so exciting!!! I can't believe we were able to pull so many more images! Thanks @rlskoeser

**Comment by rlskoeser** [comment]
@richmanrachel since iiif urls are only directly associated with the fragment and not document, you need to check the change history for the fragment to see the log entry. Here's one, does it look ok? https://test-geniza.cdh.princeton.edu/admin/corpus/fragment/28764/history/

**Comment by richmanrachel** [comment]
Oh, got it! Yes, it works:
![image](https://user-images.githubusercontent.com/68028846/121919035-9cd99300-cd04-11eb-8ca3-225b1d4cca89.png)
