### ISSUE TITLE
Stub all templates that use localizable site text

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/geniza#188]
See @gissoo's [doc with site text](https://docs.google.com/document/d/11aCR1nGLpgBHar_0nkXuh9Y0bL1oh-X-ZQvOQM6809k/edit?usp=sharing).

we need to create stub template files with placeholders for all these bits of UI text, which can first be implemented for English, and then later also localized.

<s>see also the Crowdin platform, where we could create a project and then [request open source access](https://crowdin.com/page/open-source-project-setup-request) to manage site text (and make it available in designs via a figma plugin).</s>

see [project on Crowdin](https://crowdin.com/project/geniza/) <s>GitHub integration is not yet configured</s>

## templates
- [x] doc detail page #110
- [x] scholarship records page a5f5c9a
- [x] external links page (no unique content)
- [x] doc search page #182

## snippets
- [x] doc detail page navigation a5f5c9a
- [x] main navigation 2c085c7

**Comment by rlskoeser** [comment]
@thatbudakguy is this complete now?

**Comment by thatbudakguy** [comment]
yep!
