### ISSUE TITLE
As a Content Editor, I want to download a CSV version of all or a filtered list of footnotes in the backend, in order to data work or facilitate my own research.

### ISSUE THREAD

**Issue by kmcelwee** [Princeton-CDH/geniza#189]
In the admin footnote list, you should have a button to download all footnotes as csv and a drop-down action to download footnotes sources. Here are the fields included in the csv:

- document
- source 
- location
- doc_relation (edition, translation, etc)
- notes
- url
- content (simple version of preliminary content from TEI, as displayed on admin site)
- admin_url

Please confirm you can download the whole thing as well as a selected set, and that the content looks correct.

**Comment by richmanrachel** [comment]
@rlskoeser - Works perfectly! Closing :)
