### ISSUE TITLE
As a Content Editor, I want to download a CSV version of all or a filtered list of sources in the backend, in order to data work or facilitate my own research.

### ISSUE THREAD

**Issue by kmcelwee** [Princeton-CDH/geniza#190]
## notes for testing
In the admin source list, you should have a button to download all sources as csv and a drop-down action to download selected sources. Here are the fields included in the csv:
- source_type
- authors 
- title
- journal_book
- volume
- year
- edition
- other_info
- page_range
- languages
- url
- notes
- num_footnotes
- admin_url

Please confirm you can download the whole thing as well as a selected set, and that the content looks correct.

**Comment by richmanrachel** [comment]
@rlskoeser - Both kinds of downloads work beautifully! And numbers for full import match as expected.
