### ISSUE TITLE
As a content admin, I want FGP stub documents with no descriptions suppressed and flagged and the notes updated so that I can reviewed and described them if appropriate.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#202]
split out from #179 

There are 5765 rows in the spreadsheet with "FGP stub" in the technical notes. Of these, there are 52 where the description does not include the text "Documentary per FGP - needs examination" — some of them look like actual descriptions, but a handful have only "Image not available?" for the description. 

On import into the database, the "FGP stub" technical note has been added to the document notes. 

## dev notes: 
Either as a database migration or a script, find all documents with "FGP stub" in the notes and process accordingly.
- if the document has a real description, remove the text "FGP stub" from the notes
- if the document has a stub description, set status to suppressed and replace "FGP stub" in the notes with "documentary per FGP, requires research"
- if a document is suppressed, add a log entry to document when and why it was suppressed

---- 
@mrustow please confirm, do you want all of these stubs (identified by either "image not available" or "documentary per FGP" text in the description) processed as you described, set to suppressed and have the note added that you have in the technical notes spreadsheet? 

Here is a list of the unique values that occur in the description for those that include the "documentary per FGP" text. Let us know if any of these should be treated any differently:
- Documentary per FGP - needs examination.    (5524)
- Documentary per FGP - needs examination. Image not available?  (160)
- Documentary per FGP - needs examination. Not digitized?  (6)
- Documentary per FGP - needs examination. Image not available.  (5)
- Documentary per FGP - needs examination. Very faded.  (2)
- Documentary per FGP - needs examination. Image not available. Apparently a book list in Ladino, per FGP.
- Documentary per FGP - needs examination. Image not available? Apparently a letter in Ladino, per FGP.
- Documentary per FGP - needs examination. Not digitized? Catalogued as scans of the Dead Sea Scrolls.
- Documentary per FGP - needs examination. Current: T-S 8J31.3.
- Documentary per FGP - needs examination. Includes 6 different shelfmarks. All look literary.
- Documentary per FGP - needs examination. May in fact be literary.
- Documentary per FGP - needs examination. Current: T-S 10J22.4.
- Documentary per FGP - needs examination. Apparently a letter in Ladino, per FGP.
- Documentary per FGP - needs examination. Current: T-S 8J31.7.
- Documentary per FGP - needs examination. Current: T-S 8J31.4.
- Documentary per FGP - needs examination.*
- Documentary per FGP - needs examination. Not digitized? Catalogued as a document from Yemen.
- Documentary per FGP - needs examination. It is unclear which shelfmark is meant. The only current shelfmark that might be documentary is M53 (alt: 19), which does not have images on FGP. If XIX is intended, see instead DK 230.3 (alt: XIX) or DK 228.3 (alt: 228/B, XIX).
- Documentary per FGP - needs examination. Includes 15 different shelfmarks. There are several documentary ones, but all may be Ashkenazi/non-Geniza.
- Documentary per FGP - needs examination. Image not available. Apparently a letter addressed to Yom Tov b. Eliyyahu Yisrael, in Ladino, dated 1876 CE, per FGP.
- Documentary per FGP - needs examination. Join by Elinoar Bareket.

_Originally posted by @rlskoeser in https://github.com/Princeton-CDH/geniza/issues/179#issuecomment-848791723_

**Comment by rlskoeser** [comment]
@mrustow when you get the chance, would you confirm that all of the "documentary per FGP" descriptions listed in the issue description as well as the "image not available" should be suppressed, or let us know any exceptions?

I also saw that there is an "FGP stub" tag, with substantial overlap with the technical note. There are 56 documents with the "FGP stub" tag without the technical note. The descriptions from that set that look like they have not been described are these:
- Arabic (according to FGP). Image not available.
- Arabic (according to FGP)
- Documentary per FGP - needs examination.

Should we treat these the same as the FGP stub technical note and clean up the "FGP stub" tag as part of this work?

**Comment by kseniaryzhova** [comment]
@rlskoeser this isn't a priority, Amir went through all the FGP stubs, and any remainders you can just search for in the document description field. Remainders are mostly Arabic. Anyway, closing!
