### ISSUE TITLE
Sorting fragments by collection raises a 500 error

### ISSUE THREAD

**Issue by kmcelwee** [Princeton-CDH/geniza#207]
## testing notes
in admin on the test site, go to the fragments list view and try to sort by collection — it should work and not raise an error. (Feel free to compare with production to see the difference)

--- 
Clicking on collection sort in the fragment admin causes an error. https://test-geniza.cdh.princeton.edu/admin/corpus/fragment/?o=2.1

Local debugging error:
```
Cannot resolve keyword 'lib_abbrev' into field.
```

**Comment by richmanrachel** [comment]
@rlskoeser - it works fine for me on both the test and non-test site. Closing!
