### ISSUE TITLE
As a content editor, I would like to input dates in a separate field, so that both content editors and site users can sort and filter documents by date.

### ISSUE THREAD

**Issue by mrustow** [Princeton-CDH/geniza#215]
## testing notes

I've implemented a super-simple version of this so you can start using it, and then we can revisit and refine after you've used it for a bit. 

- [x] confirm that document now has fields for original document date, calendar, and standardized date
- [x] confirm you can save without adding them (should be optional)
- [x] confirm you can add data to those fields (try searching for a description with a date, e.g. by "seleucid" and then add the date information in the description into the date fields)
- [x] confirm that admin document export includes the new date fields for the record you just edited

---- 

Here are the fields I had in mind (with explanations for those fields in parens). 

1. Date on document (for when there is an explicit date)

2. Calendar (according to which the document gives the date; these could be radio buttons)

- hijrī
- kharajī
- Seleucid
- anno mundi

3. Standardized date (CE, so Julian before 1582, Gregorian after 1582)

4. Inferred date (when there's no date on the doc, but someone has deduced one; these will often be ranges; it would be good to footnote inferred dates, and these, too, can be radio buttons)

- document editor (e.g., the transcription is by Moshe Gil, and he's also the one who inferred the date)
- team member who input the document
- computationally inferred (for later, when we can infer dates based on people's floruits, or even paleography)

**Comment by rlskoeser** [comment]
@mrustow I think we could give you a simple version of 1-3 this week if you need no or very little validation for 3. Implementing a simple version now will let you start inputting the data in a more structured form and will help us when we come back to it later to refine our solution and do more with the dates.

Am I understanding correctly that 1-3 all pertain to the document date?

I'm not sure yet how to implement 4 and think it should be a separate issue, but is good to have documented!

**Comment by richmanrachel** [comment]
Looks great! Small details:
- Kharājī needs to have the macron over the second a. 
- I think we need a bit more help text for the calendar selection (so undergrads can more easily translate what's in the description):
1. Hijrī (AH)
2. Kharājī (rare - mostly for fiscal docs)
3. Seleucid (sometimes listed as Minyan Shetarot) 
4. Anno Mundi (Hebrew calendar) 
- Current CE help text is good, but before "Julian" please add "covert to Julian..."

Could we easily add a "Has date" "Does not have date listed" Boolean filter in the Document List View for now?

**Comment by richmanrachel** [comment]
Re-opened for small changes above.

**Comment by rlskoeser** [comment]
> Could we easily add a "Has date" "Does not have date listed" Boolean filter in the Document List View for now?

@richmanrachel an empty/non-empty filter is easy if there's a single field (of these three) that you're comfortable relying on for indicating that a document has a date. Will that work for now, and if so which date do you want to base it on (original date, standard date?)?

**Comment by rlskoeser** [comment]
@richmanrachel have updated the help text and labels as directed, and the change is on the test site now. Please confirm.

**Comment by richmanrachel** [comment]
Looks great! Closing :)
