### ISSUE TITLE
As a user, I want to see a list of topic clusters so I can get a sense of the major areas of content and relationships between them.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#22]
- [x] Create a new view & template in flask app
- [x] Use Solr facet pivot to get a list of tags that appear together, with some minimum (maybe 50, to start)
- [x] Output list of tag pairs & number of documents

**Comment by rlskoeser** [comment]
- [ ] Create a new view & template in flask app
- [ ] Use Solr facet pivot to get a list of tags that appear together, with some minimum (maybe 50, to start)
- [ ] Output list of tag pairs & number of documents

**Comment by rlskoeser** [comment]
I think normally this would be 2 points, but since we're not writing unit tests for experimental/prototype code I think it's 1 point.

**Comment by rlskoeser** [comment]
@sluescher this is available on the test site now at https://test-geniza.cdh.princeton.edu/clusters/

@gissoo will be doing usability testing on the cluster search prototype, but to check the functionality please confirm that you see a list of document clusters, which are pairs of tags that occur on at least 50 document. For each cluster, you should see the two tags and the total number of documents.

**Comment by sluescher** [comment]
I am unsure how this is different from #23? I do see the list of topic clusters. I am assuming there might be more than just sets of tags at some point? Or is the plan to only have two at a time?

**Comment by rlskoeser** [comment]
@sluescher this one is the first step (just looking at the list of clusters) and #23 is the next step (selecting a single cluster to see the documents).

For the prototype, we decided to just use pairs of tags for our clusters. I think @gissoo is interested in having more than two pieces of information in a cluster (so it's more about connections within the data), and we may well generate clusters quite differently down the road, but this was a simple way to prototype the idea with the data we have now.
