### ISSUE TITLE
As a content editor, I want to merge document records without losing data so that I can combine records when I've identified duplicates or joins.

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/geniza#225]
## testing notes (round 2)

When merging documents in the admin backend:

- [x] Confirm that it now reads "Select primary document"
- [x] Confirm that you can see all scholarship records for all documents in the merge
- [x] Choose a rationale from the radio buttons; confirm that "duplicate", "join" and "other" are there
- [x] Confirm that you can't enter "other" without also entering a note below it; if you do, there should be an error after you try to submit

Note that the other requests mentioned (transcriptions labeled with footnote/citation in admin backend; all transcriptions expanded on the public site) have been spun off into separate issues.

---

## Testing Notes
- [x] Go into the admin interface and use the admin action to begin merging two or more documents. To get the same PGPIDs in the search results, you can use the "OR" syntax with their PGPIDs, e.g. "35058 OR 34031".
- [x] View the intermediate page. 
    - [ ] Is it clear what the primary document is?
    - [x] Is it clear what the "rationale" section is?
    - [ ] Do you have enough information in the "primary document" section to choose the correct document?
- [x] Click "Submit" on the intermediate page (note that this cannot be undone). Does the page redirect to the new primary document? Did the action preserve and merge all the information you expected?
- [x] Check the document history: does it include the merge with your name and the rationale you entered in the form?

## dev notes
- [x] Style `document_option_label.html`
- [x] Place the merge document view as an admin URL: https://docs.djangoproject.com/en/4.0/ref/contrib/admin/#django.contrib.admin.ModelAdmin.get_urls

---

**Is your feature request related to a problem? Please describe.**
See #170 for the management command that automatically identifies some candidates for merging and implements the logic for merging, but doesn't allow users to manually execute a merge.

See also https://github.com/Princeton-CDH/mep-django/issues/72 which provides the reference implementation for merging people, from shakespeare & company.

**Test case**
Alan's [recently identified join, `T-S 8J25.7 + T-S 8J16.15`](https://geniza.cdh.princeton.edu/admin/corpus/document/?q=T-S+8J16.15), which should be merged into a single record.

## dev notes
- [ ] create [new admin action that provides an intermediate page](https://docs.djangoproject.com/en/3.2/ref/contrib/admin/actions/#actions-that-provide-intermediate-pages)
- [ ] create a merge form & view that takes the documents to be merged, renders them with enough detail for the user to confirm the merge and choose a primary document
- [x] when the form is posted, use `Document.merge_with` method on the document selected as primary to merge the others
- [x] redirect user to the edit view for the merged document with [an info message indicating what was done](https://docs.djangoproject.com/en/3.2/ref/contrib/messages/)
- [x] require document edit permissions on the view
- [ ] error handling (but not sure yet what errors are likely to occur...)
- [x] unit tests for the new action & view

**Comment by richmanrachel** [comment]
Jake brought to my attention a good test case for making sure the merge function preserves footnotes: PGPID 3152, which is a 3 part join. The current Friedman footnote needs to be attached to all the shelfmarks (T-S 12.397 + T-S G1.5a + T-S As 155.329). 

I'm not sure how thoroughly we'll be going through the merge sheet to know whether the Primary doc has all the footnotes/attachments/etc, so just noting this down for documentation's sake.

**Comment by rlskoeser** [comment]
NOTE: we also need a way to unmerge when documents are merged by mistake

**Comment by kmcelwee** [comment]
@richmanrachel On the intermediate page, we'll ask you to select which document is the primary document. We can display a summary of each document's info before you make that choice. Would you mind providing a list of everything you want to see in that summary? Here's a rough outline of what the intermediate page will look like:

![Screen Shot 2022-01-31 at 2.11.11 PM.png](https://images.zenhubusercontent.com/5e9efff74d7b4923426b5c0d/fc7fab7c-0b01-4d62-9ad0-6e61fe901d3b)

**Comment by richmanrachel** [comment]
@kmcelwee - I think Description and whether there are any attachments to the footnotes are the most crucial things. 

We don't have a great way at the moment of distinguishing which footnotes are actually helping attach content, but this would be supremely helpful.

**Comment by richmanrachel** [comment]
@rlskoeser, @blms, and @kmcelwee - Overall, this is really easy and clear!

A few notes:
1) In the intermediate page, can we add a verb: "Select Primary Document"?
2) More on our side than yours, but we should come up with a few notes for how to phrase merge rationale so it will be consistent.
3) Could you make the scholarship records section automatically show (not drop down)? I missed it during the first merge

**Comment by alanelbaum** [comment]
Tried a few, and it seems to work without any hitches! Thanks so much for developing this! 

I definitely agree with Rachel's point #3 about scholarship records—that will be helpful when checking the merged record and making sure that the scholarship records are still looking good and deleting any duplicates that resulted from the merge.

What should I put for rationale? I imagine I'll end up typing "duplicate" hundreds of times—maybe we could make that the default selection, with an option for writing something different if the case is unusual for some reason?

**Comment by alanelbaum** [comment]
I did a test of merging two records with two different transcriptions (PGPID 516 and 4414) to see what happened. I see that both transcriptions were successfully preserved in the "Transcription" section, but on the resulting merged document record it's not clear which transcription belongs with which footnote. Maybe the editor information (in this case Gil for the Arabic-script one and Friedman for the Hebrew-script one) should be more closely linked to the transcription itself, and displayed together with it?

**Comment by alanelbaum** [comment]
Re: rationale, "join" will also be a common input. So maybe radio buttons would be ideal, where you can select "duplicate," "join," or "other: _______"

**Comment by rlskoeser** [comment]
@alanelbaum do you mean labeling the transcriptions we display in the admin site? that's probably a good idea — would it be fine to always do this or only when there is more than one?  

Did you look at how mutliple transcriptions are displayed on the public site after your test merge?

**Comment by alanelbaum** [comment]
Yes exactly - probably a good idea to always do it, but it only gets really confusing when there's more than one. (BTW I recently mentioned to Rachel that the editor information encoded within the Bitbucket files is often unreliable.)

I did check the public site (https://test-geniza.cdh.princeton.edu/en/documents/516/) - and it looks great! The one oddity is that the second transcription is concealed within a drop-down arrow.

**Comment by rlskoeser** [comment]
@alanelbaum thanks for checking — both transcriptions are collapsible, I thought that would make it easier (as a preliminary solution) to let you look at either transcription side by side with the image. (maybe the second one shouldn't be collapsed when there's no image; or maybe not at all...) I found it hard to make it clear that there is more than one! We'll get Gissoo working on the design for this sometime soon.

**Comment by richmanrachel** [comment]
@rlskoeser - Labeling all transcriptions would be a huge help. I think we've discussed this before, but knowing which footnotes are "empty" vs. "linked to content" would certainly prevent many future mistakes!

**Comment by richmanrachel** [comment]
@blms and @rlskoeser One bug that I'm still noticing that I forgot to mention yesterday: I can click the display to be in Needs Review mode, but it does not filter the content of needs review to the top of the list. So then I click the Needs Review button in the header to try to switch the filter so I can see the comments, but then the entire column disappears....

**Comment by richmanrachel** [comment]
The changes that were made are great! I think we are ready to close, though I do think we might need one more spin-off issue, because Alan is right that it's surprisingly hard to get the right search results. 

@rlskoeser, I know we shut down the convo about advanced search in the admin site a while ago, but is there a way we could at least have it for PGPIDs?

**Comment by rlskoeser** [comment]
@richmanrachel the advanced search with field-specific like `pgpid:###` that you tested for the public site is also available in the admin document search. Is that sufficient?

**Comment by richmanrachel** [comment]
@rlskoeser - no, because you can't put in multiple terms (for example to get both PGPIDs that need merging). Usually Needs Review only flags the secondary document, so I need to undo all the filters and search for both IDs to make it work
![image](https://user-images.githubusercontent.com/68028846/153297340-e6489551-3486-442f-942c-868414bbc25b.png)

**Comment by rlskoeser** [comment]
ah. here are some search syntax options that will work:
- 4421 OR 26617
- pgpid:4421 OR pgpid:26617
- pgpid:(4421 OR 26617)
