### ISSUE TITLE
As a user, when I select a topic cluster I want to browse the documents in that cluster and see their metadata and other tags so that I can explore everything in that cluster.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#23]
- [x] make cluster list (topic pairs) into links; pass tags via keyword arg to same view
- [x] if tag is specified, retrieve documents and display short record view (based on design + fields available currently)

**Comment by rlskoeser** [comment]
As with #22, please check the expected functionality: if you select a cluster from the list, you should see all documents in that cluster grouped into sub-clusters based on unique sets of tags that show up within that cluster.  (FYI: there's currently no logic to the sort order for the cluster; we've already determined it would be helpful to show the number of documents within each sub-cluster, but haven't implemented it yet.)

**Comment by sluescher** [comment]
I can see the sub-clusters and really love the Transcription and Bibliography check mark! That is much better than FJP one that only shows up once you are on the image.
