### ISSUE TITLE
As an admin, I want an easy way to get from the public document view to the edit view on the admin site, so I can make edits and correct errors..

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#231]
## testing notes
- before testing, login to the admin page: https://test-geniza.cdh.princeton.edu/admin
- then visit a document detail page (e.g. https://test-geniza.cdh.princeton.edu/en/documents/3504)
- [x] A link to "edit" with a pencil icon should appear in the upper right
- [x] This link should take you to the admin edit view for this document
- then test again as an anonymous user (log out or test in a different browser or incognito window)
- [x] confirm anonymous user does not see an edit link

## dev notes
- [x] update document detail template to add a link to the admin change view for that document
- [x] use template permissions check to only display the link if user has change permissions on documents
- [x] add template test to confirm the conditional display

We don't have any designs for this, but it's not a public feature anyway. I suggest putting it somewhere in the top right corner of the document detail page; label with text and an appropriate phosphor icon; make sure it looks reasonable on both desktop and mobile.

**Comment by richmanrachel** [comment]
Exciting update! Works well. Can we perhaps add something to @gissoo's design to show if you're logged in, or not?
