### ISSUE TITLE
500 error when trying to create a new document in the admin

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#232]
**Describe the bug**
When you try to add a new document in django admin, you get a 500 error (as reported by Alan Elbaum in Slack)

**Additional context**
Looks like an error in the template where document history is displayed — it doesn't handle the case where the document doesn't exist.

**Comment by richmanrachel** [comment]
This worked too!

![image](https://user-images.githubusercontent.com/68028846/121425685-af3c8100-c940-11eb-8723-226dc26b956b.png)
