### ISSUE TITLE
admin document csv export has wrong date for first input

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#234]
**Describe the bug**
First input column in the admin document csv export is the date from the _most recent_ log entry instead of the _first_ entry

**To reproduce**
1. Login to django admin and navigate to documents list
2. Select any subset of documents and choose export to csv 
3. Look at input date
4. See that the input date matches exactly the last modified date

**Expected behavior**
First input date should be earliest log entry date, not last modified date

**Comment by richmanrachel** [comment]
@rlskoeser - It's still not working :( 

![image](https://user-images.githubusercontent.com/68028846/121424681-98495f00-c93f-11eb-81ea-bdb506e8829b.png)

![image](https://user-images.githubusercontent.com/68028846/121424705-9f706d00-c93f-11eb-8640-d43b1c6e8b8d.png)

**Comment by richmanrachel** [comment]
Success now!
![image](https://user-images.githubusercontent.com/68028846/121425441-671d5e80-c940-11eb-867b-7f024e90d50e.png)
