### ISSUE TITLE
As a user, I want to see document titles that include shelfmark and type so I can distinguish documents at a glance.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#235]
## testing notes

visit [document type list](https://test-geniza.cdh.princeton.edu/admin/corpus/documenttype/) on the admin site:
- [x] confirm that display label is listed, and has been populated for types where display is different than type (should match Marina's list below)
- [ ] confirm you can edit or create a document type with display label — confirm you can add/or update it or leave it blank

Visit the public [document search page](https://test-geniza.cdh.princeton.edu/documents/)
- [x] Verify that document titles display in the format "**Document type**; shelfmark"
- [x] Verify that the document types display according to the labels specified below 
- [x] Verify that documents with unknown type read "Unknown type", rather than just "Unknown"
- Navigate to a document detail page
  - [x] Verify that document titles display in the same format as on the search page
  - [x] Verify document types display the correct labels
  - [ ] Verify documents with unknown type display correctly

## dev notes
Revise document display title to match the designs, and use the following labels provided by @mrustow based on document type.

| short name for back end | full name for front end |
|---|---|
| legal | legal document |
| letter | letter |
| list or table | list or table |
| literary | literary text |
| paraliterary | paraliterary text |
| state | state document |
| unknown | unknown type |

This applies to document detail page and search results

## dev notes
- add optional `display_label` field to document type model
- write a data migration to populate display labels that differ from short name
- include display label in admin list and edit form for document types
- revise `Document` `title` property to display label and follow format from the designs
- include document title in `index_data`
- display document title in search results

## Steps to test

1. Visit the document search page
2. Verify that document titles display in the format "**Document type**; shelfmark"
3. Verify that the document types display according to the labels specified in #235 
4. Verify that documents with unknown type read "Unknown type", rather than just "Unknown"
4. Navigate to a document detail page
5. Verify that 2-4 remain true on this page

## Deploy notes 

- Solr reindexing is required on deploy.

**Comment by richmanrachel** [comment]
@rlskoeser - For document types, the save button to change the labels doesn't work (it took a long time to load then landed on a 405 not allowed page).

**Comment by richmanrachel** [comment]
The unknown type also isn't showing up on the document detail view in the details (but the header is correct):
![image](https://user-images.githubusercontent.com/68028846/139945570-18a83467-aba0-450e-be1d-f5b57d57ed7b.png)

**Comment by richmanrachel** [comment]
Just for comparison, here's a letter:
![image](https://user-images.githubusercontent.com/68028846/139945665-9981e18b-a088-4fee-8a86-4e2c8f40d197.png)

**Comment by richmanrachel** [comment]
@rlskoeser - interesting! I reloaded the Document Types page, and both changes I made "funsies" and adding the ! to Literary did end up going through...

**Comment by richmanrachel** [comment]
![image](https://user-images.githubusercontent.com/68028846/139946062-2e451bfc-7e2a-4e8a-b19f-dd577b183dd1.png)

**Comment by rlskoeser** [comment]
ok @richmanrachel thanks for checking — I know Alan got a similar error a while back; I don't think it's related to this change, but if it keeps happening then it is probably something I need to follow up with PUL about.

... ooh, actually — possibly this one could help #290

**Comment by rlskoeser** [comment]
@richmanrachel thanks for catching the discrepancy between the unknown type and the other — I looked again at figma and I think that must be based on an old design because I don't see document type and shelfmark there (which makes sense, it's redundant otherwise). But in that case we should remove them.

**Comment by richmanrachel** [comment]
@rlskoeser - agreed, I think we can remove!

**Comment by blms** [comment]
@rlskoeser @richmanrachel In that case, maybe it makes sense to remove them in the course of #305 bundled with the other redesigns to that page. I'll make a note there as a reminder.

**Comment by rlskoeser** [comment]
@blms that makes sense to me, I think there are probably other discrepancies between the current template and what's in figma now. 

Based on that, @richmanrachel for the purposes of testing this issue, on document detail page only the header display is in scope. Are you comfortable accepting & closing?

**Comment by richmanrachel** [comment]
@rlskoeser - if you're confident that the slow loading is part of the PUL system, then yes!

**Comment by richmanrachel** [comment]
@rlskoeser and @gissoo - One additional comment from Marina after our meeting this morning: she would prefer that the punctuation between the Type and Shelfmark is a colon (not a semi-colon). I agree with this change.

**Comment by rlskoeser** [comment]
@gissoo any concerns with that change?

**Comment by gissoo** [comment]
@rlskoeser @richmanrachel that's totally fine! :) Thanks for tagging sorry for the delay. I'll reflect it in the designs.
