### ISSUE TITLE
Fragment reassociation doesn't update the search index

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/geniza#239]
**Describe the bug**
Changing the associated fragment for a document doesn't result in a corresponding change to the search index – the document is still findable under its old shelfmark instead of the new one. See [slack conversation](https://cdhprinceton.slack.com/archives/C016091ASAZ/p1623656912301500).

**Expected behavior**
Reassociating a document with a different fragment should immediately trigger an update to the search index, so that the document can be found using its new shelfmark.

**Comment by richmanrachel** [comment]
Worked immediately! Thanks!
