### ISSUE TITLE
As a user, when I search by keyword I want to see a list of matching clusters with the most relevant documents so that I can get to results but also see the context of related materials.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#24]
- [x] add keyword search input & form 
- [x] add new flask view & template for new search results (ideally template snippet for record display common to #23 )
- [x] implement solr search to retrieve and display documents in the cluster result format
- [x] determine and show which clusters documents in the search belong to
- [x] link clusters to cluster browse

**Comment by rlskoeser** [comment]
Decreasing from 5 to 3 points now that we aren't grouping search results.

**Comment by rlskoeser** [comment]
@sluescher the cluster search prototype at https://test-geniza.cdh.princeton.edu/clusters/ now has a keyword search option. The search fields and relevance ranking is the same as the simple search, but the result display is based on Gissoo's prototype design, similar to when you are browsing a single cluster.

Search terms in descriptions and transcriptions should be highlighted; if a search term matches a tag exactly, it should be highlighted.

If a result belongs to any clusters, those clusters should be listed under the main record. If you click them, it should take you to the cluster browse for that cluster.

**Comment by sluescher** [comment]
Search terms are highlighted in descriptions, transcriptions, and tags.

Clusters are listed under the main record and it does take me to the cluster browse.

Only comment I have is that it would be easier if the cluster browse would open on the right side, without my search disappearing. So that I could then move down my search result and explore any other clusters that are shown under other records.

**Comment by rlskoeser** [comment]
Interesting. @gissoo I think we discussed whether or not to show the clusters with the search results, didn't we? @gissoo  I'll be interested to find out what else you find out from usability testing.

**Comment by rlskoeser** [comment]
@sluescher any more testing you want to do on this one? Are you comfortable with signing off on the basic functionality working as expected?

**Comment by sluescher** [comment]
Yes. I was waiting for an answer from Gisso :) but happy to sign off with the question. Should I add my comment to the prototype document?

**Comment by gissoo** [comment]
@rlskoeser we totally did!! And I also think it makes sense from the users' side!! And it's already been on my list to do usability testing on :) @sluescher So exciting that you brought it up, thank you for writing!!
