### ISSUE TITLE
Split Goitein's Typed Texts into "Volumes" by shelfmark to make the sources easier to manage.

### ISSUE THREAD

**Issue by richmanrachel** [Princeton-CDH/geniza#240]
**Is your feature request related to a problem? Please describe.**
Currently there are nearly 2300 footnotes connected to Goitein's Typed Texts (with varied spellings and under a few source names), which makes it impossible to properly edit the source.

**Describe the solution you'd like**
I propose that we give the Typed Texts "Volumes" based on the shelfmark prefix to help divide them into more manageable chunks. Ex. Goitein, Typed Text, Vol. T-S

**Describe alternatives you've considered**
Alternately, we could use notes rather than Volume, but I think Volume will make it easier on the backend.

**Comment by rlskoeser** [comment]
@richmanrachel @mrustow splitting out footnote Goitein typed texts by shelfmark prefix looks pretty good for most cases, but still results in 1770 footnotes with the T-S prefix.  What would be a meaningful way to further subdivide?

Here's a quick count of documents associated with Goitein typed texts and  T-S shelfmarks:
- T-S 20: 15
- T-S Ar: 40
- T-S H1: 1
- T-S K2: 1
- T-S 18: 36
- T-S 13: 352
- T-S 28: 1
- T-S J1: 3
- T-S 12: 122
- T-S 8J: 513
- T-S AS: 113
- T-S Mi: 18
- T-S 6J: 86
- T-S 8.: 14
- T-S 24: 12
- T-S G1: 2
- T-S NS: 136
- T-S 16: 97
- T-S J2: 4
- T-S 10: 272

Here are the totals based on how I'm splitting the footnotes currently:
![Screen Shot 2021-06-15 at 12 58 22 PM](https://user-images.githubusercontent.com/691231/122093794-6f124e00-cdd9-11eb-8700-5f9f5bfffc2f.png)

**Comment by richmanrachel** [comment]
@rlskoeser - I just consulted with Marina, and we agree that the T-S breakdown as you have it above is good! 

Just small note that "T-S Mi" needs to be "T-S Misc." :)

**Comment by rlskoeser** [comment]
@richmanrachel ha, thanks! I neglected to note that I was just grabbing the first 7 or 8 characters of the shelfmarks. The other prefixes I'm showing are all meaningful as is?

**Comment by richmanrachel** [comment]
@rlskoeser - Yep! Others are good as is!

**Comment by rlskoeser** [comment]
@richmanrachel this change is on the test site now, please review and see if you have any concerns.

FYI, I kept the old source (which now has no footnotes associated) in case you still needed to do anything with the notes; I also left the capitalized "Typed Texts" source alone — both of those seemed small enough that someone could make the necessary changes once the main mega-source is split out.

FWIW, I think the volume display for footnotes/editors is not ideal (probably not ideal in general, and not just for volume; possibly worse for these new "volumes" we've created). I would prefer to deal with that separately; it would help to know how urgent it is to get fixed.

**Comment by rlskoeser** [comment]
closing per @richmanrachel comment on slack:
> looks great and can be closed!
