### ISSUE TITLE
As a content editor, I want to be able to edit the Historic Shelfmark so that I can correct errors in the metadata.

### ISSUE THREAD

**Issue by richmanrachel** [Princeton-CDH/geniza#241]
Based on Slack conversation in CDH-PGP initiated by Alan on 6/13.

## testing notes
- [x] when editing a fragment, you should be able to add or modify historic shelfmarks instead of the read-only configuration we had previously
- [x] if you change the main shelfmark for a fragment, it should still add the old shelfmark to the list of historic shelfmarks when you save the record

**Comment by rlskoeser** [comment]
@richmanrachel I felt like there should be validation on the field if we're making it editable, but then when I couldn't think of any meaningful validation to add. Let me know if you have any ideas.

**Comment by richmanrachel** [comment]
@rlskoeser These features work, but bring up a couple of suggestions:
- Old Shelfmark is not visible on the Document Detail page, and that's where most work will be done. Could we please add it to Document View?
- Can we change "Old PGPID: Unknown" to "Old PGPID: N/A"? I think it will reduce confusion.

As for validation, is there some way of having a pop-up "Would you like to change the shelfmark for the other documents attached to this fragment? PGPIDs x, y, z?"

**Comment by rlskoeser** [comment]
Good call on the old pgpid unknown, I had sort of noticed it in passing but not investigated. Will address.  I propose setting it to "-", which is the django default for empty fields. (We overrode that, I think primarily for unset document type, which we're calling unknown).

I can't see how to include old shelfmarks on the document edit form — we could make a list of them somewhere for display purposes, but I don't think that's what you're looking for.

I don't think a popup would help for validation... having it only be editable on the fragment page means you should be able to see associated documents (although I suppose you might have to scroll?)

**Comment by richmanrachel** [comment]
Thanks, - is fine.

Display for old shelfmark would be fine. It will just make it easier for searching, and we can open the popup for shelfmark editing as usual.

What type of validation were you thinking of or worried about?

**Comment by rlskoeser** [comment]
> Display for old shelfmark would be fine. It will just make it easier for searching, and we can open the popup for shelfmark editing as usual.

Ok, great. Please suggest where you'd like it added and open a new issue so we don't block this one from being closed.

> What type of validation were you thinking of or worried about?

Fields that we operate on automatically — in this case, adding a shelfmark if it is changed — seem like they should have some validation if they're also editable. But there's such variety in shelfmark content, _and_ there could be just one entry and not multiple — so I don't think there's a useful regular expression I could write that would do us any good. We're not doing a lot with the field, so it's probably ok — it's just potentially problematic when both humans and code are updating the same field. 🙂
