### ISSUE TITLE
As a content editor, I want to be able to filter documents by library, so that I can narrow down clusters of documents and perform other research and data tasks.

### ISSUE THREAD

**Issue by mrustow** [Princeton-CDH/geniza#248]
I'm not yet sure whether Cambridge should be handled as a single library, or whether we might want to sub-filter Cambridge by collection (i.e., shelfmark prefix), on analogy with how we're dividing up the Goitein transcription groupings. Others may have more developed ideas about this.

**Comment by rlskoeser** [comment]
Added a simple implementation of this based on collection display label for now, and @richmanrachel reviewed and signed off — included in 0.4 release
