### ISSUE TITLE
As a content admin, I would like to be able to batch upload new documents from a .csv so that I can avoid entering hundreds of documents one by one. 

### ISSUE THREAD

**Issue by mrustow** [Princeton-CDH/geniza#249]
[Is this a feature request? I'm not sure, feel free to re-categorize!]

There is one application I currently have in mind for this, but I can think of others, so it seems worth doing:

1. Lorenzo (a postdoc) is currently tasked with entering 1000+ Arabic-script documents from a spreadsheet into the PGP metadata. Some will need to be split from existing records. But others will be new, not yet represented in PGP. If Lorenzo can massage the data so that it's structured like the old PGP spreadsheet, presumably it will be a timesaver for the project, and also avoid errors, if he can simply pass a spreadsheet on to you and the contents get ingested in batch.
2. We may well want to reuse this down the road, for instance for scholars who are keeping their own big spreadsheets that they are then willing to hand to us. Oded Zinger comes to mind — at last check he had a spreadsheet of 3800 docs not all of which were in PGP. That raises the further question of what do we do if his information or entries duplicate ours, but we can cross that bridge anon.
3. Another use-case would be if Cambridge or another library comes out with a new batch of descriptions that we want to import. Maybe that can be handled via IIIF annotation, but that route would depend on many factors, so easier, it seems, would be for us to get a .csv from them with the fields that serve us.

**Comment by richmanrachel** [comment]
Just noting for the record that we now have adjusted to the CSV structure for downloads from the admin site and would likely want to structure the CSV for upload in a similar fashion.

**Comment by richmanrachel** [comment]
@blms and @kseniaryzhova - do you agree that we should officially close this story (without completing) since we discovered that it's easier to add documents than reformatting a csv to perfection?

**Comment by blms** [comment]
That makes sense to me @richmanrachel but I leave it to PMs to determine.
