### ISSUE TITLE
As a content editor, I want to be able to click on the image thumbnails so that I can examine a fragment more closely.

### ISSUE THREAD

**Issue by mrustow** [Princeton-CDH/geniza#250]
Dude, what can I say: this would be one giant step toward integrating metadata + transcriptions + images, weaning us from the Death Star that is FGP and the annoyingness that is multiple browser tabs. Here's a screenshot: 

![image](https://user-images.githubusercontent.com/73319225/122445956-1a550b80-cf70-11eb-9b38-0b4a724360da.png)

Let's click those thumbnails! <3

**Comment by rlskoeser** [comment]
@mrustow please clarify, what is that you want to happen when you click on the image thumbnail? From the discussion before I thought you wanted us to have it open the fragment view url (e.g., display on CUDL) in a new browser tab, but your comment about death stars and multiple tabs is making me question that.

**Comment by mrustow** [comment]
Ha sorry, was being too cute ☺️ Fragment view URL is right.

**Comment by richmanrachel** [comment]
This kind of exists already, you just need to click the pencil button next to the shelfmark. I agree that this feature could be clearer though. [Also, @rlskoeser - I may have found a little bug here. The images show up in the fragment view but not the document view]
![image](https://user-images.githubusercontent.com/68028846/129784944-8f2a1c17-c33a-4050-b73b-462ceb28d469.png)

How do we want to proceed?

**Comment by rlskoeser** [comment]
@richmanrachel oh, good catch — I do see that some of the thumbnail images are not rendering. It looks like the CUL images are ok but all the Cod shelfmarks I looked at are broken. I did some quick poking around and I think it's something to do with the version of IIIF Image API they support and how I'm requesting the thumbnail.

**Comment by richmanrachel** [comment]
Just checked with Marina and we can close this. The work around is good!
