### ISSUE TITLE
As a content editor, I would like to be able to distinguish between the primary and secondary languages on a document.

### ISSUE THREAD

**Issue by mrustow** [Princeton-CDH/geniza#251]
[I believe this is a schema change ... relabel as needed]

So this would mean we would have:
1.  Primary language(s)
2. Secondary language(s)
3. Probable languages(s)

Then on the workflow end, we would develop clear criteria for distinguishing among 1ary and 2ndary, as follows:

- if a letter is half in Arabic and half in Judaeo-Arabic, those are both primary languages. But if a letter is all in Judaeo-Arabic except for the Arabic-script address, Arabic is a secondary languages.
- if a legal document is in Aramaic (like Rabbanite marriage contracts), but the dowry list is in Judaeo-Arabic, those are both primary languages. But if a legal document is in Hebrew with a few Aramaic technical terms thrown in, Aramaic is a secondary language.
- We should check these rules with Eve, who has thought more about language mixtures than I have.

**Comment by rlskoeser** [comment]
More details from discussion: we want to relabel the existing language field to be the primary language (maybe just verbose name change in the code) and add a new language field for secondary languages. Validation should require no overlap of any languages (a language can only be in one of those categories at a time).

It would be great to have help text provided before we implement this.

**Comment by rlskoeser** [comment]
After discussing with @thatbudakguy , I'd like to push back on this feature request. It's hard for me to imagine us implementing a search filter that makes use of the various language fields (primary, secondary, probable) — it would require a very complicated interface. And if we're not using it in the search, I'm not sure it's worth all our collected time to implement the feature and enter the data.

Could you use a different data workflow to handle this? e.g., only record it as a language if it is over some meaningful  % of the document(i.e. primary); if it's a secondary language (like the addresses), that could be noted in the description but not in the language field.

**Comment by thatbudakguy** [comment]
> if it's a secondary language (like the addresses), that could be noted in the description but not in the language field.

I like this proposal. Just to extrapolate it a little, I think that would still mean that you could find e.g. "all documents with _any_ amount of Ladino" using the search, by searching for "ladino". What would likely happen is that documents whose language matched the term "ladino" (because it is the primary language) would appear first in your search results, but documents with "ladino" in the description would still match as well — they would just be further down in the results, reflecting the fact that the language isn't primary.

**Comment by richmanrachel** [comment]
@rlskoeser and @thatbudakguy - after your feedback and further consultation with @mrustow and Alan, we've decided that we'll actually just clean up the current Probable languages and have you rename Probable to "Secondary."

I'll close this issue and open an Enhancement issue when we're ready for the name change.
