### ISSUE TITLE
Revise the scholarship records page layout so the list of cited work looks more like a bibliography than a list

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/geniza#253]
The revised designs regarding the order of information follow [RR's comment](https://github.com/Princeton-CDH/geniza/issues/135#issuecomment-863412087) on #135, except that I put title before the name.

- [This version – A](https://www.figma.com/file/HpGBOZi9lO8B3nCAx3d4Fj/Princeton-Geniza-Project-team?node-id=1103%3A1251) is with the link to source on its own paragraph
- [This version – B](https://www.figma.com/file/HpGBOZi9lO8B3nCAx3d4Fj/Princeton-Geniza-Project-team?node-id=1114%3A110) is with the link to source on the same paragraph as the rest of the information 

Note: 
- on both versions no.1 shows the format, and 2 and 3 show the example from the data.
- I have italicized the titles 
- I have applied auto layout here as well.
- Let's decide on "transcription" vs. "edition" – as I noted in #135 I remember that we decided to use "Transcription", so let me know your thoughts.

**Comment by rlskoeser** [comment]
Thanks for working on this, @gissoo .

As I noted on https://github.com/Princeton-CDH/geniza/issues/252#issuecomment-866244609 , I think Marina and Rachel need to provide us at least preliminary citation format for sources. We have a lot of different source types (book, article, book section, unpublished...), and a lot of fields are optional, so there may be a lot of variation. I'm hoping we can figure out the variation if Marina and Rachel provide full examples for each type.

We _did_ agree on Transcription as being more accessible / comprehensible to a general audience! However, when I went to make the change in the code I was concerned about it being so visually similar to Translation; I think it could easily cause content editors confusion and they might click the wrong one if they weren't looking closely (it would also be confusing in the code). When we discussed it again, Marina agreed based on my concerns and also noted that Edition is the term used in the field.  I don't think the language in the admin interface and the public site necessarily need to match, though! Using Transcription for the public site is fine with me if you think it is the most accessible term; am curious what Marina thinks.

@gissoo some detail questions:
- What will be the text of the link for "link to source" be?  (In case it matters, many scholarship records will not have links)
- Many footnotes in the database have notes (e.g., of a transcription is by Goitein but with suggestions/emendations from Alan Elbaum, or from a published text by Goitein but with corrections from his unpublished materials); would you recommend including those here or not?  
- Do you have a sort order in mind?
- I see you have the editor listed above the numbered list — in the database, that edition/transcription one of the scholarship records. Should it be included or omitted from the list of scholarship records?

**Comment by mrustow** [comment]
I'm happy with "edition."

**Comment by gissoo** [comment]
> Thanks for working on this, @gissoo .
> 
> As I noted on [#252 (comment)](https://github.com/Princeton-CDH/geniza/issues/252#issuecomment-866244609) , I think Marina and Rachel need to provide us at least preliminary citation format for sources. We have a lot of different source types (book, article, book section, unpublished...), and a lot of fields are optional, so there may be a lot of variation. I'm hoping we can figure out the variation if Marina and Rachel provide full examples for each type.
> 
> We _did_ agree on Transcription as being more accessible / comprehensible to a general audience! However, when I went to make the change in the code I was concerned about it being so visually similar to Translation; I think it could easily cause content editors confusion and they might click the wrong one if they weren't looking closely (it would also be confusing in the code). When we discussed it again, Marina agreed based on my concerns and also noted that Edition is the term used in the field. I don't think the language in the admin interface and the public site necessarily need to match, though! Using Transcription for the public site is fine with me if you think it is the most accessible term; am curious what Marina thinks.
> 
> @gissoo some detail questions:
> 
>     * What will be the text of the link for "link to source" be?  (In case it matters, many scholarship records will not have links)
> 

- I have proposed "view record"

>     * Many footnotes in the database have notes (e.g., of a transcription is by Goitein but with suggestions/emendations from Alan Elbaum, or from a published text by Goitein but with corrections from his unpublished materials); would you recommend including those here or not?
> 

- I think it would be great if they are listed as one of the records as we discussed!

>     * Do you have a sort order in mind?
> 

- It would be great if they are sorted by the one with all scholarship types (edition, translation, and discussion) – this came out of my research – but I'm not sure what the second-level sort would be. (if there are two records and both have all the three scholarship types above then I would think the one with the most number of records should come first, @mrustow what do you think?

>     * I see you have the editor listed above the numbered list — in the database, that edition/transcription one of the scholarship records. Should it be included or omitted from the list of scholarship records?

- I have removed the editor field 
- Based on our conversations yesterday I also agree with "Edition" and have also revised it here – will need to revise it in other places in the designs.

**Comment by gissoo** [comment]
@rlskoeser @mrustow Thanks for writing! I have revised the designs based on Marina's examples in #252 – [here are the revised designs](https://www.figma.com/file/HpGBOZi9lO8B3nCAx3d4Fj/Princeton-Geniza-Project-team?node-id=1143%3A4)

Question:
1. Do we want to include the source types here as well? We didn't discuss source types before, will they be useful / needed by the users? And should I add them to the sitemap?

**Comment by richmanrachel** [comment]
@gissoo - the revised design is much better! 
1) I don't think we need to add source types (it should be obvious by the proper formatting of the bibliographic information).

Minor design quibbles: 
A) Is there a way to make the first and second lines of the source entry align? It seems to be off by one space (perhaps because of the numbering).
B) Could we use a different font or layout for the edition/discussion/translation labels? I'm not sure it's easily understood by a first time user.
C) I'm not sure I would understand what "View Record" means either without clicking on it. I think @rlskoeser's "Link to Source" would be clearer.

Thanks!

**Comment by richmanrachel** [comment]
Just a screenshot to illustrate the issues to above:
![image](https://user-images.githubusercontent.com/68028846/123984797-f0014600-d992-11eb-8105-5bce29dab2fc.png)

**Comment by rlskoeser** [comment]
I agree with Rachel, most people will be able to tell what the source types are based on the formatting of the sources. (Although I don't know how accessible/friendly that is to non-scholars; but maybe they aren't the main audience for this page?)

I'm also not sure about the edition/discussion/translation layout. Could they be on the same line, more like a sentence or description (includes x, y, z) ? Or offset someway to differentiate from the source?

For the link — could we just make the source clickable if there's a url? (Or maybe just the title? Although not everything has a title.) "view record" and "link to source" aren't meaningful link titles, and it's not ideal to repeat the same link text over and over on the same page.

**Comment by richmanrachel** [comment]
@rlskoeser - I think that by high school students should have at least some familiarity with basic bibliographic format, so things should at least be easily searchable without the source type listed. The one exception might be to explicitly list "Unpublished" as such, so folks don't go down rabbit holes to search for the unfindable...

I would be comfortable noting edition/description/translation in sentence format.

I like your idea of making the source clickable! That's definitely better than random titles.

**Comment by gissoo** [comment]
@rlskoeser @richmanrachel thank you for the comments! [Here is the revised design](https://www.figma.com/file/HpGBOZi9lO8B3nCAx3d4Fj/Princeton-Geniza-Project-team?node-id=1143%3A4) along with some comments – note: the second page on the right is exactly the same except for a style difference for "unpublished"

- Rachel, thanks for catching the alignment issue!! I have fixed it now
- I agree with your thoughts on the source type. 
- Regarding the links, since you both felt strongly about it I have removed it. I still prefer to have a separate link – "link to source" is what I had proposed before but it did not make enough sense to RSK so I revised to "view record" (since the page is called "scholarship records") – having the link repeat is not an issue to me only because we do this in other places all the time – I have revised it now so that the title of the source is the link, I would vote against turning the entire source to a link – it creates a poor experience for readability – 
Q: What percentage of the sources do not have a title?
Because I would suggest that we default to having the title of the source as a link and only when there is no title we make the entire source to a link. 

- I have also made minor changes to Edition/Translation/Discussion

- I have added two styles for "Unpublished" in no.5 – let me know if you would like it to be simpler

**Comment by richmanrachel** [comment]
@gissoo  - Thanks so much! It looks much better and clearer. The only feedback @mrustow and I have is related to the design of the box for edition/translation and how close it is to the line separating entries: to me the way the lines are connected looks like tabs on a file folder and is therefore a little confusing. Could you play around with adding white space below it, or making the gray go all the way across the screen?

**Comment by gissoo** [comment]
Marina is happy with the new layout for [this page](https://www.figma.com/file/anZFStv7zBaVWnFxr95nKt/Work-in-Progress-%2F-WIP?node-id=2%3A611) – we will experiment with colors for links and for the boxes that are currently in grey.
