### ISSUE TITLE
Join fragments re-ordering themselves

### ISSUE THREAD

**Issue by richmanrachel** [Princeton-CDH/geniza#254]
**Describe the bug**
Per Alan: "I think I’ve reproduced a potential bug that Marina first noticed: when you first add a join and list it in the proper order and then click save, the order of the fragments gets jumbled or reversed. Then if you go back in to the document record and list them in the proper order and click save, that fixes the problem. I also figured out a workaround: if you add the joins in reverse order, they’ll flip once you save them and be in the right order."

**To reproduce**

**Expected behavior**

**Screenshots**

**Device information**
 - Device: [e.g. iPhone 6, Samsung Galaxy S10, MacBook Pro]
 - OS and version: [e.g. macOS 10.14, Windows 10, iOS 8.1, Android 9]
 - Browser and version: [e.g. Firefox 72, Chrome 79, Safari 13]
 - Site version [e.g. 0.24.1 - check in the site footer]

**Additional context**

**Comment by kseniaryzhova** [comment]
@rlskoeser not really an issue since you can just manually rearrange and hit save. Closing!
