### ISSUE TITLE
As a Content Editor, I want to see Help text for Document Type so that I can make an informed decision while editing documents.

### ISSUE THREAD

**Issue by richmanrachel** [Princeton-CDH/geniza#255]
If you could please provide the following link as Help Text for "Type" in Document View:

"Link to PGP Document Type Guide: https://docs.google.com/document/d/1FHr1iS_JD5h-y5O1rv5JNNw1OqEVQFb-vSTGr3hoiF4/edit"

My only concern is that while I was able to update permissions to make it accessible to anyone with Pton Google access, there might be some people who will need to ask for permission on the fly.

**Comment by richmanrachel** [comment]
@rlskoeser - It works! And I love the way you integrated it. My only suggestion is if it's easy to make it open in a new tab rather than take the researcher off of the database?

**Comment by rlskoeser** [comment]
@richmanrachel good point, makes sense here — have updated so the document should open in a new tab, please confirm.

**Comment by richmanrachel** [comment]
@rlskoeser - perfect, closing!
