### ISSUE TITLE
As a content editor, I want to see admin actions beyond my most recent ten or a specific document's history, so that I can review past work.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#267]
Based on Alan's request to have access to his edit history beyond the 10 most recent actions listed on the admin dashboard, as a way to check recent work if you realize you made a mistake. 

## testing notes
- [x] on the main admin dashboard page, you should now see a new "administration" section with Log Entries listed
- [x] the Log Entries list view should give you basic access to all actions documented in the admin site, with search, filtering by action type and user
- [x] on the main admin dashboard page, at the bottom of the list of recent actions, you should see a "view more actions" link — clicking on it should take you to the log entry list prefiltered for actions associated with your current login account

**Comment by richmanrachel** [comment]
@rlskoeser - this is phenomenal! Love it! Ready for launch :)
