### ISSUE TITLE
As a user, I want transcription language detected and used for search so that I can see what languages are used and take advantage of language-specific search functionality.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#27]
- add logic to transcription script to autodetect language; try [spacy fastlang](https://spacy.io/universe/project/spacy_fastlang)
- pull xml tags from the xml when present; check against detected languages
- include languages in transcription json files
- update indexing script to index detected languages
- update solr config & indexing script to use language-specific text fields

**Comment by richmanrachel** [comment]
In conversation with Marina on 8/18/21, we agreed that this isn't worth pursuing at this time.
