### ISSUE TITLE
As a content editor, I would like to see Historic Shelfmark on the Document edit page, to ensure that my work is correct when working with old scholarship.

### ISSUE THREAD

**Issue by richmanrachel** [Princeton-CDH/geniza#271]
## Testing notes (QA)

On the [QA site admin](https://test-geniza.cdh.princeton.edu/admin/):
- [x] Edit a document that has historical shelfmarks. They should show up in the top section alongside PGPID and old PGPID.

---

As followup to #241, we would like a read-only Historic Shelfmark field to be present on Document Detail view adjacent to the other PGPID/Old PGPID information (see image below). 

**Is your feature request related to a problem? Please describe.**
Given that most of our researchers will only be working in Document View, it's necessary to see the historic shelfmark in this view. Without it, it could lead to confusion, particularly for less experienced researchers doing data entry from older source material.

![image](https://user-images.githubusercontent.com/68028846/129971486-57476479-c708-4b25-aa00-416c5ae4329a.png)

**Comment by kseniaryzhova** [comment]
@blms Could we do this please, esnpecially since we just ingested a ton of historic shelfmarks. How long would it take?

**Comment by blms** [comment]
Definitely @kseniaryzhova, probably a 3 hour or less task. I'll put it on my list!

**Comment by kseniaryzhova** [comment]
@blms Great, definitely lower priority," to do when there's a lull in the other high priority work" kind of thing.

**Comment by kseniaryzhova** [comment]
#1469 is the same, closing this one!

**Comment by blms** [comment]
@kseniaryzhova Reopening as this refers to the admin site, not the public site!

**Comment by kseniaryzhova** [comment]
@blms perfect! Thanks, closing!
