### ISSUE TITLE
As a content editor, I want to view source URLs when I download the sources CSV in order to more easily find/update external sources.

### ISSUE THREAD

**Issue by richmanrachel** [Princeton-CDH/geniza#278]
Context: there are a few Asana cleaning tasks pertaining to the cleaning/checking of external links (particularly Marina's google doc translations). When creating a work flow for the RAs, I discovered that the current sources CSV download does not include the URLs, and therefore it is difficult to develop a proper workflow.

In conversation with @rlskoeser on 8/17/21, she said it should be easy to add the existing URL field to the CSV. Thanks!

**Comment by rlskoeser** [comment]
@richmanrachel I believe this was addressed as part of Ben's work on #313 — would you confirm in qa and comment either way?

**Comment by richmanrachel** [comment]
@rlskoeser, no it didn't work. I do see a URL tab on the CSV now, but it's not filled in for any of the unpublished sources.

**Comment by richmanrachel** [comment]
![image](https://user-images.githubusercontent.com/68028846/145244849-3df6ed6a-dce4-47b2-a72c-16d9657f6b31.png)

**Comment by rlskoeser** [comment]
@richmanrachel I'm not sure we have any URLs on sources in the database yet! Would you test adding one and downloading again?

**Comment by rlskoeser** [comment]
noting from my brief testing: selecting items and exporting partial data seems to include the urls, but exporting all records as csv does _not_ ; unclear what should cause this, since it is running basically the same code (the querysets may be slightly different?)

**Comment by kseniaryzhova** [comment]
@rlskoeser works for me - I see both public and admin site URLs in the csv. Not clickable until you put it in Google Sheets but that's fine. Thank you!
