### ISSUE TITLE
As a user, I want to sort search results by the number of scholarship records so I can easily find documents with scholarly work available or that have not been written about.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#294]
## testing notes
- [ ] visit the document search page, and without entering a query, confirm that results are sorted by "Scholarship Records (Most–Least)"
- [x] verify that you can select "Scholarship Records (Most–Least)", "Scholarship Records (Most–Least)", and "Relevance" in the "Sort by" dropdown
- [x] after typing a query and selecting a sort option, click the search submit button, and confirm that the results are as expected
- [x] confirm that sorting by "Scholarship Records (Most–Least)" displays the expected results
- [x] confirm that sorting by "Scholarship Records (Least-Most)" displays the expected results
- [x] confirm that sorting by "Relevance" displays the expected results

## dev notes
- [x] add sort options to the form : "Scholarship Records (Most–Least)" and "Scholarship Records (Least–Most)"
- [x] add logic to the view to sort the solr queryset appropriately using the total scholarship field that is already indexed
- [x] confirm the rendered form on the search results page displays the correct sort status
- [x] add unit tests for the sort logic in the view

**Comment by richmanrachel** [comment]
@rlskoeser - It looks good!  It defaults to relevance, but we can switch the sort-by, and honestly relevance is better as a default.
