### ISSUE TITLE
As a user I would like to filter my search by document type so that I can view specific types of documents

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/geniza#296]
## testing notes
test on the document search https://test-geniza.cdh.princeton.edu/en/documents/
- [x] should be able to filter by one or more document types
- [x] when no document type is selected, should show results of all types

## dev notes
- [x] add document type facet field to search form (adapt from S&co or PPA)
- [x] add faceting on document type field in solr query
- [x] display facet field with totals
- [x] when type is set in request, filter queryset 
- [x] display selected document type in the form

**Comment by richmanrachel** [comment]
Omg, @mrustow you are going to jump for joy when you see this! I LOVE the addition of numbers for how many results fall into which categories (and I clearly need to change back Funsies -> Lists, haha). This will truly improve everyone's research experience. Thank you!!!

![image](https://user-images.githubusercontent.com/68028846/142683605-14e90594-7ad0-49c3-aea8-44f6476752ee.png)
