### ISSUE TITLE
As a user I would like to see which page I'm on when viewing search results and navigate between pages so I can see more results.

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/geniza#298]
## testing notes
test on the document search https://test-geniza.cdh.princeton.edu/en/documents/
- [x] results should be paginated
- [x] test entering a search query with greater than 50 results, should have pages that you can click through
- [x] test entering a search query with fewer than 50 results, pagination should disappear

note that some work on design/style is forthcoming in #361

## dev notes
- [x] use django paginator on solr queryset search in document search view — should be similar to this code in ppa: https://github.com/Princeton-CDH/ppa-django/blob/main/ppa/archive/views.py#L347-L350
- [x] include needed pagination variables in template context
- [x] create template snippet to render pagination per design and include at top and bottom of search results; adapt from ppa pagination https://github.com/Princeton-CDH/ppa-django/blob/main/ppa/archive/templates/archive/snippets/pagination.html
- [x] unit tests to confirm pagination works: displays correctly, links work, can retrieve a secondary page

**Comment by richmanrachel** [comment]
Perfect!
