### ISSUE TITLE
Revise the new search prototype so that when a search term is entered document tags are matched while showing contextual information about the clusters in which the documents appear so that the user can learn more about the position of the document with respect to the clusters

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/geniza#31]

**Comment by gissoo** [comment]
@rlskoeser what do you think about my revision? I have written some notes by the designs – [here are the ideas](https://www.figma.com/file/HpGBOZi9lO8B3nCAx3d4Fj/Princeton-Geniza?node-id=135%3A0)

**Comment by rlskoeser** [comment]
@gissoo thank you for the revisions!

One import question, to help me understand what you intend and figure out how to build this: when you're thinking of clusters, are they always the same set of initial clusters that you see on the first cluster list page? Or would we ever dynamically generate clusters within a particular result set?

I like the first option better— get the searcher straight to the most relevant documents, but give them context about the clusters that are relevant to their search.  (I wonder if the cluster summary at the top should show more details, like how many total documents in that cluster and how many match this search — but I'd prefer not to implement that right away anyhow, so I'm good with the simple list you have now.)

I think the second option, that shows clusters only, is problematic in a few ways: 
- you don't see any documents at all on the first page and have to click through to see them
- documents may be included in multiple clusters
- in the current data & the way we're generating clusters, some documents are not in _any_ clusters and will never be findable this way

**Comment by gissoo** [comment]
@rlskoeser sorry I should have been clearer: I meant the second option as a "cluster view" that can be seen by "sort by cluster". So the default view would be the document list. But I think it would be important to have a way to view them by clusters as well if possible. Your third point is very helpful!! If we do approach it this way there would be a way to communicate that I think.

**Comment by gissoo** [comment]
> @gissoo thank you for the revisions!
> 
> One import question, to help me understand what you intend and figure out how to build this: when you're thinking of clusters, are they always the same set of initial clusters that you see on the first cluster list page? Or would we ever dynamically generate clusters within a particular result set?
> 

- If I understand your question correctly, then I think they are always the same set of clusters (so i.e. no new/unknown clusters would be formed) but a filtered/relevant version of them in the search. 

> I like the first option better— get the searcher straight to the most relevant documents, but give them context about the clusters that are relevant to their search. (I wonder if the cluster summary at the top should show more details, like how many total documents in that cluster and how many match this search — but I'd prefer not to implement that right away anyhow, so I'm good with the simple list you have now.)
> 

- regarding the "cluster summary having more details including the total docs in that cluster", I'm not sure about that. I think it's more important on that page to communicate how many in each cluster match this search, but then if the cluster is selected there would be more details shown regarding how many total documents are in the cluster. 

> I think the second option, that shows clusters only, is problematic in a few ways:
> 
>     * you don't see any documents at all on the first page and have to click through to see them
> 
>     * documents may be included in multiple clusters
> 
>     * in the current data & the way we're generating clusters, some documents are not in _any_ clusters and will never be findable this way

- sorry I answered this in the earlier comment, I should have been clearer on Figma.

**Comment by rlskoeser** [comment]
@gissoo thanks for explaining. Yes, there should be a clearer way to communicate how and why you would get from one view to the other.

This isn't a sort, since we're not re-ordering the results, and it's not even really a grouping of the results since it doesn't display any documents but just the clusters.

How does the view you have labeled as "sorted by cluster" relate to the initial cluster list view?

**Comment by gissoo** [comment]
@rlskoeser thanks for writing! That makes sense I don't know why I was thinking of it as a sort and not a "view". 

I don't think it relates much to the initial cluster list view or that it has to, because the context here is different.

**Comment by gissoo** [comment]
RSK and I have agreed that we **won't** include grouped cluster information with the search results for this round (v2 and v3) since it's still hard to tell how useful it would be. RSK will implement the page labeled as ["V4" in the designs here](https://www.figma.com/file/HpGBOZi9lO8B3nCAx3d4Fj/Princeton-Geniza?node-id=143%3A49). 

Note: clusters on V4 are clickable and would take the user to that particular cluster.
