### ISSUE TITLE
Implement styles for site navigation on mobile 

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/geniza#312]
## testing notes
- [ ] On desktop, visit any user-facing page (e.g. https://test-geniza.cdh.princeton.edu/documents/) and hover over the "About" section of the top navigation menu, and verify that a sub-menu dropdown appears with more items
- [ ] On mobile, visit any user-facing page and click the hamburger menu icon next to "GENIZA" at the top of the screen.
  - [ ] Verify that clicking on this icon brings up a menu with several options
  - [ ] Verify that clicking "About" in this menu brings up a sub-menu with more items
  - [ ] Verify that clicking the back icon (<) returns to the previous menu
  - [ ] Verify that clicking the close icon (X) closes all menus

## Dev notes
- [x] Also translate aria-label for nav

**Comment by gissoo** [comment]
- Thank you, @rlskoeser ! I verified everything and it works well on firefox and safari. However, on Chrome mobile nav when I select the "About" no submenu items show up 

- (may not be useful: if you're on chrome desktop, hover over the about drop down, and then shrink the page to get the mobile nav, select the mobile nav it already opens in "about" expanded and does not show the default menu items unless you select the back/left chevron)

**Comment by blms** [comment]
@gissoo Thanks for testing! Strange, I can't replicate that Chrome issue. Which OS and version of Chrome are you using? And are you testing on a mobile device or the responsive design mode of the desktop browser?

**Comment by gissoo** [comment]
@blms I can't replicate the issue on mobile, it's just on my desktop and I think my browser is older. If you can't replicate the issue on desktop then ignore it, there shouldn't be a problem.
