### ISSUE TITLE
As a user I would like to see scholarship records for each document so that I can learn more about research that has been done about each document

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/geniza#313]
## testing notes
- [x] Evaluate the brief citations that appear in Document Detail pages (under "Editor") for a range of documents, e.g. https://test-geniza.cdh.princeton.edu/en/documents/3504/ and make note here of any changes to which fields should be included/excluded
- [x] Check also a range of full citations in Scholarship Records pages, e.g. https://test-geniza.cdh.princeton.edu/en/documents/3504/scholarship/ and make note of any changes to fields/formatting there
- [x] No rush, but might be worth creating Asana tasks to populate new fields: Publisher, Place Published, and Journal Issue
  - [x] Perhaps add some fake publisher info to the existing test data to see what citations will look like when that info is available

Note that #389 was moved into a separate issue, so footnote locations within a source still only display on the Document Detail view for the time being.

## dev notes
- Revise existing template to match the new design for document relation (edition/transcription/discussion)
- Revise `geniza.footnotes.Source` string method to generate citations that are better formatted based on the type of course
  - follow the way the string method is structured now — look at commonalities between the formats and then try to combine them sensibly
  - probably also need a formatted version and then a wrapping method that calls it and strips the tags. something like a method named `formattted_display` that takes all the functionality we have now in the `str` method, and adds `em` tags and whatever other formatting is needed, and then the `str` method basically calls that and runs `striptags`

draft format we're targeting:

- **Book:** Moshe Gil, Palestine during the First Muslim Period, 634–1099, in Hebrew (Tel Aviv, 1983), vol. 2, doc. 134
- **Article:** S. D. Goitein, "New Sources from the Geniza" (Hebrew), Tarbiz 18 (1954): 7–19
- **Book section:** S. D. Goitein, "New Documents on the Gaonate in Palestine," in Salo Baron Jubilee Volume on the Occasion of His Seventy-fifth Birthday, ed. Arthur Hyman (New York, 1975), 2:55–74
- **Dissertation:** Ṣabīḥ ʿAodeh, "Arabic Letters from the Cairo Geniza," in Hebrew (PhD diss., Tel Aviv University, 1982), doc. 5
- **unpublished:** S. D. Goitein, typed texts; suppress volume if any; see #252

Needs to handle optional fields gracefully.

We want to use CMS to the degree possible, and make things consistent. 

All non-English languages should be specified as (in Hebrew) for all types per CMS, so:
Author, Title of Book (in foreign language) (City: Publisher, year).
Author, "Title of Article" (in foreign language) # (year): #–#.

**Comment by rlskoeser** [comment]
@mrustow @richmanrachel Ben has made some great progress on implementing the scholarship records page and revising the citation output format to standardize and use CMS, but his work raised some questions that we need your input on.

I think there's some tension between the desire to use CMS and our previous decisions to keep these source notes a bit simpler than full-blown citations 

1. Ben added new fields to `Source` record for place of publication and publisher. Do you want them? Or not want them?
2. Formatted citations per CMS would include (n.p., n.d.) when publication information and publisher is not present. Ben is currently excluding it for unpublished sources, but this is a bit at odds with the brief citations you had before, and may impact a number of sources until you populate the publication information. Should we diverge from CMS and omit when publication information and date are not set?

**Comment by blms** [comment]
Hi @mrustow @richmanrachel, I also wanted to pass along this list of data entered into the "Other Info" field of some Sources. I think these basically fall into three categories: page ranges (which we already have a field for), publication place/publisher info (which we've proposed adding a field for), and notes that should perhaps not be part of the citation.

<details>
<summary>All populated "Other Info" fields</summary>

Source ID 783
Citation: Avraham David, "Between Ashkenaz and the East in the Sixteenth Century: Ashkenazic Jews in the Land of Israel as Reflected in the Cairo Geniza" (in Hebrew), Rishonim ve-Aharonim, From Sages to Savants: Studies Presented to Avraham Grossman (n.p., 2010).
`other_info`: pp. 309–28

Source ID 804
Citation: Geoffrey Khan, "A Judaeo-Arabic Document from Ottoman Egypt in the Rylands Genizah Collection", in From Cairo to Manchester: Studies in the Rylands Genizah Fragments (n.p., 2013).
`other_info`: pp. 233–48

Source ID 799
Citation: Dotan Arad and Esther-Miriam Wagner, "A Letter by Isaac Bayt ʿAṭṭān to Moses b. Judah (1480s)", in A Handbook and Reader of Ottoman Arabic (n.p., 2021).
`other_info`: pp. 143–48

Source ID 797
Citation: Geoffrey Khan, "A Petition to the Fāṭimid Caliph al-Āmir from the Cairo Genizah Concerning an Inheritance", Orientalistische Studien zu Sprache und Literatur Festgabe zum 65. Geburtstag von Werner Diem (n.p., 2011).
`other_info`: Wiesbaden: Harrassowitz, 2011, 175–86

Source ID 789
Citation: Paul Fenton, "A Re-discovered Description of Maimonides by a Contemporary", Maimonidean Studies 5 (n.p., 2008).
`other_info`: 267–91

Source ID 802
Citation: Siam Bhayro, "A Syriac Fragment from the Cairo Genizah", Wiener Zeitschrift für die Kunde des Morgenlandes 94 (n.p., 2004).
`other_info`: pp.39–51

Source ID 628
Citation: Esther-Miriam Wagner, A newly-discovered fragment of a letter written by Maimonides, Fragment of the Month (n.p., 2007).
`other_info`: Taylor-Schechter Genizah Research Unit, Cambridge University Library

Source ID 767
Citation: Andrew Sharf, "An Unknown Messiah of 1096 and the Emperor Alexius", Journal of Jewish Studies 7 (n.p., 1956).
`other_info`: no. 1 and 2

Source ID 572
Citation: Marmorstein, "Beiträge zur Geschichte und Literatur der gaonäischen Periode" (in German), MGWJ 51 (n.p., 1907).
`other_info`: no shelfmark given

Source ID 778
Citation: Dotan Arad, "Cairo's Maghribians and Musta'ribs: From Close Cooperation to Conflict and Estrangement" (in Hebrew), in Studies in Jewish History Presented to Joseph Hacker (n.p., 2014).
`other_info`: Yaron Ben-Naeh et. al. eds. Jerusalem: Zalman Shazar Center, 2014

Source ID 727
Citation: Lévi Israël,  "Document relatif à la «Communauté des fils de Sadoc»" (in French), Revue des études juives 65, n°129 (n.p., 1913).
`other_info`: pp. 24-31

Source ID 723
Citation: Adalbert Merx,  Documents de paléographie hébraïque et arabe (in French) (n.p., 1894).
`other_info`: Leiden: Brill, 1894

Source ID 771
Citation: Dotan Arad, "Documents in Arabic and Judeo-Arabic Relative to the History of the Jewish Community in Jerusalem" (in Hebrew), in The History of Jerusalem: The Mamluk Period (1260-1517) (n.p., 2013).
`other_info`: eds. Yvonne Friedman and Joseph Drory.

Source ID 21
Citation: Ṣabīḥ ʿAodeh, "Eleventh Century Arabic Letters of Jewish Merchants from the Cairo Geniza" (in Hebrew), PhD diss., (n.p., 1992).
`other_info`: PhD diss. Tel Aviv University

Source ID 785
Citation: Jacob Mann, "Glanures de la Gueniza" (in French), Revue des études juives 74, no. 148 (n.p., 1922).
`other_info`: pp. 148–59

Source ID 780
Citation: Alexander Scheiber, "Isaac Ibn Chalfon's Panegyric Poem Addressed to Samuel Han-Nagid: From the Kaufmann Geniza", Acta Orientalia Academiae Scientiarum Hungaricae Vol. 10, No. 1 (n.p., 1960).
`other_info`: pp. 91–95

Source ID 801
Citation: George Kiraz, "Learning Syriac and Garshuni in Early Modern Egypt: Evidence from the Cairo Genizah", Intellectual History of the Islamicate World (n.p., 2020).
`other_info`: pp.1–26

Source ID 17
Citation: S. D. Goitein, Nahray (in Hebrew).
`other_info`: unpublished corpus of editions

Source ID 301
Citation: Mordechai Akiva Friedman, "New Fragments from the Geniza of Maimonides' Responsa (With Addenda to the Published Responsa)" (in Hebrew), in Hebrew and Arabic Studies in Honor of Joshua Blau (n.p., 1993).
`other_info`: Hiqre 'Ever va-'Arav : mugashim li-Yehoshu'a Bla'u
Ed. H Ben-Shammai

Source ID 800
Citation: Friedrich Niessen, "New Testament translations from the Cairo Genizah", Collectanea Christiana Orientalia 6 (n.p., 2009).
`other_info`: pp. 201–22

Source ID 271
Citation: Moshe Gil, "Palestine During the First Muslim Period (634–1099): Additions, Notes, and Corrections" (in Hebrew), Teuda 7 (n.p., 1991).
`other_info`: 281–345

Source ID 45
Citation: S. Assaf, "Sefer ha-shetarot le-Rav Hai bar Sherira Ga'on" (in Hebrew), Tarbiz 1 (n.p., 1930).
`other_info`: Trans. Goitein in the notes linked below

Source ID 675
Citation: Dotan Arad, Syria’s links with the Jews of Cairo in the 15th and 16th centuries, Fragment of the Month (n.p., 2009).
`other_info`: Taylor-Schechter Genizah Research Unit, Cambridge University Library

Source ID 786
Citation: Dotan Arad, "The Jews of Alexandria in the 15th Century in Light of New Documents" (in Hebrew), Peʿamim 156 (n.p., 2018).
`other_info`: pp. 167–84

Source ID 770
Citation: Dotan Arad, "The Mustaʿrib Jews in Syria, Palestine and Egypt: 1330-1700" (in Hebrew), PhD diss., (n.p., 2013).
`other_info`: PhD Dissertation. The Hebrew University of Jerusalem.

Source ID 788
Citation: Mordechai Akiva Friedman, "The Nagid, the Nasi and the French Rabbis: A Threat to Abraham Maimonides’ Leadership" (in Hebrew), Zion 82 (n.p., 2017).
`other_info`: 193–266

Source ID 781
Citation: "“Let's learn Turkish”: A Turkish-Arabic Glossary from the Cairo Genizah", Turcica 48 (n.p., 2017).
`other_info`: pp. 451–73

</details>

**Comment by richmanrachel** [comment]
@rlskoeser - I'll do my best answering your questions, but I'll add this to tomorrow's agenda so we can get MR's opinions.

> Ben added new fields to Source record for place of publication and publisher. Do you want them? Or not want them?
- I don't feel strongly either way.

> Formatted citations per CMS would include (n.p., n.d.) when publication information and publisher is not present. Ben is currently excluding it for unpublished sources, but this is a bit at odds with the brief citations you had before, and may impact a number of sources until you populate the publication information. Should we diverge from CMS and omit when publication information and date are not set?
- Could we perhaps differentiate between a brief citation on the Document Details page versus a proper CMS citation on the Scholarship Record page? If it's not too much extra logic to create, I think it would be an intuitive differentiation between the repetition of information across those two pages.

@blms - I agree with you that we should just do some data work to get rid of the information that doesn't belong/put it into its correct place. How quickly do we need this done? I'm worried our RAs are short on time at this point in the semester, but I could try to do it quickly myself if needed.

**Comment by rlskoeser** [comment]
> * Could we perhaps differentiate between a brief citation on the Document Details page versus a proper CMS citation on the Scholarship Record page?

I like this idea a lot! I'm not sure how much extra work, might depend on how "simple" the brief citation is (or how different from the proper citation).

**Comment by blms** [comment]
> How quickly do we need this done? I'm worried our RAs are short on time at this point in the semester, but I could try to do it quickly myself if needed.

@richmanrachel no rush! It only needs to be done as quickly as you want the citations to reflect all the existing data. Until then, page numbers will just be omitted from the citations and publisher info will get the "n.p." abbreviations.

**Comment by richmanrachel** [comment]
@blms - great! I'll add this list as an Asana task while I'm thinking about it...

@rlskoeser - I guess the simpler one could drop the place of publication and publisher, and maybe even page numbers or year? If we drop whole fields, I assume it's easier to write consistent logic?

**Comment by rlskoeser** [comment]
Yes, dropping whole fields and keeping things consistent across types (as we can) would probably help.

@blms any opinions on the approach to the simpler citation? Could it make sense to add a flag to the formatted display method that would omit some fields, so the logic is shared where appropriate?

**Comment by blms** [comment]
@richmanrachel @rlskoeser Yes, that makes sense to me. That way we can also adjust on the fly if we decide to change which fields should be included.

That also brings up the question we were discussing in #313 about footnote page numbers (Footnote - Location field) vs source page numbers (Source - Page Range/Other Info fields). I wonder if the display of these should differ between detail and scholarship records pages?

I'll paste here the list of footnotes that have both:


<details>
<summary>Source page range AND footnote location</summary>

```
Footnote ID: 		 6645
Footnote: 		 Discussion of T-S Ar.30.232 + … (PGPID 20354)
Source ID: 		 783
Source: 		 Avraham David, "Between Ashkenaz and the East in the Sixteenth Century: Ashkenazic Jews in the Land of Israel as Reflected in the Cairo Geniza" (in Hebrew), Rishonim ve-Aharonim, From Sages to Savants: Studies Presented to Avraham Grossman (n.p., 2010), 309–28
Footnote location: 	 314–15
Source other_info: 	 pp. 309–28

Footnote ID: 		 6317
Footnote: 		 Edition and Translation of Moss. I,40 (PGPID 26639)
Source ID: 		 727
Source: 		 Lévi Israël, "Document relatif à la «Communauté des fils de Sadoc»" (in French), Revue des études juives 65, n°129 (n.p., 1913), 24–31
Footnote location: 	 25
Source other_info: 	 pp. 24-31

Footnote ID: 		 6755
Footnote: 		 Edition of CUL Or.1081 2.75.3 (PGPID 31469)
Source ID: 		 801
Source: 		 George Kiraz, "Learning Syriac and Garshuni in Early Modern Egypt: Evidence from the Cairo Genizah," Intellectual History of the Islamicate World (n.p., 2020), 1–26
Footnote location: 	 17–18, 20–22
Source other_info: 	 pp.1–26

Footnote ID: 		 6756
Footnote: 		 Edition of CUL Or.1081 2.75.6 (PGPID 31470)
Source ID: 		 801
Source: 		 George Kiraz, "Learning Syriac and Garshuni in Early Modern Egypt: Evidence from the Cairo Genizah," Intellectual History of the Islamicate World (n.p., 2020), 1–26
Footnote location: 	 3–7
Source other_info: 	 pp.1–26

Footnote ID: 		 6754
Footnote: 		 Edition and Translation of T-S 13J7.8 + … (PGPID 34432)
Source ID: 		 800
Source: 		 Friedrich Niessen, "New Testament translations from the Cairo Genizah," Collectanea Christiana Orientalia 6 (n.p., 2009), 201–22
Footnote location: 	 213–16
Source other_info: 	 pp. 201–22

Footnote ID: 		 6716
Footnote: 		 Edition of T-S NS 311.31 + … (PGPID 9451)
Source ID: 		 271
Source: 		 Moshe Gil, "Palestine During the First Muslim Period (634–1099): Additions, Notes, and Corrections" (in Hebrew), Teuda 7 (n.p., 1991), 281–345
Footnote location: 	 #137a (p.314)
Source other_info: 	 281–345

Footnote ID: 		 6717
Footnote: 		 Edition of DK 123f (PGPID 34267)
Source ID: 		 271
Source: 		 Moshe Gil, "Palestine During the First Muslim Period (634–1099): Additions, Notes, and Corrections" (in Hebrew), Teuda 7 (n.p., 1991), 281–345
Footnote location: 	 #165a (p.315)
Source other_info: 	 281–345

Footnote ID: 		 6718
Footnote: 		 Edition of T-S AS 158.174 (PGPID 22385)
Source ID: 		 271
Source: 		 Moshe Gil, "Palestine During the First Muslim Period (634–1099): Additions, Notes, and Corrections" (in Hebrew), Teuda 7 (n.p., 1991), 281–345
Footnote location: 	 #183a (p.316)
Source other_info: 	 281–345

Footnote ID: 		 6719
Footnote: 		 Edition of ENA 1490.7 (PGPID 12471)
Source ID: 		 271
Source: 		 Moshe Gil, "Palestine During the First Muslim Period (634–1099): Additions, Notes, and Corrections" (in Hebrew), Teuda 7 (n.p., 1991), 281–345
Footnote location: 	 #192a (p.317)
Source other_info: 	 281–345

Footnote ID: 		 6720
Footnote: 		 Edition of JRL Series L 75 (PGPID 34268)
Source ID: 		 271
Source: 		 Moshe Gil, "Palestine During the First Muslim Period (634–1099): Additions, Notes, and Corrections" (in Hebrew), Teuda 7 (n.p., 1991), 281–345
Footnote location: 	 #203a (p.320)
Source other_info: 	 281–345

Footnote ID: 		 6721
Footnote: 		 Edition of T-S AS 147.10 (PGPID 4115)
Source ID: 		 271
Source: 		 Moshe Gil, "Palestine During the First Muslim Period (634–1099): Additions, Notes, and Corrections" (in Hebrew), Teuda 7 (n.p., 1991), 281–345
Footnote location: 	 #262a (p.322)
Source other_info: 	 281–345

Footnote ID: 		 6722
Footnote: 		 Edition of T-S NS 325.81a (PGPID 31252)
Source ID: 		 271
Source: 		 Moshe Gil, "Palestine During the First Muslim Period (634–1099): Additions, Notes, and Corrections" (in Hebrew), Teuda 7 (n.p., 1991), 281–345
Footnote location: 	 #265a (p.323)
Source other_info: 	 281–345

Footnote ID: 		 6715
Footnote: 		 Edition of T-S 10J32.8 + … (PGPID 1553)
Source ID: 		 271
Source: 		 Moshe Gil, "Palestine During the First Muslim Period (634–1099): Additions, Notes, and Corrections" (in Hebrew), Teuda 7 (n.p., 1991), 281–345
Footnote location: 	 #38 (p.311)
Source other_info: 	 281–345

Footnote ID: 		 6714
Footnote: 		 Edition of BL OR 10578H.34 (PGPID 34264)
Source ID: 		 271
Source: 		 Moshe Gil, "Palestine During the First Muslim Period (634–1099): Additions, Notes, and Corrections" (in Hebrew), Teuda 7 (n.p., 1991), 281–345
Footnote location: 	 #3a (p.311)
Source other_info: 	 281–345

Footnote ID: 		 6713
Footnote: 		 Edition of BL OR 5542.30 (PGPID 6224)
Source ID: 		 271
Source: 		 Moshe Gil, "Palestine During the First Muslim Period (634–1099): Additions, Notes, and Corrections" (in Hebrew), Teuda 7 (n.p., 1991), 281–345
Footnote location: 	 #439a (p.334)
Source other_info: 	 281–345

Footnote ID: 		 1688
Footnote: 		 Edition of JRL Gaster heb. ms 1772/3 (PGPID 32340)
Source ID: 		 271
Source: 		 Moshe Gil, "Palestine During the First Muslim Period (634–1099): Additions, Notes, and Corrections" (in Hebrew), Teuda 7 (n.p., 1991), 281–345
Footnote location: 	 #7, p. 333
Source other_info: 	 281–345

Footnote ID: 		 6680
Footnote: 		 Edition of ENA NS I.92 + … (PGPID 11977)
Source ID: 		 788
Source: 		 Mordechai Akiva Friedman, "The Nagid, the Nasi and the French Rabbis: A Threat to Abraham Maimonides’ Leadership" (in Hebrew), Zion 82 (n.p., 2017), 193–266
Footnote location: 	 239–42
Source other_info: 	 193–266
```

</details>

**Comment by richmanrachel** [comment]
@blms and @rlskoeser 
> That also brings up the question we were discussing in #313 about footnote page numbers (Footnote - Location field) vs source page numbers (Source - Page Range/Other Info fields). I wonder if the display of these should differ between detail and scholarship records pages?
- Yes, this actually would make sense! We should cite the page number for the Footnote on the Document Detail view, because that's showing what page the actual transcription is from. The page range for the article can be kept in the Scholarship Records field. 

Keeping this logic of Document Detail = directly related to what you see in the document vs. Scholarship Record = where to look for more info could be a good guiding principle.

**Comment by blms** [comment]
Thanks much @richmanrachel, this was super helpful.

A couple of other questions that have come up while working on this:
1. Should we add a "journal issue" field? It seems issue number is usually included in citations for journal articles, but I don't see a way to enter it currently.
2. Would it be ok for the "Edition" field to only accept a number? That way it can be formatted with ordinal numerals (e.g. "5th ed."). Right now it is only being used once (in the copy of data that I have), to store publication info: "Jerusalem: Shazar" (for the source Avraham David, "Between Ashkenaz and the East in the Sixteenth Century: Ashkenazic Jews in the Land of Israel as Reflected in the Cairo Geniza").

**Comment by rlskoeser** [comment]
@blms this might be a pretty picky thing, and isn't necessarily specific to this issue, but I've noticed that when you're switching between document tabs (doc details, scholarship records) you have to click on the words — but the design makes me think I should be able to click anywhere on that "block" (roughly); right now it's possible to get a point between the two lines that is not clickable. Could you make the `a` tags blocks so the whole thing is clickable?

**Comment by blms** [comment]
@rlskoeser Done in #388, should be available next deploy to QA!

**Comment by blms** [comment]
@rlskoeser Added some testing notes here.

**Comment by richmanrachel** [comment]
Some of my initial concerns were about formatting, but when I changed the window size to be smaller they went away. See for example how the tags show up on the larger window:
![image](https://user-images.githubusercontent.com/68028846/144661297-b158fc58-978d-43f8-a1c5-8c1297e841a2.png)
Vs. slightly smaller window:
![image](https://user-images.githubusercontent.com/68028846/144661350-b07bc16f-91d1-42d7-a0f8-5eb28cbbedb8.png)

**Comment by richmanrachel** [comment]
The smaller window version is much clearer for me (having the tags separated and the editor information more neatly stacked). I do wonder if we want some kind of unpublished marker next to Craig Perry's name here because it's a little confusing to see it hanging there. 

Should we also change "Editor" to "Editors" when there is more than one?

**Comment by richmanrachel** [comment]
@blms - I like the way the Scholarship Records page works! The fields seem to be correct on both pages, except perhaps the lack of unpublished marker on Document Details (which I know is the opposite of what I said the other day... sorry!).

@rlskoeser, my biggest meta question is how do we know which of the editors listed made the transcription that will appear on the page? Is that information going to be included closer to the transcription itself?

**Comment by richmanrachel** [comment]
My fake publishing location was an instant success:
![image](https://user-images.githubusercontent.com/68028846/144665988-700ab52c-14e4-43bf-93c2-f9ab9aec66af.png)

**Comment by richmanrachel** [comment]
Just going to set this to Tested: Needs Attention to make sure we address the Unpublished question.

**Comment by rlskoeser** [comment]
> @rlskoeser, my biggest meta question is how do we know which of the editors listed made the transcription that will appear on the page? Is that information going to be included closer to the transcription itself?

I had some questions about that too — on the document details page should we only show the editor for the edition that is available digitally? Or all known editions?  (I don't actually remember what the current logic is, but your screenshot made me think we're displaying all editions.)

We'll probably need to display the editor/source with the transcription text as well, since we know we have at least some cases where there are multiple transcriptions for the same document.

**Comment by richmanrachel** [comment]
@rlskoeser - Perhaps we should show this brief citation directly with the matching transcription text, and not have it at the top of the page? I think this would make sense intuitively, to understand that the transcription has been touched/edited by x person/s, but go to the Scholarship Records for other types of information.

**Comment by blms** [comment]
@rlskoeser @richmanrachel Indeed, the current logic is to show "All footnotes for this document where the document relation includes edition; footnotes with content will be sorted first."

> Perhaps we should show this brief citation directly with the matching transcription text, and not have it at the top of the page?

In that case, when a transcription isn't available online, should there be no "Editor" section on the document detail view? That makes sense to me, but just wanted to confirm.

(On that note, is the transcription currently possible to view? I see the excerpts in search results but not sure where they appear on the document detail view.)

> The smaller window version is much clearer for me (having the tags separated and the editor information more neatly stacked). 

The tags appear in the right column, rather than vertically below the rest of the metadata, as a result of adapting the designs for only the MVP features. See screenshot of design below—without the cluster and fragment info, the right column is just left with the tags. I'm happy to make the change, since I think it makes sense to wait for the columns until we have those other features, but want to get @gissoo's approval before doing so.

<img width="546" alt="Screen Shot 2021-12-06 at 9 31 59 AM" src="https://user-images.githubusercontent.com/7234006/144864502-d579eaaf-5f91-40d1-a65d-4082a10ec986.png">

**Comment by richmanrachel** [comment]
> In that case, when a transcription isn't available online, should there be no "Editor" section on the document detail view? That makes sense to me, but just wanted to confirm.
- @blms - Yes, I don't think an editor should appear on the document detail page if we're not displaying what they've edited. @mrustow may disagree with me, though. 

> (On that note, is the transcription currently possible to view? I see the excerpts in search results but not sure where they appear on the document detail view.)
- I noticed this too... I assumed it was just out of scope for this issue or temporarily dropped while you were building something? But @rlskoeser - are transcriptions supposed to be showing at the moment?

- The tags do feel like they're strangely hanging on the side by themselves, so I would also do away with columns for now if it's okay with @gissoo.

**Comment by rlskoeser** [comment]
I agree, we should only display editor of digital edition on the main document page. @blms do we have an issue yet for the simple citation on document detail page? Can we fold this in to that? I don't want to make this issue any bigger!

We haven't implemented images & transcription on document detail page yet. Hopefully coming soon! #322 

@blms are you clear on what is needed to revise this issue and pass acceptance testing? I wasn't clear on what was needed with unpublished items, but perhaps you and Rachel have already discussed. (Or it is part of a separate issue?)

**Comment by richmanrachel** [comment]
@rlskoeser - I think whether we add "unpublished" after an editors name might functionally be a design issue. I was worried that Craig Perry's name above looked bare without additional information next to book titles, but it won't look weird if it's clearly part of the transcription information. Perhaps we do want to keep "unpublished" as part of the simple citation regardless, but we can probably close this issue? @blms - what do you think?

**Comment by blms** [comment]
@richmanrachel That makes sense to me—I'll add that "unpublished" bit to #390 and we can close this one.

**Comment by richmanrachel** [comment]
@blms - great, thank you!
