### ISSUE TITLE
Design a 404 error page for the site to help inform users in the case of an error

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/geniza#316]

**Comment by gissoo** [comment]
@rlskoeser @blms please review [the designs here](https://www.figma.com/file/anZFStv7zBaVWnFxr95nKt/Work-in-Progress-%2F-WIP?node-id=535%3A25642), let me know what you think. The designs are intended to be used as templates.

**Comment by blms** [comment]
Templates look fine to me. Do we want to hammer out exactly the content that should appear on these pages as well? Or are they going to be managed by content admins through Wagtail?

**Comment by rlskoeser** [comment]
@gissoo these look fine to me. I thought Marina had identified images she wanted to use (I remember she had one in mind at least for the 404). Do you not already know whether it will be portrait or landscape? I think it's fine for you to decide what image layout you want to use on these pages. I think someone (probably you) will need to edit the 404 image to remove the blue background, and you could make other adjustments at that point if you wanted.

@blms I don't think error page content can/should be managed through wagtail — they should be implemented as templates with static image content. I know for sure the 500 can't pull in other data because you can't run the risk of triggering an error when you're rendering your error page.  I think this means that we should have at least the images (if not the finalized text) ready before you implement the error templates.

**Comment by gissoo** [comment]
@rlskoeser thanks for writing. @rlskoeser @blms I have edited the image for this error. Please review the designs again. If ok, I'll upload the image to github.

**Comment by rlskoeser** [comment]
@gissoo wonderful! It looks like there are a few gray and white artifacts in the image in Figma, does that matter? (I'm fine with it if you are; also, we can absolutely work with this version for now if you want to fine-tune the image later.)

Somehow I didn't notice until there was an actual image, but the description placeholder text on mobile looks very close to the left margin — is that following your standard text margins for mobile?

I thought Marina had some suggested text for the 404 page ("you've hit a lacuna" or something like that?), but I don't see it in the site text error page document.

**Comment by gissoo** [comment]
> @gissoo wonderful! It looks like there are a few gray and white artifacts in the image in Figma, does that matter? (I'm fine with it if you are; also, we can absolutely work with this version for now if you want to fine-tune the image later.)
> 

- @rlskoeser thanks for writing!! I have kept those on purpose because it's still paper that's not been deteriorated. 

> Somehow I didn't notice until there was an actual image, but the description placeholder text on mobile looks very close to the left margin — is that following your standard text margins for mobile?
> 

- yes, that's the regular margins we are using – if I customize it for mobile I will also customize it for desktop

> I thought Marina had some suggested text for the 404 page ("you've hit a lacuna" or something like that?), but I don't see it in the site text error page document.

- I also don't see any descriptions in the doc, I'll ask them to review this issue now so they can let us know.

**Comment by gissoo** [comment]
@rlskoeser how do you feel about the page title to be sitting in the middle of the image? (Like how they have it in the google doc) – because if we do that then I have an idea of how it would also look for the 500 error. Let me know please

**Comment by gissoo** [comment]
@mrustow @richmanrachel please review [the designs here ](https://www.figma.com/file/anZFStv7zBaVWnFxr95nKt/Work-in-Progress-%2F-WIP?node-id=535%3A27525)and let me know what you think 

- What description do you like to accompany the image? Rebecca recalls, ""you've hit a lacuna" or something like that?"

**Comment by rlskoeser** [comment]
> @rlskoeser how do you feel about the page title to be sitting in the middle of the image? (Like how they have it in the google doc) – because if we do that then I have an idea of how it would also look for the 500 error. Let me know please

I like how it looks! Seems like it makes it more distinctive and memorable, different from other pages. Shouldn't be too hard to implement, I don't think — @blms any concerns about implementation?

**Comment by blms** [comment]
Nope, should be fine!

**Comment by gissoo** [comment]
@rlskoeser @blms thanks for writing. Please [see this ](https://www.figma.com/file/anZFStv7zBaVWnFxr95nKt/Work-in-Progress-%2F-WIP?node-id=535%3A27525) – the only problem is the image would need to be larger as you see in order for the page title type style to fit in it

**Comment by blms** [comment]
That's OK, all styles can be specified uniquely for error pages if need be.

**Comment by gissoo** [comment]
@blms oh then I'll redefine the page titles :D Thanks for writing

**Comment by richmanrachel** [comment]
@gissoo  - I like it! If we do want a cheekier phrase, I would go with "Oops, you've hit a lacuna! Page not found." 

Not everyone will know what a lacuna is, but the imagery + page not found language should help make it fun even if they don't know that vocab.

**Comment by gissoo** [comment]
@richmanrachel Great! thanks for writing. Since we already say "not found", we could also just say "Oops, you've hit a lacuna!" – but I'm fine either way – I think it's totally fine that some users don't know what Lacuna means, if it makes them curious enough they would look it up, which is also fun :) (not that I don't think of using the contextual note feature to define it for them on the page :D )

**Comment by gissoo** [comment]
@rlskoeser @blms @richmanrachel @mrustow please review [these designs](https://www.figma.com/file/anZFStv7zBaVWnFxr95nKt/Work-in-Progress-%2F-WIP?node-id=535%3A27525) and let me know what you think – @blms I defined new H level type styles for these and added them to the same type style sheet on figma – editing the images took a lot of time – @rlskoeser thanks for catching the white spots they weren't going away the easy way! The grey ones are fine, but the white ones were problematic on the dark mode as you had also seen!)

**Comment by blms** [comment]
Looks good to me! Defer to @richmanrachel @mrustow on image and text.

**Comment by richmanrachel** [comment]
@gissoo  - Marina and I agree that we like the current image. Please just get rid of "Page not found" in the middle of the image, so it only says 404 error there. Looks great :)

**Comment by gissoo** [comment]
@rlskoeser @mrustow @richmanrachel I have dropped the second line. But I think on Slack messages and DMs we keep going back and forth between dropping the 404 vs. the "not found" – I prefer to keep the "Not Found" as the page title as it's more user friendly. Please review the designs and let's come to an agreement regarding what piece of text to drop from this page, it won't matter for the design, as the design is done. @blms I have eliminated one type style for the page title of this page (the regular weight since we omitted the second line of the page title)

**Comment by richmanrachel** [comment]
@gissoo - looks good to me!

**Comment by gissoo** [comment]
will upload image to github
