### ISSUE TITLE
Design a 500 error page for the site to help inform users in the case of an error

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/geniza#317]

**Comment by gissoo** [comment]
@rlskoeser @blms please review [the designs here](https://www.figma.com/file/anZFStv7zBaVWnFxr95nKt/Work-in-Progress-%2F-WIP?node-id=535%3A31406) and let me know what you think. The designs are intended to be used as templates. 

Note: 
- On desktop max width for landscape image is 400px and max height for portrait is 400px.
- On mobile max width for landscape image is 280px and max height for portrait is 280px.  
Using a 4:3 ratio for these. Regretting not using these for the content pages. Would like to systematize our image sizes for projects.

**Comment by blms** [comment]
Same as https://github.com/Princeton-CDH/geniza/issues/316#issuecomment-1006761515 on this one! One other question, is the light mode desktop header meant to wrap onto a second line?

**Comment by rlskoeser** [comment]
Looks reasonable to me. @gissoo maybe I don't know what you mean by your comment about these designs being used as templates?

I like that they're consistent, should be pretty easy to make a base error page template that will be used for both 404 and 500 (and any other error pages if we decide we need others later on).

**Comment by gissoo** [comment]
@rlskoeser sorry don't know why I used that term – mainly meant it for a generic use as I had forgotten we have links to the images and have decided on both 

– @rlskoeser @blms @mrustow @richmanrachel please review the [designs here](https://www.figma.com/file/anZFStv7zBaVWnFxr95nKt/Work-in-Progress-%2F-WIP?node-id=559%3A36668) and let me know what you think – tried to make this one more consistent with the 404 design that you had on the google doc. The type styles are the same as what I have done in the 404 page. Also the body text here is also new only because it's center-aligned.

Note: max image height for desktop is 400px and for mobile is 350px now.

**Comment by gissoo** [comment]
@mrustow @richmanrachel let me know what description you'd like to have on this page. I thought we had discussed something that was fun like the 404 version.

**Comment by richmanrachel** [comment]
@gissoo - this image doesn't quite have the same resonance as the 404 one to me. What message were you trying to convey? Server can't complete the join?

**Comment by gissoo** [comment]
@richmanrachel the 500 error is more about something being "broken" – so that is what is being conveyed visually.

**Comment by richmanrachel** [comment]
@gissoo  - got it... I think the way the current join looks is too clean, maybe? I think there are more jagged joins and perhaps one that's vertical rather than horizontal will feel more broken?

**Comment by mrustow** [comment]
I love how these are coming out! 

For the 404 error, I'd delete the text in the hole (it looks awkward) and just keep the text below. Otherwise perfect. 

For the 500 error, I would delete "500 Error" and keep "Server error" as is. I quite like it, but I'd be curious to see whether Rachel is correct that a vertical join will feel more broken. Or possibly a multi-part join? I'll see if I can round up some more options from the team.

**Comment by richmanrachel** [comment]
I'm having a hard time finding exactly what I had in mind, but these ones are clearly broken in shape: https://cudl.lib.cam.ac.uk/view/MS-TS-00010-J-00021-00011/1, https://cudl.lib.cam.ac.uk/view/MS-TS-00010-J-00030-00006, https://cudl.lib.cam.ac.uk/view/MS-TS-00008-00155

**Comment by richmanrachel** [comment]
Hi @gissoo - Marina and I are together now and we agree that the current image looks too clean to clearly convey the "broken" idea. Here's another few images that we really like that could be paired with text like, "This page is not working [insert cry emoji] 500 error"
![T-S 12 717](https://user-images.githubusercontent.com/68028846/148828407-0c29ca67-0801-45e0-b42c-388f6947ea1f.png)

**Comment by mrustow** [comment]
Here are the individual images
![T-S NS J334](https://user-images.githubusercontent.com/73319225/148828512-f6d698ec-394f-44d0-9a24-83d123655f54.jpg)
![T-S 12 717](https://user-images.githubusercontent.com/73319225/148828515-5e0081c4-5101-4714-a920-64ce8d8aafc5.jpg)

**Comment by gissoo** [comment]
@richmanrachel @mrustow Great! Since we have a decision now, I'll go ahead and edit these two images to go on the 500 error page.

**Comment by gissoo** [comment]
@rlskoeser @mrustow @richmanrachel I have edited the new images and placed them on the page. Again, I have dropped the second line of the page title. Note: I have put the images together in a way to make the combo a portrait/vertical image.

**Comment by richmanrachel** [comment]
@gissoo  - I love the new images! Great job with editing. I'm doubting my decision about the cry emoji, though. It looks very childish and out of context with your pretty design...

**Comment by rlskoeser** [comment]
The images look great! I wonder if there's a way to put less whitespace between them (break "server error" across two lines?), but I don't feel strongly about that.

I agree about the text, I don't think the emoji works well and I think we could do better with the language. Could we say something like "Something went wrong putting this page together" ?

**Comment by gissoo** [comment]
@rlskoeser @richmanrachel thanks for the feedback! I agree about the emoji on the page, but wanted you to see it first. I've eliminated it. 

@rlskoeser the reason I avoided wrapping the page title is if I do wrap it I will need to create a separate type style for it which we don't actually have right now because of the leading. (the leading will need to be decreased). If we have strong feelings about it then it makes sense otherwise I want to avoid creating more type styles at this scale.

**Comment by rlskoeser** [comment]
@gissoo thanks for explaining, let's not introduce any new type styles for this page

**Comment by richmanrachel** [comment]
@gissoo - Just reviewed with @mrustow and @zb8683 and we like the current text and image! The only concern that was raised is if the text is too far down on the mobile version. Marina proposed moving "Server Error" above the right image and moving the other text below the left image. But this is not crucial for MVP.
