### ISSUE TITLE
Design a way to navigate to a cluster from the search results so the user can view a specific cluster and learn more about the documents it contains

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/geniza#32]

**Comment by gissoo** [comment]
@rlskoeser I have made it clearer following our conversation on pages [V4a](https://www.figma.com/file/HpGBOZi9lO8B3nCAx3d4Fj/Princeton-Geniza?node-id=143%3A49) and [V4b](https://www.figma.com/file/HpGBOZi9lO8B3nCAx3d4Fj/Princeton-Geniza?node-id=143%3A124) where the user will be taken once they have selected a cluster, in the designs "#Illness #Appeal" are shown as an example.
However there is still one thing that I'm not clear on: when they are taken to [the cluster browse view (v4b)](https://www.figma.com/file/HpGBOZi9lO8B3nCAx3d4Fj/Princeton-Geniza?node-id=143%3A124), on the left side of the page, where is "#Illness #Appeal" positioned? Is there still a list? And where on that list will "#Illness #Appeal" be, and why? Would it be where it will always be (which is based on the number of documents it contains?) for instance it will be #10 in the list and will remain there in this navigation scenario as well?

**Comment by rlskoeser** [comment]
@gissoo thanks for making that clearer in the designs.

From my perspective, the cluster browse view that you go to is the same one that you go to from the cluster list. So, yes there is still a list, and the selected cluster still occurs in whatever order it otherwise occurs (right now ordered by document count).

**Comment by rlskoeser** [comment]
@gissoo I'm going to close this, since the specific task here is complete. The open questions about the cluster browse view can be things to incorporate into your prototype testing and continued thinking as we continue to refine the prototype.
