### ISSUE TITLE
As an admin, I want TEI transcription content regularly synchronized to the new database so that transcriptions are updated with changes in the current system.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#321]
## testing notes
- [x] in the admin site, look at documents with digitized transcriptions associated; confirm that updated transcriptions now display line numbers that match what is in the xml / what is on PGP v3 site (note that transcriptions for documents in our error cases, i.e. joins and multiple editions, will not have updated content and should continue to display the old version with line numbers)
- [x] in the admin site, check a few footnotes with digitized transcriptions — confirm there is a log entry documenting that it was updated via script
- [x] check a few records to confirm that transcriptions are being matched correctly based on filename and pgpid

----- 

Until we have a new solution for managing and editing transcriptions, we need to use the existing TEI and make sure the new database is pulling in updates regularly.

## dev notes
We need a new management command that can be configured to run as a nightly cron job.
- [x] add and document settings for path to local copy of TEI git repo 
- [x] clone/pull any changes from the TEI git repo to local copy
- [x] match TEI to the correct footnote based on PGPID and source note; needs to handle old PGPIDs for transcriptions associated with merged documents. Matching up properly may require some data cleanup in the source notes. (for initial implementation, handle simple cases only!)
- [x] convert TEI to html that can be used in an IIIF Annotation List; should include labels for any blocks and line numbers in the TEI. Adapt from prototype code https://github.com/Princeton-CDH/geniza/blob/experiment/search/scripts/tei_transcriptions.py
- [x] update transcription content associated with the footnote
- [x] add a django admin log entry if the transcription has changed (would be nice to use git log entry details here, but probably not be worth the effort, given that this is an interim solution)
- [x] script should include reporting to help with concerns raised in #295 — include total number of transcription files, documents with transcriptions, number of fragments, and how how many joins

- [x] update document detail admin to handle the new format

**Comment by rlskoeser** [comment]
Hello @richmanrachel @mrustow — I'm finally circling back to working on the transcription synchronization we planned for the fall MVP, and I have a number of questions.

Here is the summary output the script is generating with totals for various categories:
```
Processed 4,557 TEI/XML files; skipped 38 TEI files with no text content.
39 documents not found in database.
290 documents with multiple fragments.
1,232 documents with multiple editions; 40 multiple editions with content (19 unique documents).
63 documents with no edition.
3,799 documents with one edition.
Updated 3,798 footnotes.
```

My approach for now is to synchronize the transcription content from the TEI into the content field in the existing footnote; from the numbers above, you'll see there are some places where that's causing me some trouble. I need help investigating and resolving some of these. 

## notes
- no text content: we were aware of these and I don't think it's a problem; just reporting so we have numbers
- multiple fragments: not a problem, just including for reporting purposes
- one TEI file (`8594.xml`) has a translation and no transcription; this is out of scope for my current work, but I wanted to mention because I don't want the content to get lost. We might also want to be thinking about how to handle translations — it seems to me that it would be valuable to include translation text in the public search.

## questions
- a number of documents have more than one footnote that provides an edition; if I filter to the one that has content, then I would preserve the mapping of footnote to edition content that we established on import. Does that seem like a reasonable approach for now, or should I compare source with `sourceDesc` in TEI? (Note: using current content mapping won't handle all cases, see problems)

## problems
- documents not found: these IDs aren't listed as either current or past ids. When I looked at one of the TEI files and searched on the shelfmark listed, I didn't find any results
- documents with multiple editions: these are footnotes with document relationship of `edition`; if I find the one that currently has content, then we preserve the initial mapping
- there are 40 TEI files / 19 documents where the document has multiple editions with content associated; I suspect these are all merges but have only  investigated briefly. Here's one example: https://geniza.cdh.princeton.edu/admin/corpus/document/2493/change/  Two footnotes from the same source which are associated with different parts of the transcription. I'm not sure the best way to resolve this! One option would be to have someone (probably would have to be Alan?) combine the two XML files.
- In some cases there are multiple footnotes with editions but none with content (don't know how many yet; at least 1). I can try matching source name on the `sourceDesc` contents in the TEI, but don't know yet how reliable it will be.
- 63 documents with no edition: not finding an existing footnote to attach the content to. In one example there's no footnote at all: https://geniza.cdh.princeton.edu/admin/corpus/document/2285/change/  In this case the TEI doesn't include a source description; even if it did, I don't think it's structured enough for me to generate a footnote automatically.

What's the best way to get help investigating these? I can generate some lists; maybe multiple separate lists for each different kinds of problems?

**Comment by rlskoeser** [comment]
A lower priority question, about formatting. The TEI includes a number of `rend` tags; how important are these? Can we ignore for the fall MVP? Are any of these important?
- superscripts with numbers; they look like they could be footnote markers, but I don't see any footnotes
- four documents have `rend=col` for columns with column breaks
- 84 documents have a `desc` description at the beginning of the TEI; ok to ignore? examples: 5293,5291, 5300, 786
- I see formatting (italics, bold, center) but I think they are all in descriptions or source descriptions and not in transcription text

**Comment by rlskoeser** [comment]
Ack, sorry — I have yet another question: I had been planning to have this tei synchronization script generate admin log entries on footnote records when it updates the transcription content, but now am questioning the usefulness of that, since this is an interim solution for transcriptions. Any opinions on whether this is valuable to document or would clutter the database needlessly?

**Comment by richmanrachel** [comment]
@rlskoeser - thanks for the research you did and the good questions. I will set aside most of my meeting with Marina on Wednesday morning to investigate, and put a marker in the agenda to bring it up the discussion points as well!

**Comment by rlskoeser** [comment]
@richmanrachel that sounds great. Should I go ahead and create a list of PGPIDs and xml files for reference/investigation? I should be able to do that sometime today so you'd have it available for your meeting tomorrow.

**Comment by richmanrachel** [comment]
@rlskoeser - that would be amazing. Thanks a million!

**Comment by rlskoeser** [comment]
@richmanrachel when you discuss with Marina, please also discuss how much of this we need to handle for a first-pass implementation; I'd like to get the transcription sync out for testing so we can build out the functionality that depends on it — I think we should be able to proceed with that while we work on resolving these problem.

**Comment by richmanrachel** [comment]
@rlskoeser - sounds good. Thank you so much!

**Comment by richmanrachel** [comment]
> a number of documents have more than one footnote that provides an edition; if I filter to the one that has content, then I would preserve the mapping of footnote to edition content that we established on import. Does that seem like a reasonable approach for now, or should I compare source with sourceDesc in TEI? (Note: using current content mapping won't handle all cases, see problems)
- We're not quite sure that it will map correctly... perhaps we can walk through it together? How are you determining which footnote has content? Fingers crossed this is as easy as you think it is!

**Comment by rlskoeser** [comment]
oh, sorry, that was unclear! "footnote with content" means the footnote that we attached the initial transcription text to when we did the spreadsheet import. (I think we got some of those wrong but they have been cleaned up / consolidated?)

**Comment by richmanrachel** [comment]
> there are 40 TEI files / 19 documents where the document has multiple editions with content associated; I suspect these are all merges but have only investigated briefly. Here's one example: https://geniza.cdh.princeton.edu/admin/corpus/document/2493/change/ Two footnotes from the same source which are associated with different parts of the transcription. I'm not sure the best way to resolve this! One option would be to have someone (probably would have to be Alan?) combine the two XML files.
- Yes, we can have Alan do this. I think in this case we can just delete one of the footnotes because they're both Goitein, Typed Texts.

**Comment by richmanrachel** [comment]
>oh, sorry, that was unclear! "footnote with content" means the footnote that we attached the initial transcription text to when we did the spreadsheet import. (I think we got some of those wrong but they have been cleaned up / consolidated?)
- @rlskoeser - we're totally blanking on this... Can you show us at the meeting, tomorrow, please?

**Comment by richmanrachel** [comment]
> In some cases there are multiple footnotes with editions but none with content (don't know how many yet; at least 1). I can try matching source name on the sourceDesc contents in the TEI, but don't know yet how reliable it will be.
- Let's not worry about this if it's only one case.

**Comment by rlskoeser** [comment]
yes, absolutely! let's plan to talk through whatever is confusing or can't be resolved asynchronously

**Comment by richmanrachel** [comment]
> 63 documents with no edition: not finding an existing footnote to attach the content to. In one example there's no footnote at all: https://geniza.cdh.princeton.edu/admin/corpus/document/2285/change/ In this case the TEI doesn't include a source description; even if it did, I don't think it's structured enough for me to generate a footnote automatically.
- We do need to clean up the TEI files that have sources/footnotes embedded. Working on a workflow now. Marina just wants to make sure that the information about when they were initially entered into the PGP can be manually input if needed as these internal source notes often indicate documents added to the PGP in the 80's.

**Comment by richmanrachel** [comment]
> A lower priority question, about formatting. The TEI includes a number of rend tags;
- What does "rend" mean? @rlskoeser

**Comment by rlskoeser** [comment]
>     * What does "rend" mean? @rlskoeser

Ah, sorry — rendition; it's an attribute that's usually used to indicate formatting

**Comment by richmanrachel** [comment]
>A lower priority question, about formatting. The TEI includes a number of rend tags; how important are these? Can we ignore for the fall MVP? Are any of these important?
- Overall, yes, we can ignore italics/bold, and we want to get rid of the descriptions from the TEI. The only concern is the 4 columns, as lists are actually in columns, but we might be able to ignore for MVP because it's such a small group.

**Comment by richmanrachel** [comment]
> I had been planning to have this tei synchronization script generate admin log entries on footnote records when it updates the transcription content, but now am questioning the usefulness of that, since this is an interim solution for transcriptions. Any opinions on whether this is valuable to document or would clutter the database needlessly?
- We think it will be helpful to know when the transcription moved from bitbucket to Django, so it won't be clutter? But not sure we entirely understand the question.

**Comment by rlskoeser** [comment]
Output from running the script in qa:

```
Processed 4,557 TEI/XML files; skipped 38 TEI files with no text content.
39 documents not found in database.
274 documents with multiple fragments.
614 documents with multiple editions; 42 multiple editions with content (20 unique documents).
64 documents with no edition.
3,800 documents with one edition.
Updated 4,354 footnotes.
```

**Comment by richmanrachel** [comment]
Looks great! Closing :)
