### ISSUE TITLE
As a user, I want to see images and transcription, if any, for all fragments associated with a document so I can see the full contents that are available.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#322]
## testing notes
When you access documents on the public site (e.g., when selected via search https://test-geniza.cdh.princeton.edu/en/documents/ ) you should see a mirador viewer with text and images when there is image/transcription content available.
For now, transcription is linked only to the first image.

Be aware: in some cases where the TEI sync transcription is not working and we have old imported transcription content, the display may be off (the system thinks there is transcription content, but it isn't in a form that can be included in the viewer).

- [x] document with no iiif images and no transcription should not display the viewer
- [x] document with images only should display images similar to before
- [x] document with images and transcription should have transcription content loaded as an annotation in mirador associated with the first image; the annotation panel should be open by default
- [x] document on multiple fragments with iiif available should display a single mirador viewer with all images loaded into a single sequence
- [x] document with transcription and no images should load mirador viewer and display the transcription with an empty canvas labeled image unavailable
- [x] transcriptions should display line numbers
- [x] in the copyright panel on the left (click the (c) icon), attribution information should display text indicating the content was compiled by PGP, and then include additional language from external providers (i.e. a CUL statement)
- [x] in the information panel (click the i), you should see the PGP document title, description, and PGPID.

## dev notes

- [x] write a new view to assemble and serve a IIIF Presentation manifest for each document (if relevant; 404 if no transcriptions or no fragments with IIIF images; manifest with annotation list only if no images but transcription)
    - [x] include images from all associated fragments
    -  ~include all unique logos from source manifests~
    - [x] for now, simple metadata based on the document (ignore source metadata); implement minimal required metadata per IIIF Presentation spec https://iiif.io/api/presentation/3.0/#31-descriptive-properties
- [x] if any transcriptions are associated, include as annotation list in the manifest
- [x] display local manifest on public document detail view, with annotation panel default to on; adapt from search prototype code https://github.com/Princeton-CDH/geniza/blob/experiment/search/scripts/templates/iiif_viewer.html

**Comment by rlskoeser** [comment]
I underestimated the complexity of this, increasing from 5 to 8 points

**Comment by richmanrachel** [comment]
@rlskoeser - I couldn't resist looking at this before my 3pm meeting... will finish testing later. But is there any way to make the viewer bigger? This might involve @gissoo as well, but having the two panes constrained to the middle of the page rather than the full width is a little hard to use.

**Comment by rlskoeser** [comment]
@richmanrachel I've been wondering about the sizes also. I think we can't make it full-width because it will be a scroll trap, but maybe we can give it more space than we're giving it right now. interested to hear what Gissoo thinks also.

@richmanrachel more info that may help: 
- you can drag to resize the annotation pane; you can pop it out into a separate box, that puts it on the right side of the image.
-  I can configure where the thumbnails go, maybe they're taking up too much space right now on the side and should go on the bottom instead.
- there is an option for you to make mirador full-screen mode, but that's turned off right now because it isn't playing nicely with our styles; maybe fixing that would help?

**Comment by richmanrachel** [comment]
@rlskoeser - Yes, being able to go full screen if desired would be immensely helpful for all researchers!

I did play around with the other options, and they're certainly helpful, but you do still have to compromise on which pane shows you the whole line of text:
![image](https://user-images.githubusercontent.com/68028846/146443483-3ab3a9b6-4172-43ee-8f65-1336849faf1c.png)


The bigger problem, though, is that this one I was just looking at (ID 1921) is pulling the wrong transcription text... image is correct.

**Comment by richmanrachel** [comment]
The text on the site is also doing the strange thing with diacritics that Startwords did (luckily it's not an issue in Mirador): 
![image](https://user-images.githubusercontent.com/68028846/146444080-bb2d9b11-7e5d-4cc9-8aca-5e9929f40f8e.png)

**Comment by richmanrachel** [comment]
@rlskoeser - the same wrong transcription is showing up for this join as well: https://test-geniza.cdh.princeton.edu/en/documents/2216/

But all the actual testing components work and are beautiful!!!

**Comment by rlskoeser** [comment]
@richmanrachel I think I've fixed the problem with the wrong transcriptions showing up, please confirm.

I also enabled the mirador fullscreen option, if you want to check that out.

**Comment by richmanrachel** [comment]
@rlskoeser - Yes, it's fixed, and the fullscreen is super helpful - thanks!!!

The only frustration is that in the case of 1921, the verso is actually what the transcription is for, but you can't see it because it's associated with the recto/first picture. I assume given your description above, that this will be a next stage of development?

**Comment by rlskoeser** [comment]
@richmanrachel correct. I don't want to spend a lot of time segmenting transcription out and aligning with the images now because we now that the implementation is going to change.

I thought about attaching the transcription to every image, so you'd always have it available, but that turned out to be difficult!

**Comment by richmanrachel** [comment]
@rlskoeser - fascinating... My only concern is that it doesn't seem like you can copy and paste the transcriptions in the viewer, so not only can you not see them next to the write image, but you can't cheat by copying them onto a word document and having two windows open at once. Are you able to enable copy-paste?

**Comment by rlskoeser** [comment]
@richmanrachel I don't think we can enable copy/paste annotation text in Mirador right now. I was thinking of including the text of the transcription on the page for fallback functionality without javascript; maybe there's a way to make that version available for copy/paste (hidden by default, but expand to view and copy) — but I feel like it would be pretty clunky.  (copy/paste is on our requirements list, though! so we'll get to it)

**Comment by richmanrachel** [comment]
@rlskoeser - Okay. I think this will be a blocker for switching URLs, since this is one of the primary ways scholars use the site, but I can close for now!

**Comment by rlskoeser** [comment]
Good to know that it's that crucial! (makes sense.) I'm not sure when/how can we discuss an interim solution, but I'll make an issue so we don't lose track.
