### ISSUE TITLE
As a content editor, I want to create and edit content pages on the site so that I can update text on the site when information changes.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#328]
## testing notes

Visit https://test-geniza.cdh.princeton.edu/cms
- [x] Log in (if not already logged in)
- [x] Try to edit the existing content pages
- [x] Verify that the changes show up on https://test-geniza.cdh.princeton.edu/ by clicking the links in the header
- [x] On that same page (i.e. without returning to the Wagtail Admin interface), verify that the "Wagtail User Bar" appears (a [clickable circle](https://user-images.githubusercontent.com/7234006/145879209-a30b1976-ee3c-402a-91ab-20dee56b45aa.png) in the bottom left corner of the screen)
  - Note that this will only appear to logged in users and we can move/alter if it is intrusive, just comment here if that is the case
  - [x] Click the wagtail user bar and try to use the available functions

Visit https://test-geniza.cdh.princeton.edu/admin
- [x] Under "Content pages" --> "Contributors", add a few contributors to appear on the credits page
- [x] Verify that any contributors you add appear on https://test-geniza.cdh.princeton.edu/credits

## Deploy notes

- [x] Run `python manage.py bootstrap_content -H HOSTNAME -p PORT -l LANG` with appropriate values

## dev notes

basic setup for wagtail, including base template for content pages; one of example of each new page type should be added to lighthouse and percy builds

estimating as 5 points for now, with home page included; we may want to create a separate issue for the home page, but we don't have any designs for it yet, so let's just build out a basic version now that can be refined later

should be similar to work on S&co; see https://github.com/Princeton-CDH/mep-django/issues/157

- [x] add wagtail to python requirements and include in installed apps
- [x] bind wagtail admin interface urls to `/cms/`
- [x] create basic home page and content page models (or all content pages?) with basic page content (can adapt from mep-django)
- [x] setup templates and styles for content pages based on the designs in figma 
- [x] write a manage command to setup basic site content — should create placeholders for the pages we expect to include; will be used for bootstrapping content on the site and for ui/ux testing
- [x] add sample content page to lighthouse for testing (include home page also if different enough to merit)
- [x] add sample content page to percy for testing (include home page also if different enough to merit)
- [x] turn on the wagtailuserbar

**Comment by richmanrachel** [comment]
@rlskoeser - apologies for the evening testing! Everything is good except the movement from Wagtail to the site for content pages. I assume I did it right by clicking the "go live" button, but it didn't show up on the frontend. Did I miss a step, or has something gone wrong?

**Comment by rlskoeser** [comment]
@richmanrachel that was a misconfiguration on our part! The wagtail site url was configured wrong on the test site.  I've corrected that now, please test the "view live" / " go live" again when you can.

@blms does this indicate I did something wrong when I ran the bootstrap script, or does the wagtail site just need to be edited when we deploy wagtail for the first time? I specified `-H test-geniza.cdh.princeton.edu`.

**Comment by richmanrachel** [comment]
@rlskoeser - great! I needed to click a different option on the bottom of the Wagtail page ("publish") rather than just save, but it worked!
![image](https://user-images.githubusercontent.com/68028846/146013684-801ad52c-5a79-4173-9739-be2106a2dc56.png)

**Comment by rlskoeser** [comment]
Increasing from 5 points to 8 because this involved more than I'd accounted for.
