### ISSUE TITLE
Revise content/generic page styles to make sure all the needed styles have been designed 

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/geniza#329]
This issue covers styles for the following pages: How to Cite, Technical, Credits, Data Exports, and FAQ , (i.e everything under the “About” in the sitemap) as well as the Contact Us page. 

@rlskoeser Following our meeting last week I have revised and added the styles we need. I have created a page on mobile, tablet and desktop with all the content styles on it, I have also listed the styles next to the pages. Could you please check [these pages](https://www.figma.com/file/HpGBOZi9lO8B3nCAx3d4Fj/Princeton-Geniza-Project-team?node-id=1522%3A2787) (the 3 pages with "ALL CONTENT STYLES – 10/20" written on top) and let me know if everything looks ok? 

I'm not sure about your vision for the anchor links – I'm thinking to place all the h2s that exist on a page on top of that page as in-page links, is this useful? Also, do you want users to be able to link to a specific part of a page? In that case I can place a link icon next to a heading as an example.

**Comment by rlskoeser** [comment]
@gissoo for the anchor links: I was thinking of what we did for S&co, e.g. on the FAQ https://shakespeareandco.princeton.edu/about/faq/#names

- when you hover over a section title that has a link, you get a permalink icon (we borrowed this convention from code documentation)
- when you use an anchor link, the active section is highlighted

I'd rather not have to auto-generate in-page links as a table of contents.

It occurs to me that the anchor links are probably not necessary for MVP, so we could leave that out for now (or even possibly entirely); what's your preference?

The styles look good to me generally. A question and a comment:
- where is the hyperlink style? 
- I like the idea of the blockquote, but the close quotes look like the number 9 to me

**Comment by rlskoeser** [comment]
I like that link icon, and I'm fine with it being visible all the time. (You probably didn't design these for S&co; maybe Nick came up with it? I know I came up with the line along the side.)

Ok, I wasn't sure if the gray underline was the link. I think remember you have trouble with figma inline styles like this; that looks fine to me once it's a color so it's more recognizable as a link.

I don't feel strongly about the quote icon, just thought I would mention; defer to Marina.  Placement and alignment is nice.

**Comment by richmanrachel** [comment]
@gissoo - it seems fine to me, but I don't think I'd be able to come up with missing design styles without talking through it together. 

The quotation marks maybe look too modern to me? But again, I have to defer to @mrustow.

**Comment by mrustow** [comment]
I am always afraid to close issues ... I leave that to you
