### ISSUE TITLE
scholarship counts should always be displayed in search results

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#337]
## testing notes
test on the document search https://test-geniza.cdh.princeton.edu/en/documents/

- [x] counts for transcription, translation on search results should always be displayed, even when count is 1
- [x] counts should use the new format (number first, no checkmark)
- [x] labels should be correct for plural/singular depending on the count 

---- 

current template logic only displays scholarship counts when there is more than 1, but it seems to be a template bug (maybe improper nesting of conditionals with the plural labels)

>     * should scholarship record counts always be shown? I don't remember know why we only show if more than one, or if it's a bug in the template logic

per @gissoo : this was not a design decision, I think it's a bug. 

Should be revised based on design changes in #338  once those designs are approved.

**Comment by richmanrachel** [comment]
Looks much better, thanks!
