### ISSUE TITLE
tag model names and help text for translation

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#342]
We need to add translation to text for our models! Django documentation recommend you explicitly set model verbose names and make them translatable — which we have _not_ done yet. 

Localizing the admin site is less important than the public site, so we could hold off on this; but it will probably be more efficient to have all of the site text (as much as possible) ready for translation at the same time.

_Originally posted by @rlskoeser in https://github.com/Princeton-CDH/geniza/pull/341#discussion_r741358548_

**Comment by kseniaryzhova** [comment]
@rlskoeser is this still relevant?

**Comment by rlskoeser** [comment]
@kseniaryzhova I think it probably isn't a priority — do we care about making the admin site usable in translation (and is it worth the effort), or is it ok to assume people contributing to the project read English?

**Comment by richmanrachel** [comment]
@kseniaryzhova - if this is just for admin site I think we can close.

**Comment by kseniaryzhova** [comment]
@richmanrachel agreed, closing!
