### ISSUE TITLE
Revise the latin typeface options so that they could be more narrow and condensed while readable to match the hebrew typeface style

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/geniza#350]
@mrustow @richmanrachel please review [the designs here ](https://www.figma.com/file/anZFStv7zBaVWnFxr95nKt/Work-in-Progress-%2F-WIP?node-id=13%3A1472)– I have shared access with you to the figma file. 

I am proposing three typefaces – I must say I find the first two a lot more readable than the third one (Saira) and loving Muller a lot as well. Out of all the options on the internet these seem to be some of the most readable condensed typefaces that still come with a good variety of weights. Muller is not free and needs to be purchased if we decide to go with it. 

I have also received the contact info of two designers whose native language is Hebrew. So I'll be talking to them soon. 

Let me know your thoughts about the typefaces here.

**Comment by richmanrachel** [comment]
@gissoo - I agree that we should NOT use Saira. I doubt it's worth paying for a font since Roboto Condensed is good enough? But of course, deferring to @mrustow who has many more feelings on this subject :)

**Comment by mrustow** [comment]
@gissoo I absolutely love Roboto condensed.
