### ISSUE TITLE
Revised designs for pagination controls

### ISSUE THREAD

**Issue by blms** [Princeton-CDH/geniza#361]
## dev notes
- [ ] Design for pagination on mobile (meeting 48x48px requirement from Lighthouse)
- [ ] Design for pagination with fewer than 5 pages of results
- [ ] Decisions/designs for accommodating 3, 4, 5 digit numbers in numbered search results
  - Or reimplement with no negative margins so that the margin will always be consistent

## additional notes
Hope it's OK for me to set this chore up and assign to @gissoo! Just want to get more organized so I know what's being blocked by what.

**Comment by gissoo** [comment]
@blms I created these variants based on your requirements above: 
- [desktop](https://www.figma.com/file/anZFStv7zBaVWnFxr95nKt/Work-in-Progress-%2F-WIP?node-id=435%3A30017)

- [mobile](https://www.figma.com/file/anZFStv7zBaVWnFxr95nKt/Work-in-Progress-%2F-WIP?node-id=435%3A30093)


but I may need to consult with the design team at OIT about this – it can be a bit tricky, we haven't even considered this scenario for the design system project – feel free to move this back in the backlog or close it if the designs help address your requirements for now.

**Comment by blms** [comment]
Thanks @gissoo! Sorry I missed this earlier. This looks perfect as far as I can tell. I'll give it a try during the pagination implementation and see what Lighthouse says, then close if it is accepted or let you know otherwise.

**Comment by blms** [comment]
Lighthouse accepted!
