### ISSUE TITLE
Design an expanded/clicked site navigation on mobile so that users can use the site on mobile

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/geniza#370]
@rlskoeser @blms please view the [two options I have provided here](https://www.figma.com/file/HpGBOZi9lO8B3nCAx3d4Fj/Princeton-Geniza-(Project-team)?node-id=1858%3A953) for the "About" subpages and let me know your thoughts.

**Comment by blms** [comment]
I had imagined something like the second option (non nested), but I think I like the first (nested) option more. I like how it keeps all menu items the same size and indentation, while not taking up too much vertical space and preventing unnecessary scrolling.

**Comment by rlskoeser** [comment]
I like the simplicity of both options.  I don't have a strong opinion between the two options.

@blms any difference in difficulty of implementing the two?

**Comment by blms** [comment]
The second one would likely be easier to implement.

**Comment by blms** [comment]
Closed by #372.
