### ISSUE TITLE
permissions error trying to delete a document because it wants to delete the associated log entry

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#371]
## testing notes
go to the document admin list on the test site and choose one to delete
- [x] confirm the delete review screen doesn't complain about permissions
- [x] confirm the delete review screen includes language about suppressing and merging documents in preference to deleting
- [x] confirm you are actually able to delete the object
- [x] go to the log entries admin list and confirm there is a new log entry for the deletion

--- 
Error has been reported by both Alan and Marina

<img width="1054" alt="01C2D919-22C0-4F62-888C-802C9B2D2F47" src="https://user-images.githubusercontent.com/691231/142446334-37a8e56b-bb74-4644-9732-54ca90f0254a.png">

Normally we'll want to suppress or merge documents rather than deleting, but it should be possible for content editors to delete them when the need arises.

**Comment by richmanrachel** [comment]
Draft for custom language for admin delete: 
Are you sure this document should be deleted? Please only delete documents created in error. Non-documentary sources should be suppressed. Duplicates should be merged. Thanks for keeping our database safe and clean!

**Comment by richmanrachel** [comment]
@rlskoeser - Perfect! And we also confirmed that it doesn't screw with the existence of the fragment (tested with both T-S 20.117 and BL OR 5566B.23).
