### ISSUE TITLE
As a long-time geniza researcher, I want links that I've bookmarked to redirect to the same content on the new version of the PGP site so I can access the documents I'm interested in.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#373]
## Testing notes
This configuration will only matter once we change urls in production so that the site is running at geniza.princeton.edu

- [x] Does https://test-geniza.cdh.princeton.edu/pgpsearch/ redirect to the search page?
- [x] Does https://test-geniza.cdh.princeton.edu/pgpsearch/?a=object&id=26617 redirect to the document detail page for PGPID 26617?
- [x] Does https://test-geniza.cdh.princeton.edu/pgpsearch/?a=search&type=&q=rachel redirect to the search page with search text rachel
- [x] does https://test-geniza.cdh.princeton.edu/pgpsearch/?a=tag&tag=illness redirect to the search page with a query for `tag:"illness"` ?

If you want to try others, you can test any single document, tag search, or search on the PGPv3 site. All you need to do is find the url on the old pgp site and then edit the location to change `geniza.princeton` to `test-geniza.cdh.princeton` to see if the redirect works as expected

---

PR: https://github.com/Princeton-CDH/cdh-ansible/pull/115

Add rewrite rules to nginx so that old pgpid urls resolve to new permalinks:

- [x] individual documents, format: https://geniza.princeton.edu/pgpsearch/?a=object&id=2570
- [x] search page: https://geniza.princeton.edu/pgpsearch/
- [x] tag search https://geniza.princeton.edu/pgpsearch/?a=tag&tag=illness

**Comment by kmcelwee** [comment]
I don't know where to put this, but I believe these are the three lines that need to be added:

```nginx
rewrite ^/pgpsearch/\?id=(\w+)&a=object.*$ /documents/$1/ last;
rewrite ^/pgpsearch/\?a=object&id=(\w+).*$ /documents/$1/ last;
rewrite ^/pgpsearch.*$ /documents/ last;
```

## Notes
* Even though the last rewrite matches the two above, I expect that the first two will execute their redirects first and it will never reach the third because of the `last` flag https://www.nginx.com/blog/creating-nginx-rewrite-rules/
> The `last` flag ... tells NGINX to skip any subsequent Rewrite‑module directives in the current server or location block and start a search for a new location that matches the rewritten URL. 
* I'm not putting any language in the redirect, is it smart enough to redirect to your preferred language or will it just always go to `/en/documents...`
* This assumes that the `q` parameter is last. That's how it's handled when the links are constructed, but of course it could go anywhere. Should we handle for that?
* The `id` parameter needs `a=object`. It cannot operate alone on the site, so I'm not worried about that case.

**Comment by rlskoeser** [comment]
@kmcelwee redirects need to be added to the passenger nginx config file in the cdh-ansible repo; please open a PR with proposed changes. It looks like you should be able to use the `passenger_extra_config` variable — see something similar we did for CDH web https://github.com/Princeton-CDH/cdh-ansible/blob/main/group_vars/cdhweb/vars.yml#L46-L51

Why don't you start drafting testing notes based on your expectations; we'll use them to confirm behavior in qa. 

- agree with your approach to omit language; django should redirect to user's preferred language (if available)
- write the redirects to match the urls in the format that PGP v3 constructs them; seems ok to assume that's the only format that actually matters (until/unless we find otherwise)
- I'm not sure what you mean about the `q` parameter — we're not actually using it anywhere in the redirect, are we?

When checking the urls, I just noticed that PGP v3 has a tag search, which we currently don't... It would be nice to support redirects on those urls too, but we don't have anything to redirect to!

**Comment by rlskoeser** [comment]
first round of testing, this isn't working — everything is redirecting to the search page

**Comment by richmanrachel** [comment]
It's perfect! Closing!
