### ISSUE TITLE
As a content admin, I want to easily see and sort documents that need review so that I can manage the queue more efficiently.

### ISSUE THREAD

**Issue by richmanrachel** [Princeton-CDH/geniza#383]
## Testing notes
- [x] On the admin document list view, you can now toggle between default display and a "needs review" display — test that selecting this adjustes which columns are displayed based on your list
- [x] On the admin main page, click on "Documents" in the "Awaiting Review" panel: it should take you to the document list filtered to documents that need review, sorted by the needs review field, with the review display mode turned on, and a placeholder needs_review field search query

Note that in the current implementation the "needs review" display is not sticky, meaning you will have to select it again after you make changes to the page (like sorting or pagination). I could imagine this getting annoying, but wanted you to test this approach before investing more in it. How usable is this? How often do you find yourself having to change modes again?

---

**Fields**
No new fields need to be added at this point. Let's see if we can improve the system just through a better list view.

**List Fields**
Which fields should be included on the django admin list view? Could we try keeping all existing fields except Transcription, Image, and Tags and add Needs Review? Here's current screenshot for reference:
![image](https://user-images.githubusercontent.com/68028846/144489090-26e72fba-08d6-4aea-92bb-cc7fe41607c1.png)

**Default sort**
Which field should be used for initial sorting?
- Needs Review

**Filters**
I don't think we need to do this yet, but maybe if we decide drop-down menu is best, we can filter by ScriptMerge, etc

**Additional context**
Being able to sort by the Needs Review column so that we can potentially download a CSV or copy/paste PGPID numbers to assign a workflow will dramatically improve our ability to look through the items in the review queue. Right now there are too many and we are struggling with who and how to get through them, as we can's see the Needs Review notes anywhere but on the home admin page for the first 10.

**Comment by rlskoeser** [comment]
I'm hoping that we can leverage django admin to come up with a simple solution for this. you can register a model in django admin twice if you use a proxy model — see https://books.agiliq.com/projects/django-admin-cookbook/en/latest/add_model_twice.html

Proposed solution: make a proxy model and secondary admin for documents, customize queryset to only include documents that need review, adjust the columns displayed to show the needs review 
 field with plenty of space (minimal other columns, only as needed to help triage review), and then make sure the edit link goes to the main document change form.

**Comment by rlskoeser** [comment]
@richmanrachel came up with a new approach for this, please test and let me know what you think.

**Comment by richmanrachel** [comment]
@rlskoeser - I like it! My only question (and maybe it's just because my brain is fuzzy) is why do we need to be able to toggle the search views? It seems like just being able to click the resort on Needs Review and having access from admin page is enough
![image](https://user-images.githubusercontent.com/68028846/151422615-4b94a601-88ef-470e-b08a-d93b52b0e3f7.png)

**Comment by rlskoeser** [comment]
@richmanrachel try a hard refresh to get the new styles — you should see the columns change when you toggle between views

**Comment by richmanrachel** [comment]
Got it - thanks!
