### ISSUE TITLE
As a user, I want an option to sort documents randomly so that I can easily discover documents I haven't looked at before.

### ISSUE THREAD

**Issue by richmanrachel** [Princeton-CDH/geniza#387]
## testing notes
All tests should be done on the [test site document search page](https://test-geniza.cdh.princeton.edu/en/documents/)

- [x] when you load the page, default sort should be random
- [x] if you reload the page without making any changes, you should get a different set of results
- ~if you page through your random results, you should get the _same_ randomly ordered documents; check this by looking at the first one or two random results, selecting a different page of results, then going back to the first page and see that it's the same [NOTE: this appears not to work in test because we're using Solr cloud... ]~
- [x] pagination should be disabled 
- [x] enter a keyword term (sort should switch to relevance); then clear your search term (sort should switch back to random)

---- 
**Is your feature request related to a problem? Please describe.**
As an easy way to allow both new and experienced Geniza scholars alike to explore our thousands of documents, it would be wonderful to have a Random Document feature.

**Describe the solution you'd like**
We could have a Random Document button on the site menu and/or a Random Sort in the Search Page (that RSK rightfully suggested could be a default to consistently promote discovery).

## dev notes
Solr has an existing random field we can use; tricky part might be making sure we keep the same random seed when paginating within a random search result. If we generate a random seed for the random sort field each time it's requested, then perhaps we can just pass that into the pagination parameters; if it's not set and random sort is requested, we generate a new one.

- [x] add random sort option and make it default
- [x] when random sort is requested, generate a short numeric random number to use with solr's built in random dynamic field
- [x] include random seed in pagination links; reuse when set to preserve the _same_ random order

**Comment by rlskoeser** [comment]
@richmanrachel @mrustow question about how to implement this: do you want to get a new set of random documents every time you refresh the page with the random sort (but keep that sorting if you page through the random sort for some reason)? Or should everyone get the same set of random documents each day?

Asking based on Marina's description of a "random fragment of the day" in the homepage text, want to make sure I'm implementing what you want.

**Comment by rlskoeser** [comment]
@richmanrachel I agree, this is confusing! We have worked planned to give you a visual indicator that there are filters active (Gissoo needs to design, then we will implement); @gissoo also mentioned something about the fact that we don't have a reset/clear filters option, which it sounds like we may want to consider.

**Comment by richmanrachel** [comment]
@rlskoeser - great. I think this is worth prioritizing, because these filters are so awesome! @gissoo - you're totally right that we need a reset/clear filters button.

I think it would also help if the filters didn't send you to another page, so you could see which filters were on (and adjust them) as you search.

**Comment by richmanrachel** [comment]
Random sort works - closing!
