### ISSUE TITLE
As a front-end user, I want to see brief citations in the Document Detail view, more concise than those in Scholarship Records.

### ISSUE THREAD

**Issue by blms** [Princeton-CDH/geniza#390]
## testing notes
- [x] Check various document detail pages, e.g. https://test-geniza.cdh.princeton.edu/en/documents/5504/, and verify that the brief citations under "Editor"/"Editors" look correct, and are not missing any citation fields or including unwanted ones
- [x] Verify that the "Editors" section citations only refer to digital editions, and that the section does not appear when there is no digital edition available
   - note: digital editions are only visible from the search results at the moment, as transcripts don't appear in the document detail view yet
- [x] Verify that "Editors" is correctly pluralized based on the number of people listed

## dev notes

- [x] Add "unpublished" to brief citations.
- [x] Only show brief citations for available digital editions.
- [x] Pluralize editor heading if there is more than one digital edition

<details>
<summary>docs with more than one digital edition</summary>

- Bodl. MS heb. f 29/69 + … (PGPID 2493)
- Bodl. MS heb. f 39/29 (PGPID 606)
- CUL Or.1080 J24 (PGPID 9121)
- CUL Or.1080 J38 (PGPID 4743)
- ENA 2727.7b (PGPID 4740)
- T-S 12.190 (PGPID 9089)
- CUL Or.1080 J23 (PGPID 5552)
- ENA NS 13.1 + … (PGPID 9804)
- T-S 8J5.1 (PGPID 2142)
- NLI 577.3/2 (PGPID 848)
- T-S 8J10.16 (PGPID 1849)
- ENA NS 21.14 (PGPID 2691)
- T-S K15.85 (PGPID 4585)
- T-S 8Ja1.3 (PGPID 4717)
- T-S 10J12.5 + … (PGPID 4721)
- T-S Misc.25.103 (PGPID 4738)
- ENA NS 21.7 (PGPID 5410)
- Bodl. MS heb. d 74/41 (PGPID 591)
- DK 333 (alt: 18) (PGPID 4495)

</details>

**Comment by richmanrachel** [comment]
Looks perfect! Closing!
