### ISSUE TITLE
Add styles for UI components in default, hover, focus, active, and disabled states for light and dark mode 

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/geniza#393]
Please review the styles for UI components in [various states here](https://www.figma.com/file/anZFStv7zBaVWnFxr95nKt/Work-in-Progress-%2F-WIP?node-id=188%3A33275)

Note: 
- I have labeled each state

- There are two versions, one where everything except the links are red, and one with green – I prefer the red version, but want to make sure we look at both in case we feel strongly about the red. 

- I will add the styles for the dark mode here too – the dark mode styles for buttons have already been added here.

**Comment by richmanrachel** [comment]
@gissoo - could you please define your terms? I think I understand that "hover" means "what it looks like when your mouse is over the button" and "default" as the state when you're not hovering, but what do "active" and "focus" mean?

**Comment by blms** [comment]
@richmanrachel "Active" is when you are currently clicking on the button, and "focus" is when you use the Tab key to select a button.
![144879975-6f4440e5-499f-425e-b59a-c8903827a916](https://user-images.githubusercontent.com/7234006/144880193-c9a8095a-47bc-40f2-b1ca-2dd191ec39d2.png)

**Comment by rlskoeser** [comment]
Great to have all these styles and modes documented! I don't think I have any additional comments beyond what I already said about the colors.

**Comment by blms** [comment]
This all looks good to me!

**Comment by gissoo** [comment]
@richmanrachel sorry – @blms thanks for explaining! 
Just to add: some components like the tabs and the top navigation in the header or the pagination don't have a "default" because there is always one menu item/page/tab that's active – but buttons for instance always has a default look.

**Comment by richmanrachel** [comment]
@gissoo and @blms - thanks! Not sure I totally understand how to read the designs, but they seem good (and I trust Rebecca and Ben)!
