### ISSUE TITLE
Update sitewide type to use purchased fonts, new styles

### ISSUE THREAD

**Issue by blms** [Princeton-CDH/geniza#396]
## dev notes

- [x] Use the new typefaces provided by Gissoo
- [x] add a note to dev instructions in the readme
- [x] add to gitignore to ensure we don't accidentally add purchased fonts to the git repo
- [x] Use new type sizes and styles

**Comment by gissoo** [comment]
Thank you !! A couple of points:
- I wonder if the two type styles below should be in fact 18 on desktop and 16 on mobile – the current active sort option looks too large, do you agree? 
<img width="653" alt="Screen Shot 2021-12-15 at 5 30 10 PM" src="https://user-images.githubusercontent.com/44615389/146274868-29e07d55-8d64-4fe4-bfa5-6d2f78d2d64e.png">

- The "Description" header on the document detail view needs to be bold and 20px on desktop 
- The "unpublished" should not be italicized 
- The "Transcription / Edition / Discussion" text in the grey box should be 18px on desktop and 16px on mobile 
- The page titles on content pages need to be bold and all page titles need to be 24px, I see some being 25.6px 

- Question: how are we calculating the type sizes? Is it by percentages? I see a lot of decimals, just wondering, it's not creating any significant changes except in the page title.

**Comment by blms** [comment]
> I wonder if the two type styles below should be in fact 18 on desktop and 16 on mobile – the current active sort option looks too large, do you agree?

I think either is fine, so let's make it smaller!

> Question: how are we calculating the type sizes? Is it by percentages? I see a lot of decimals, just wondering, it's not creating any significant changes except in the page title.

I am using a harmonic type scale, which was implemented before I started working on the project, though I changed the scale factor from 1.25 to 1.125 to more closely match the `px` values you chose. It uses `rem` units:

```scss
// Type scale: generate sizes according to harmonic ratio. This scale is based
// on the "Major Second" scale, with a scale factor of 1.125. See:
// https://baseline.is/tools/type-scale-generator/
$text-size-xs: 0.79rem; //   ~ 13px
$text-size-sm: 0.89rem; //   ~ 14px
$text-size-md: 1rem; //      = 16px
$text-size-lg: 1.13rem; //   ~ 18px
$text-size-xl: 1.27rem; //   ~ 20px
$text-size-2xl: 1.42rem; //  ~ 23px
$text-size-3xl: 1.6rem; //   ~ 26px
$text-size-4xl: 1.8rem; //   ~ 29px
$text-size-5xl: 2.025rem; // ~ 32px
```

There are two things going on here:
1. Using `rem` units instead of pixels, which should be done for accessibility to ensure that all type sizes scale appropriately when a user changes the base font size of their browser up or down from 16px (which is the default basis for 1rem)
2. Using a "harmonic scale" so that each successive size is multiplied by a consistent factor (in this case, 1.125)

Since it sounds like it's significantly impacting the design, we can make adjustments to the latter, as I think it was simply a design decision and without a clear technical or accessibility need. We can simply adjust the `rem` values to match as close as possible to the px values you specified. I'll go ahead and do that!

**Comment by blms** [comment]
Confirmed in QA site
