### ISSUE TITLE
As a front-end user I want to see the footer to view a list of website's menu items, licensing, accessibility, and links to social media 

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/geniza#397]
here are links to the designs: 

- [for desktop light mode](https://www.figma.com/file/anZFStv7zBaVWnFxr95nKt/Work-in-Progress-%2F-WIP?node-id=421%3A25253)

- [for mobile light mode](https://www.figma.com/file/anZFStv7zBaVWnFxr95nKt/Work-in-Progress-%2F-WIP?node-id=421%3A25670)

- [for desktop dark mode](https://www.figma.com/file/anZFStv7zBaVWnFxr95nKt/Work-in-Progress-%2F-WIP?node-id=421%3A26983)

- [for mobile dark mode](https://www.figma.com/file/anZFStv7zBaVWnFxr95nKt/Work-in-Progress-%2F-WIP?node-id=421%3A26591)

**Comment by blms** [comment]
Confirmed present in QA (implementation already reviewed in percy)
