### ISSUE TITLE
Look into type configuration for Percy and deploying to QA and production 

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/geniza#400]

**Comment by rlskoeser** [comment]
documenting the advice I got from @thatbudakguy :

we'll need percy-specific css to pull the fonts from production; here's an example (although the `font-face` is a bourbon mixin so ours will look slightly different)

https://github.com/Princeton-CDH/cdh-web/blob/d6002dc1933a4d6e97f5459aafc9ab92cb1f8050/sitemedia/scss/_fonts.scss#L36-L41

The qa & production deploys will need to be updated to include the fonts, and configure them so they're available for local referrer or when requested from percy
