### ISSUE TITLE
increase footnote source field site in document detail view so the names and titles don't get cut off

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#404]
## testing notes (qa)

- [x] In the QA admin interface, navigate to a document (edit view) with attached footnotes and confirm that the full titles of source records display properly in the table

---

is there an easy way to make the source box bigger in document detail view? The names get cut off so I have to open the edit window to see which book the source is from:
![image](https://user-images.githubusercontent.com/68028846/145432411-76c98fff-cebb-40b4-8169-38f17b5d7773.png)

_Originally posted by @richmanrachel in https://github.com/Princeton-CDH/geniza/issues/325#issuecomment-989992857_

**Comment by richmanrachel** [comment]
@blms - it works! The sizing looks a little funny though (it seems to be double spaced in the source name, and the urls also create odd spacing)
![image](https://user-images.githubusercontent.com/68028846/154360835-d3132c94-a408-472b-90f8-e54fed24ab6c.png)
I'm not sure it's worth fixing this for the backend, but just wanted to make a note.
