### ISSUE TITLE
Revise the type styles to ensure they are appropriate for the new typefaces (Greta Sans and Frank Ruehl) + organize them on Figma so that it's easier for the dev team to implement them

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/geniza#408]
@blms here is the [revised type style sheet](https://www.figma.com/file/HpGBOZi9lO8B3nCAx3d4Fj/Princeton-Geniza-(Project-team)?node-id=1937%3A5514) – they are more specifically defined here, let me know if you have any questions.

**Comment by blms** [comment]
All looks good! Thanks for the specific labels.
