### ISSUE TITLE
Revise the logo based on the feedback received in issue #283

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/geniza#409]
Here are the [new versions for the logo](https://www.figma.com/file/anZFStv7zBaVWnFxr95nKt/Work-in-Progress-%2F-WIP?node-id=314%3A13296) based on feedback that was given by the team, especially Marina and Rachel – let me know if any of these work and your thoughts.

**Comment by gissoo** [comment]
here is the temporary logo approved till we finish revising the permanent one: 

- [for desktop light mode](https://www.figma.com/file/HpGBOZi9lO8B3nCAx3d4Fj/Princeton-Geniza-(Project-team)?node-id=2300%3A16460)
- [for mobile light mode](https://www.figma.com/file/HpGBOZi9lO8B3nCAx3d4Fj/Princeton-Geniza-(Project-team)?node-id=2300%3A16461)
- [for desktop dark mode](https://www.figma.com/file/HpGBOZi9lO8B3nCAx3d4Fj/Princeton-Geniza-(Project-team)?node-id=2300%3A16466)
- [for mobile dark mode](https://www.figma.com/file/HpGBOZi9lO8B3nCAx3d4Fj/Princeton-Geniza-(Project-team)?node-id=2301%3A16480)

**Comment by richmanrachel** [comment]
@gissoo - dark mode looks great! I do think the light mode one would benefit from some color, but I like the direction we're heading!

**Comment by mrustow** [comment]
ditto — thanks for doing this.
