### ISSUE TITLE
As a content editor, I want to be able to manage pages and page order in the site navigation menu or about submenu, so that I can update the site as content changes.

### ISSUE THREAD

**Issue by blms** [Princeton-CDH/geniza#410]
### creating new pages
- Visit https://test-geniza.cdh.princeton.edu/cms
- Log in and click Pages, then click on the English home page ("The Princeton Geniza Project")
- Confirm that you can see a page called About and its type is a Container page
- Click the green right arrow to the right of the About page
- Confirm that several content pages are child pages of this About page
- Try adding a new child page with the "Add Child Page" link at the top. Give it a title and body, click "Promote" and check "Show in menus", then at the bottom next to "Save draft," click the arrow and click "Publish"
- Once published, return to https://test-geniza.cdh.princeton.edu
- Confirm that your new child page shows up in the About menu in the top navigation, and you can navigate to it

### managing page order
- Visit https://test-geniza.cdh.princeton.edu/cms, click Pages, then click on the English home page
- Click the green arrow to the right of the About page
- At the top, click "More" > "Sort menu order"
- Reorder the pages by dragging them around with the handles on the left
- Return to https://test-geniza.cdh.princeton.edu and confirm that the About menu order has changed accordingly

### managing translations
- Visit https://test-geniza.cdh.princeton.edu/cms, click Pages, then click on the Hebrew home page this time
- Click "edit" under some of the pages, such as Contact Us, About, and About's subpages
- Click "Translate this page", then "Submit"
- In the Content section, by each field, confirm you can see a button that says "Translate". Press that button on some fields  and try translating them to Hebrew
- Click "Publish in Hebrew" at the bottom
- You may see a warning "Published [page] in Hebrew with missing translations" if there are fields left untranslated, which includes the Slug field in the Promote section. Feel free to ignore or translate them
- Return to https://test-geniza.cdh.princeton.edu and switch to Hebrew using the language switcher in the top-right corner
- Confirm that your translations appear in the menu(s)

## dev notes 
- [x] Create ~"Main navigation" and~ "About" link pages and make appropriate content pages subpages
- [x] Update nav template to programmatically display the pages

## deploy notes
See `DEPLOYNOTES.md`. In addition:

- Content editors should be made aware that to edit pages in sub-menus, in the Wagtail admin, they need to click the green right arrow button next to a Container page. Editing the Container page itself will only allow them to change its title or slug.
- Content editors should also be made aware that new content pages must be of type "Content page", regardless of whether they are to appear in the main navigation or a sub-menu. If they want the new page to appear in a sub-menu, they should be made child pages of an existing "Container page" (like the others in that sub-menu).

**Comment by rlskoeser** [comment]
in case it's useful, here's similar template code for our cdh website primary navigation (although that nav is much more complicated than anything we're doing here):
https://github.com/Princeton-CDH/cdh-web/blob/main/templates/snippets/primary_navigation.html#L9-L36

**Comment by rlskoeser** [comment]
increasing estimate to 3 to more accurately reflect the complexity

**Comment by richmanrachel** [comment]
Creating new pages - everything works! We need to make sure I have a copy of these instructions for the future :) 

Managing page order - all is good!

Translations:
- I was able to change the name of the container "About." Changing the names of the child-pages was a little less intuitive, but I could change it as well. 
- @blms Are we going to have to manually add translations for everything?

**Comment by blms** [comment]
@richmanrachel Thanks, glad to hear things worked well! Unfortunately, yes, all content must be translated manually—at least for everything you want translated!

**Comment by rlskoeser** [comment]
@richmanrachel regarding translation: it looks like wagtail supports generating `.po` files for export and import if we want to outsource content translation that way; we'll probably need to decide how much of the site content we want translated. We don't have to translate all of it.

**Comment by richmanrachel** [comment]
@rlskoeser - Okay great! Yes, it obviously won't be too hard translating all the names of the content pages. @mrustow - we'll just have to decide if there are any content pages we want to write in Hebrew and Arabic.
