### ISSUE TITLE
off-screen menu shows up when resizing browser window

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#411]
## testing notes

Confirm the mobile menus do not appear from offscreen during any of the following actions:

- [x] on desktop, resizing the browser anywhere on the site
- [x] on mobile, typing in the search box
- [x] on mobile, navigating to a document detail view

---

When I resize the window, at certain widths the mobile menus show up and then disappear again at the sides of the page.

I think this is a bug but not a very high priority one, since I don't think it's too likely to happen with real-world behaviors.

Here's a video capture of the behavior:

https://user-images.githubusercontent.com/691231/145892212-75d2569c-5b4f-42c5-8307-e717f702c919.mov

**Comment by blms** [comment]
Also appears on mobile, e.g. when searching or navigating between search and document details.

**Comment by rlskoeser** [comment]
tested with browser resizing, browser simulating mobile, and used Firefox on my phone — no sign of the off screen menu when it isn't supposed to be there! (and still works as expected when I want to use the menu)
