### ISSUE TITLE
As an admin, I want numeric footnote locations automatically prefixed with 'pp.' so the meaning of the numbers will be clear to public site users.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#412]
## dev notes
Create a new data migration to update footnote locations that start with numeric values to add 'pp.'

this should be close to the regex we need:
`^\d+[-–\bf,\s]?`

(one more digits, followed by a dash, word boundary, whitespace, or the character `f`)

Maybe we can exclude the numeric + hebrew letter document indicators in a separate queryset filter; this should be the character range we need `(?![\u0590-\u05fe])`

_Originally posted by @rlskoeser in https://github.com/Princeton-CDH/geniza/issues/389#issuecomment-993598276_

revision needed after testing: add a special case for purely numeric locations, apply p. only instead of pp.

**Comment by rlskoeser** [comment]
@richmanrachel I implemented the 'pp. ' prefixing migration for numeric footnote locations that we discussed. The best way to review is probably to download the footnotes as csv and check the locations.

**Comment by richmanrachel** [comment]
@rlskoeser - how big should this download be? It's at 10 MB now and still going up...

**Comment by richmanrachel** [comment]
Oh I see - it has all the transcription content now!

**Comment by richmanrachel** [comment]
@rlskoeser - looks much better! I don't mind that the small number of single pages say pp. like here. Now maybe we can just make the "Edition" clickable instead of "includes"?
![image](https://user-images.githubusercontent.com/68028846/146277038-563d81c3-ed9b-4394-9c00-4a8066027d62.png)

**Comment by rlskoeser** [comment]
@richmanrachel I don't think we should make Edition clickable. It's much easier in the code if we generate the link in the same place, and it's better for the user if things are consistent. Can we come up with language for resources that have a link but no location? "See external resource" or "See online resource" or something like that? @gissoo any thoughts?

**Comment by rlskoeser** [comment]
@richmanrachel I did a quick query, it looks like there are 66 footnotes where the location is purely numeric (one or more digits, no other content). It's not too much more work to make those start with p. instead of pp. It will likely miss cases where there is mixed content (e.g. a single page number with a document number), but would rather be conservative in which ones we target. What do you think? Stick with pp. or revise logic to make these 66 p. ?

**Comment by richmanrachel** [comment]
> I don't think we should make Edition clickable. It's much easier in the code if we generate the link in the same place, and it's better for the user if things are consistent. Can we come up with language for resources that have a link but no location? "See external resource" or "See online resource" or something like that?
- @rlskoeser, hmmm. Nothing great is popping to mind but I do think we need to work on this. I'll add it as a final item on today's agenda to see if a group brainstorm is useful.

As for the 66, I'll ask Marina because I have a feeling she might be pickier than I am.

**Comment by rlskoeser** [comment]
@richmanrachel revised version of this data migration ran when I deployed against a fresh copy of production data just now. Please confirm that locations that were previously numeric only are now prefixed with `p.` instead of `pp.`

**Comment by richmanrachel** [comment]
@rlskoeser - Perfect!
