### ISSUE TITLE
Wagtail bootstrap script doesn't work as expected

### ISSUE THREAD

**Issue by blms** [Princeton-CDH/geniza#413]
## dev notes
- [x] If default site exists, set the fields to the provided values

**Comment by rlskoeser** [comment]
tested this in qa after I loaded fresh data from production, and confirmed that it now works as expected

**Comment by rlskoeser** [comment]
fyi @blms I don't consider something a bug unless the problem makes it into production; if we catch a problem before we make a release, then it's not a bug :-)
