### ISSUE TITLE
As a user, I want to change site language so that I can switch languages when I don't want to use the browser-detected default.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#429]
Note that this is just an initial implementation so that we have the functionality available to help us with the functionality while we're developing it and for translators to review. We'll revise when there is a design available. 

## testing notes
- [x] confirm there is a language switcher form in the top right on every page
- [x] confirm that you can use the form to change the language used on the site
- [x] the language you choose persists as you navigate around the site

## dev notes
Implement a language-switching form; should be available on every page.

Should be able to adapt the form from the i18n prototype, which uses an existing django i18n view: https://github.com/Princeton-CDH/geniza/blob/experiment/i18n/geniza/templates/base.html#L19-L35

**Comment by rlskoeser** [comment]
@gissoo (sorry to add to your list!)

Nick implemented a basic form when he built the i18n prototype; here's what it looks like:

![Screen Shot 2021-12-16 at 3 12 20 PM](https://user-images.githubusercontent.com/691231/146443118-af1d23b7-d25e-4d19-9632-f42ab9f7a754.png)
![Screen Shot 2021-12-16 at 3 12 16 PM](https://user-images.githubusercontent.com/691231/146443127-d30be7e2-9e00-4532-ae56-a01376984dd9.png)

Could you suggest where it should go on the page for desktop/mobile, and any other context/visuals that would be important to include? Hoping we can use the styles from the components you've already designed.

**Comment by richmanrachel** [comment]
It works! So cool!
