### ISSUE TITLE
As a scholar, I want to get a copy of transcription text so that I can easily reference it and use it elsewhere.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#434]
## testing notes

all download tests should be done from document detail page, for documents with a digitized transcription associated
- [x] download link should appear just above the mirador viewer
- [x] download link text should include edition author's name; check display for sources with
  - [x] one author
  - [x] two authors
  - [ ] more than two authors
- [x] downloaded text filename should include pgpid, slugified shelfmark, and slugified author last name
- [ ] check file contents: I added rtl and ltr marks for content and line numbers, and I also added some whitespace justification; I'm also now including the labels
- [x] documents without a transcription available should not have a download link
- [ ] check the search results to make sure transcription display and transcription search is still ok (formatting has changed slightly; now will include labels and line numbers)

--- 

Limitation with displaying transcription as annotation in mirador  — not available to select for copy/paste.

... My only concern is that it doesn't seem like you can copy and paste the transcriptions in the viewer, so not only can you not see them next to the write image, but you can't cheat by copying them onto a word document and having two windows open at once. Are you able to enable copy-paste?

_Originally posted by @richmanrachel in https://github.com/Princeton-CDH/geniza/issues/322#issuecomment-996252389_

## dev notes
- [x] include slugified shelfmark in filename (first one only for join)
- [x] add line numbers to plain text version of transcription
- [x] move link to just above image viewer and label based on author, e.g. "Download Goitein edition"

**Comment by rlskoeser** [comment]
@richmanrachel @mrustow would a plain text download of the transcription text be sufficient for now?  That seems like it would be the easiest solution. 

If that's acceptable, two followup questions:
1. Should the plain text file include line numbers? (My guess is yes; does formatting matter?)
2. Is it ok if search term highlighting of transcription text includes line numbers? (currently it does not; it's much easier if we use the same plain text version for both of these things)

**Comment by rlskoeser** [comment]
Also: not specifically related to this issue, but how much would it help in the interim if the transcription text was displayed for every image? I can look into that again.

**Comment by richmanrachel** [comment]
@rlskoeser - I think a plain text download would work. Can we test it?

1. Yes, I think line numbers would be helpful. And I think it'd be annoying, but okay as a temporary solution to have to add in line breaks myself. (I assume that's what you mean by formatting?)
2. Oooh, I don't think that would be good, because then if a phrase is broken across a line, a search wouldn't work.
3. Having the transcription text for every image would be great!

Would it make sense to do a test of downloading plain text with and without line numbers to see which feature if more useful if we already have to add line breaks?

**Comment by rlskoeser** [comment]
@richmanrachel it would have line breaks, but in a plain text file I don't think we can do much with alignment or spacing.

I can try to do a quick implementation of the text file download so you can see what the plain text looks like right now without line numbers.

**Comment by rlskoeser** [comment]
Ok @richmanrachel — quick implementation is on the test site so you can see what it looks like. For documents with an edition that has text associated via the new transcription sync, you should see a "download as text" link under the editor citation on the main document page.

This version of the text has line breaks but no line numbers.

**Comment by richmanrachel** [comment]
@rlskoeser - the text file is very unfriendly looking (super small and a bad font), but when I copy-pasted+match style into my word document it looked great!
![image](https://user-images.githubusercontent.com/68028846/148298763-eaa63fb3-740c-43c0-abb1-2536bc05979a.png)
![image](https://user-images.githubusercontent.com/68028846/148298788-83f17560-b891-434a-9c36-3de8a38d0dbf.png)

**Comment by richmanrachel** [comment]
The placement of the "Download as text" button does not make sense right now, but I assume this was just part of your quick solution. Putting a screenshot here for documentation:
![image](https://user-images.githubusercontent.com/68028846/148298967-50e6e943-7926-4b7d-ba4b-0dc6547a2a97.png)

@mrustow - would you mind testing this too, please?

**Comment by rlskoeser** [comment]
@richmanrachel correct on placement/styles — would want input from Gissoo on how to present this to users to make it most legible.

**Comment by rlskoeser** [comment]
Notes from discussion with @richmanrachel :
- download link should be right next to the image viewer since there's where you're looking at the transcription that you can no longer highlight for cut & paste
- would be great if the link said something like "download Goitein edition"

**Comment by mrustow** [comment]
I agree, the .txt file is unfriendly (can it default to RTL somehow?). I couldn't get the copy-paste to work on Safari — couldn't highlight the text and keep it highlighted long enough to copy it.

**Comment by rlskoeser** [comment]
@mrustow @richmanrachel it sounds like my plain text solution isn't good enough; what would be ideal/preferred? Would you rather download a file, copy and paste something from the document page? If file a download, what format would you prefer?

**Comment by rlskoeser** [comment]
increasing estimate from 1 to 2 for additional complexity in text version of transcription

**Comment by richmanrachel** [comment]
@rlskoeser -  RTL encoding isn't working correctly with the line numbers in the txt file or when copy-pasting into Pages :( 
![image](https://user-images.githubusercontent.com/68028846/149808612-07a15dbe-ee2b-4645-b0e1-39cf0e2ee000.png)
![image](https://user-images.githubusercontent.com/68028846/149808657-5b2bb129-1e74-43c1-bbac-635754f42f48.png)

**Comment by richmanrachel** [comment]
I do love the new content markers and how clear it is which part of this text is from which part of the join. 

I should note that the slugified name only captures one shelfmark in the join.

**Comment by richmanrachel** [comment]
I'm not finding any 3+ authored editions that actually have a download option (they're all co-authored editions on google docs that haven't been put into TEI yet).

**Comment by richmanrachel** [comment]
Adding the line numbers to the txt did (as expected) mean that I did not get search results back for phrases that crossed line breaks :( 

@rlskoeser - I can't quite tell what will make this issue good enough for now, as we really do need this release for the backend changes to the bibliography and language filters...

**Comment by richmanrachel** [comment]
Closing and creating new issue, per @rlskoeser's recommendation. This is good enough for internal release now.
