### ISSUE TITLE
Design the site footer for the Hebrew version of the site 

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/geniza#440]

**Comment by gissoo** [comment]
@mrustow @richmanrachel please look at the footer design below or on [Figma](https://www.figma.com/file/anZFStv7zBaVWnFxr95nKt/Work-in-Progress-%2F-WIP?node-id=1126%3A32266) and let me know if you notice anything that looks wrong regarding the direction/orientation/order of elements for the Hebrew version of the footer. ![Screen Shot 2022-03-16 at 6.51.09 PM.png](https://images.zenhubusercontent.com/5bf307a69d595b459ec91bb1/e64dd2c2-e252-4e87-89e2-5553542a0ab8)

**Comment by gissoo** [comment]
recording RR's comment: ![Screen Shot 2022-03-17 at 11.38.58 AM.png](https://images.zenhubusercontent.com/5bf307a69d595b459ec91bb1/f740f04a-7d8e-44c5-bec7-bd85b6976fa5)

**Comment by richmanrachel** [comment]
@gissoo - okay, this works!
