### ISSUE TITLE
As a front-end user I want visual signifiers for the search form on the search page to improve my experience when I hover, click on, navigate through them with the keyboard, or know when an item is disabled

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/geniza#449]
## testing notes (QA)

- [x] Visit the documents search page, https://test-geniza.cdh.princeton.edu/en/documents/, and confirm that the search styles match the designs
- [x] Test interactions such as click, hover, focus, select filter/sort options (note that the first time you click on a filter option, you will see the "focus" style, click a second option to see the "active" style on the first one you clicked)

---

Here are links to the designs: 

- [for desktop light mode](https://www.figma.com/file/anZFStv7zBaVWnFxr95nKt/Work-in-Progress-%2F-WIP?node-id=421%3A23976)
- [for mobile light mode](https://www.figma.com/file/anZFStv7zBaVWnFxr95nKt/Work-in-Progress-%2F-WIP?node-id=421%3A24196)
- [for desktop dark mode](https://www.figma.com/file/anZFStv7zBaVWnFxr95nKt/Work-in-Progress-%2F-WIP?node-id=421%3A26117)
- [for mobile dark mode](https://www.figma.com/file/anZFStv7zBaVWnFxr95nKt/Work-in-Progress-%2F-WIP?node-id=421%3A25898)

**Comment by gissoo** [comment]
@blms Thank you!! The search functions look match the designs and function like the design intended – however the sort options allow you to see and choose "relevance" without inputting any search terms, I think we don't want that, correct @rlskoeser ?

- Also, we should eventually add a visual signifier to show when there are active filters for when the filter is collapsed right now (or _hidden_ as the original designs in Figma show)

**Comment by blms** [comment]
@gissoo @rlskoeser Did we decide on JS to check for input into the search box for choosing "relevance"?

Or maybe it would make more sense to make the search box input a required field when "relevance" is selected?

The original implementation did not allow selecting "relevance" even if you had entered text, as it would only become enabled after you made a search with a different sort option.

**Comment by blms** [comment]
@gissoo @rlskoeser Closing this, split the other two concerns off into two new issues:

https://github.com/Princeton-CDH/geniza/issues/523
https://github.com/Princeton-CDH/geniza/issues/524

@gissoo Thanks for your review!
