### ISSUE TITLE
As a front-end user I want to see buttons along with visual signifiers for the tabs on the site to improve my experience when I hover, click on, navigate through them with the keyboard, or know when an item is disabled

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/geniza#450]
## testing notes (round 2)

- [x] check mobile select underline for "view document details"
- [x] check dark mode colors, style, interactions for "view document details"

---

## testing notes (QA)

- [x] Check hover, focus, and click states for "View document details" button (mobile/desktop, light/dark)

---

here are links to the designs:

- [for desktop light mode](https://www.figma.com/file/anZFStv7zBaVWnFxr95nKt/Work-in-Progress-%2F-WIP?node-id=421%3A25119)
- [for mobile light mode](https://www.figma.com/file/anZFStv7zBaVWnFxr95nKt/Work-in-Progress-%2F-WIP?node-id=421%3A25186)
- [for desktop dark mode](https://www.figma.com/file/anZFStv7zBaVWnFxr95nKt/Work-in-Progress-%2F-WIP?node-id=421%3A26458)
- [for mobile dark mode](https://www.figma.com/file/anZFStv7zBaVWnFxr95nKt/Work-in-Progress-%2F-WIP?node-id=421%3A26531)

**Comment by blms** [comment]
@rlskoeser @gissoo Are the primary and secondary buttons MVP? I don't see them being used anywhere at the moment.

**Comment by gissoo** [comment]
@blms that's a great question! If we don't have a use case for them right now, they should not be mvp, it's just easier to take them into account and design them from the beginning, so I would say the design part was mvp but do not think the implementation needs to be. @rlskoeser what do you think?

**Comment by rlskoeser** [comment]
I agree, let's not implement designs until/unless we need them (unless it is going to cause us problems in some way)

**Comment by gissoo** [comment]
@blms it works perfectly on desktop, couple of points:
- on mobile on select the underline does not appear 
- on dark mode the button does not follow the button component designs – to simplify buttons on dark mode they are all black and white in the designs but I do like this more for the "icon buttons" as it brings more attention to the button on the page – but I think it complicates for primary and secondary buttons on dark mode which is why I went black and white – once and if we have the primary and secondary buttons implemented in the future we can test, wanted to make sure this is documented.
