### ISSUE TITLE
As a front-end user I want to see the header and visual signifiers for the site's main menu to improve my experience when I hover, click on, navigate through menu items with the keyboard, or when an item is disabled

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/geniza#452]
## testing notes (QA)

- [x] Visit the QA site https://test-geniza.cdh.princeton.edu/ and confirm that the new header design is present on both mobile and desktop, light and dark mode
- [x] On desktop, test hover interactions with both main and sub-menu on light and dark mode
- [x] Visit a page from the menu and sub-menu and confirm the "current page" indicator is correct
- [x] Test the mobile menu and confirm it works as expected

---

Here are the links to the designs:

- [for desktop light mode](https://www.figma.com/file/anZFStv7zBaVWnFxr95nKt/Work-in-Progress-%2F-WIP?node-id=421%3A24685)

- [for mobile light mode](https://www.figma.com/file/anZFStv7zBaVWnFxr95nKt/Work-in-Progress-%2F-WIP?node-id=421%3A24910)

- [for desktop dark mode](https://www.figma.com/file/anZFStv7zBaVWnFxr95nKt/Work-in-Progress-%2F-WIP?node-id=421%3A24796)

- [for mobile dark mode](https://www.figma.com/file/anZFStv7zBaVWnFxr95nKt/Work-in-Progress-%2F-WIP?node-id=421%3A24990)

**Comment by blms** [comment]
Background color needs to be `var(--background)`, not transparent.

<img width="227" alt="Screen Shot 2022-01-12 at 12 43 35 PM" src="https://user-images.githubusercontent.com/7234006/149194239-a7fea5c8-475c-4640-9fda-307cd56db452.png">

**Comment by rlskoeser** [comment]
The about menu opens on hover, but it is also clickable and when I click the page jumps down (presumably to the anchor link). Clicking seems to toggle the direction of the ^ but hovering does not.

**Comment by blms** [comment]
> The about menu opens on hover, but it is also clickable and when I click the page jumps down (presumably to the anchor link).

Yes, I wasn't sure how to handle this on desktop, since this is also the link to open the submenu on mobile. It seems that making this not clickable, or using `preventDefault` in JS, would break the mobile functionality… 🤔 

> Clicking seems to toggle the direction of the ^ but hovering does not.

That's odd, it's working for me locally but not on the test site either. Maybe it has to do with its dependence on JS (to add the `.open` class/set the `aria-expanded` attribute). Maybe I could fix it with this change:
```diff
&.open a.open-sub-menu::before,
a[aria-expanded="true"].open-sub-menu::before,
+&:hover a.open-sub-menu::before {
    transform: rotate(-180deg);
}
```

**Comment by blms** [comment]
> Clicking seems to toggle the direction of the ^ but hovering does not.
@rlskoeser this is suddenly working for me now! Maybe a JS caching issue?

**Comment by rlskoeser** [comment]
> > Clicking seems to toggle the direction of the ^ but hovering does not.
> 
> @rlskoeser this is suddenly working for me now! Maybe a JS caching issue?

yes, confirmed! sorry I didn't think to try a hard refresh first

**Comment by rlskoeser** [comment]
> > The about menu opens on hover, but it is also clickable and when I click the page jumps down (presumably to the anchor link).
> 
> Yes, I wasn't sure how to handle this on desktop, since this is also the link to open the submenu on mobile. It seems that making this not clickable, or using `preventDefault` in JS, would break the mobile functionality… 🤔

Yeah, I see. Wonder if you could easily adjust the relative placement of the anchor on desktop to compensate so it wouldn't jump?

**Comment by gissoo** [comment]
Thank you @blms !! This is so exciting!! A couple of things I noticed:
- I don't know why the active state in the mobile menu in the first image below is not as bold as it is in the designs (the second image)
<img width="293" alt="Screen Shot 2022-01-12 at 5 12 01 PM" src="https://user-images.githubusercontent.com/44615389/149231166-4f28672b-77ff-4b7c-8d1f-a4a239bee31e.png">
<img width="478" alt="Screen Shot 2022-01-12 at 5 13 55 PM" src="https://user-images.githubusercontent.com/44615389/149231377-5abc8b09-4816-40db-8f37-559171c6c1d7.png">

- when shrinking the desktop screen by hand (just because I do it to see if anything odd happens), the transition is weird, recorded it below
https://user-images.githubusercontent.com/44615389/149233220-8b0c2a83-67d1-40af-918c-50c4a9a00253.MOV

- The logo in the header should not have a hover style, it currently does on both the light and the dark mode
<img width="265" alt="Screen Shot 2022-01-12 at 5 24 50 PM" src="https://user-images.githubusercontent.com/44615389/149232614-89df1679-9187-4dbc-b36e-4ea0bd7bcf76.png">

- In the implementation it seems like the image in the header transitions to 0% opacity but in the designs it's still visible, it's very subtle and not a deal breaker if it's time consuming, just noting the difference here, the current implementation makes it look kind of empty in the mobile version. 
<img width="327" alt="Screen Shot 2022-01-12 at 5 21 18 PM" src="https://user-images.githubusercontent.com/44615389/149232215-fded90db-e9cd-421d-b756-3dfc8232ac0e.png">
<img width="492" alt="Screen Shot 2022-01-12 at 5 15 55 PM" src="https://user-images.githubusercontent.com/44615389/149231640-7d163d3f-53be-4c79-8174-8fcf16eaef94.png">

**Comment by gissoo** [comment]
> 



> > > The about menu opens on hover, but it is also clickable and when I click the page jumps down (presumably to the anchor link).
> > 
> > 
> > Yes, I wasn't sure how to handle this on desktop, since this is also the link to open the submenu on mobile. It seems that making this not clickable, or using `preventDefault` in JS, would break the mobile functionality… 🤔
> 
> Yeah, I see. Wonder if you could easily adjust the relative placement of the anchor on desktop to compensate so it wouldn't jump?

>

@rlskoeser @blms would there be any accessibility issues here with the "About"? I know we did the same with PPA but just confirming. Jes (from WDS) was telling me today that the accessibility team said to her that they recommend even the word "about" in this case would take the user to a landing page, even if it means it's a list of contents for the page, just like the CDH site does, where all 1st level categories are clickable and take you to a landing page.

**Comment by rlskoeser** [comment]
I think it would be better to have an actual about page. It bother me that we have urls nested under `/about/` but no actual page at the `/about/` url.

@blms why would mobile need to be different from desktop?

**Comment by rlskoeser** [comment]
Oh right, because on mobile the about menu is an off-screen menu.... Wonder how we can simplify that.

I think we should adjust this, but IMO we can live with current version for MVP

**Comment by blms** [comment]
This one is ready for a re-review in QA! @gissoo

**Comment by gissoo** [comment]
@blms thanks so much! Everything seems to have been fixed and we decided the weird transition issue when shrinking the desktop by hand does not matter right now especially since it doesn't break anything. Everything looks great! Thanks for your comments regarding the "about", agreed with both of you.
