### ISSUE TITLE
As a user, I want to see all shelfmarks associated with a document, so that I can identify and find the supporting information from its various sources.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#460]
# Testing notes
- [ ] Find a document with multiple shelfmarks (e.g. PGPID 444), ensure that the shelfmarks are listed on the page. Are they listed correctly?
- [x] Find a document with a single shelfmark, ensure that it is also listed in the metadata on the document detail page

---

When a document has multiple shelfmarks, we're abbreviating the list for the title on the document detail page — but we never implemented the full list of shelfmarks that Gissoo designed! Those should be added to document metadata page.

figma link: https://www.figma.com/file/HpGBOZi9lO8B3nCAx3d4Fj/Princeton-Geniza-(Project-team)?node-id=851%3A6369 

- should use the same format and styles as other items in the metadata section
- should only be displayed when there is more than one shelfmark/fragment (I think that was the intention; but wondering if we should revisit to make document pages consistent and the shelfmark explicit)
   -  if `document.fragment.count` or `document.textblock_set.count` is greater than 1, display shelfmark (unless we decide it should always be displayed)
   - output `document.shelfmark` (combined version that is not abbreviated)
   - unit test template logic with the fixtures `document` (one fragment) and `join` (two fragments)

## revisions after testing
- [ ] always display shelfmark metadata, regardless of fragment count

**Comment by richmanrachel** [comment]
@rlskoeser - I don't think this is working. You can't see the second shelfmark for 444 anywhere on the page:
![image](https://user-images.githubusercontent.com/68028846/148264026-b52d8998-b55c-43a9-b804-842563319b86.png)

**Comment by richmanrachel** [comment]
@rlskoeser - oops, I again wrote too quickly and had to delete my first message. I didn't realize the test site was sending me to the real frontend... It works, but I don't like the inconsistency. Let me chat with @mrustow about this.

**Comment by rlskoeser** [comment]
I wondered about the inconsistency as well

**Comment by mrustow** [comment]
@richmanrachel I'm here if you want to discuss IRT

**Comment by richmanrachel** [comment]
@rlskoeser and @gissoo - Marina and I just met and we agree that we need to have the full set of shelfmarks in the title (especially if the join is only 2, we might be flexible about 3+). 

Although I initially thought it would be repetitive to have the shelfmark in the title and listed again below, Marina has convinced me that this repetition is productive as it's "easier on the eyes" and will help scholars keep track of this most crucial data point.

**Comment by rlskoeser** [comment]
@richmanrachel please confirm, for this specific issue are you requesting that we always display the shelfmark in the metadata no matter how many shelfmarks are associated with the document?  (It makes sense to me that it's better to be explicit and consistent.)

We can make a separate issue to revise the document title; @gissoo could you advise on max number of shelfmarks to include? It seems like there is plenty of room on desktop, but I'm not sure what the implications are for mobile. However, it would be nice to be more consistent with the search result display.

**Comment by richmanrachel** [comment]
@rlskoeser - Yes. We should always display the full set of shelfmarks. Thanks!

**Comment by rlskoeser** [comment]
@richmanrachel shelfmark metadata has been revised to display for all documents regardless of the number of fragments, please confirm on the test site.

**Comment by richmanrachel** [comment]
@rlskoeser - yes. The titles are still cut off, though.

**Comment by rlskoeser** [comment]
I made a separate issue about changing the title — we're tracking that on #493 now

**Comment by richmanrachel** [comment]
That's right. Should I close this issue, then?

**Comment by rlskoeser** [comment]
yes, please do if you're satisfied with the shelfmark display!
