### ISSUE TITLE
As a front-end user I want to see the PGP logo on the site

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/geniza#464]
here are links to the temporary logo approved till we finish revising the permanent one: 

- [for desktop light mode](https://www.figma.com/file/HpGBOZi9lO8B3nCAx3d4Fj/Princeton-Geniza-(Project-team)?node-id=2300%3A16460)
- [for mobile light mode](https://www.figma.com/file/HpGBOZi9lO8B3nCAx3d4Fj/Princeton-Geniza-(Project-team)?node-id=2300%3A16461)
- [for desktop dark mode](https://www.figma.com/file/HpGBOZi9lO8B3nCAx3d4Fj/Princeton-Geniza-(Project-team)?node-id=2300%3A16466)
- [for mobile dark mode](https://www.figma.com/file/HpGBOZi9lO8B3nCAx3d4Fj/Princeton-Geniza-(Project-team)?node-id=2301%3A16480)

**Comment by blms** [comment]
Confirmed present on QA site, further issues tracked in #452.
