### ISSUE TITLE
As a front-end user, I want to be able to switch between dark and light mode manually with a toggle or button.

### ISSUE THREAD

**Issue by blms** [Princeton-CDH/geniza#467]
## Testing/review notes:

- [x] Visit https://test-geniza.cdh.princeton.edu/ and confirm that your browser picks up your system's setting for light or dark mode.
- [x] In the top right corner, click on the switch with the sun and moon icon, and confirm that you can toggle back and forth between light and dark mode.
- [x] after changing the light/dark mode from the default site, click around the site a bit and confirm that your choice stays selected

This also is just a placeholder design for now, so design review may be additionally needed.

## dev notes

Attempted solutions (to add dark mode snapshots to Percy builds) that did not work:
- [x] Percy-specific CSS media query
- [x] Enable `force-dark-mode` argument in Selenium `ChromeOptions`

Solutions to try:
- [x] Dark/light mode switcher in UI manually clicked by Selenium

**Comment by richmanrachel** [comment]
It all works and looks awesome! The only odd thing to me is that there are three different icons that all do the same thing: 
![image](https://user-images.githubusercontent.com/68028846/148982935-7fd32c5e-82ca-45d2-9261-fb2ca08f290a.png)
@rlskoeser / @gissoo is this how it's supposed to be?

**Comment by blms** [comment]
@richmanrachel That's a good point, I see how that's confusing! It's all all meant to be one big toggle, but maybe it makes more sense if the sun always switches to light, and the moon always switches to dark.

**Comment by rlskoeser** [comment]
It's a placeholder design because we needed the functionality for testing — @gissoo interested in your input on this. (I can't remember if we asked to put this on your list of design tasks. Is there an existing PU design system component we could adapt by any chance?)

**Comment by richmanrachel** [comment]
@rlskoeser and @blms - great! Should I close then because functionality works, or keep it open for Gissoo?

**Comment by rlskoeser** [comment]
@richmanrachel my preference would be to close it and revisit design later — is this usable enough for MVP?

**Comment by richmanrachel** [comment]
@rlskoeser - okay yes. Thanks!
