### ISSUE TITLE
search for partial shelfmarks doesn't yield the expected results

### ISSUE THREAD

**Issue by alanelbaum** [Princeton-CDH/geniza#468]
## testing notes

Searching on partial shelfmarks (especially parts of dot-separated text) should now result in much better results. 

- [x] test public search with a partial shelfmark like `T-S+Ar.35` and relevance sort, e.g. https://test-geniza.cdh.princeton.edu/en/documents/?q=+T-S+Ar.35&sort=relevance
- [x] test admin search with a partial shelfmark like `AIU II.A.`

---- 

**Describe the bug**
Original Slack message: How does one pull up all the documents (say) in the T-S Misc.29 folder? They all begin with T-S Misc.29, but typing that string yields only 1 document (from another folder). Searching T-S Misc.29.* also leads to nothing. Searching T-S Misc. 29.* (not sure why adding a space helps) yields the documents I’m looking for, but also a whole bunch of irrelevant documents from other folders. Should I be going about this differently? Would it be difficult to adjust the search settings such that searching T-S Misc.29 or “T-S Misc.29” would only yield records that contain that string?

**To reproduce**
1. Go to the Django backend.
2. Try searching the opening string of whichever folder you are interested in, e.g., T-S Misc.29, or ENA NS I, or T-S Ar.35.
3. The results will be a bit chaotic.

**Expected behavior**
The JTS Viewer is very intuitive for me. E.g., if you type in ENA NS 77 and hit search, you get all the records that contain the string ENA NS 77, which in practice means you get the entire ENA NS 77 folder.

**Screenshots**

**Device information**
 - Device: MacBook Air
 - OS and version: OS X 10.15.7
 - Browser and version: Firefox and Chrome
 - Site version: v. 0.7.0

**Additional context**

**Comment by rlskoeser** [comment]
confirmed working as expected in qa
