### ISSUE TITLE
Create deploy playbook for geniza i18n prototype

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/geniza#47]
- [x] needs apache configured to allow deployment side-by-side with search prototype
- [x] needs separate playbook with different `app_name`; uses django-specific roles/localsettings setup
- [x] needs mysqlclient deps installed on target machine so it can talk to mysql database (via `common` role)
- [x] clean up `template_path` settings in group vars for all projects since default was updated to be smarter

**Comment by rlskoeser** [comment]
@thatbudakguy this is done, right?

**Comment by thatbudakguy** [comment]
yep! merged.
