### ISSUE TITLE
As a content admin, I want to add and edit page ranges in Source records so I can document where in a book or journal the content appears.

### ISSUE THREAD

**Issue by blms** [Princeton-CDH/geniza#473]
The page range is missing from Source admin! 😱 

Fixed in #474, should be ready on next deploy.

**Comment by richmanrachel** [comment]
Works! Closing :D

**Comment by richmanrachel** [comment]
Oops, closed too hastily. @rlskoeser  and @blms - the field works, but it didn't update the sources page on the front end. Is it supposed to show up here? (the pp. 18-39 was already there. I added the bogus pp. 10-15 to the source).
![image](https://user-images.githubusercontent.com/68028846/148263544-1744fbde-e49c-45ae-91f1-98448447ae23.png)

**Comment by blms** [comment]
I see from the URL bar that is the production site, I guess the same config issue that caused problems in #460. Looks like it is working fine on the test site!
https://test-geniza.cdh.princeton.edu/en/documents/1741/scholarship/

**Comment by richmanrachel** [comment]
@blms - oh fantastic! I can close for real, then :)
