### ISSUE TITLE
As a content editor, I want scholarship record summary information included in documents metadata so I can quickly see who has published on the document without switching context.

### ISSUE THREAD

**Issue by mrustow** [Princeton-CDH/geniza#475]
## testing notes

- [x] the documents CSV export should now include a `scholarship_records` field
- [x] should appear after the description
- [x] should include the short display version of the footnote record for all footnotes associated with that document
- [x] should handle multiple footnotes
- [x] should be empty if there are no footnotes
- [x] download should still be reasonably quick (expect it to be similar to before)

----
As a content admin, I would like footnotes included in .csv exports from the admin interface so that I can see who has published the document just by looking at the subset of docs I've exported, without referring back to the admin interface and without having to input the information manually.

Admittedly, the resulting .csv will be unwieldy, but it's already unwieldy and one can easily jettison columns, whereas it's difficult to add information that isn't there.

**Comment by mrustow** [comment]
It would be hugely useful if we had info at the level that we get in the drop-down menu when adding a transcription, so, e.g., "Khan, Arabic Legal and Administrative Documents" or "Goitein, unpublished transcriptions, T-S 8." Minimal is better than maximal!

**Comment by rlskoeser** [comment]
@mrustow ok, thanks for elaborating. And just to confirm, you prefer to have all this with the documents metadata, not in a secondary file?

**Comment by mrustow** [comment]
right. most intuitive for me would be in the column to the right of the description, because that's where it was in the old days.

**Comment by kseniaryzhova** [comment]
@rlskoeser I think we can close (or merge?), given we have a separate csv for footnotes that has all of this information listed.

**Comment by rlskoeser** [comment]
@kseniaryzhova thank you for reminding me about this! I meant to take a look and see how easily we can add to the export and how much it impacts the time. I know it would be easier for Marina if we have that information included in the main documents spreadsheet.

**Comment by kseniaryzhova** [comment]
@rlskoeser works for me! Thank you, closing!
