### ISSUE TITLE
As a user I want to know when there is a 500 / internal server error on the site so that I know what it is and what my options are

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/geniza#483]
## testing notes (qa)

- [x] Visit https://test-geniza.cdh.princeton.edu/_500/ to force a 500 error, and confirm font sizes, spacing, and images look right (these were not possible to confirm on Percy)

## dev notes
add an error page template for 500 errors based on the design

**Comment by gissoo** [comment]
@blms on this page only the "Search" is showing up in the menu, is this normal?

**Comment by rlskoeser** [comment]
> @blms on this page only the "Search" is showing up in the menu, is this normal?

@gissoo including the menu requires adding more information into the context, and could trigger an error — default django behavior is to try to minimize the possibility of generating errors when you're generating the 500 error page, so I decided we should omit links to the dynamic navigation pages. Hopefully people won't see this page often, and what nav is present is enough to get away from the error page, so it should be sufficient.  Sorry I didn't think about this when you were working on the designs for the error pages — 500 is the only one that is like this. If you have thoughts on how you'd like us to revise this later on please let me know.
