### ISSUE TITLE
Display Typed Text Volume Name in Footnote Detail Source Box

### ISSUE THREAD

**Issue by richmanrachel** [Princeton-CDH/geniza#486]
## testing notes (QA)

- [x] In the admin interface, confirm the volume names appear for unpublished sources (see below for more detail)
- [x] in the public document detail view, confirm that the volume for unpublished sources is not displayed

---

**Is your feature request related to a problem? Please describe.**
When trying to clean up Goitein's typed texts into volumes, we discovered that you can't easily change the source from the footnote detail view. In contrast to published works in volumes (such as Gil, Kingdom of Ishmael, vol. 3), Goitein's typed texts don't display their volume number in the drop down menu and therefore are hard to sort.

Here's a screenshot for reference:

![image](https://user-images.githubusercontent.com/68028846/148111987-7b46ae3b-21ec-469d-842d-7a65e6765671.png)

**Describe the solution you'd like**
Hopefully this is just an easy fix, updating the code to pull volume number/letters wherever they exist into the source drop down menu.

**Comment by rlskoeser** [comment]
@blms I think this is a fairly easy fix — we need to add the volume back to the string method for unpublished sources; my only concern is that I'm not sure where else we're using the string method, it might require changing the method we use to display sources elsewhere

**Comment by richmanrachel** [comment]
It works! Such an easy but useful improvement - thank you!
