### ISSUE TITLE
Fix lighthouse failures

### ISSUE THREAD

**Issue by kmcelwee** [Princeton-CDH/geniza#488]
Failing Lighthouse tests have piled up (Lighthouse may have updated recently, but errors may have also been introduced).

## dev notes
- [x] get things passing
- [x] configure to ignore if there are things we can't get passing that we can live with
- [x] revisit the font preloading

**Comment by rlskoeser** [comment]
✅  All checks are now passing! Let's keep them that way — PRs should now address any failing lighthouse tests before merging.
