### ISSUE TITLE
suppressed documents shouldn't be included in public document search

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#492]
## Testing notes
Find a few suppressed documents via the admin document list: https://test-geniza.cdh.princeton.edu/admin/corpus/document/?status__exact=S 
- [x] Use the public search to try to find a few suppressed documents in a few different ways (shelfmark, distinctive text from the description, pgpid:##, etc) and confirm they do _not_ show up in the public search

**Describe the bug**
Suppressed documents currently are findable via public search

**To reproduce**
Here's a sample search for a suppressed document in production:
https://geniza.cdh.princeton.edu/en/documents/?q=Erroneous+%22There+is+no+attached+Goitein+index+card%2C+and+the+fragment+is+literary+%28Bible%29%22&sort=relevance

It's findable in the document search, but when you click view document details you get a 404 because the suppressed logic is working there.

**Expected behavior**
Suppressed documents should be included from the document search on the public site.

---- 

## dev notes
In `DocumentSearchView.get_queryset`, the solr queryset needs to be filtered by status.
Should be as simple as `DocumentSolrQuerySet.filter(status="Public")`

It would be better if the "Public" text was not hard-coded; we're currently indexing the display value, which isn't available as a constant on the Document class — so either the choice labels should be updated to make them constants so we can refer to them via variable _or_ the index data should use the one-letter code instead of the display value. (I'm not sure why I used the display value; I don't see anywhere else obvious that we're using it).

Add a suppressed document fixture & test to confirm it's not available in the public search.

**Comment by richmanrachel** [comment]
Works! Closing!
