### ISSUE TITLE
Revise the homepage banner image on desktop and mobile

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/geniza#496]

**Comment by gissoo** [comment]
@rlskoeser @blms @mrustow @richmanrachel I revised the banner images a bit and revised it for the dark mode – please [review the designs](https://www.figma.com/file/anZFStv7zBaVWnFxr95nKt/Work-in-Progress-%2F-WIP?node-id=587%3A22233) and let me know what you think

**Comment by blms** [comment]
@gissoo The images look good to me, but I wonder if the text could be moved up significantly? I'm thinking it might look good to have the same amount of space between the site name header and body text, as between the nav and the site name header. Right now, especially on mobile, it takes a lot of scrolling to get to the content.

**Comment by gissoo** [comment]
@blms thank you for your feedback! I have revised it, please check and let me know what you think

**Comment by blms** [comment]
@gissoo They look great! (lower designs) I see what you mean on mobile, but my personal feeling is that it's a good balance between form and function. It might not be clear otherwise when you first load the page on mobile that there is text content below, if you scroll down.

**Comment by gissoo** [comment]
perfect, thanks for to you both. Closing this issue! Will upload the revised images on github.
