### ISSUE TITLE
As researcher, I want footnotes from the same source counted and displayed as a single scholarship record so that multiple links to parts of same document don't inflate the scholarship count and display.

### ISSUE THREAD

**Issue by richmanrachel** [Princeton-CDH/geniza#501]
## testing notes (round two—QA)

- [x] Check scholarship records pages for [PGPID 3504](https://test-geniza.cdh.princeton.edu/en/documents/3504/scholarship) and [PGPID 7665](https://test-geniza.cdh.princeton.edu/en/documents/7665/scholarship) to see a range of footnotes, and confirm the layout and text for the footnote links are satisfactory (feel free to check others as well)

---

## testing notes (QA)
- [x] Test document scholarship counts for accuracy, when sorting a search by scholarship records and when viewing individual documents
- [x] Confirm that previously-inflated documents like PGPID 7665 have accurate counts, and their scholarship records pages make sense

---

**Is your feature request related to a problem? Please describe.**
Currently PGPID 7665 looks like it has 14 footnotes, but really 7-8 are pages of the same PDF. So when sorting by scholarship records, the count is misleading. 

## dev notes
- [x] revise model index data so that all scholarship counts are totals of unique sources, not footnotes
- [x] revise document tabs so that scholarship count is reflected the same way (sources, not footnotes)
- [x] revise document scholarship template to display all footnotes for the same source together (use the  `regroup` if possible/appropriate)
- [x] on document scholarship template, display document relation type if set for any of the footnotes associated with that source

**Comment by blms** [comment]
@rlskoeser Quick questions about this:

1. We are talking about `Footnote` URLs, not `Source` URLs, correct? If so, then it is Footnotes that should be merged?
2. In that case, does each URL also need an associated `location`? Currently, most of these duplicates have different URLs _and_ different locations. (PGPID 7665 is a good example)

**Comment by blms** [comment]
After my last comment, I'm thinking through this with a function `footnotes_by_source` that will group footnotes on a particular document by source. Then these sources could only be displayed once on the Scholarship Records page. The footnote locations/URLs could appear as a comma-separated list, like "see X, Y, Z for" in the shaded box. And each source record would only be counted once in the scholarship counts.

However, this raises one question: are there any cases (or foreseeable cases) where there are multiple footnotes on a document with the same source, but different document relations?

**Comment by rlskoeser** [comment]
@blms thanks for thinking this through! You're right that we need to preserve location as well as url, and that editing multiple entries like that on a single footnote does not seem like a good idea. Also, this approach was sort of a provisional solution anyway, since the records that are currently causing the most problems are PDFs that were digitized in chunks but should be combined into a single document.

I agree with you, we should not change the data model — we just need to adjust how we're counting things when we index solr, and aggregate for display. Given that there are no admin-facing changes, I'm inclined to close this issue as a `won't fix` and revise #503 to reflect the new approach. Does that sound good to you?

For the template, I did a quick check and it looks like we should be able to use the built in template tag [regroup](https://docs.djangoproject.com/en/4.0/ref/templates/builtins/#regroup). For display: some of the links are much longer, so I'd been thinking of putting each link on a separate line and just indenting subsequent links so they line up with the first one (rather than adding punctuation as you've done here). I don't know how that will look with short links like the one in your screenshot, though  — it will take more space, but might also be easier to scan and keep track of which ones you've clicked on.

For the index counts and the display, I think it makes sense to count each source once, and count it for each type of document relation once if it appears on any of the footnotes.

**Comment by blms** [comment]
@rlskoeser Thanks so much! Great calls all around. I agree with closing this as `won't fix` and moving the template/indexing work into #503. (My commits on that are tagged with 501 but that's probably fine?)

Great idea also with just counting each type of document relation once. Should that go for the overall scholarship record count as well, or just the individual counts for each type of document relation?

I didn't know `regroup`. I'll take a look at that tomorrow!

**Comment by rlskoeser** [comment]
I will make this one the primary ticket and close the other, since the conversation and your commits are all linked to this one.

Yes, I think overall scholarship record and each type should could count unique sources instead of footnotes.

**Comment by blms** [comment]
@rlskoeser Sounds good.

> Yes, I think overall scholarship record and each type should could count unique sources instead of footnotes.

Oops, I should clarify here: should the "counting each doc relation once individually" go for the overall scholarship records count as well? I'm imagining a scenario with four footnotes: 

- 2 Editions with Source A
- 1 Translation with Source A
- 1 Discussion with Source B

In the new scheme (counting doc relation once per source), this should look like:

- 1 Edition
- 1 Translation
- 1 Discussion
 
Previously, this would have also meant that overall scholarship records = 4. Should the overall scholarship records count now be 2 (unique sources) or 3 (each unique "source and doc relation" combination)?

**Comment by rlskoeser** [comment]
I think it makes more sense to count unique sources for the total scholarship count — that is going to be more meaningful to researchers using the site, and it will be more consistent with the revised display on the scholarship records page.

**Comment by richmanrachel** [comment]
@rlskoeser and @blms - 7665 looks almost perfect! The only oddity is the way "for" is after the first source and "edition" is at the bottom:
![image](https://user-images.githubusercontent.com/68028846/151224672-f814943f-3454-478c-9951-5aa2c9e9477c.png)

**Comment by richmanrachel** [comment]
The counts are looking great, I think we just need to fix the style issue above!

**Comment by blms** [comment]
@richmanrachel I think that was @rlskoeser's solution to the problem of the even more unwieldy list in this original design:

<img width="627" alt="150025005-2e65a53c-c0df-41db-9f92-f634976da8a9" src="https://user-images.githubusercontent.com/7234006/151229379-2de6566a-16f8-4e7f-90c7-241b4e77bd9a.png">

Would it make most sense for "see...for" to surround the last item in the list, rather than the first?

This issue might also benefit from @gissoo's input.

**Comment by rlskoeser** [comment]
@richmanrachel what you would you expect/prefer to see in terms of the labeling and the edition? Maybe the "see x for" approach doesn't work with this kind of content... 

Agree, would be helpful to get Gissoo's input.

**Comment by richmanrachel** [comment]
Hmmm... @rlskoeser, I can't think of a great solution off the top of my head. @mrustow - any thoughts?

**Comment by gissoo** [comment]
@rlskoeser @blms I don't think "for Edition" makes sense here – I had context of what we're trying to do with this information and still didn't understand it while looking at either of the screenshots just now. 

Can we do the following? "For edition, translation, discussion see: URL1, URL2 ...."

**Comment by gissoo** [comment]
@rlskoeser @blms more specifically imagining: 

"For edition, translation, discussion see
_URL 1, URL 2 ..._"

(with line break to make it easier to read as well.)

**Comment by rlskoeser** [comment]
@gissoo that sounds ok, will it work for page numbers and document numbers? we want to treat them the same. 

I like the idea of flipping the order so you have some expectation of what you're going to get before you click a link

**Comment by gissoo** [comment]
@rlskoeser I was thinking of those cases too! Yes, it should work for those as well.

**Comment by blms** [comment]
@gissoo Quick question, which of these two options were you suggesting?

<img width="646" alt="Screen Shot 2022-01-28 at 10 49 21 AM" src="https://user-images.githubusercontent.com/7234006/151578452-b3248a4d-8443-4d2f-81de-651abf3e0e51.png">

<img width="632" alt="Screen Shot 2022-01-28 at 10 51 01 AM" src="https://user-images.githubusercontent.com/7234006/151578449-8b852a67-6d50-413b-a635-4522776e75d0.png">


There are also some edge cases I'm wondering about:

1. No footnote URL or location named—OK to fallback to the old display?
    
    <img width="627" alt="Screen Shot 2022-01-28 at 10 59 50 AM" src="https://user-images.githubusercontent.com/7234006/151579920-05563600-9c39-4725-a31b-caae6d880dfb.png">

2. Only footnote URL but no location named—how do we handle this link text? Just the word "footnote"?
    
   <img width="631" alt="Screen Shot 2022-01-28 at 11 00 24 AM" src="https://user-images.githubusercontent.com/7234006/151580106-7188e18a-ab31-4eea-8936-9603b11d2020.png">

**Comment by blms** [comment]
Maybe in the latter case it also makes sense to fall back to the original behavior—at least when there's only one such footnote in the list.

<img width="650" alt="Screen Shot 2022-01-28 at 11 08 00 AM" src="https://user-images.githubusercontent.com/7234006/151581205-494b03dd-92a0-4262-9570-a2c874ef92c4.png">

or yet another alternative:

<img width="647" alt="Screen Shot 2022-01-28 at 11 06 10 AM" src="https://user-images.githubusercontent.com/7234006/151581214-c0de879f-a398-4b03-9bf5-1b213fd5663c.png">

**Comment by rlskoeser** [comment]
I'm going to let Gissoo weigh in with her thoughts on how to handle the different cases — will just note that I think we should try to keep them as consistent as possible (e.g. not move order/link placement, etc)

question: why are we displaying "unpublished" twice?

**Comment by blms** [comment]
> question: why are we displaying "unpublished" twice?

@rlskoeser The “unpublished” label below appears on all unpublished works. The “unpublished” in the citation is for a work that doesn’t have a title—it falls back to source type (closest I could get per CMS “a short description of the work” in place of a title). But this is definitely redundant in the case of an unpublished *and* untitled source. Maybe something like “untitled” or “[no title]” would be better?

**Comment by rlskoeser** [comment]
Ah, I see — some unpublished works have a title (like "typed texts") but many do not; for those, we are showing unpublished twice. If we need a title / title placeholder, I like [no title] better (and can imagine it would be confusing if we just listed a name with no title placeholder); adding some version of untitled / no title eems like a better solution to the duplicate unpublished problem. @richmanrachel any opinion?

**Comment by richmanrachel** [comment]
@rlskoeser - I agree. Sorry I didn't get a chance to bring Marina in on this while we were meeting, but I'll ask her. I don't have a strong preference between "untitled" and "[no title]"

**Comment by gissoo** [comment]
@blms @rlskoeser

- I think we should always keep the link on the same line (either the first line or the second) – I think based on these cases the link should be on the second line at all times. So I agree with Rebecca.

- It's kind of weird that one URL is "449-464", or "card #8981", or "Footnote" ...is there a way to make their names more consistent? Can we have a placeholder on the first line for these? For instance, it would be:

_for translation, edition, discussion see card #8981/footnote/449-464_
URL

- For the ones with no links, then I think the following would make sense:
 
_includes edition/translation/discussion_

or 

_for edition/translation/discussion_

**Comment by gissoo** [comment]
> @gissoo Quick question, which of these two options were you suggesting?
> 
> <img alt="Screen Shot 2022-01-28 at 10 49 21 AM" width="646" src="https://user-images.githubusercontent.com/7234006/151578452-b3248a4d-8443-4d2f-81de-651abf3e0e51.png">
> 
> vs
> 
> <img alt="Screen Shot 2022-01-28 at 10 51 01 AM" width="632" src="https://user-images.githubusercontent.com/7234006/151578449-8b852a67-6d50-413b-a635-4522776e75d0.png">
> 

- the first one

**Comment by richmanrachel** [comment]
@blms - it looks great to me! Marina did get back to me later to see if we could change [no title] to “digital geniza document edition," but with the "online resource" language now, I'm not sure that's necessary. I'll send her a screenshot of the current qa site.

**Comment by richmanrachel** [comment]
@blms - Marina writes: "if it’s not a very big job to change it, i think [digital geniza document edition] will work better for citation purposes."

**Comment by richmanrachel** [comment]
Perfect, thank you!
