### ISSUE TITLE
As a content admin, I want duplicate footnotes with different urls automatically consolidated. 

### ISSUE THREAD

**Issue by richmanrachel** [Princeton-CDH/geniza#503]
**Is your feature request related to a problem? Please describe.**
See #501 

**Describe the solution you'd like**
We want a one-time data migration to pull different PDF pages, that should be unified, together.

## dev notes
probably only applies to the links we imported; most frequently with goitein typed texts & index cards; need to check if it happens with the others (india traders & jewish traders)
- [ ] write a data migration to identify duplicate footnotes, move urls to the first, delete the redundant ones

**Comment by rlskoeser** [comment]
No longer needed to due to change in approach. See #501 for discussion.
