### ISSUE TITLE
As a content editor, I want to merge similar tags so I can consolidate redundant tags and decrease clutter in the database.

### ISSUE THREAD

**Issue by richmanrachel** [Princeton-CDH/geniza#506]
## Testing notes

In the [QA site admin](https://test-geniza.cdh.princeton.edu/admin), go to the Taggit > Tags section.

- [x] Select several tags that should be merged into one canonical tag. Make note of the documents tagged with the non-canonical variations.
- [x] There should be a dropdown menu item at the top of the Taggit > Tags list that says "Merge selected tags". Choose that dropdown option and click "ok". You should be taken to a form.
- [x] There should be a list of all the tags you chose, and each tag should show the number of documents tagged with it.
- [x] Choose the canonical tag in this list and click "submit". You should be taken to the page for that tag, showing all of its tagged documents.
- [x] All documents that used to be tagged with the other tags should be tagged with the canonical tag. The other tags also should not appear in the list under Taggit > Tags.

---

**Is your feature request related to a problem? Please describe.**
The tagging feature is currently cluttered due to similar tags (slaves vs. slavery, etc). This will help us clean the data and maintain a more useful set of tags in perpetuity. 

**Describe the solution you'd like**
In the Tag List, select the tags you want to merge in the action bar and click go.

## dev notes
New admin action to merge tags, similar to #225 — needs a review screen so editor can choose which tag should remain and confirm the change. Should create a log entry documenting the merge.

**Comment by mrustow** [comment]
Can I make a plug for this issue? I'd like to do some tag cleanup. 

Also, in the admin interface > Taggit > Tags, how hard would it be to add a column with the number of times the tag appears in the database? If there are zeros that aren't also duplicates, it would be nice to be able to delete them without having to click into the tag to see whether it's being used for a document. If you agree, I'd be happy to write a user story.

thx :)

**Comment by mrustow** [comment]
@kseniaryzhova flagging this: can we put this in the queue?

**Comment by kseniaryzhova** [comment]
@blms works like a dream, thanks! Closing!
