### ISSUE TITLE
django admin document filter by "has transcription" reports inaccurate numbers

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#507]
## testing notes

Use the transcription filter in the document admin list and check to see if the number of documents matches what you expect for both has transcription and no transcription.

**Describe the bug**
Filtering django admin document list by has transcription is giving different numbers in production than it was previously, which we don't think is due to changes in the data (but should confirm!). It also generates different results than filtering in python console. 

**Additional context**
Unclear what the django empty filter is doing; maybe it doesn't work properly for our json field; suggest using a custom filter that checks for the content we actually expect to indicate the presence of transcription content synced from TEI. We may also want to compare exports from the earlier version of the database to check for any problems or discrepancies.

**Comment by richmanrachel** [comment]
Yes, this is looking much better! Here's a screenshot with current site on the right and test on the left:
![image](https://user-images.githubusercontent.com/68028846/149013075-37eff8db-ae2e-4015-a8fc-372a3d76ef00.png)

**Comment by richmanrachel** [comment]
And for total transcriptions, test is now (i think correctly) reading 4,236 total docs with transcriptions (vs. 1,017 on current site). Closing!

**Comment by rlskoeser** [comment]
reopening — this shouldn't have been closed, since even though the filter works, it introduced a performance problem when applying this filter in combination with others

**Comment by rlskoeser** [comment]
please retest and confirm that the "has transcription" filter in the admin document list can be used with three or more other filters without the page becoming unusably slow

**Comment by richmanrachel** [comment]
@rlskoeser - It works! Hallelujah!
