### ISSUE TITLE
Design a generous search interface for the holistic search idea so that users can learn about the relationship between clusters of data

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/geniza#51]
Here is the link to the [proposed data scheme and two versions for stage 1 UI + flow for the cluster view](https://www.figma.com/file/HpGBOZi9lO8B3nCAx3d4Fj/Princeton-Geniza?node-id=432%3A0)

Note: "stage 1 UI" is the first step for designing a UI – colors, font, line, and shape weights, and alignments are not complete. 

1. have proposed a way to categorize the clusters and the documents (The data scheme) – the condition mentioned in the data scheme is later used to create a graph where the clusters can be placed. **But** this is just a suggestion and I want to propose this to the project team and have conversations on the data scheme proposal and the condition mentioned. 

2. have proposed two ways of representing the clusters (v1 and v2) 
- v1: using the most common tag such as "tax" and grouping all the other tags that accompany it 
- v2: using the logic in v1 but labeling the group with a unique name such as "finance" – or not labeling it at all but that might be problematic once in the document list. 

3. have proposed 3 ways of navigating the clusters in each version. 
- to view all of the clusters
- to view one cluster
- to view a sub cluster

4. have shown how a shared sub cluster between two clusters might be handled  

5. the document list shows the sub cluster with the largest number of documents first 
Note: the document list does represent the intended logic however does not match the number of documents in the mock up because that is not necessary to reach the goal of this issue and convey the goal of this design. 

**Questions for you:** 
1. Does the design and the data scheme make sense to you? If not, please say why 
2. Is there something that you need to help you understand the design which is missing here?

**Comment by gissoo** [comment]
@rlskoeser @thatbudakguy Please read the above, and answer the questions. 
Note: I've been trying to reach Figma to request an educational version of Figma but have not been successful yet. I think once we do that and I can make you editors it will be much easier for you to view anything on Figma.

**Comment by thatbudakguy** [comment]
this data scheme seems difficult for us to maintain.

- for a cluster topic, like "Tax", it's not clear to me how to represent it - the object of a document, as you have here? a state or condition of subjects or people (being taxed)? an action (taxing people)? it seems to me that it will likely appear in all of these forms and more, and we will need the context of the document itself to determine which is being used.
- i'm wondering who makes the decisions about how the various cluster topics are categorized. if it's the current PGP team, that's potentially a lot of labor.
- it also seems difficult to defend such decisions in a scholarly context - what resource would we be able to cite in order to prove that "Tax", as a concept, is more "object" than "action" in the context of the PGP? making that argument for one topic alone seems like it would require an entire paper.
- i'm unclear how this data scheme applies when the clusters are not clusters of tags. we've discussed and prototyped assuming that they are, but i think we've also acknowledged many times that the tags are problematic and perhaps not the best starting place for clusters (at least not in their current state).

lastly, on the interface prototypes - i think we might run into a very different issue that @rlskoeser has written about, which is that representing more than a few overlapping categories using a 2d visualization is very difficult. in the prototypes, it looks as though clusters are represented as 2d shapes (circles or "blobs") which overlap when they share subclusters or documents. the problem is that for any number of clusters larger than about 4 or 5, it rapidly becomes impossible to generate a shape that intersects in the correct way for all the clusters. unfortunately, i think this problem is rooted in mathematics and thus unavoidable. there has been some work on how to visualize this (@rlskoeser knows more, I think there's something called an UpSet plot?) but visually it looks very different from what I see here, and I'm not sure it would align with how you're thinking of a generous search interface.

**Comment by gissoo** [comment]
> this data scheme seems difficult for us to maintain.
> 
>     * for a cluster topic, like "Tax", it's not clear to me how to represent it - the object of a document, as you have here? a state or condition of subjects or people (being taxed)? an action (taxing people)? it seems to me that it will likely appear in all of these forms and more, and we will need the context of the document itself to determine which is being used.
> 
>     * i'm wondering who makes the decisions about how the various cluster topics are categorized. if it's the current PGP team, that's potentially a lot of labor.
> 
>     * it also seems difficult to defend such decisions in a scholarly context - what resource would we be able to cite in order to prove that "Tax", as a concept, is more "object" than "action" in the context of the PGP? making that argument for one topic alone seems like it would require an entire paper.
> 
>     * i'm unclear how this data scheme applies when the clusters are not clusters of tags. we've discussed and prototyped assuming that they are, but i think we've also acknowledged many times that the tags are problematic and perhaps not the best starting place for clusters (at least not in their current state).
> 

- Thanks for writing, @thatbudakguy !! – I think I would like to talk through this with the Geniza team at a meeting specifically about data – I think anyway we do expect some labor with data as the current tagging system doesn't work and it will be revised – But this is just an example of a model I'm thinking of – I think it would be super helpful to talk through and see how it's best possible to systematize the clusters – a way that would be possible to defend. I also think a lot of the specifics of the interface will depend on our decisions with the data. I'm not sure what would be the best starting place when creating this interface unless we talk about possible approaches with data. What I have proposed is one way that I thought of it. 

> 
> lastly, on the interface prototypes - i think we might run into a very different issue that @rlskoeser has written about, which is that representing more than a few overlapping categories using a 2d visualization is very difficult. in the prototypes, it looks as though clusters are represented as 2d shapes (circles or "blobs") which overlap when they share subclusters or documents. the problem is that for any number of clusters larger than about 4 or 5, it rapidly becomes impossible to generate a shape that intersects in the correct way for all the clusters. unfortunately, i think this problem is rooted in mathematics and thus unavoidable. there has been some work on how to visualize this (@rlskoeser knows more, I think there's something called an UpSet plot?) but visually it looks very different from what I see here, and I'm not sure it would align with how you're thinking of a generous search interface.

- I think visualizations such as the upSet plot doesn't really align with how I have been thinking about this type of interface – there needs to be a balance of it being a data viz and an interface for browsing through documents – so it's not how I have been thinking about it exactly and don't think it's necessary the solution – but your concerns make sense to me, and I think there are more ways I need to explore these.

**Comment by gissoo** [comment]
@thatbudakguy Also, thinking more about it, the reason that I proposed this kind of data scheme is that it's very applicable in some ways (not in every way) – (but it can let us stay away from getting into certain biases) _but_ again your concerns make sense – I also don't know how it would work with the content of the documents, so a conversation would be great

**Comment by rlskoeser** [comment]
@gissoo your data scheme looks interesting, but like Nick I have concerns about how we would actually implement and maintain this.  I can see how the dimensions would add more context to the data ... I think basically I agree with all of Nick's comments about the data scheme.

Can you explain how your proposed data scheme would fit with the new relational database structure? Does it only apply to tags, or would it incorporate other information as well, like people, dates, places?

Previously we discussed other possible ways of clustering documents besides tags, have you considered any other options? Would it help to have someone work with you on exploring & prototyping options?

I remember from your initial goals that the clusters were about making relationships and connections between the documents more visible, and I'm wondering if what you're proposing still does that. In particular, labeling clusters seems like it would lose some of that.

The graph layout you propose is interesting, but I'm also wondering how feasible that is... It suggests to me that there is a _spectrum_ of how human- or object- centric a particular tag is (same for action/state), but tracking the information that would let us plot things this way would make the tag/cluster management even more challenging.

I'm open to discussing your proposed data scheme with the team, but I'd like to hear more about how it fits with the relational database and whether you've considered other approaches for generating and managing clusters.

**Comment by gissoo** [comment]
@rlskoeser thanks for writing!! 

> @gissoo your data scheme looks interesting, but like Nick I have concerns about how we would actually implement and maintain this. I can see how the dimensions would add more context to the data ... I think basically I agree with all of Nick's comments about the data scheme.
> 
> Can you explain how your proposed data scheme would fit with the new relational database structure? Does it only apply to tags, or would it incorporate other information as well, like people, dates, places?
> 

- No, what I'm proposing is strictly for tags or whatever they would be called (whatever that will make up a cluster) and nothing else. 

> Previously we discussed other possible ways of clustering documents besides tags, have you considered any other options? Would it help to have someone work with you on exploring & prototyping options?
> 

- I should go back and refresh on what the other possible ways were. 

> I remember from your initial goals that the clusters were about making relationships and connections between the documents more visible, and I'm wondering if what you're proposing still does that. In particular, labeling clusters seems like it would lose some of that.
> 

- I totally agree, that's why I am unsure about the variation with labels – It doesn't need to have a label as I have mentioned in my notes. 

> The graph layout you propose is interesting, but I'm also wondering how feasible that is... It suggests to me that there is a _spectrum_ of how human- or object- centric a particular tag is (same for action/state), but tracking the information that would let us plot things this way would make the tag/cluster management even more challenging.
> 

- yes I have been unsure about the graph in general – but mainly exploring ways of systematizing the data. 

> I'm open to discussing your proposed data scheme with the team, but I'd like to hear more about how it fits with the relational database and whether you've considered other approaches for generating and managing clusters.

- can you ask me some specific questions when you say "how it fits with the rational database"? It would help me understand what aspects of it you're talking about.

**Comment by rlskoeser** [comment]
>   Can you ask me some specific questions when you say "how it fits with the rational database"? It would help me understand what aspects of it you're talking about.

If you're only thinking of including tags then this wouldn't interact with the rest of the relational database, so my question is irrelevant. But if that's the case, it seems like it might be kind of a loss?  (IDK, or maybe it will simplify things.) Existing tags for names and places will become person records in the database.

**Comment by gissoo** [comment]
> > Can you ask me some specific questions when you say "how it fits with the rational database"? It would help me understand what aspects of it you're talking about.
> 
> If you're only thinking of including tags then this wouldn't interact with the rest of the relational database, so my question is irrelevant. But if that's the case, it seems like it might be kind of a loss? (IDK, or maybe it will simplify things.) Existing tags for names and places will become person records in the database.

hmm ...:exploding_head: waste in the sense that we won't be able to reuse the current tags? Let me give this some fresh thought next week – clearly was trying to simplify this, but that might be an illusion and also wasn't thinking of sustainability – feeling strongly though that places and dates don't make sense with the clusters ...I'll give it thoughts next week – thank you for writing!! Super helpful!!

**Comment by rlskoeser** [comment]
@gissoo small clarification: my comment about it being a possible loss is because there would potentially be a lot of information we have about the documents that wouldn't be included in the clusters. However, maybe that would actually simplify the clustering and tagging so it can be more concentrated on themes and contents instead of the other information currently included in tags (like names and dates). 

One more thought: would allowing tags to be hierarchical help with the clustering? That seems like it would be simpler to maintain (and something I think the team is already considering) than the more complicated scheme you proposed, but IDK how much it helps with the clustering. (Maybe it helps with redundant/overlapping tags.)

**Comment by gissoo** [comment]
> @gissoo small clarification: my comment about it being a possible loss is because there would potentially be a lot of information we have about the documents that wouldn't be included in the clusters. However, maybe that would actually simplify the clustering and tagging so it can be more concentrated on themes and contents instead of the other information currently included in tags (like names and dates).
> 

@rlskoeser Thanks for writing!! This makes a lot of sense and I agree, also my goal. 

> One more thought: would allowing tags to be hierarchical help with the clustering? That seems like it would be simpler to maintain (and something I think the team is already considering) than the more complicated scheme you proposed, but IDK how much it helps with the clustering. (Maybe it helps with redundant/overlapping tags.)

- I think it largely depends on how it's done – it could be helpful with overlapping tags, I could also see it as defeating the purpose of this vision only if not done right. Would love to discuss with the team.
