### ISSUE TITLE
Require a commit message string to enable Percy in PR commits

### ISSUE THREAD

**Issue by blms** [Princeton-CDH/geniza#513]
- Add a conditional to workflows to only do the visual testing CI step if `[run percy]` is in the commit message, only in PRs. 
- In push to `develop`, allow skipping with `[skip percy]`

**Comment by blms** [comment]
@rlskoeser Looks like the push to `develop` without a special message worked, so feel free to close this once you test `[skip percy]`.

**Comment by rlskoeser** [comment]
@blms I tried adding the `[skip percy]` directive to a PR merge commit here https://github.com/Princeton-CDH/geniza/commit/952ee9587df97f6ffdf99ac839ea56b1126b2f88

 — but the percy workflow still ran.

Would you expect this to work? Did I do anything wrong?

**Comment by blms** [comment]
@rlskoeser Huh! That looks right, and it should have worked. I'll take a look.

**Comment by blms** [comment]
@rlskoeser I made a small alteration and it worked on a direct push to `develop`. Let's see if it also works on next merge commit, otherwise I'll revisit. I may need to add a special case for that to the `get_commit_msg` job.

**Comment by rlskoeser** [comment]
great, thanks  — I'll test again the next time I merge a PR

**Comment by rlskoeser** [comment]
success!
