### ISSUE TITLE
As a global admin, I want a one-time import of the list of library collections that includes name, abbreviation and location, so that I can manage the library collection info in the database.

### ISSUE THREAD

**Issue by sluescher** [Princeton-CDH/geniza#52]
## testing notes

- Confirm that the list of libraries/collections has been correctly imported from the ontology spreadsheet
- Check that the edit history for a few records to confirm that there is a log entry showing the record was imported by script

**Comment by rlskoeser** [comment]
@sluescher please confirm, should I be using the Libraries file in the ontologies directory in Google Drive? If so, is it ok if I publish to the web as CSV and use that for import? Alternatively I could download it as csv file if you don't expect any further changes.  

Also, do I need to do anything with the **Current List of Libraries** column?

**Comment by sluescher** [comment]
Current List of Libraries is the info currently in the PGP spreadsheet in the column "Library." It is there as the checking list.

I think it should be fine to publish it (I'll double check with Marina). There might be changes happening.

Once we upload the metadata spreadsheet, will it be possible to link library and document automatically according to the library column?

**Comment by rlskoeser** [comment]
@sluescher ah, I see — the first column is how they appear in the sheet now (mixture of names and abbreviations), and the other fields are how they should be listed in the database. 

Yes, we can use the Library sheet both to populate the fields in the database and as a lookup to match the libraries as listed in the sheet to the new versions in the database.

**Comment by rlskoeser** [comment]
@sluescher sorry, more questions! I think both name and abbreviation should be required and unique, does that sound right? 

What should I do with the "ENA (should be JTS)" in your Libraries spreadsheet?

**Comment by sluescher** [comment]
Well, ENA is in the library column, but it shouldn't be because it's part of the shelfmark, not the library. It should be JTS (Jewish Theological Seminary). So we need to correct that. I will set someone on it.

**Comment by rlskoeser** [comment]
@sluescher we can convert ENA to JTS on import if it's consistent, no need to have someone make those changes manually

**Comment by sluescher** [comment]
I will check how many instances there are (might also a good way of seeing whether there's other issues with the record). If it's 1 or 2, it's not a big deal. If it's a bunch of them, I will happily rely on the conversion

**Comment by sluescher** [comment]
It is only one instance. taking care of it.

**Comment by sluescher** [comment]
✓ Confirm that the list of libraries/collections has been correctly imported from the ontology spreadsheet
✓ Check that the edit history for a few records to confirm that there is a log entry showing the record was imported by script

At least one spelling mistake, but I assume that was imported 😆

**Comment by sluescher** [comment]
Checked with @mrustow and Rachel. All good!
