### ISSUE TITLE
As a front-end user, I should not be able to sort by relevance without any search text, since relevance is not meaningful without search terms.

### ISSUE THREAD

**Issue by blms** [Princeton-CDH/geniza#523]
## testing notes
- [x] try making a search with no query text, and "relevance" selected for the sort option, and confirm that an error appears in the form
- [x] comment any thoughts on the design of the error display
- [x] compare with the following behavior and comment any thoughts:

> On the [prosody archive search](https://prosody.princeton.edu/archive/) we implemented js logic to disable/enable relevance, and automatically switch the sort to relevance when you start typing a search term, but preserve your sort if you change it — which I know is kind of complicated, and should not be MVP. Maybe we could have Gissoo do some usability testing on the two searches with regard to sort behavior to help figure out what would help users most.

_Originally posted by @rlskoeser in https://github.com/Princeton-CDH/geniza/pull/534#pullrequestreview-858429524_

## dev notes

Possible solutions:

- JS to check for input into the search box; if not present, disable "relevance"
- make the search box input a required field when "relevance" is selected

**Comment by gissoo** [comment]
@blms @rlskoeser 
- the error message appears in the form
- the error message looks fine, but it doesn't have to display "Errors:" for those looking at the screen – you can just display the message. 
- you have written: "On the prosody archive search we implemented js logic to disable/enable relevance, and automatically switch the sort to relevance when you start typing a search term, **but preserve your sort if you change it** — which I know is kind of complicated, and should not be MVP. Maybe we could have Gissoo do some usability testing on the two searches with regard to sort behavior to help figure out what would help users most." – by "but preserve your sort if you change it" you mean preserve the "relevance" ? Let me know – Sure I can reach out to the ux office for a quick usability testing on it 
- I wish "Relevance" would not even be an option when there is no query text

**Comment by blms** [comment]
@gissoo Thanks!

> the error message looks fine, but it doesn't have to display "Errors:" for those looking at the screen – you can just display the message.

Good call, I'll leave this issue open until implementing that.

> by "but preserve your sort if you change it" you mean preserve the "relevance" ?

No, it will automatically choose "relevance" when you start typing some text—but if you change it away from "relevance" after typing text, then it should preserve your choice.

It actually seems like the Prosody Archive search isn't working quite as described. It does have "relevance" disabled when there is no text. But then once you have entered text, it seems to always change back to "relevance" when you edit the search text, even if you changed it to something else before.

> I wish "Relevance" would not even be an option when there is no query text

That's how the Prosody Archive does it, and then it automatically chooses "relevance" when you enter text because it might be confusing to users that they would have to change it once they entered text. This strongly assumes that "relevance" is the desired sort option, but it probably is when you're entering a query, at least at first!

We can definitely go with that approach after MVP if you and the UX office agree on it.

**Comment by rlskoeser** [comment]
> It actually seems like the Prosody Archive search isn't working quite as described. It does have "relevance" disabled when there is no text. But then once you have entered text, it seems to always change back to "relevance" when you edit the search text, even if you changed it to something else before.

IIRC our assumption was that if you _changed_ your keyword search terms you would still (again) want to see the most relevant results first. But I do remember it being something we discussed a fair bit, and we should have probably thought about usability testing on it before.

@blms @gissoo I can't tell from the comments, what is needed to address concerns for the short term? Is this resolved, or just needs to be reviewed again after the latest PR?

**Comment by blms** [comment]
@rlskoeser For MVP I think we just need to confirm that the "Errors:" header doesn't display (on redeploy).

Not sure what to do with this issue, maybe it should branch into another for post-MVP so we can close this one.

**Comment by blms** [comment]
Confirmed on QA site, moving remaining discussion into #550.
