### ISSUE TITLE
Design an "active filter" indicator for the search form

### ISSUE THREAD

**Issue by blms** [Princeton-CDH/geniza#524]
Originally posted by @gissoo in https://github.com/Princeton-CDH/geniza/issues/449#issuecomment-1011518093:
> Also, we should eventually add a visual signifier to show when there are active filters for when the filter is collapsed right now (or hidden as the original designs in Figma show)

**Comment by rlskoeser** [comment]
work completed; asset added to git & specifics communicated for implementation
