### ISSUE TITLE
As a global admin, I want to be able to add a library collection not represented on the list in order to expand our content footprint and edit those already in the list.

### ISSUE THREAD

**Issue by sluescher** [Princeton-CDH/geniza#53]
## testing notes
log in on an account with **Content Admin** group permissions
- [x] list view should include library, collection name, library abbreviation, abbreviation, location
- [x] should be able to edit existing records or add new one
- [x] should be able to save a record with collection name but no library
- [x] should be able to save a record with library but no collection name
- [x] should not be allowed to save a record with both collection name and library empty
- [x] should be able to delete an existing record
- [x] should be able to add a new record
- [x] if you try to enter a collection with a library + collection combination that already exists, you should get an error

log in on an account with **Content Editor** group permissions
- [x] should be able to view collections but not add, edit, delete

---
For example, when new collections become available or there are name changes.

**Comment by rlskoeser** [comment]
@sluescher in my draft db diagram I had the fields name, code, and url. I think based on your wording code should be abbreviation. Do you want the url field so that we can (eventually) link to libraries, or should I leave it out?

**Comment by sluescher** [comment]
Yes, please with url!

**Comment by sluescher** [comment]
Add the fields "Collection" (text, optional) and "Locations" (text).

**Comment by sluescher** [comment]
Question: do we want Collection abbreviation?

**Comment by rlskoeser** [comment]
@mrustow @sluescher we decided yesterday we only need a single abbreviation.  One more question: do you still want to call this "Library" or should it be called "Collection" ? Looking at your list, I think Collection might be a little clearer (especially for the one collection held jointly by two libraries), but I think either is fine. I just want to make sure to call it whatever makes the most sense to you.

**Comment by sluescher** [comment]
But then we have a library with multiple collections. I do think Collections might be a more dynamic term than library, which feels stiff. This is for how we call the entity?

**Comment by rlskoeser** [comment]
Yes, this is for the name of the entity. That's another good reason to go with Collection instead of Library — there are some libraries with more than one collection

**Comment by sluescher** [comment]
✓ list view should include abbreviation, library, location, and optional collection name
✓ should be able to edit existing records or add new one; collection name should be optional
✓ should be able to delete an existing record
✓ (is included in #2 but works) should be able to add a new record
✓ if you try to enter a collection with an abbreviation that already exists, you should get an error
✓ if you try to enter a collection with a library + collection combination that already exists, you should get an error

Passes the test with flying colors 🌈.

**Comment by sluescher** [comment]
Functionalities checked with @mrustow and Rachel: green light.

Notes:
- Add a cancel button to the save buttons when editing or adding a record.
- Abbreviations should not be case-sensitive and unique.

**Comment by rlskoeser** [comment]
@sluescher thanks for following up. In regard to your notes:

- If you don't want to save when editing or adding a record, you can use the browser back button.
- Can you elaborate on the point about abbreviations? That seems like something we need to address before considering this accepted.

**Comment by sluescher** [comment]
Should I put it on the agenda for Thursday? Or do we want to slack on it?

**Comment by rlskoeser** [comment]
@sluescher ok, so abbreviations entered in different case are currently treated as unique and they shouldn't be. Thanks for catching that. 

To correct this, would it work for us to convert all abbreviations to upper case? Or is it better if we preserve case as entered and adjust the unique validation so it is not case-sensitive?

**Comment by sluescher** [comment]
This is a question I'd like to discuss with @mrustow. Will get back to you!

**Comment by rlskoeser** [comment]
Documenting decision from Marina:
> I would prefer to preserve case as entered and adjust the unique validation so it is not case-sensitive.

**Comment by sluescher** [comment]
I think we have messed the unique part up. Sorry :( The libraries section has undergone some modifications... I wanted to put it on the list for next week's meeting, but we could do it via slack

**Comment by rlskoeser** [comment]
Increasing estimate from 2 to 3 to account for needing to differentiate library/collection on import for some CUL collections based on shelfmark.

**Comment by rlskoeser** [comment]
@richmanrachel Stephanie tested an earlier version of this, but given all the changes we've made since then, I think nearly all of it needs to be tested again. (The permissions haven't changed, so I don't think you need to test that part)

**Comment by richmanrachel** [comment]
It all works! I would just recommend making "Name" -> "Collection Name" for total clarity.
