### ISSUE TITLE
Improving txt file download on frontend especially in relation to line numbers.

### ISSUE THREAD

**Issue by richmanrachel** [Princeton-CDH/geniza#530]
**Is your feature request related to a problem? Please describe.**
This is a continuation of the work in #434. We are creating a temporary txt file download to allow researchers to copy/save transcriptions from the website to their own computers for research purposes. 

The problems we've run into:
1) Adding line numbers is a necessity, but messes up the RTL encoding (don't know if that's the right word?)
2) Adding line numbers also creates problems for searching transcription phrases that go over line breaks

**Describe the solution you'd like**
Try to figure out a way for line numbers to be downloaded but not mess up search results or text direction. 
Open to however we can accomplish this for MVP

**Comment by kseniaryzhova** [comment]
Irrelevant, closing!
