### ISSUE TITLE
As an admin, if I change a document I want the log entries to be correctly associated with the document.

### ISSUE THREAD

**Issue by blms** [Princeton-CDH/geniza#537]
## testing notes (QA)

- [x] In the admin panel: make changes to a document, save those changes, and check the [Log Entries](https://test-geniza.cdh.princeton.edu/admin/admin/logentry/). Confirm that your change is there, then click on the link in the log entry and confirm it takes you to the correct document.
- [x] Test that you can delete a document or multiple documents from the admin panel without receiving a permissions error

Previously, because of some workarounds we did, log entries were being associated with a model called "documentprefetchableproxy" instead of Document, and they were not correctly linking to the document that was changed.

---

## dev notes

- [x] ~~Remove `DocumentPrefetchableProxy` model~~
- [x] ~~Replace with `GenericRelation` reimplementation that overrides `__init__`~~
- [x] ~~Inherit everything else from [existing `GenericRelation`](https://github.com/django/django/blob/2c76c27a951ee76c6f763a05c7e119305a21c78d/django/contrib/contenttypes/fields.py#L275)~~
- [x] add a unit test to check the admin delete page — it shouldn't display the text about not having permissions
- [x] Data migration to change all `LogEntries` that were attached to `DocumentPrefetchableProxy` instances to go to the correct `Documents`
- [x] Consider implications for #498

**Comment by richmanrachel** [comment]
Still getting errors when trying to delete :( 
![image](https://user-images.githubusercontent.com/68028846/151249673-dcda7bcd-2123-4cac-ba13-43cec5c38b69.png)

**Comment by richmanrachel** [comment]
Oh, but it's actually the whole site for me right now!

**Comment by richmanrachel** [comment]
Success on both counts! Closing :)
