### ISSUE TITLE
As a global admin, I want to be able to add and edit a language, script, or correlation between language and script in our ontology, in order to expand our content footprint.

### ISSUE THREAD

**Issue by sluescher** [Princeton-CDH/geniza#54]
## testing notes
log in on an account with **Content Admin** group permissions
- list view should include language, script, and optional display name
- should be able to edit existing records or add new one; display name should be optional
- should be able to delete an existing record
- if you try to enter a language + script combination that already exists, you should get an error

log in on an account with **Content Editor** group permissions
- should be able to view languages and scripts but not add, edit, delete

-----
1) Adding a new language or script or correlation (for example, Georgian or Arabic in Greek script); 2) Editing a language or script already in the list, or the correlation between them.

**Comment by kmcelwee** [comment]
Hi @sluescher! 

* Do you want a field for vocalizations on the language? Or would you like to tie that information to the document itself?
* If it helps I've attached a document of all the unique languages in the metadata spreadsheet here: [https://app.zenhub.com/files/297446715/7fa07f30-749e-4a10-8164-544fb055f325/download](https://app.zenhub.com/files/297446715/7fa07f30-749e-4a10-8164-544fb055f325/download)

We were thinking of having our Language object structure to be something like:
* name (optional)
* script (required)
* language (required)

Where in displays we'd combine the script and language field unless it's overwritten by the "name" field. Could I just get the all clear that that system makes sense and would be a good workflow?

If it's easier to explain over zoom, feel free to reach out!

**Comment by sluescher** [comment]
Hi @kmcelwee!

This is the "ontology" of languages and scripts that we compiled: [link](https://docs.google.com/spreadsheets/d/1m-6SWU2gSNcferuU4Uzri2IQLUSbj3U5voas0xCofOQ/edit?usp=sharing). We do want vocalization. 

Language and script would be tied together. What do you mean by "overwritten by the "name" field"?

**Comment by kmcelwee** [comment]
@sluescher 

Great! I'll include vocalization in the Language admin.

To make automated ingestion more straightforward, I've separated out the vocalizations into different rows in the sheet. Please double check that my edits were appropriate.

And then "name" would be a display name (I'll actually change the field to "display name" to make it more clear). When a language is shown to a user, we might auto-generate something like:
```
Judaeo-Arabic (Hebrew script, Tiberian vocalization)
```
But I know that Hebrew script is implied, so we'd give you the option of overriding the autogenerated display text to whatever you prefer. Does that make sense? Is the format above appropriate? I can forward along the python logic if you'd like

**Comment by rlskoeser** [comment]
@sluescher I'm a little concerned about including vocalization in the Language/Script table — I think it will make it more difficult for content editors, since they'll have to read and select the correct combination of three things instead of two  (although in your current list there are only two variants with vocalization, so it might not be too bad). I just wondered if it would make more sense to track that at the document level. When I asked Kevin how many records currently have vocalization, he reported:
> 8941 PGPIDs have language listed, 227 of them include the word “vocalisation" 

From my review of the list Kevin shared yesterday, I'm unclear on how the vocalisation notes in the current spreadsheet match the new language/script ontology — perhaps a vocalization note would be useful to capture this information? (Unless you don't care about it)

Could you explain more about what you want to do with the vocalization field? Are you concerned about controlling data entry for consistency, do you expect to do analysis or filtering on the basis of it? 

Also, what is the "number" field in the spreadsheet, and do we need to do anything with it?

**Comment by sluescher** [comment]
I think we want the vocalization as a variant, but it can be separate from the language/script duo. As long as there's a way to capture it in case a scholar further ahead plans on doing research on it.

Number can be ignored for import.

**Comment by sluescher** [comment]
Good morning! Where do I find the access info to log-in as content editor? I logged in with my account (which I assume should be Admin), but I cannot do any of the below (so I guess I am set to editor?)
- should be able to edit existing records or add new one; display name should be optional
- should be able to delete an existing record
- if you try to enter a language + script combination that already exists, you should get an error

**Comment by rlskoeser** [comment]
Drat! I have you as a member of the content admin group, but it looks like the permissions for that group are set incorrectly (they're the same as content editor). I will investigate and correct.

**Comment by rlskoeser** [comment]
@sluescher I've corrected the permissions for the content editor group. Please try again.

**Comment by sluescher** [comment]
**Content admin**
All works!
✓ list view should include language, script, and optional display name
✓ should be able to edit existing records or add new one; display name should be optional
✓ should be able to delete an existing record
✓ if you try to enter a language + script combination that already exists, you should get an error

<img width="592" alt="Screen Shot 2021-02-17 at 9 58 27 AM" src="https://user-images.githubusercontent.com/30683720/108223037-5fbf1480-7107-11eb-8c64-621f3e1d10bf.png">

**Content editor**
All purrfect!

**Comment by sluescher** [comment]
@mrustow to log in on the [site](test-geniza.cdh.princeton.edu/) as content editor, use 
username: majhul
password: cdhpgp2021!

**Comment by mrustow** [comment]
Worked like a charm.
