### ISSUE TITLE
Percy loads IIIF images incorrectly in snapshots using OpenSeadragon

### ISSUE THREAD

**Issue by blms** [Princeton-CDH/geniza#558]
## dev notes

Percy loads IIIF images incorrectly when using OpenSeadragon, such that they seem to have a max-width applied.

<img width="483" alt="Screen Shot 2022-02-28 at 2 34 54 PM" src="https://user-images.githubusercontent.com/7234006/156047108-2b6c2a86-2eba-4273-ae39-78b3faf2507a.png">

**Comment by blms** [comment]
Looks like this succeeded, at least partially, on merge:
https://percy.io/2cf28a24/geniza/builds/15365758

Though it still did not pick up the IIIF image.

**Comment by kseniaryzhova** [comment]
@blms confirm if we can close?

**Comment by blms** [comment]
@kseniaryzhova Yup, this appears to be fixed now!

https://percy.io/2cf28a24/geniza/builds/22990951
