### ISSUE TITLE
As a global admin, I want a one-time import of the list of all languages and scripts, and their correlation, so that I can access, display and manage the information in the database.

### ISSUE THREAD

**Issue by sluescher** [Princeton-CDH/geniza#56]
## testing notes

- Confirm that the list of languages + scripts has been correctly imported from the ontology spreadsheet
- Check that the edit history for a few records to confirm that there is a log entry showing the record was imported by script

**Comment by sluescher** [comment]
- [x] Confirm that the list of languages + scripts has been correctly imported from the ontology spreadsheet
- [x] Check that the edit history for a few records to confirm that there is a log entry showing the record was imported by script

Confirmed and checked!

**Comment by sluescher** [comment]
Forgot that @mrustow has to have a look at it. My bad.

**Comment by mrustow** [comment]
Smooth sailing. You're stars. 🤩
