### ISSUE TITLE
Design an annotated image for the FAQ page so we can help inform users how to understand the document detail page

### ISSUE THREAD

**Issue by richmanrachel** [Princeton-CDH/geniza#576]
_This issue tracks design work through the [CDH design review workflow](https://princeton-cdh.github.io/docs/workflows/#workflow-5)._

Here is a link to the FAQ mock up: https://docs.google.com/document/d/1kUA-xgbG1BlL3uY9XDOKBd3mnEHFAdkEsHM-V1tWkQc/edit#heading=h.8lti09ha4npt

**Description:**
We would like to have an annotated image of a Document Detail page to help new PGP users understand what information we've included and where.

**How the proposal/idea can fail:** 
I don't know if/how an annotated image can be accessible for screen readers.

**Comment by kseniaryzhova** [comment]
@blms closing, we're better served using videos to explain the function of the doc detail page.
