### ISSUE TITLE
As a frontend user, when the term "See PGPID ___" appears, I would like it to link to the corresponding PGP document so that I can easily access referenced documents.

### ISSUE THREAD

**Issue by richmanrachel** [Princeton-CDH/geniza#578]
## testing notes (qa)

- [x] On the QA public site, visit a document detail page for a document with "See PGPID ___" in the description, and confirm it links to the referenced document

---

**Is your feature request related to a problem? Please describe.**
Rebecca rightfully pointed out that we use this language both for future merges as well as for related documents. This will help users more easily navigate to the page where better or related information exists. 

**Describe the solution you'd like**
Automatic link when "See PGPID ___" appears

## dev notes
- [x] create a new template filter; propose name `pgp_urlize` since we may eventually add support for shelfmarks also; use a regex to do a global search for `PGPID (\d+)` (maybe with word boundaries on both sides); use the captured digit to generate a url to the PGP document in question, and turn the text into a link
- [x] apply the template to the description text on the document detail page
- [x] unit test cases: one id, two ids, id coming directly before a period or comma

**Comment by richmanrachel** [comment]
@rlskoeser - It works, but something is going wrong... there are only 2 documents being pulled by the search "see pgpid" on the front end, while there are 193 on the admin site (180 of which are public)

**Comment by rlskoeser** [comment]
@richmanrachel is it possible you have some search filters applied that are limiting your results?

**Comment by richmanrachel** [comment]
@rlskoeser was right. It's working!
