### ISSUE TITLE
As a content editor, I want to be able to underline text in the Wagtail CMS.

### ISSUE THREAD

**Issue by blms** [Princeton-CDH/geniza#580]
## testing notes (QA)
From the [QA Wagtail admin](https://test-geniza.cdh.princeton.edu/cms):
- [x] edit a page and try adding an underline with the toolbar button and with the keyboard shortcut
- [x] edit a page and try adding two blockquotes next to each other. click "preview" and confirm that the close quote and open quote are separated
- [x] create a new page, go to the "promote" tab and confirm it is set to appear in menus

## dev notes

- [x] Add underline style using `mark` elements

Can also roll in the following tweaks:
- [x] Remove embed option until/unless we have a design for it
- [x] Set new content pages to appear in menu by default
- [x] Fix bug with back-to-back blockquotes (edge case but easy enough to fix)

**Comment by richmanrachel** [comment]
@blms - looks perfect!
