### ISSUE TITLE
As a content editor, I want to be able to separately define alt text and caption for images in Wagtail.

### ISSUE THREAD

**Issue by blms** [Princeton-CDH/geniza#581]
## testing notes (qa)
- [x] From the [QA Wagtail admin](https://test-geniza.cdh.princeton.edu/cms), edit a page and confirm you can add an image block with captions and alt text

**Comment by richmanrachel** [comment]
@blms - it may just be my image type/file size, but it didn't work :(

**Comment by blms** [comment]
@richmanrachel What happened when you tried? (A screenshot or video would help if you can't easily describe!) And @rlskoeser I'm wondering if this is a config or code issue… it might be the former if it's just the upload that's failing.

**Comment by rlskoeser** [comment]
@blms ooh good call, I remember now that we had problems with file sizes on our other app because the defaults are set pretty low. I'll look into it.

**Comment by richmanrachel** [comment]
@blms and @rlskoeser - would you like me to add screenshots/a more detailed description, or would you like to check on file size first?

The process did seem to work (in terms of being able to select jpgs from my desktop) but the broken image icon was present once I uploaded and again on the site page.
![image](https://user-images.githubusercontent.com/68028846/153266349-56343333-aac8-408f-bb41-ccc7f9160b3e.png)

**Comment by rlskoeser** [comment]
@richmanrachel oh, sorry! I'm looking into this — I think there's a server configuration missing, which is why you aren't seeing the images. I'm working on the change

**Comment by blms** [comment]
@richmanrachel Thanks for the screenshot anyway! It also exposed the "{'paragraph': '" there, which shouldn't be present—at least not visible to the user. So we may have to do some troubleshooting on that too. I assume it's not visible in the text while you're editing it?

**Comment by richmanrachel** [comment]
@blms - It is actually in the text:
![image](https://user-images.githubusercontent.com/68028846/153267378-12ff06b1-1b65-4e69-9660-4550cf7f0f96.png)
I'll try deleting just to make sure

**Comment by richmanrachel** [comment]
Yes - confirmed that the image still isn't working but wonky paragraph text was deletable :)

**Comment by blms** [comment]
@richmanrachel Ah! Okay, that's a relief 😄  It may be a side effect of the migration we did.

**Comment by rlskoeser** [comment]
@richmanrachel I think I've configured the upload directory properly now on the test site (although I have not increased the default file size limits); please test the image upload and image caption again when you can.

**Comment by richmanrachel** [comment]
Great! I didn't even have to upload a smaller image - when I reloaded, it worked!
![image](https://user-images.githubusercontent.com/68028846/153277514-70e732ac-a17e-4b5a-8b66-2fea64011417.png)

**Comment by blms** [comment]
Should be ready to close then, right? Unless you wanted to test again with a new image @richmanrachel!

**Comment by richmanrachel** [comment]
@blms - very right. Sorry, was caught reminiscing about how cute my friend's baby cousin is, haha
