### ISSUE TITLE
As a content editor, I want to add SVG images to content pages so that I can include data visualizations and other scalable images.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#590]
## testing notes (qa)

- [x] In the [QA Wagtail interface](https://test-geniza.cdh.princeton.edu/cms), edit a content page and add an "SVG" block in the body (instead of "image" or "paragraph"). Confirm that you can upload an SVG image file, add a caption, etc.

## dev notes

Hopefully we can adapt the svg image block directly from mep-django codebase

**Comment by blms** [comment]
Just noticed from the merge Percy screenshots that it looks like the max-width for landscape images has changed, so I'll have to make sure to fix that!
