### ISSUE TITLE
As a content editor, I want to add translations for document types to the database, in order to make the content more accessible to Hebrew and Arabic users of the public site.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#592]
## testing notes (qa)
- [x] In the admin interface, try to edit a Document Type and confirm you can add translations (for both name and display name) in Hebrew and Arabic
- [x] Once you have added some translations, visit a document detail page of a type you translated on the public site, and change your language with the dropdown in the upper right. Confirm that the document detail page now refers to the translated document type in the chosen language

## dev notes
- [x] enable model translation for document type model label and name fields
- [x] update string method if needed (will automatically return field for current language?)
- [x] update document detail page to use translated document type label (if any change is needed)
- [x] index english document label in solr (for now)
- [x] update any test fixtures to explicitly reference the en document type

(updating search page and search results to use translations will be handled separately)

**Comment by richmanrachel** [comment]
@rlskoeser - I was able to input translations, but when I clicked "save" the browser seemed to take forever to load and I eventually got this error message:
![image](https://user-images.githubusercontent.com/68028846/156224111-ab55f287-4624-4e4b-80ff-4db520b01151.png)

**Comment by richmanrachel** [comment]
Just reloaded the page to try again, and I guess it did save:
![image](https://user-images.githubusercontent.com/68028846/156237617-7c4807f9-40f4-4285-8b99-14e313a370a2.png)

**Comment by rlskoeser** [comment]
@richmanrachel I was wondering if it was a transitory error but haven't had time to test — would you mind trying again?

**Comment by richmanrachel** [comment]
@rlskoeser - I tried to add the translations for List or Table and it was still loading incredibly slowly and then gave me the 405 error message.

**Comment by rlskoeser** [comment]
@richmanrachel oh! I think I know what's happening... Although I'm not sure about a solution.

We have signals configured so that documents will be automatically reindexed in Solr so changes will be available for the public search if any of the related content in the database changes. Saving a document type means that all of the associated documents get reindexed in Solr — which, for the larger types, could be a noticeable amount of time.

I think we still want that behavior, and you shouldn't be editing these all that frequently — so maybe it's acceptable. What do you think?  We could add a warning to the list or edit view if that would help.

**Comment by richmanrachel** [comment]
@rlskoeser - agree, it shouldn't happen frequently, and since it does end up saving it's probably okay?

**Comment by richmanrachel** [comment]
@rlskoeser - I felt comfortable closing, but we should at least warn Itay and others who will be editing langauges.

**Comment by rlskoeser** [comment]
@richmanrachel that makes sense to me — thank you
