### ISSUE TITLE
As a content admin, I want to be able to see which transcriptions belong with which footnote.

### ISSUE THREAD

**Issue by blms** [Princeton-CDH/geniza#596]
## Testing notes

In the admin interface, navigate to a document that has multiple transcriptions (such as PGPID 5555) and confirm:
  - [x] Both transcriptions are preceded by source citations
  - [x] It is clear which source belongs to which transcription

---

@rlskoeser - Labeling all transcriptions would be a huge help. I think we've discussed this before, but knowing which footnotes are "empty" vs. "linked to content" would certainly prevent many future mistakes!

_Originally posted by @richmanrachel in https://github.com/Princeton-CDH/geniza/issues/225#issuecomment-1034082821_

I did a test of merging two records with two different transcriptions (PGPID 516 and 4414) to see what happened. I see that both transcriptions were successfully preserved in the "Transcription" section, but on the resulting merged document record it's not clear which transcription belongs with which footnote. Maybe the editor information (in this case Gil for the Arabic-script one and Friedman for the Hebrew-script one) should be more closely linked to the transcription itself, and displayed together with it? 

_Originally posted by @alanelbaum in https://github.com/Princeton-CDH/geniza/issues/225#issuecomment-1033081856_

**Comment by richmanrachel** [comment]
@blms and @rlskoeser - this works properly, but is it possible to display the transcriptions side-by-side?

**Comment by blms** [comment]
@richmanrachel Yes, that should be possible! I'll make a new issue for it.
