### ISSUE TITLE
As a front end user, I want to see all transcriptions expanded by default when viewing a document.

### ISSUE THREAD

**Issue by blms** [Princeton-CDH/geniza#597]
## testing notes (qa - round 2)

- [x] Visit a document detail page for a document with multiple transcriptions, e.g. https://test-geniza.cdh.princeton.edu/en/documents/5555/ and confirm editions/authors stand out properly in the transcriptions view

---

## testing notes

- [x] Visit a document detail page for a document with multiple transcriptions, e.g. https://test-geniza.cdh.princeton.edu/en/documents/5555/ and confirm that both transcriptions are possible to read, and not collapsed (i.e. you don't have to click an arrow to show them)
- [x] Confirm that you can collapse and expand them by clicking the arrow next to the source citation
- [x] Comment feedback about the expand/collapse ability, intended to help you view each transcription individually side by side with the images; thoughts about clarity of which transcription is associated with which source record; separation of the two transcriptions; etc. This will help Gissoo with coming up with a design for multiple transcriptions.

---

both transcriptions are collapsible, I thought that would make it easier (as a preliminary solution) to let you look at either transcription side by side with the image. (maybe the second one shouldn't be collapsed when there's no image; or maybe not at all...) I found it hard to make it clear that there is more than one! 

_Originally posted by @rlskoeser in https://github.com/Princeton-CDH/geniza/issues/225#issuecomment-1033099103_

**Comment by richmanrachel** [comment]
@blms and @rlskoeser - This looks great! Only small fix needed is to bold the names of the editions/authors to make them stand out properly.

**Comment by richmanrachel** [comment]
Perfect, closing :)
