### ISSUE TITLE
As a content admin, I want to see multiple transcriptions arranged horizontally, rather than vertically.

### ISSUE THREAD

**Issue by blms** [Princeton-CDH/geniza#608]
## testing notes (qa)

- [x]  In the admin interface, navigate to a document that has multiple transcriptions (such as PGPID 5555) and confirm the transcriptions are arranged horizontally

---

is it possible to display the transcriptions side-by-side?

_Originally posted by @richmanrachel in https://github.com/Princeton-CDH/geniza/issues/596#issuecomment-1039456402_

**Comment by richmanrachel** [comment]
The side-by-side looks great! My only question is about these drop downs for languages:
![image](https://user-images.githubusercontent.com/68028846/154361480-a2f38f60-76dd-4fa3-bd42-c22e90706731.png)
@blms or @rlskoeser - are these part of another issue?

**Comment by blms** [comment]
@richmanrachel yes—I think related to https://github.com/Princeton-CDH/geniza/issues/591… let's close this one for now and I'll add your comment to that one!
