### ISSUE TITLE
As a content admin, I want to search for documents by transcription content so I can work with and export content based on transcription text.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#612]
## testing notes

in the [document admin list](https://test-geniza.cdh.princeton.edu/admin/corpus/document/), try searching on content that only occurs in transcription text and confirm that you get results. You can use the term Marina wanted to search on and export: אצחאבנא

**Comment by richmanrachel** [comment]
@rlskoeser - this is great!

@mrustow - I'm getting 173 results for אצחאבנא: is that what you expected?

**Comment by richmanrachel** [comment]
It looks like Marina isn't online now, and it seems to be working well (getting same results on front and backend), so closing for now.
