### ISSUE TITLE
As a frontend user, I want my search terms to match variant forms of the words I enter so that I can find all related content.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#620]
## testing notes
test using the keyword search on the public site: https://test-geniza.cdh.princeton.edu/en/documents/

- [x] searching on `doodle` should also return results for `doodles` and vice versa (can also test with goods/good)
- [x] exact matches should be returned before partial matches when sorting by relevance 
- [x] variant words should be highlighted in description
- [x] same logic and highlighting should work when searching on the description field (i.e. description:doodle — one exception, shorter documents may skew relevance sorting)

**Comment by richmanrachel** [comment]
@rlskoeser - looks perfect! And extra fun to test with "doodle" now that we can see some of them :)
![image](https://user-images.githubusercontent.com/68028846/154362442-3696e67f-af35-4b1c-9655-fe4ddd0f572e.png)
