### ISSUE TITLE
As a content editor, I want to suppress documents, so that the records are kept updated. 

### ISSUE THREAD

**Issue by sluescher** [Princeton-CDH/geniza#63]
## testing notes
- [x] Change the "Status" on a few documents and ensure that the "public" field on the list view updates properly.
- [x] Filter by status in the list view side bar and ensure that it works properly.

## dev notes
We have similar functionality in ppa, maybe a useful reference: https://github.com/Princeton-CDH/ppa-django/blob/main/ppa/archive/models.py#L285-L293

- [x] add `status` choice field to `Document` with options public, suppressed; set default to public
- [x] make status editable in admin
- [x] make status visible in list view as boolean field (see ppa implementation: https://github.com/Princeton-CDH/ppa-django/blob/main/ppa/archive/models.py#L323-L328)
- [x] enable filter on status in list view

May want to implement #78 in tandem with this one

**Comment by richmanrachel** [comment]
Works perfectly! I'll show this to Marina on Thursday morning, but I think it's safe to close now.
