### ISSUE TITLE
Adjust the site header for the Hebrew site in a way that wouldn't affect the logo's shape 

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/geniza#631]

**Comment by gissoo** [comment]
@rlskoeser @blms for the Hebrew site the edges of the header need to shift to accommodate for the logotype which would be placed on the right, therefore the header will be a different file than what is used on the English site – Wanted to make sure you know about this and you are ok with this. Please let me know.

**Comment by rlskoeser** [comment]
that sounds ok to me

**Comment by blms** [comment]
Yes that should be fine!

**Comment by gissoo** [comment]
The header has been adjusted to fit the logotype. MR and RR loved them. New logo and header files will need to be uploaded for the Hebrew version. (New logo files because of the adjustments that needed to be made to the fade at the far right for the RTL version.) 

Here are the designs: https://www.figma.com/file/anZFStv7zBaVWnFxr95nKt/Work-in-Progress-%2F-WIP?node-id=936%3A20491
