### ISSUE TITLE
Copy-pasting transcriptions from the public site results in extraneous whitespace

### ISSUE THREAD

**Issue by blms** [Princeton-CDH/geniza#632]
## Bug description
When copying transcription text from the public site and pasting it into an application such as MS Word or the Notes app, extraneous tab indents are inserted on each line.

**To reproduce**
1. Visit a document description page that includes a transcription
2. Scroll down to the transcription
3. Select and copy the text of the transcription
4. Open Microsoft Word, or the Notes app on Mac
5. Paste the transcription text and see extra tab indents

## dev notes

- possibly need to swap out the element used for each line
- also uses bullets instead of line numbers
- there is also different behavior when selecting a header with transcription text, or just transcription text
- could be solved with a one-click copy button
- could use an existing stimulus clipboard component

**Comment by kseniaryzhova** [comment]
Fixed with new transcription editor, closing!
