### ISSUE TITLE
As a front-end user, I want visual indicators for filtering search results, in a separate panel from the main search functions, so that I know where they are and can easily ignore them if I do not want to filter.

### ISSUE THREAD

**Issue by blms** [Princeton-CDH/geniza#633]
## testing notes (qa - round two)

On the document search page, click the "Filters" button and confirm:
- [x] the "close" button has the correct focus style (on mobile)
- [x] either the individual filter option focus styles are OK (per [comment](https://github.com/Princeton-CDH/geniza/issues/633#issuecomment-1051031596)), or they are not, in which case please create a design issue

## testing notes (qa)

On the document search page, click the "Filters" button and confirm:
- [x] Alignment, spacing, and colors are correct
- [x] Visual result of clicking on each filter is correct
- [x] Visual result of tabbing through the filters is correct

**Comment by gissoo** [comment]
Thank you, Ben! I think everything looks good here! 
When hovering over a selected filter there is a darker green, is this the grey hover on top of the green that appears as a darker green? That's fine, it actually works. But it's also appearing as you select a filter, when a filter is selected here the color shouldn't become the darker green, it should just be the bright green. 
![Screen Shot 2022-02-25 at 10 29 13 AM](https://user-images.githubusercontent.com/44615389/155742020-052ca7a3-9601-470f-ade4-20af9fe6b66a.png)

the other thing I noticed is that the X button on the filters window should follow the icon button focus style, so it would have a green outline on lightmode and a blue one on dark mode.

**Comment by blms** [comment]
Thanks @gissoo! 
1. That is the "focus" style, since that option now has focus (i.e. if you press tab on your keyboard the focus will move to the next one). Should we differentiate that from the hover style somehow? We need some way to indicate "selected AND focused".
2. Good catch, I'll fix that!

**Comment by gissoo** [comment]
@blms so the grey is also being used as the focus style? that's what I'm seeing. 
I see it now. I don't know, I'll think about it. It's fine as is for now. thanks

**Comment by gissoo** [comment]
@blms for the new desktop version below are a couple of usability reqs: 
- the filter window shouldn't collapse after submitting search / it shouldn't collapse unless the user has collapsed it
- the expanded filter window shouldn't cover the sort, and results numbers
- there should be a submit/apply button on the expanded filters (or some hint of what users should do to see new results, i.e. "pressing enter") – till we have reactive search

**Comment by blms** [comment]
Thank you @gissoo!

> the expanded filter window shouldn't cover the sort, and results numbers

How do you recommend placing it? Can you provide a wireframe or describe how it should work?

> there should be a submit/apply button on the expanded filters (or some hint of what users should do to see new results, i.e. "pressing enter") – till we have reactive search

OK! If all goes well, we are about to have reactive search :)
