### ISSUE TITLE
Refactor all JS to Stimulus

### ISSUE THREAD

**Issue by blms** [Princeton-CDH/geniza#634]
## dev notes

[Stimulus](https://stimulus.hotwired.dev/) was first used for the relevance sort in #550, the following should also be refactored to use Stimulus:

- [x] `search.js` (all functionality should be moved over to `controllers/search_controller.js`)
- [x] `submenu.js`
- [x] `theme_toggle.js`
- [x] `openseadragon.js` (see #684)

**Comment by blms** [comment]
@rlskoeser exactly!

**Comment by rlskoeser** [comment]
@blms what about openseadragon init?

**Comment by blms** [comment]
@rlskoeser Ah, I didn't think to include it since it's just injecting OSD vendor code into the HTML, but it probably should be included, I'll add it to the list!

**Comment by rlskoeser** [comment]
We may want to split this out into separate subtasks, but can wait and see how it goes; am wondering if the seadragon should be more of a progressive enhancement. I was looking at the site on my phone and wasn't seeing images on detail pages — which we should check on — but made me wonder if you really want deep zoom by default on mobile.

**Comment by blms** [comment]
@rlskoeser Good call, and I see the mobile issue—it occurs on pages where there are images but no transcription. I'll track it as a bug!

**Comment by rlskoeser** [comment]
@blms great — thanks for documenting, we should get that resolved

**Comment by rlskoeser** [comment]
confirmed in qa, but noticed we're still including a main.js bundle that appears to be empty — let's remove that one before we close this

**Comment by rlskoeser** [comment]
confirmed main.js removed in qa
