### ISSUE TITLE
As a front end user, I want to filter search results to records with discussion available, so that I can find documents with existing scholarship notes.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#637]
## testing notes (qa)

- Navigate to the document search page on the QA site, type in a search query and press the submit button
- [x] Click the "Filters" button below the search bar and confirm "Has Discussion" appears as a filter with a count of documents matching your search terms that have discussions
- [x] Enable that filter and click "Apply", then confirm the results all have discussions

**Comment by richmanrachel** [comment]
Works with the same caveats as #630 and #636. One style thing I noticed though, @gissoo, is that the checkmark and down arrow look extremely similar in a confusing way:
![image](https://user-images.githubusercontent.com/68028846/155752260-2ac8db31-ede9-460d-aca6-0add311eb0cb.png)

**Comment by richmanrachel** [comment]
Should I be making a new design issue for this?

**Comment by blms** [comment]
@richmanrachel Yes, please!

**Comment by rlskoeser** [comment]
functionality testing passed, design concerns addressed separately
