### ISSUE TITLE
As a global admin and content editor, I want to clone a document and have a record of the process, to keep track of the origins of the document record and changes in the data. 

### ISSUE THREAD

**Issue by sluescher** [Princeton-CDH/geniza#64]
## testing notes
- [x] Choose a document from the document list for editing, and use the 'save as new' button at the bottom. Confirm that all fields are populated from the original document record, and there is a note added that this record was cloned from the other one.
- [x] Do the same test, but add content to the notes field of the first document before saving it. Confirm that the note about the record being cloned is added to whatever text you added in the notes field.
- [x] Confirm that date created and last modified are set accurately for the new record, and not copied from the previous one.

## dev notes
ideal implementation:
- [x] add a button to the edit view next "save and continue", etc. that's "clone this" or similar
- [x] button links to a new add view with all fields prepopulated using current values from the object, but doesn't submit (so user can change it before submitting)
- [x] prepopulate notes field with text "cloned from str(document)"

**Comment by rlskoeser** [comment]
@richmanrachel this one is ready for testing now. I didn't think about it until recently, but I do wonder whether the legacy input and legacy input date should be removed when you clone a document like this. Can you consider this when you do the testing and let us know if you think they should be removed?

**Comment by richmanrachel** [comment]
Everything good! Marina worked as content editor and I as global admin, and it worked on both ends! Closing :)
