### ISSUE TITLE
revise the "selected" state for the scholarship records filters so that it's easier to identify what's been selected.

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/geniza#650]

**Comment by gissoo** [comment]
@richmanrachel @rlskoeser This is how I was thinking to address this issue, are these scholarship records indicators better now?! I personally like the second option more – the problem is that I cannot add a fill color to this particular phosphor icon because of the way it was originally created so I ended up having to add a circle myself. But it's probably worth it because it's way more visible.

 ![Screen Shot 2022-03-01 at 5.20.51 PM.png](https://images.zenhubusercontent.com/5bf307a69d595b459ec91bb1/7269b203-977a-4018-8e3c-18b6736a9c4f)

[Screen Shot 2022-03-01 at 5.26.16 PM.png](https://images.zenhubusercontent.com/5bf307a69d595b459ec91bb1/d590b164-51df-4c43-9da3-9670a928d659)

**Comment by rlskoeser** [comment]
The circle helps a lot to differentiate from the drop-down; filled in circle vs. empty circle looks much easier to visually differentiate selected/unselected

**Comment by richmanrachel** [comment]
@gissoo - I agree with Rebecca. The second option is great, thanks!

**Comment by blms** [comment]
Also agree! And I think there's a built in Phosphor icon with the filled in circle, if that's what you were trying to find:

<img width="530" alt="Screen Shot 2022-03-02 at 9 43 29 AM" src="https://user-images.githubusercontent.com/7234006/156384076-c8ef8b5e-8537-4e33-b297-5da1bdecc47f.png">

**Comment by gissoo** [comment]
duhhhh it was in their "fill" category ...I forgot they had that!!! thanks @blms!!!  
(although there is a similar problem with the fill version :D ...we can't color the check mark white, but the check mark is pretty visible on the light mode, so it's good, I'll be the only who notices it :D ) – it won't work on certain backgrounds, but right now it works. 

just documenting here that the size of the icon square is 30x30 px on desktop and 
- For the active state: the icon style is fill, the color of the circle is #567856.
- For the default state: the icon style is "regular", and the only color on the whole icon is #567856 

- here is [the link to the desktop version on Figma](https://www.figma.com/file/anZFStv7zBaVWnFxr95nKt/Work-in-Progress-%2F-WIP?node-id=421%3A23976) so you can see its placement relative to the other icons below and/or above it. 

- here is [the link to the mobile version on Figma](https://www.figma.com/file/anZFStv7zBaVWnFxr95nKt/Work-in-Progress-%2F-WIP?node-id=421%3A24196) 

- here is [the link to the desktop dark mode on Figma](https://www.figma.com/file/anZFStv7zBaVWnFxr95nKt/Work-in-Progress-%2F-WIP?node-id=421%3A26117)

- here is [the link to the mobile dark mode on Figma](https://www.figma.com/file/anZFStv7zBaVWnFxr95nKt/Work-in-Progress-%2F-WIP?node-id=421%3A25898)
