### ISSUE TITLE
Design a favicon for the site using the logo so that it would be easier for users to identify which tab is the PGP site.

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/geniza#651]

**Comment by gissoo** [comment]
This is what will appear as a small icon on the browser tab – @rlskoeser @blms @richmanrachel does this one look better ?![Screen Shot 2022-02-28 at 6.39.58 PM.png](https://images.zenhubusercontent.com/5bf307a69d595b459ec91bb1/f1759ab8-c856-4570-8885-a566810266a7)

or this one? 
![Screen Shot 2022-02-28 at 6.42.29 PM.png](https://images.zenhubusercontent.com/5bf307a69d595b459ec91bb1/f42c6541-d793-44f1-ad0b-a061db799fdb)

- I find the second one (the zoomed in version) way more flattering and visible with the focus on the tear

- can we customize it so that for dark tabs it would show our dark mode designs? (If we can't then let's not bother with the dark mode designs for this issue because the green looks a lot better and more visible if we have one option) but here is what it would look like. 

![Screen Shot 2022-02-28 at 6.51.09 PM.png](https://images.zenhubusercontent.com/5bf307a69d595b459ec91bb1/224cb998-fef5-43b2-b58e-50a0ae7b2565)

![Screen Shot 2022-02-28 at 6.46.09 PM.png](https://images.zenhubusercontent.com/5bf307a69d595b459ec91bb1/d2ce3924-dad4-410b-b462-3ce86de60428)

**Comment by rlskoeser** [comment]
Hi @gissoo — I agree, the second, zoomed in one is much more recognizable and visible.

I did some quick looking, it seems the usual way to do a dark mode favicon is to use javascript to switch it (also possible to use svg in css, which sounds more complicated than necessary); I don't think that's worth our effort or yours, so let's just have one version.

**Comment by gissoo** [comment]
@rlskoeser that's what I suspected, I agree, thanks for writing!!

**Comment by richmanrachel** [comment]
@gissoo - I agree with everything above: the zoomed in one is great and no need to do separate dark mode icon :)

**Comment by blms** [comment]
Also agree, I like zoomed in light mode best!

**Comment by gissoo** [comment]
perfect!! Thanks, all!! I'll upload the favicon files to the develop branch.
