### ISSUE TITLE
As a front end user, I want to click on the document title in search results so I can get to the details more easily.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#659]
## testing notes
on the  [test documents search](https://test-geniza.cdh.princeton.edu/en/documents/)
- [x] confirm that you can click on the title of the result to go to the document details. (You can actually click almost anywhere in the card except the text fields below)
- [x] confirm that you can still select the following text content for copy and paste : description, transcription, input date, pgpid

**Comment by richmanrachel** [comment]
@rlskoeser - this is great, thank you!
