### ISSUE TITLE
investigate non-transcription content in footnotes

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#661]
I think the "has transcription" filter is correctly pulling content, but there is one document that doesn't have proper content (and is probably an issue with the TEI because it appears the same way in the admin site): 
![image](https://user-images.githubusercontent.com/68028846/155750409-ada8b636-317b-4a0a-b9ce-15d57bd926ff.png)

_Originally posted by @richmanrachel in https://github.com/Princeton-CDH/geniza/issues/630#issuecomment-1050999926_

## dev notes
- investigate relevant footnotes and see if the admin history sheds any light on where the text is coming from
- check sync transcription script behavior if needed
- propose a way to remove/clean up the stray content (one-time solution is fine as long as we can confirm it won't come back)

See also Alan's comment & screenshot on slack for another set of documents with this problem: https://cdhprinceton.slack.com/archives/C016091ASAZ/p1645731671269579

**Comment by richmanrachel** [comment]
@rlskoeser - is this still an issue? We may be able to close.

**Comment by rlskoeser** [comment]
@richmanrachel I think it's probably not something we should (or can) handle as dev work but with data workflows and cleanup, so I think it makes sense to close
