### ISSUE TITLE
Design checkmarks so that they aren't as easily confused with down arrows.

### ISSUE THREAD

**Issue by richmanrachel** [Princeton-CDH/geniza#662]
@gissoo, when testing #637, I noticed that it's hard to tell the difference in the filter list between a down arrow and a checkmark:
![image](https://user-images.githubusercontent.com/68028846/155753712-60edef44-103b-48dc-ab53-d4003f37bcbb.png)

Hopefully a small design change can make these two sigla more distinguishable!

**Comment by rlskoeser** [comment]
@gissoo I think this has been addressed, right?

**Comment by rlskoeser** [comment]
this was resolved a while ago, closing as a duplicate
