### ISSUE TITLE
"Combining dot above" rendered incorrectly in transcriptions

### ISSUE THREAD

**Issue by blms** [Princeton-CDH/geniza#670]
## testing notes

Review the second transcription (by Goitein and Friedman) on PGPID 9083 linked below and check if the combining dot renders correctly. Recommend testing in multiple browsers, since before we saw different behavior on this with different browsers.

----

Unicode Character “◌̇” (U+0307) Combining Dot Above is missing from Frank Ruhl 1924 MF, so it does not render correctly in transcriptions.

Example: https://geniza.princeton.edu/en/documents/9083/

<img width="209" alt="Screen Shot 2022-02-28 at 1 52 26 PM" src="https://user-images.githubusercontent.com/7234006/156051957-8f96f623-1a43-4d54-9d99-3aa894454dda.png">

**Comment by blms** [comment]
Additional missing glyphs in Arabic:
https://geniza.princeton.edu/en/documents/9140/

**Comment by blms** [comment]
Seems to behave differently on different browsers, and is not resolved by Unicode normalization. Another example: https://geniza.princeton.edu/en/documents/4767/

May be related to fallback font behavior. Noting some different options here:

Default (Frank Ruhl):
![Screen Shot 2022-09-29 at 10 38 51 AM](https://user-images.githubusercontent.com/7234006/193061665-63d5c3c7-da6b-45b5-94ca-bf685f5ba01d.png)

`font-family: serif` or `font-family: Georgia` (what I thought our fallback was already!)
![Screen Shot 2022-09-29 at 10 38 18 AM](https://user-images.githubusercontent.com/7234006/193061720-a04a8f0e-5598-49df-b00b-ab65b43642ac.png)

`font-family: 'Greta Sans Hebrew Regular'`
![Screen Shot 2022-09-29 at 10 38 41 AM](https://user-images.githubusercontent.com/7234006/193061879-3b0bf15f-ee48-424e-b611-a28c1bc036f7.png)

`font-family: Times New Roman`
![Screen Shot 2022-09-29 at 10 38 29 AM](https://user-images.githubusercontent.com/7234006/193061943-8eac749a-003b-457e-b18d-9dff2851e80c.png)

All tested on Chrome.

**Comment by kseniaryzhova** [comment]
@rlskoeser @blms It works partially (same transcription, test site)
![image](https://user-images.githubusercontent.com/105385128/196521958-a12e9223-7b74-4033-af70-951df4b78747.png)

**Comment by rlskoeser** [comment]
Maybe this is a Windows-specific rendering problem...

Here's current versions of the Goitein + Friedman transcription on PGPID 9083:

production
![Screen Shot 2022-10-24 at 3 38 47 PM](https://user-images.githubusercontent.com/691231/197611905-e18d1fd9-78b8-4c84-8a2c-ecaf440cc515.png)


test
![Screen Shot 2022-10-24 at 3 39 27 PM](https://user-images.githubusercontent.com/691231/197611916-1ad89392-1194-4174-8219-e44afa0e1688.png)

**Comment by richmanrachel** [comment]
@kseniaryzhova - is this still an issue for you on a PC? The Ju-Ar ones look fine to me on my Mac, but the Arabic one (https://geniza.princeton.edu/en/documents/9140/) is still showing a weird box.

**Comment by kseniaryzhova** [comment]
@richmanrachel @blms 
For me it's uneven, sometimes the combining dot works and sometimes it doesn't (this is from PGPID 9083)
<img width="691" alt="image" src="https://github.com/Princeton-CDH/geniza/assets/105385128/d6bdfea6-6b68-47aa-b0c7-06d7b5072e1a">
I do get the empty squares for the Arabic script.

**Comment by blms** [comment]
@richmanrachel It's interesting; looking more closely at PGPID 9140, I think that might be an error in the transcription. If it is meant to be a combining dot above, it's using a different Unicode symbol for that than the others: [ U+F0C2](https://www.compart.com/en/unicode/U+F0C2) rather than the typical [◌̇ U+0307 combining dot above](https://www.compart.com/en/unicode/U+0307). It's the only transcription on the site that uses that character.

@kseniaryzhova Sounds like it's still just a PC issue with the latter character. Maybe it will resolve itself with later Windows versions of browsers…

**Comment by richmanrachel** [comment]
Closing because it's an issue of original font that should be re-typed to avoid issues (not a dev problem).
