### ISSUE TITLE
As a front end user, I want a filter for documents that have images, so that I can limit results to documents where I'll have ready access to visuals of the fragments.

### ISSUE THREAD

**Issue by blms** [Princeton-CDH/geniza#691]
## Testing notes (QA)

On the document search:
- [x] Enable the "Has Images" filter and confirm only documents with images show up
- [x] Combine with other filters and confirm it works as expected
- [x] Comment: should it be first in the list, or below the scholarship records filters?

**Comment by richmanrachel** [comment]
@blms - it looks great! I like having the images filter first in the list. I'll double check with Marina shortly about her preferences, but I think we can close for now!
