### ISSUE TITLE
Implement pagination for the hebrew site 

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/geniza#693]
## testing notes (qa)

- [ ] After a hard refresh (shift + refresh), confirm that you can switch between languages
- [ ] On the QA site, visit the document search page, and switch your language to Hebrew. Confirm the pagination looks and works correctly

---

Please refer to [the comment on design issue #441](https://github.com/Princeton-CDH/geniza/issues/441#issuecomment-1049250603)

**Comment by gissoo** [comment]
@blms I can't confirm the correctness of "previous" and "next". But the designs are correct. 

The problem is that when I choose to view the site in Hebrew:

1. nothing happens till I change the sort from "Random" to something else. 
2. even when the sort is not on "random", the pagination text changes to Hebrew but the numbers don't till I do a hard refresh ...as of right now the Hebrew switch is not working at all

**Comment by blms** [comment]
Thanks @gissoo, I think this is a Turbo issue 😬  @rlskoeser but we can prioritize it for later, since we're not shipping out Hebrew yet… should I make a new issue for that?

**Comment by richmanrachel** [comment]
@gissoo - Not sure if I'm supposed to be testing this or not, but everything is working for me on Chrome as expected except for the lack of space between the search result number and the document title:
<img width="689" alt="image" src="https://user-images.githubusercontent.com/68028846/160673764-49161874-7dac-483b-8aaf-820344a0b2d4.png">
In contrast, the English page looks like this:
<img width="724" alt="image" src="https://user-images.githubusercontent.com/68028846/160673859-f41ba715-9d86-4c8d-9468-ebdd2508f5b5.png">

**Comment by gissoo** [comment]
@richmanrachel thanks for testing – yes I can see the issue with spacing only for the 1st doc. But I'll wait till I hear back from @blms about my earlier comments since I've already tested this, and then can test again.

**Comment by blms** [comment]
@gissoo I believe the things you mentioned should be fixed now since the form does not use Turbo. Can you try those again?

@richmanrachel: I actually hadn't implemented the design for that part yet! I think this issue is just for the pagination, meaning, the "previous," "next," and page numbers links. So I think those things you mentioned would go under an issue "search results" instead.

Gissoo, do we have an implementation issue for the design of the individual search results in RTL? I see it was mentioned in your [design issue here](https://github.com/Princeton-CDH/geniza/issues/443#issuecomment-1085100158), but I only see an implementation issue for the [form](https://github.com/Princeton-CDH/geniza/issues/753).

**Comment by gissoo** [comment]
@blms thanks for reminding me of the RTL search results page, I must have forgotten about that one! 

Everything looks great now! 

some unrelated questions and inconsistent issues:
1. are we still going to display the random sort by default?
2. not sure if this is intentional but when I refresh and hard refresh the page the sort doesn't go back to what it was in default, seems a bit weird (I know we'll have a reset button but this is still odd for some reason)
3. the language switcher on safari seems a bit glitchy, it was not changing from Hebrew to English after pressing "go" – but I'm not having issues with it after a few tries

**Comment by blms** [comment]
@gissoo 

> 1. are we still going to display the random sort by default?

I'm not sure if we ever came to a decision on that. @rlskoeser?

> 2. not sure if this is intentional but when I refresh and hard refresh the page the sort doesn't go back to what it was in default, seems a bit weird (I know we'll have a reset button but this is still odd for some reason)

Can you open a new issue with this?

> 3. the language switcher on safari seems a bit glitchy, it was not changing from Hebrew to English after pressing "go" – but I'm not having issues with it after a few tries (oh this one is related to the issue, my bad)

Same as above, I don't think it's directly related to pagination so makes sense to open a new issue.

I'll close this one for now since it sounds like pagination is all set.
