### ISSUE TITLE
Implement the site header for the Hebrew site 

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/geniza#696]
## testing notes (qa)

On the QA site, visit the home page and switch to Hebrew mode, then check the header:
- [x] Desktop light/dark
- [x] Mobile light/dark
- [x] On another page (not home page)

And confirm it looks and functions as expected.

---

Please refer to [this comment on the design issue #631](https://github.com/Princeton-CDH/geniza/issues/631#issuecomment-1049247983)

the header files have been uploaded to github

**Comment by blms** [comment]
Possible side effect from the work on this issue: when you switch between light and dark on mobile, the menu items' text color does not update, so they appear invisible.

**Comment by richmanrachel** [comment]
@gissoo - this worked perfectly for me on Chrome on desktop!

**Comment by gissoo** [comment]
@richmanrachel thanks for testing!

@blms There are a couple of issues on mobile and safari desktop and mobile, they're not terrible but wanted to make sure they are documented here:
- on mobile chrome, safari, and FF the language toggles don't show up, not sure if it's part of this issue or is intentional
- on mobile, on Safari, the logo's side (its bottom left) seems a bit off 
<img width="173" alt="Screen Shot 2022-04-04 at 12 31 16 PM" src="https://user-images.githubusercontent.com/44615389/161589972-13a941bd-9da7-4746-8459-75212d1807e1.png">

- on desktop on safari the bottom part below "project" is a bit off
<img width="238" alt="Screen Shot 2022-04-04 at 12 33 08 PM" src="https://user-images.githubusercontent.com/44615389/161590236-8e1f14f2-291e-486e-8a98-f0104a498136.png">

- on mobile on safari the header image seems to suddenly disappear rather than a smooth transition – I don't know if it's also an issue on the dark mode, but it's definitely an issue on light mode. 
<img width="423" alt="Screen Shot 2022-04-04 at 12 35 14 PM" src="https://user-images.githubusercontent.com/44615389/161590558-48411c6f-21ee-4320-9b65-63cef16840d6.png">

**Comment by blms** [comment]
> on mobile chrome, safari, and FF the language toggles don't show up, not sure if it's part of this issue or is intentional

That is intentional until we have a design for it, as it breaks layout on mobile!

**Comment by gissoo** [comment]
Ben, thank you! These look much better now! The only one that is very noticeably wrong is this one, desktop Firefox, if you can't replicate it then ignore me.

<img width="273" alt="Screen Shot 2022-04-14 at 1 48 33 PM" src="https://user-images.githubusercontent.com/44615389/163447652-690bedcd-ccd9-482f-bede-32174105d91c.png">

**Comment by blms** [comment]
@gissoo, I can't replicate, here's what it looks like for me on FF. Maybe a cached version on your end?

<img width="255" alt="Screen Shot 2022-04-14 at 1 57 35 PM" src="https://user-images.githubusercontent.com/7234006/163449522-30b255c3-8920-44e0-bedd-5e17cf547343.png">

Should we go ahead and close this?
