### ISSUE TITLE
Revise the header styles so that H2 and H3, and H3 and body text would become easier to distinguish from each other 

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/geniza#704]

**Comment by gissoo** [comment]
@richmanrachel @mrustow Please look at the two proposed revisions and compare them to the current one which I have also included here. I have placed the header sizes next to each header. The changes will affect the size of the page title as well, which you see here as well. 

[Here is the link to the revisions in Figma](https://www.figma.com/file/HpGBOZi9lO8B3nCAx3d4Fj/Princeton-Geniza-(Project-team)?node-id=2735%3A14073)

**Comment by mrustow** [comment]
I prefer Proposal 1.

**Comment by gissoo** [comment]
Thanks @mrustow! I've also adjusted the sizes on mobile based on proposal 1 and updated the typestyle sheet [here, on Figma](https://www.figma.com/file/HpGBOZi9lO8B3nCAx3d4Fj/Princeton-Geniza-(Project-team)?node-id=1937%3A5514) NOTE: This change does not affect the Error page headers. 

<img width="414" alt="Screen Shot 2022-03-25 at 12 43 26 PM" src="https://user-images.githubusercontent.com/44615389/160164170-1d235632-c64a-4768-b563-490210e5273e.png">
