### ISSUE TITLE
As a front end user, I want to be able to easily select shelfmarks for copy and paste on the document detail page, so that I can enter that information elsewhere.

### ISSUE THREAD

**Issue by blms** [Princeton-CDH/geniza#705]
## review notes

- [x] On a document detail page, click on the shelfmark(s) in the title header, and confirm all shelfmarks are automatically selected
- [x] Confirm that is the desired functionality, rather than selecting individual shelfmarks

## dev notes

- [x] try css `user-select`
- [x] fix edit container in the way for logged in users
- [x] stimulus controller for copy (disabled for now)

**Comment by richmanrachel** [comment]
@blms - I love this! I'll see if I have a moment to ask Marina about it at the end of our meeting with Gissoo, but I think it's nice that the joins come together (since I want the full document, not just individual fragments to be recorded in my notes).

**Comment by rlskoeser** [comment]
@richmanrachel I wondered about that! I had assumed individual shelfmarks but when I saw Ben's implementation recognized it had never been made explicit.

**Comment by richmanrachel** [comment]
@blms - Marina loves the single click for the joins! "It's like getting a hug from a developer!" :) I think that merits closing, haha
