### ISSUE TITLE
As a frontend user, I want to search in Arabic script and get search results from both Arabic and Judaeo-Arabic transcriptions so that I can find more content that matches my search.

### ISSUE THREAD

**Issue by richmanrachel** [Princeton-CDH/geniza#706]
## testing notes
- [x] review the [character mapping in the code](https://github.com/Princeton-CDH/geniza/blob/4d1f24f418e009d00d20d390f685400888e776a2/geniza/corpus/ja.py#L5-L35) to check that I correctly adapted the characters from the chart in Marina's document  (although the mixed ltr/rtl display is a little mixed up on some of the lines in the github view)
- [x] review [Hebrew script final character mapping](https://github.com/Princeton-CDH/geniza/blob/4d1f24f418e009d00d20d390f685400888e776a2/geniza/corpus/ja.py#L37-L44) 
- [x] try some keyword searches in arabic script on the [test site search](https://test-geniza.cdh.princeton.edu/en/documents/) — you should get matches in both arabic and judaeo-arabic when the word occurs in both forms

---- 

**Is your feature request related to a problem? Please describe.**
Millions of Arabic speakers around the world could be interested in the Cairo Geniza and would be able to understand many of documents if Hebrew script was not a blocker. 

**Describe the solution you'd like**
Use [Marina's Arabic to Judaeo-Arabic conversion chart](https://docs.google.com/document/d/1hcwWwBuPEmxc_FHpSk1JWoBZvs5Y1LOn8v6PIqaP9mA/edit) to convert Arabic queries so that they also search against Judaeo-Arabic.

**Comment by rlskoeser** [comment]
@richmanrachel could you provide a few search terms I could use for testing? i.e., a few arabic terms that will match existing judaeo-arabic transcriptions

**Comment by richmanrachel** [comment]
@rlskoeser - sure! 

دينار
مصحف
سنة
Is that enough? (those respectively are dinār [the gold coin/main currency], maṣḥaf [a book/usually a Bible], and sana [year])

**Comment by rlskoeser** [comment]
@richmanrachel this one is ready for testing now. I tried the three terms you gave me to test with and only one of them is returning judaeo-arabic matches – I don't know if this means they don't occur, or if I've done something wrong with the mapping.

I've been trying to figure out a way for you to test the conversion I'm doing more directly, and so far nothing obvious has come to mind; if testing indirectly through the search is inconclusive or problematic, let's figure out a way you can test it more directly.  (One idea, if there are problems: you could give me a  larger set of test words and expected judaeo-arabic equivalents, and I could add them to my automated testing.)

**Comment by richmanrachel** [comment]
@rlskoeser, I noticed a few problem in the code (line 30 is just wrong: "ن": "ה",  # ن or ة), ע ع is missing, and the Hebrew letters you have with dots on them (lines 9, 10, 12, and 21) likely won't appear with dots in our transcriptions. In line 38 (for the final kaf), the dot is in the wrong place - it should look like 
<img width="147" alt="image" src="https://user-images.githubusercontent.com/68028846/163850555-68fdba6c-4423-4272-9a25-0874bed86a62.png">
(sorry, I could not get my keyboard to cooperate to type it properly. I'll try again tomorrow). 

But I think something bigger is wrong, because when I typed in the equivalent words for "year" my results were 67 for שנה and 9 for سنة (but only with existing Arabic script). So even though these don't have any of the affected characters from the code, something still isn't working.

**Comment by rlskoeser** [comment]
@richmanrachel @mrustow The professions spreadsheet with arabic and judaeo-arabic terms was incredibly helpful for testing and fine-tuning my conversion. I was able to correct some letter conversions that I had incorrectly transferred from Marina's document to my code, and I added a few more mappings based on the conversions in the spreadsheet that are not in Marina's document. 

Could you confirm that these additions are correct?

| Arabic | JA |
|-------|---|
| ئ |  י | 
| ؤ | ו|
|أ | א|
| آ |  א|
|ء |  |

Based on the examples, it looked like ء should be ignored. Are there any other characters like this?

When I ignore the differences between accented characters, I'm down to 67 mismatches between what I'm generating via my code and the version in the profession spreadsheet. I made a [google sheet of these mismatches](https://docs.google.com/spreadsheets/d/1Aq9Mezjh4eDmal2fB5z4uo1aEpHZ0KVCcCT9rJfYwjU/edit#gid=898348417). I included both unaccented versions and accented versions.

Could someone to review to help me address the remaining discrepancies? The two patterns I noticed:
- Final letter differences; am I doing this incorrectly or are these values from the spreadsheet wrong?
- differences in duplicated letters — it looks like sometimes they are collapsed
 
There are probably other problems — hopefully they will be easy for you to spot!

**Comment by richmanrachel** [comment]
@rlskoeser - yes,  ء should be ignored. But aren't we going from Hebrew -> Arabic so it won't be relevant? It will just be missing in the Judaeo-Arabic (and Arabic readers will have to supply it themselves). 

Same with the additions you have above. They're correct but only really relevant when you're going from Arabic script to Hebrew script.

**Comment by rlskoeser** [comment]
@richmanrachel thanks for reviewing and confirming via discussion on slack that my final letter logic is correct.

We decided to implement arabic to hebrew script first since it's simpler (without the alternate characters / choices we have to handle in the other direction).

I'll go ahead and merge in this revised functionality and deliver so you can try it out on the test site.

**Comment by richmanrachel** [comment]
@rlskoeser - it's working quite well! The Arabic sources don't necessarily get listed first, and I'm not sure I tested all the more complicated characters, but it's definitely a good start.

Should we close now and refine search results elsewhere?

**Comment by rlskoeser** [comment]
@richmanrachel that makes sense to me — I like the idea of closing and refining.  I hadn't thought about boosting the arabic results first, but that sounds like it would be logical.
