### ISSUE TITLE
Long lines in transcriptions break layout in admin interface

### ISSUE THREAD

**Issue by blms** [Princeton-CDH/geniza#708]
## steps to reproduce

- Check a document with a long line in a transcription, such as PGPID 9052, in the admin interface

~~This should be resolved by #724  — please confirm~~

**Comment by richmanrachel** [comment]
@blms and @rlskoeser - I don't think this was fully solved. Now the transcription for 9052 is just stuck in a weird box with a scroll (when you expect it to wrap). https://test-geniza.cdh.princeton.edu/admin/corpus/document/9052/change/?_changelist_filters=p%3D4%26textblock__fragment__iiif_url__isempty%3D0%26transcription%3Dno

**Comment by richmanrachel** [comment]
@blms - I'm afraid it's still looking as weird as it did a few days ago. 
<img width="582" alt="image" src="https://user-images.githubusercontent.com/68028846/164543469-a37f9925-efb7-4914-aae4-57d25587625c.png">

**Comment by blms** [comment]
@richmanrachel That's odd! Can you try a hard refresh? If still not working, can you provide me the PGPID so I can take a look at it on my computer?

**Comment by richmanrachel** [comment]
@blms - wow, that hard refresh is magic indeed! Thanks!
