### ISSUE TITLE
check for mismatched shelfmarks on fragments we expect to have images for

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#709]
We have digitized images for two large collections, but not all the fragments from those collections have been associated. Alan indicated there may be some mismatches where fragments in our db have not yet been split apart; if we can do some fuzzy matching on the fragments we expect to have images for but don't, it would add in data work needed to remedy that. 

## dev notes

Generate an export from the production database and compare fragment shelfmarks to these spreadsheets to look for mismatches

- [x] Cambridge [shelfmark iiif spreadsheet](https://docs.google.com/spreadsheets/d/1TqfH_G5yPCeuvDSREee6ad9-ReJvHD4hUHU37f09xsA/edit#gid=592712075)
- [x] JTS [PUL JTS shelfmarks](https://drive.google.com/file/d/1bXkFBCsdQhwbsljF-bHUltTf2gJGg0fx/view?usp=sharing)

jupyter notebook or colab is fine, just want a report we can share with the team to check.

**Comment by kmcelwee** [comment]
First go at this report, let me know if I misunderstood something: https://gist.github.com/kmcelwee/bcf3cf3fdbfd9d9fe2c454f738318895

**Comment by rlskoeser** [comment]
@kmcelwee please generate a report on shelfmarks in the collections we have images for that do _not_ currently have images associated. I want to know if there are _similar_ shelfmarks in the spreadsheets that we used to assign them that were missed on import because they do not match exactly.

**Comment by kmcelwee** [comment]
@rlskoeser I'm fairly certain that's what my output shows? https://gist.github.com/kmcelwee/bcf3cf3fdbfd9d9fe2c454f738318895?permalink_comment_id=4093097#gistcomment-4093097

I collected all fragments from production. This is the list of mismatches with the provided CSVs, including empty strings.

**Comment by rlskoeser** [comment]
Discovered a few sets of mismatches in the CUDL spreadsheet:
- leading zeroes on on the NS J## shelfmarks; e.g., we have T-S NS J98 but the spreadsheet lists it as T-S NS J098
- Mosseri vs Moss.
