### ISSUE TITLE
As a front end user, I want some kind of progress/loading indicator during search, so that I know my input was accepted.

### ISSUE THREAD

**Issue by blms** [Princeton-CDH/geniza#711]
## dev notes
https://github.com/hotwired/turbo/issues/61#issuecomment-752717046
- [ ] style `.turbo-progress-bar`
- [x] use `html` element rather than `body` for applying theme overrides, so we can get the variables

**Comment by richmanrachel** [comment]
@rlskoeser - is this worth keeping open? Everything loads so quickly for me that it's unnecessary on my end.

**Comment by kseniaryzhova** [comment]
Search loads super quickly on the public site, so closing!
