### ISSUE TITLE
As a frontend user, I want to see primary and secondary languages when they've been assigned so that I have access to the known information about the document.

### ISSUE THREAD

**Issue by richmanrachel** [Princeton-CDH/geniza#715]
## testing notes
Review public document details pages on test site for documents with and without languages.
- [x] documents without languages set should not display any language sections
- [x] document should display one or more primary languages when set
   - [x] single language examples: PGPIDs 468, 495, 473
   - [x] multiple language examples: PGPIDS 503, 462
- [x] documents should display one or more secondary languages when set
   - [x] single secondary language examples: PGPIDs 475, 501, 712
   - [x] multiple secondary language examples: PGPIDs 1036, 1442

Note that I'm not currently displaying the contents of the language notes anywhere — I couldn't figure out how to easily fit it into the display; maybe we can fold this into the other document detail revisions that Gissoo needs to do.

**Is your feature request related to a problem? Please describe.**
We need the front and backend information to be more similar, as we're asking RAs to avoid repeating information in the description that has a dedicated field. 

**Describe the solution you'd like**
Language should show up as another field (perhaps below editor information and above the description).

**Comment by richmanrachel** [comment]
<img width="622" alt="image" src="https://user-images.githubusercontent.com/68028846/157901654-7cec97dd-e0eb-4b6a-97e9-c8889c731ea6.png">
Is it just the font, or is there actually more space between Hebrew and Judaeo-Arabic than Primary Languages and Hebrew?

**Comment by richmanrachel** [comment]
@rlskoeser - everything works, but I think we still need to improve design to make the internal headers clearer and to handle language notes (as you mentioned above). 

I don't see a current issue of @gissoo's to track these details. Should I close and make one?

**Comment by rlskoeser** [comment]
@richmanrachel I agree, the problem with the internal headers is more and more obvious to me — I wanted to work within the existing styles for this quick change, but agree we need to address. It makes sense to me to add an issue for that. We may need an epic to track all the revisions needed for the document detail page, but creating the specific issue for this is fine for now.
