### ISSUE TITLE
In the admin interface, when I drop a IIIF link into the appropriate space, I get an error message. 

### ISSUE THREAD

**Issue by mrustow** [Princeton-CDH/geniza#723]
In fragment view, I take a link formatted like this — 

https://cudl.lib.cam.ac.uk//iiif/MS-TS-NS-00099-00055

and put it here — 

<img width="888" alt="image" src="https://user-images.githubusercontent.com/73319225/157780767-2e97b5fb-a03c-405f-ad7e-1eb940704cd4.png">

and get the following error message: 

![image (1)](https://user-images.githubusercontent.com/73319225/157780795-e614f0bf-5ae3-490d-baf9-dc0cd88a6c6a.png)

At least that's what happened when I input the link. But when I checked back later, it was fine: 

<img width="1050" alt="image" src="https://user-images.githubusercontent.com/73319225/157780913-b9da744e-74f4-4971-8670-94305a3c05b8.png">

Using MacOS 12.2.1, Vivaldi 5.1.2567.57 (Stable channel) (x86_64) Revision d6362af7ddc855068c1f06e19b65312c2f160e1f

**Comment by richmanrachel** [comment]
It worked right away for me! Closing!
