### ISSUE TITLE
As an admin user in document view, I'd like to be able to zoom on the fragment's IIIF image thumbnail so I can determine the language and check other metadata details as I'm writing or editing a description. 

### ISSUE THREAD

**Issue by mrustow** [Princeton-CDH/geniza#724]
## Testing notes (QA)

In the admin UI on the QA site, navigate to the list of documents. Click on some documents and confirm:
- [x] you can see images/transcriptions on documents that have them (try by filtering on documents that: only have image, only have transcription, have both, and have neither)
- [x] you can zoom and rotate IIIF images from within the document edit form
- [x] this layout and approach is OK, or comment feedback/suggestions

---

At the moment, I have to hit the edit pencil under "related fragments," then in the pop up window, scroll down, and most likely enlarge the pop-up window before I can see what's on the image. 

Also, some of the IIIF images are sideways (e.g., [T-S NS 99.55](https://cudl.lib.cam.ac.uk/view/MS-OR-01080-00001-00088/1)), so it would be great to be able to rotate the images from document and fragment view. 

## dev notes
Let's switch the admin document change form to use the same image & transcription display that we're using on the public site. That way, all improvements for display and transcription will be available in both places as we improve things and build out the functionality. 

It should be easy enough to include the template snippet. What about the javascript? Should we split out search and viewer so that we can load just what's needed?

This change should also resolve #708

**Comment by richmanrachel** [comment]
@mrustow - does this earlier user story capture the same solution? https://github.com/Princeton-CDH/geniza/issues/384 

(But thank you for bringing this up again! I agree we can improve image viewing in the admin site)

**Comment by mrustow** [comment]
Ah yes that’s it — sorry, I hunted for it but was searching IIIF instead of mirador so didn’t find it.

**Comment by richmanrachel** [comment]
Closed #384 so that we could focus on the image aspect rather than Mirador specifically. Here's the phrasing of the previous issue for ease: 
"As a content editor, I would like to see the Mirador viewer for the document in the Admin Document Detail Page so I can properly consult the image while updating the metadata. #384"

**Comment by richmanrachel** [comment]
@rlskoeser and @blms - this is great for now! Can't wait until we can edit the transcriptions right there too! (which means that there should be an empty transcription box for those without transcriptions so we can add them in the future, instead of having the image take over the whole section).
