### ISSUE TITLE
In the admin interface, typing Hebrew into the language field makes Aramaic pop up instead of Hebrew. 

### ISSUE THREAD

**Issue by mrustow** [Princeton-CDH/geniza#725]
In document view, type Hebrew into the language field. This happens: 
<img width="1172" alt="image" src="https://user-images.githubusercontent.com/73319225/157782839-c4a517a8-a4b5-4e44-902e-e8e6ff4f4af7.png">

(Vivaldi 12.2.1)

**Comment by rlskoeser** [comment]
The fields we have configured to be searchable for Language+Script are `language`, `script`, and `display_name`; your search term is searching across all of these and then returning all matches, alphabetized by display name.  

Do you want me to revise which fields are searchable?

**Comment by richmanrachel** [comment]
@rlskoeser - would the search be faster/more responsive if we get rid of script?

**Comment by rlskoeser** [comment]
I don't think the speed will change much since there aren't that many records — although I do think the django built-in search isn't optimized all that well. Is it slow now?

It does seem like the script field is giving you some of the false matches — if you can find everything you need by label or language, it could make sense to drop.

**Comment by rlskoeser** [comment]
removed `script` from searchable fields in 3c78e820

**Comment by richmanrachel** [comment]
@rlskoeser - For languages it's still pretty slow... I just typed the whole word "Hebrew" and had to wait an additional few seconds for any options to come up. 

Fragment name comes up quickly in the Related Fragment section.

Footnote sources are definitely better now that I know to write the title first!

**Comment by rlskoeser** [comment]
closing per feedback on Slack from @richmanrachel that we don't need to search on `script` in this case
