### ISSUE TITLE
Design headers within the Document Detail View so that it is more clear what is a header vs content.

### ISSUE THREAD

**Issue by richmanrachel** [Princeton-CDH/geniza#730]
_This issue tracks design work through the [CDH design review workflow](https://princeton-cdh.github.io/docs/workflows/#workflow-5)._

**Description:**
The more information we add to Document Detail View, the less clear it is which words are meant as headers and which are part of the content:
<img width="549" alt="image" src="https://user-images.githubusercontent.com/68028846/157904675-5f52d110-b05c-4d0b-bf0b-4aa005aa3de9.png">

I think the solution is to design/use a distinct header style.

**Comment by rlskoeser** [comment]
This has also been resolved, I think the work must have been tracked under a different issue. Closing as a duplicate.
