### ISSUE TITLE
Bad Request 400 when trying to move attachments

### ISSUE THREAD

**Issue by alanelbaum** [Princeton-CDH/geniza#733]
**Describe the bug**
Footnotes / scholarship records / index cards / Goitein notes are often associated with the incorrect record. They also need to be moved when documents are demerged. A few months ago, I accomplished this by clicking on the pencil icon under the relevant footnote, ctrl+f to find the right entry, then changing the old PGPID to the new PGPID. A few versions ago, this started yielding Bad Request 400s. 

**To reproduce**
I've tagged some of these in Needs Review. E.g.,
1) [ENA 4011.48 (PGPID 6837)](https://geniza.princeton.edu/admin/corpus/document/6837/change/)
Card #6825 needs to be moved to PGPID 11105, but I get a Bad Request 400 when I try (Alan, 2/25/22)

2) [ENA 2739.7 (PGPID 9259)](https://geniza.princeton.edu/admin/corpus/document/9259/change/)
the Goitein attachment needs to be moved to PGPID 6688, but I get a Bad Request 400 when I try (Alan, 2/24/22)

3) [T-S 12.710 (PGPID 7336)](https://geniza.princeton.edu/admin/corpus/document/7336/change/)
card #7952 needs to be on PGPID 3200, but there's a Bad Request (400) error when I try

## testing notes
- [x] check the source edit page to confirm inline footnote editing does not include the notes field
- [x] check the document edit page to confirm inline footnote _does_ still include the notes field
- [ ] test the examples Alan identified above (make sure to try on the test site)

## dev notes

Per meeting conversation 4/13, we've decided to try reducing the number of fields displayed per footnote to see if that helps with this problem — we're going to drop the `notes` field from the footnote inline on the source edit page.

**Comment by rlskoeser** [comment]
@alanelbaum sorry for the delay on investigating this! I think the problem is that there are too many footnotes associated with that indexcard source record. Do you find that the source record is pretty slow to load, with that many footnotes? 

The particular 400 error is because Django has limits on how many form elements it allows to be submitted at a time, and saving this source record means submitting a form with all the associated footnotes.

The best thing to do would be to edit the footnote directly. I see that there isn't an easy way to get from the document detail page to the footnote. What if we gave you an edit button that took you to the footnote instead of the source record?

**Comment by richmanrachel** [comment]
@rlskoeser - I'm still getting a 400 error when I try things the way Alan did it
<img width="655" alt="image" src="https://user-images.githubusercontent.com/68028846/163268398-5dce4bd2-1411-44ca-9697-eb8eef6fec69.png">
I did not have a problem opening the document page and another tab and copying from one source into another, but I understand that's not as efficient as what Alan wants.

**Comment by zb8683** [comment]
@rlskoeser [This spreadsheet](https://docs.google.com/spreadsheets/d/1ueSUuHpw3-Cze5CMZxKGen3hYYN8zO2WP2m_pNf6lOI/edit#gid=0) has a list of bibliographic sources that Ilana was unable to save info for. I've highlighted the ones in question on the sheet., two for _In the Kingdom of Ishmael_ and one for _Palestine During the First Muslim Period_ I know Marina mentioned India Book volume 4, which is reflected on the sheet, but for some reason doesn't come up when filtering for books or when searching all sources. I have no idea where volume 4 went, which is a little concerning.

**Comment by rlskoeser** [comment]
> .... India Book volume 4, which is reflected on the sheet, but for some reason doesn't come up when filtering for books or when searching all sources. I have no idea where volume 4 went, which is a little concerning.

Sorry for the delay on looking into this. I compared records in test and production, and the [source record with db id 141 is labeled as India Book vol 4 on the test site](https://test-geniza.cdh.princeton.edu/admin/footnotes/source/141/change/) — the [same record in production](https://geniza.princeton.edu/admin/footnotes/source/141/change) has the title _Ḥalfon the Traveling Merchant Scholar : Cairo Geniza Documents_ — is that the proper title? The first few footnotes look correct to me. You could label it "India Book" in the notes for searching purposes in the admin.

**Comment by rlskoeser** [comment]
ok, now investigating the inline footnotes problems.

I've turned on an option to give you a change link so you can get directly to the specific footnote from either the source or document record — this is on the test site now, and I think gives a good solution for the problem Alan initially reported, needing to move footnotes to a different document.

However, it does not resolve the problem of updating source records that have lots of footnotes, which I know you need to do to correct the metadata.

The source record for Alan's first example — Card #6825 wrongly associated with ([ENA 4011.48 (PGPID 6837)](https://geniza.princeton.edu/admin/corpus/document/6837/change/). Footnote is linked to Goitein unpublished editions volume "ENA", which has **416** footnotes on the test site.  (Big, but not the biggest; I see one over 700).

According to a quick javascript inspection, that page has **3810** input elements on the page!  The default Django max is 1,000; I increased that to 2,000 a while back when we first ran into problems.

I checked the html, it looks like each footnote inline has 8 fields — some of them are hidden fields for form management that django needs. ( `8 x 416 = 3328` — looks like that's in the right ballpark)

I can turn off the option to delete footnotes from the inline form, so we have one less input per footnote, and I can increase the max number of form elements Django allows. The largest number of footnotes associated with one source that I see in production right now is 774 for one of the Goitein unpublished edition sources. `7 x 774 = 5418` — so I could try setting the maximum to 6,000 ? 

These source pages are unusably slow for me locally — so I'm not sure this is a great long-term solution; but Marina indicated that they are usable for her on production, so maybe it's ok, at least for now...  I also think we're unlikely to add other sources that have this many footnotes — does that seem accurate?

@richmanrachel let me know if you want me to try removing the delete field and upping the maximum number of form fields allowed.

**Comment by rlskoeser** [comment]
I found another option! There's a `django-admin-inline-paginator` library we can try. It's hard to see how well-supported it is, but it looks like it might be good enough for what we need.

Want to try it? If so, LMK how many footnotes you want to see per page. Maybe 100 ?

**Comment by richmanrachel** [comment]
@rlskoeser - I think pagination makes more sense than getting rid of the delete button! 100 should certainly be sufficient. Even 50 is probably fine.

**Comment by rlskoeser** [comment]
@richmanrachel I've implemented the pagination for the footnote inline on the admin source edit page. Please check it out and test a variety of scenarios:
- [ ] edit source record data
- [ ] edit a footnote on the first page
- [ ] edit a footnote not on the first page
- [ ] add a new footnote

**Comment by richmanrachel** [comment]
@rlskoeser - I'm not sure the work-around you implemented to get to the footnote edit page is helpful. When I was trying to do example 1, I couldn't find the correct footnote on the source page, and when I'm in the footnote I can't change the associated PGPID: 
<img width="960" alt="image" src="https://user-images.githubusercontent.com/68028846/166508857-1ba12359-40cf-497c-ae5f-2e284985f35f.png">

**Comment by richmanrachel** [comment]
Not hugely important, but a little confusing -- for some reason, the way the pagination works has a highlighted background for the page you're not on:
<img width="230" alt="image" src="https://user-images.githubusercontent.com/68028846/166509873-175587ac-05c2-49ab-98b9-3682064640ac.png">
Is this just part of the Django package we can't change?

**Comment by richmanrachel** [comment]
I now see that this type of pagination makes way more sense with more than two pages! 
<img width="461" alt="image" src="https://user-images.githubusercontent.com/68028846/166510711-29c4d129-467c-4176-b50a-77551c1fa50c.png">

**Comment by richmanrachel** [comment]
@rlskoeser - after finally finding the card #6825 on the typical edit source page, I wasn't able to save the updates the first time without fixing the language of the source. Then when I added it and tried again, I got this error message:
<img width="790" alt="image" src="https://user-images.githubusercontent.com/68028846/166512262-e1601f85-e05d-466d-abee-c300d51f2ebe.png">

**Comment by richmanrachel** [comment]
@rlskoeser and I solved it/decided this is good enough.
