### ISSUE TITLE
Create designs for stickers 

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/geniza#734]
@mrustow @richmanrachel please review the designs for stickers and let me know what you think we should or should not go with. There is a variety here, below. The ones with dashed round outlines are meant to be cut as a round sticker. And they are all 1.5 inch stickers. Mana told me the printing services print at any size. So let me know if you have preferences with the size if you have something specific in mind. ![Screen Shot 2022-03-16 at 6.44.22 PM.png](https://images.zenhubusercontent.com/5bf307a69d595b459ec91bb1/243790e8-16d9-47c9-8ae7-ced889ffafee)

**Comment by gissoo** [comment]
recording MR's and RR's comments here:
![Screen Shot 2022-03-17 at 11.35.45 AM.png](https://images.zenhubusercontent.com/5bf307a69d595b459ec91bb1/ed843a47-d481-4e46-8b2a-eb67785e2483)

**Comment by mrustow** [comment]
I would do 18/19 with vertical rather than horizontal divider. I love 22/23 -- what about trying the half/half treatment for those as well?

**Comment by mrustow** [comment]
Ah OK I agree — but what about 22/23 with the horizontal divide? 

And 18 and 19 shouldn't be divided at all, I see that now.

**Comment by richmanrachel** [comment]
I think 21 and 8/9 are my favorites!

**Comment by gissoo** [comment]
@mrustow What do you think? These are 22/23 with a horizontal divide: 
![Screen Shot 2022-03-22 at 6.25.39 PM.png](https://images.zenhubusercontent.com/5bf307a69d595b459ec91bb1/5bb93619-1015-4eaf-8c66-3f2292f4d123)

**Comment by mrustow** [comment]
Meh ... too busy. I'd go with 22 and 23 and have them both printed if possible. But I also appreciate Rachel's comment about 20-21 because they have the full name. Also I like the way the ombré effect makes it look like the page is receding into the background. I guess all in all I prefer 20-21.

**Comment by mrustow** [comment]
agree with 20, 21, 22, 23. Let's skip 8 and 9.
