### ISSUE TITLE
Create designs for PGP notebook swag 

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/geniza#735]
@mrustow @richmanrachel please review the designs for the seed paper notebook and let me know which ones you'd like and which you don't, or if you have something specific in mind. The dimension for the specific product the team has found is 3x5", so I'm following that. We will definitely ask for a sample so we can see what the colors will look like on the material. 

![Screen Shot 2022-03-16 at 6.40.56 PM.png](https://images.zenhubusercontent.com/5bf307a69d595b459ec91bb1/d2b354b4-c924-49f0-82c0-90074442d7ff)

**Comment by gissoo** [comment]
Recording MR's and RR's comments here:
![Screen Shot 2022-03-17 at 11.46.54 AM.png](https://images.zenhubusercontent.com/5bf307a69d595b459ec91bb1/b5a634a9-d7bb-47f8-9abe-67632e8d7cd9)

**Comment by mrustow** [comment]
I love both designs out to the edge.

**Comment by richmanrachel** [comment]
Agreed - they look great out to the edge! We should maybe do a sample of each kind to see how it interacts with the binding.
