### ISSUE TITLE
edit link on public document detail site doesn't work properly because of Turbo

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#738]
**Describe the bug**
Clicking the edit link on the document details page of the public site doesn't load the admin page properly.

**To reproduce**
1. Log in to the backend with an account that has document edit permission
2. Go to the public document details page
3. Click the edit link
4. See a blank public site page (header/footer but no content)
5. If you reload the page, you'll see the admin edit page correctly.

**Expected behavior**
You should see the edit page for that document in the admin without having to reload.

**Additional context**
This is a Turbo problem — Turbo is trying to load the link in the current turbo frame, and we need to tell it not to.

**Comment by richmanrachel** [comment]
Fixed!
