### ISSUE TITLE
As a content editor, when I change the shelfmark for a fragment I want the previous shelfmark automatically added to the list of historic shelfmarks in order to keep track of old identifiers.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#74]
## Testing notes
- [x] Change the shelfmark of a fragment and ensure that the change is reflected under "historical shelfmark"
- [x] Change the shelfmark multiple times and ensure that (1) all shelfmarks under "historical shelfmark" are unique and (2) the current shelfmark is not duplicated in the historical shelfmark

## dev notes
- [x]  copy TrackChangesModel from mep/ppa — https://github.com/Princeton-CDH/mep-django/blob/main/mep/common/models.py#L143 
- [x] set `Fragment` to extend TrackChangesModel
- [x] adapt slug tracking logic from mep: on save, if shelfmark has changed, add the old one to the list of historic shelfmarks (see https://github.com/Princeton-CDH/mep-django/blob/main/mep/people/models.py#L480-L486 ); we can either keep historic shelfmark as a text field and delimit with semi-colons, or try out the postgres-specific arrayfield: https://docs.djangoproject.com/en/3.1/ref/contrib/postgres/fields/#arrayfield 
- [x] make sure historic shelfmark list only includes unique entries when updating
- [x] configure historic shelfmark to be read only on django admin edit form
- [x] update help text for shelfmark / historic shelfmark as needed/appropriate

**Comment by richmanrachel** [comment]
Works beautifully!
