### ISSUE TITLE
As a content editor, I want access to manuals and other documentation when I'm editing records, so that I can easily find relevant guidelines for my task.

### ISSUE THREAD

**Issue by zb8683** [Princeton-CDH/geniza#745]
**Help text and locations:**
For questions on the purpose of fields and how to complete them, refer to [PGP Database User Manual](https://docs.google.com/document/d/1_2XcTtkX-YwRBwTDQK5CevdlHpVt3_4fwmfli_3on88/edit#)
Location: below top shelfmark/PGPID heading

Refer to [language tagging section](https://docs.google.com/document/d/1_2XcTtkX-YwRBwTDQK5CevdlHpVt3_4fwmfli_3on88/edit#heading=h.yktzf2k3khi4) of user manual
Location: below language fields

Refer to [description guide](https://docs.google.com/document/d/1bC_P5Bgvve4O7PgcbLtReTM62H4oywDYzypfPz4xEPo/edit#heading=h.z1t5kmwpib9z)
Location: below description

Names should not be anglicized; use the [following transliteration conventions](https://docs.google.com/document/u/0/d/12cch8bYqH3XihjppiylO2B5aAEVfRBCTd9_KqzysGhc/edit)
Location: below description guide

Refer to [Date section of user manual](https://docs.google.com/document/d/1_2XcTtkX-YwRBwTDQK5CevdlHpVt3_4fwmfli_3on88/edit#heading=h.ucsc09avy3y3)
Location: between calendar and document date standardized

Use [a calendar converter](https://www.fourmilab.ch/documents/calendar/)
Location: below “CE date (convert to Julian before 1582, Gregorian after 1582)” etc.

[Google Doc version](https://docs.google.com/document/d/1ZlJHnbjOPparGi3WN8QEcs-HBXRlsUm1WsFDBmuRmxM/edit)

**Comment by richmanrachel** [comment]
Closing. Created #1712 instead
