### ISSUE TITLE
Revise the new order of content on the doc detail page and ensure the backend aligns with the interface

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/geniza#747]

**Comment by gissoo** [comment]
@rlskoeser please take a look at [the proposed order of the content here](https://www.figma.com/file/anZFStv7zBaVWnFxr95nKt/Work-in-Progress-%2F-WIP?node-id=1184%3A35954), I would like to make sure I have your agreements and/or disagreements with these ideas: (plz let's NOT discuss the styling and layout here)

After discussing with Marina and Rachel the following are what they specifically desired and thought would be best: 

1. Shelfmark and Editor are more important, therefore are placed on one side
2. The rest (doc date, primary and secondary languages) are placed together on the right
3. the tags are grouped separately, placed below the two columns and would take over the width of the two columns and then wrap to the next line
4. The input date is now more human-readable as "in PGP since ...", thanks to Marina!! And it's placed right below the tags because it is indeed something that scholars look for when viewing docs. 
5. The permalink was decided to be at the bottom of the page, MR and RR argued that it's not something that would need to be anywhere on top or the middle of the page. – I suggest it stays outside of the transcription panel and just below it.

**Comment by rlskoeser** [comment]
@gissoo this order and placement looks great to me. Thank for explaining the rationale. Will you do something on mobile to indicate the right-side group on desktop are less important, or is order sufficient?

I like giving the tags more space.

The "in PGP since ... " language is great!

Permalink at the very bottom makes sense to me, looks good where you have it.

**Comment by gissoo** [comment]
@rlskoeser Thanks!! I don't think doing anything differently on mobile about the right-side group is necessary – not sure what the goal would be since they are now both left-aligned - let me know if you are detecting any potential issues that I may not be seeing

**Comment by gissoo** [comment]
@rlskoeser Also, I asked about the image permissions statement for docs with multiple shelfmarks and MR noted that we should do it on a "shelfmark by shelfmark basis" – indicating for each shelfmark. Please ask during our meeting tomorrow if this is unclear.

**Comment by rlskoeser** [comment]
> @rlskoeser Thanks!! I don't think doing anything differently on mobile about the right-side group is necessary – not sure what the goal would be since they are now both left-aligned - let me know if you are detecting any potential issues that I may not be seeing

It looks like the right column fields are "grouped" on mobile based on the spacing (I wasn't sure how to comment because you said not to discuss layout!) — the grouping to me indicates that those things belong together more than that they are secondary. Is there a reason not to keep the spacing consistent on mobile so the fields are evenly spaced? Also remember that these are all optional and we will often not have them. Will the extra space look weird if there is only one field? (e.g., we only have a date, or we only have a primary language)

**Comment by rlskoeser** [comment]
> @rlskoeser Also, I asked about the image permissions statement for docs with multiple shelfmarks and MR noted that we should do it on a "shelfmark by shelfmark basis" – indicating for each shelfmark. Please ask during our meeting tomorrow if this is unclear.

That makes sense. Could you suggest how to revise the current layout? Probably not worth a lot of your time if this is provisional; could we just bold the shelfmarks and put each one on a separate line?

**Comment by gissoo** [comment]
> > @rlskoeser Thanks!! I don't think doing anything differently on mobile about the right-side group is necessary – not sure what the goal would be since they are now both left-aligned - let me know if you are detecting any potential issues that I may not be seeing
> 
> It looks like the right column fields are "grouped" on mobile based on the spacing (I wasn't sure how to comment because you said not to discuss layout!) — the grouping to me indicates that those things belong together more than that they are secondary. Is there a reason not to keep the spacing consistent on mobile so the fields are evenly spaced? Also remember that these are all optional and we will often not have them. Will the extra space look weird if there is only one field? (e.g., we only have a date, or we only have a primary language)
>

- @rlskoeser sorry ...Ahh! Yes there is spacing, sorry I missed that ...Your point is valid, but they were grouped by spacing when they were right-aligned as well! I think it's better to give it some spacing for readability and creating some sense of what group of info is more stable and prominent and what isn't. But I can see what you are saying too.

**Comment by gissoo** [comment]
> > @rlskoeser Also, I asked about the image permissions statement for docs with multiple shelfmarks and MR noted that we should do it on a "shelfmark by shelfmark basis" – indicating for each shelfmark. Please ask during our meeting tomorrow if this is unclear.
> 
> That makes sense. Could you suggest how to revise the current layout? Probably not worth a lot of your time if this is provisional; could we just bold the shelfmarks and put each one on a separate line?
>

thanks @rlskoeser I did exactly what you suggested since I would have done the same thing :) – I just added some paragraph spacing to make them easier to read – the text is just a sample and I didn't list all the shelfmarks, but just pay attention to the formatting on desktop and mobile. The spacing between each shelfmark is 12px on desktop and 8px on mobile.
