### ISSUE TITLE
Revise the styling of fields and labels and notes on the doc detail page 

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/geniza#748]

**Comment by gissoo** [comment]
@rlskoeser I would like to have your agreements and/or disagreements on the the layout and styling decisions below, [here are the designs](https://www.figma.com/file/anZFStv7zBaVWnFxr95nKt/Work-in-Progress-%2F-WIP?node-id=1184%3A35954):

1. MR and RR's initial decisions about the order of the fields on this page were being affected by how well they were reading the content – they mentioned they find it a lot easier to read the content if the right column stays left-aligned (it was right-aligned in the designs before) – therefore I have made some adjustments here with its width in relation to the left column – the left column is taking %48.7 of the width, the right column is taking %45, and the space between the two is about %6.18 (note: the full width is 566px) – let me know if this info is helpful – because now the right column can look very misaligned and "in the middle" in relation to the rest of the page if the width of both columns are equal – they would stack on mobile!

2. MR and RR both like having the bold as well as the green indicators for the labels.

3. because of the new language of "input field" I have revised the styling, so no need for a bold label – I have slightly lightened it using this color, #595959 – let me know if adding a new color is something we should avoid, and we could just use the #3d3d3d, I'm fine with it, it's a subtle change. 

4. Permalink is supposed to align with the margins of content in the transcription panel
because it's easier to see and read it after scrolling down from that panel (on both desktop and mobile)

5. MR and RR are fine with keeping the collapsible option for the image permissions statement – I did note to them that I'm thinking it could rather go into a new tab in the transcription panel – so might change as we talk about the transcription panel sketches

NOTE: I have placed spacing guides on the mockups – please let me know if you have any questions.

**Comment by rlskoeser** [comment]
Thanks for all of the details here about what you're changing and why. Everything looks great to me.

1. interesting about alignment & readability but it makes sense to me. Also interesting that the spacing needs to be other than 50/50 to make it look balanced.
2. I like the combination of green indicators and bold too, glad we're going with that.
3. New color is ok with me as long as it passes accessibility contrast checks.
4. Permalink alignment makes sense to me.
5. Great. We can easily make it collapsible in the short term and then revisit later if needed.

**Comment by gissoo** [comment]
@rlskoeser thank you! The color passes all the accessibility contrast checks. The green indicator is 8x16px and it's 12px away from the text next to it. I will go ahead and close now
