### ISSUE TITLE
Implement the flipped order of tabs for RTL 

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/geniza#754]
[Here are the designs on Figma](https://www.figma.com/file/anZFStv7zBaVWnFxr95nKt/Work-in-Progress-%2F-WIP?node-id=1014%3A25846)

**Comment by blms** [comment]
I believe this one is already done—@gissoo gan you confirm on the QA site?

**Comment by blms** [comment]
@gissoo Thanks! Yes, it's my understanding that the translations are preliminary, so out of scope for this issue I think. OK to close, then?
