### ISSUE TITLE
As a user, when I’m reading transcription text, numbered lines should only wrap when necessary (based on display width), so that I can see more clearly how the lines match up with the original.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#755]
## testing notes
- [ ] review the TEI changes on bitbucket : https://bitbucket.org/benjohnston/princeton-geniza-project/pull-requests/20 
- [ ] look at a variety of documents modified and compare on production and test sites to see how the lines have been adjusted
- [ ] when lines are combined, is the order correct?

## dev notes
- [x] clean up with identity transform so semantic changes will be easier to identify
- [x] cleanup labels that are mistagged as lines to avoid consolidating with lines
- [x] cleanup line numbers that are in content instead of attributes
- [x] write an xslt to consolidate unnumbered lines following a numbered line 
- [x] run new xslt against all current TEI transcription files; review locally to check changes
- [x] open pull request for review before merging in changes
- [x] update staging site with content from pull request branch to review in context
- [x] don't wrap lines that only include dashes or dots and whitespace
- [ ] don't wrap lines with single letters and apostrophes
- [x] remove lines with only single bracket or ampersand

**Comment by rlskoeser** [comment]
ok @richmanrachel,  I'm ready for a first round of review on the transcription line cleanup work.

I've modified a set of TEI documents and opened a pull request for those changes on the bitbucket transcription repository, and I've loaded that version of the transcription content into the test site for review.

What I would recommend is that you work from the bitbucket pull request I've opened so that you can look at the changes in the TEI, and then use the PGPID from the filename to look at the content on the test site; it may also be helpful to compare the same document on the production site.

There are 710 files changed — I don't expect you to look at all of them on the site! Please look at enough to see what's going on and give me feedback on my questions below; once we make some decisions I can refine the logic and run the conversion again to skip the things we don't want to wrap. 

I have some questions about specific things I noticed, wanted to get input before revising the logic:
- some transcriptions have what about lines like this `----- `;  see 1461 for an example; 1772 for another; my guess is that these should not be wrapped, but would like to know why they are in the transcription
- some lines only have spaces and periods (1685, 1690, 1816, others); should these also not be wrapped
- other documents have lines with spaces and a few characters or fractions; for example, see 1679, 1698. Should these also not be merged? What are these lines?
- 1736 has a line that looks like a label but it is in brackets; should I edit and convert to label without brackets?
- a few records have a line with just a curly bracket `{` (e.g. 2522, 2523); should those lines not be merged? a few others have just an ampersand on a line by itself (2693)
- there is a footnote in 4766 that got mangled in my conversion (wasn't expecting nested tags); do I have your ok to remove the footnote?

**Comment by richmanrachel** [comment]
@rlskoeser - starting from your questions first:
1) The dotted line in 1461 seems to be separating two documents on the same fragment. In 1772 I can't tell if it's just a messed up way of trying to indicate that there's a box around the name of the signatory or what.
2) 1685, etc, are using periods to show that this is the middle of a fragment and we don't know what's missing. So correct - they should not be wrapped.
3) 1679 is more complicated - it seems like the Coptic numerals are interlinear editions to make it easier for someone to eyeball the amounts of products being sold. But on neither the test nor production site are these amounts spaced properly on the transcription to align how they should in the document. 1698 is one of those authentication signatures where mini-letters are added above and below the person's name. I don't think either of these should be merged, but they should perhaps be revisited when we can add annotation labels.

**Comment by richmanrachel** [comment]
4. re: 1736, yes, you're correct that Gil is trying to indicate where the second part of the join begins. The shelfmark is a label.
5. The curly brackets in 2522 and 2523 are errors (or an outdated way of indicating the text will continue on another part of the document) and can be deleted. 2693 ampersand also seems to be an error that should be deleted.
6. I can't seem to get into Bitbucket to understand what happened with the footnote. But we don't believe in footnotes for editions on the web, so removal should be fine.

**Comment by richmanrachel** [comment]
@rlskoeser - in sum, it looks like your logic did everything correctly! There's just some messiness on our end that was confusing you. 

I checked a few additional docs I've been working on recently, and the transcriptions all look right!

**Comment by rlskoeser** [comment]
since you're having trouble accessing bitbucket, I'll give you some pgpids and line numbers to check:
- pgpid 1064 lines 10 and 17
- pgpid 1080 lines 28 and 18
- pgpid 1088 line 17
- pgpid 1113 lines 26 and 28 (I think this is one of those where lines should not be combined)
- pgpid 1156 line 13
- pgpid 1197 line 2 — what to do with "in reverse writing"? would normally convert to a label but it includes hebrew script and I wasn't sure how to separate 
- pgpid 1217 lines 15 and 22
- pgpid 1250 several lines combined
- pgpid 1253 lines 15, 26, and verso 1
- pgpid 1386 — almost every line

examples of blank lines being removed:
- pgpid 1328 blank line removed after line 10
- pgpid 1330 several blank lines removed
- pgpid 1401 blank line after 15

**Comment by richmanrachel** [comment]
1080: שוליים ימניים is a label "right margins" and should not be wrapped
(sorry, can't figure out how to make that next RTL after pasting the Hebrew phrase

**Comment by richmanrachel** [comment]
1088 has a bigger problem... it's a duplicate/join with 5965, but I can't find the text marked in 1088 as "verso" anywhere in the document. This one we should hand off to Alan.

**Comment by richmanrachel** [comment]
1197: I don't see any reverse writing... even the slashes in that last word of line two are not necessary.

**Comment by richmanrachel** [comment]
1217 has a bunch of inline corrections and alternate readings. For example, in line 22, the ? is showing that Goitein isn't sure the word should be read "Torah" and then he adds in parentheses that Motzkin read it as "sharīʿa", then he goes on to correct what he sees as misspellings by the author. Not sure what we want to do with these, but hopefully this helps you read what's going on!

**Comment by richmanrachel** [comment]
1253: did you get the PGPID right? the document I'm looking at only has 18 lines...

**Comment by rlskoeser** [comment]
> 1253: did you get the PGPID right? the document I'm looking at only has 18 lines...

I must not have! I was worried I was going to typo one of them. You've probably looked at enough to get some idea of what's going on. I am going to need help on figuring out what we need to do about some of these, would be great to have Alan take a look once I refine the line wrapping logic.

**Comment by richmanrachel** [comment]
@rlskoeser - Yes, I think overall what you're doing is correct.

1330 is just super messy.

The others that I didn't mention above are all correct (1064, 1156, 1250, 1386, 1328, and 1401)

**Comment by rlskoeser** [comment]
@richmanrachel I've made some changes and would like another round of review. 

I couldn't figured out a pattern to identify the lines that include interlinear corrections or accents. Sometimes it's single characters separated by spaces, sometimes more than one character, sometimes there are apostrophes, sometimes not; sounds like sometimes there are whole words.  Maybe we need to add an attribute in the xml to flag them for what they are, so I can ignore them now and so we an identify them when we revisit this content later on.

I removed single lines with just an open or close bracket or two ampersands (those changes are already in the main version of the TEI files), and fixed a couple more mis-tagged labels.

I've revised my earlier stylesheet to ignore lines that only have spaces and periods, dashes, or underlines.

The updated pull request is on bitbucket; 612 files have been modified: 
https://bitbucket.org/benjohnston/princeton-geniza-project/pull-requests/20

I ran the sync transcription script on the test site against this branch of the TEI files so you can see how the revised lines display on the site.

I think someone with bitbucket access needs to look at the changes on bitbucket and compare how things look on the test site. It's a lot of files to check, but hopefully most of them can be flipped through fairly quickly.

**Comment by rlskoeser** [comment]
@richmanrachel does it make sense to you if we close this TEI wrapped line cleanup task as a "won't fix" now that we've confirmed in #1038 that we can migrate the content in a way that preserves the line numbers and makes them easy to cleanup in the new editor?

**Comment by richmanrachel** [comment]
@rlskoeser - works for me!
