### ISSUE TITLE
As a content editor, I want to add block-level transcription to documents with images so that I can make existing transcription content available in the site.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#757]
## testing notes 2 (qa)

Using the [new transcription page](https://github.com/Princeton-CDH/geniza/issues/911):
- [x] Confirm images are loading
- [x] Confirm you can save/edit/delete transcriptions on PGPID 11248

## notes for testing
Go to the test site and make sure you are logged in as a content editor. Find a document with images associated and go to the public document details view.  If you navigate from the public search, you will need to reload the page because the transcription javascript doesn't play nicely with turbo yet.

At the right of the image/transcription view you should see a "transcribe" button, which will put you into transcription/annotation mode.

Please try creating, editing, and deleting some test annotations. Here are some things you may want to try:
- [x] draw a rectangle on the image then cancel
- [x] draw a rectangle on the image, add any text, and save
- [x] reload the page and re-enable transcription mode — confirm that the text you added was saved and persistent
- [x] click the text block or the rectangle on the image to edit
- [x] change the text and save
- [x] change the image selection zone and save
- [x] delete a saved annotation, then reload to confirm it was removed from storage

We're aware of an issue where editing the zone on the image and then updating and saving the text reverts the zone back to what it was before you changed it. You will likely find others!

## dev notes
- [x] add a toggle between view and edit modes if user has permission
- [x] edit mode turns enables Annotorious with at least rectangle select
- [x] #758
- [x] #759
- [x] attach annotations to canvas id instead of image
- [x] #930

**Comment by richmanrachel** [comment]
@rlskoeser - another little error, because I just reloaded the test admin page I was on and saw that "transcribe" was an option: I clicked it and it acted like the "save" button, saving changes and sending me back to the document list view.

Then I moved to the public test site, and "transcribe" just zooms me in on the image. I can't seem to draw boxes or anything....

**Comment by rlskoeser** [comment]
ah, yeah — forgot to warn you that the transcribe functionality is partially present in the admin view but I don't expect it to be operational right now. 

You have to hold shift before you click on the image — sometimes the first time I try it moves the image and the next time it lets me select a zone.

**Comment by richmanrachel** [comment]
Update: drawing boxes was not possible for me on Chrome Version 101.0.4951.54 (Official Build) (arm64)

I was able to draw boxes (and delete them via the esc button) on Safari Version 15.1 (17612.2.9.1.20)

But even on Safari, I couldn't figure out how to add/edit text. There were also some weird issues with the boxes as I was zooming/moving around the screen (here you can see how half of it disappeared):
<img width="611" alt="image" src="https://user-images.githubusercontent.com/68028846/168167375-7a40a435-11bc-4628-a087-2c4c36dee48f.png">

**Comment by richmanrachel** [comment]
[That's also really strange that my screenshot inverted....]

@rlskoeser - Am I supposed to see any menu items to help guide me where to transcribe? I don't see a text box, and when I started typing to see if it filled in the existing box, it just moved me around the screen.

**Comment by richmanrachel** [comment]
With some troubleshooting through private Slack messages, I figured out my browser window at first wasn't wide enough to show the transcription options.

For whatever reason, @rlskoeser's test on PGPID 2806 is working and saving, but Rachel's on 11248 doesn't save. Perhaps it's because 2806 has an existing transcription and 11248 doesn't? 

I can't get the boxes to resave in different configurations.

**Comment by rlskoeser** [comment]
A few more notes from discussion with RR on Slack yesterday:
- transcription editing should be on a separate page, not embedded on document details or document admin edit form (although it should be linked and accessible from both for those who have permission); this is better for implementation anyway, since it simplifies permissions checks (happen at the view-level) and turbo integration (transcription page can break out of the turbo frame)
- transcription interface needs to be much more responsive than the current prototype is; e.g., RR wants to use the browser at half-width on a laptop screen so she can refer to other sources as she works on the transcription. Gissoo's designs for image + transcription should help significantly here.
- content editor permissions are appropriate access for allowing transcription (probably key on permission to edit documents)

**Comment by rlskoeser** [comment]
I tested making an annotation on a document that has a CUDL image and it worked fine; I have a suspicion the problem may be the image ids we have for JTS/Figgy content, maybe we're not urlencoding the urls properly. I think we'll be adjusting what ids we use to attach our annotations, but this is good to be aware of and make sure we test on both sets of content.

**Comment by mrustow** [comment]
I tested everything with a CUDL image (PGPID 18622) on Vivaldi and it all worked perfectly. My only complaint is that the image box is small; I couldn't both read as up-close as needed and see the entire line. I have some suggestions there but I'll hold off until design implementation.

**Comment by richmanrachel** [comment]
@rlskoeser - any updates on this one? It's been tagged with "tested needs attention" since May.

**Comment by richmanrachel** [comment]
@rlskoeser - the images aren't really loading on the transcribe page (I tried this PGPID and 2 others with CUDL and ENA). They flash on and then disappear :(

**Comment by richmanrachel** [comment]
@blms and @rlskoeser - for some reason the transcription edit button has disappeared... I have the top admin edit button, but not the transcription one

**Comment by richmanrachel** [comment]
It works! Closing!
