### ISSUE TITLE
Implement the search results page in RTL orientation so that the page can be read properly in Hebrew and Arabic 

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/geniza#769]
## Testing notes (QA)

On the QA site, switch to Hebrew and navigate to the search results page and confirm:
- [ ] Search results look correct on mobile and desktop
- [ ] Tag orientation looks correct
- [ ] "PGP ID" is not translated

~~Two things that I know are different are the document type + shelfmark pair (e.g. "Letter," "Legal," followed by a colon and shelfmark) and the tags (hash symbol before the tags in RTL). Should these change to match the designs and/or do we need to consult with folks about these?~~

---

[Here are the designs on Figma](https://www.figma.com/file/anZFStv7zBaVWnFxr95nKt/Work-in-Progress-%2F-WIP?node-id=1225%3A30407)

@blms Note: the PGP ID field won't be translated. I'm yet to find out whether it is ok for it to be positioned RTL – will inform you once I find out, I think for now it's ok to assume that it will have a RTL orientation.

**Comment by richmanrachel** [comment]
This seems to be a constant feature of switching between languages on computers, but is there anyway that periods/other punctuation can remain in their proper LTR position? 

As you can see in this screenshot, the punctuation moves to the lefthand side, making it especially confusing in entry 11 where the ellipses is meant to indicate that the description continues (not a strange gap before the quotation):
<img width="682" alt="image" src="https://user-images.githubusercontent.com/68028846/165999588-65e336fb-6fc5-4292-963a-455ec9d0b720.png">

**Comment by gissoo** [comment]
@blms thanks!! I agree with Rachel's comment above, it's problematic. 
I think there are three parts that need to match the designs, 1. Marina had said the PGP ID label shouldn't be translated in the design stage 2. the title of the document should be "document type: shelfmark number", it's hard to read it in the current implementation now – sorry if my note in the issue description is confusing, I meant it should still read just like the LTR, e.g. "Legal: T-S 24.11 +", however it should be right-aligned in the container so it's matching with the rest of the fields. I'm still going to double check this whenever I resume working on the RTL issues. 3. the orientation of the tags (should be left-aligned), it's hard to read them with the hashtags all being RTL.

**Comment by blms** [comment]
Punctuation etc. in English document types and descriptions showing up in the RTL site have been split off into separate issues:  #842 and #843

**Comment by gissoo** [comment]
@blms the document title looks correct now. So the placement of the tags and the translation of the PGP ID field will be covered in the other two issues? If yes, then please feel free to close this. Thanks for tackling this!

**Comment by gissoo** [comment]
@blms I was referring to my previous comment above and noticed the orientation of the tags is still on the right. According to the designs that I had linked in the description of this issue they should sit on the left, (which I think was a decision Marina and I and Rachel agreed on at our meeting back then).

tags look like the below in the designs I'm looking at. 
<img width="269" alt="Screen Shot 2022-05-09 at 11 48 41 AM" src="https://user-images.githubusercontent.com/44615389/167447918-32857f3a-d4c9-489f-99a5-045ec0904ddc.png">
