### ISSUE TITLE
Implement the revised document detail view fields on top of the page on desktop and mobile 

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/geniza#774]
## testing notes (QA)

- [x] On the QA site, confirm that the document detail view looks and works as expected (light/dark, mobile/desktop)
- [x] Check a range of documents with different amounts of information. (Some examples: [845](https://test-geniza.cdh.princeton.edu/en/documents/845/), [3435](https://test-geniza.cdh.princeton.edu/en/documents/3435/), [6021](https://test-geniza.cdh.princeton.edu/en/documents/6021/), [12053](https://test-geniza.cdh.princeton.edu/en/documents/12053/), [13745](https://test-geniza.cdh.princeton.edu/en/documents/13745/),  [14810](https://test-geniza.cdh.princeton.edu/en/documents/14810/), [23195](https://test-geniza.cdh.princeton.edu/en/documents/23195/))

---

[Link to mock-ups on Figma](https://www.figma.com/file/anZFStv7zBaVWnFxr95nKt/Work-in-Progress-%2F-WIP?node-id=1184%3A35954)

- [x] order of editor, primary and secondary language fields 
- [x] alignment for fields on the right column (left-aligned now) 
- [x] alignment for the tags and the "in PGP since" fields (taking the full line) 
- [x] green bullet styles, 7BAC7 for light mode and C37F97 for dark mode – shown on the side of the mock up annotated in red
- [x] all field label font styles (bold) 
- [x] color for the "In PGP since" text: 595959 on light mode and CFCFCF on dark mode
- [x] placement of the permalink field (at the very bottom of the page, above the footer) 
- [x] link phosphor icon on the circle next to the permalink label (f7f7f7 icon on a 3d3d3d circle for light mode and the reverse for the dark mode – shown on the side of the mock up annotated in red) – size of the circle is 22px on desktop and mobile 
- [x] spacing between the two columns as well as the columns with the tag and "In PGP since" fields, and the permalink with the transcription panel – all marked in red on the mock-ups.

**Comment by gissoo** [comment]
@blms thank you!! 

- Could you remove the spacing between the editor field and the primary language field on mobile here? 
I agree with Rebecca, that spacing is not necessary on mobile and it's really weird on cases like this, sorry. 

<img width="312" alt="Screen Shot 2022-04-22 at 6 52 52 PM" src="https://user-images.githubusercontent.com/44615389/164814762-2e20ab36-0bdc-4d99-8cd2-4ab29781c280.png">


- I also forgot that we got rid of the line that was sticking on the left of the green line in tabs – could you align the columns with the tabs? – the green indicator for the fields on the first column is falling slightly off on the left of the tab – it looks weird 

<img width="859" alt="Screen Shot 2022-04-22 at 6 54 48 PM" src="https://user-images.githubusercontent.com/44615389/164814893-a5ce99a6-a7d5-4dd5-b122-7f4448cccbfa.png">

**Comment by gissoo** [comment]
> @gissoo I have a couple of questions on this one before I move forward:
> 
> > the spacing between the tags looks so awkward, should we consider a faded colored background/highlight instead of a link style?
> 
> That would be fine with me, did you want to come up with a design for this before I move forward, or open a new issue instead?
> 

- Yes! That's a good idea! I will open a new issue! 

> > could you align the columns with the tabs? – the green indicator for the fields on the first column is falling slightly off on the left of the tab – it looks weird
> 
> Should all of the content have width reduced to align on both sides with the tabs, then? You can see other fields also fall outside of that—I've marked those with red lines here:
> 

- @blms yes! Thanks! That's how it was in the designs, we forgot to catch the alignments when you decided to cut the edges of the tab borders. 

> <img alt="Screen Shot 2022-04-25 at 11 26 43 AM" width="686" src="https://user-images.githubusercontent.com/7234006/165128263-921be1dd-6b43-4ecb-b9fc-4ec1e47d0f2f.png">

**Comment by richmanrachel** [comment]
Not sure if I'm supposed to comment on this (but trying to be diligent and look at all open issues awaiting testing!), but the spacing overall looks good to me! The only issue I'm seeing (and no worries if this is out of scope or will be irrelevant soon enough anyway) but the borders for scrolling the transcription on dark mode look funky and nearly cut off the line numbers:
<img width="934" alt="image" src="https://user-images.githubusercontent.com/68028846/165998596-e700acca-8de8-4e87-83f5-7e644ab0ed06.png">

**Comment by gissoo** [comment]
@blms thank you!! Everything looks great! The only thing I noticed is an inconsistency in the weight of the tags' green underlines on Firefox (the mobile view of the desktop browser), only on 3435 – ignore me if you can't replicate it, also not sure how much it matters since there is already an issue to revise the tag styles, but odd that it's only on 3435
![Screen Shot 2022-05-02 at 3 56 45 PM](https://user-images.githubusercontent.com/44615389/166316418-90d4ac29-a8fb-4272-a075-192d102855a1.png)

**Comment by blms** [comment]
Can't replicate, I'm wondering if somehow your browser did some scaling when you switched to responsive design mode?

<img width="471" alt="Screen Shot 2022-05-02 at 4 06 36 PM" src="https://user-images.githubusercontent.com/7234006/166317898-0716ce9f-9a55-406a-ade5-27e26723f84a.png">

Either way, I'll close since you said to ignore if I can't replicate! Feel free to open a bug issue if it comes up again after the tags redesign though.
