### ISSUE TITLE
Design for when an image is not available

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/geniza#787]

**Comment by gissoo** [comment]
@mrustow @richmanrachel please only look at the missing fragment component below (we'll discuss the other parts in separate issues) and let me know:
**1.** if you are OK with the statement for when we have a link to the source of the fragment – "To view this fragment visit URL " – please suggest a language if this is not correct.  
**2.** the placement of the  – when we have a link to the source of the fragment. 
![Screen Shot 2022-04-28 at 2.16.42 PM.png](https://images.zenhubusercontent.com/5bf307a69d595b459ec91bb1/149ff0a1-b69c-4190-b838-a4cfd755b063)

![Screen Shot 2022-04-28 at 2.17.38 PM.png](https://images.zenhubusercontent.com/5bf307a69d595b459ec91bb1/7ef65918-aea4-4d28-bc0b-ae457507ecc6)



![Screen Shot 2022-04-28 at 2.10.03 PM.png](https://images.zenhubusercontent.com/5bf307a69d595b459ec91bb1/8ecab5b4-92f1-4979-8c4f-bf41cfc32771)

![Screen Shot 2022-04-28 at 2.10.21 PM.png](https://images.zenhubusercontent.com/5bf307a69d595b459ec91bb1/26af73aa-5ad2-4611-baf2-7f7756f5421e)

**Comment by mrustow** [comment]
Wording: fine as is, just insert a comma after fragment. I don't understand the second question.

**Comment by richmanrachel** [comment]
@gissoo - I don't understand the question about the dash either. 

Perhaps we want to change the word "URL" to "FGP" and have it be an active link? Or will we be linking to stable images from non-IIIF collections here too?

**Comment by gissoo** [comment]
@mrustow @richmanrachel thanks, your suggestions are helpful, will do. Sorry, second question was meant to be about the placeholder text's position on the page relative to the rest of the content and if you're ok with it. 

Rebecca let me know that there is more than one type of case to handle for this, I'm pulling back this issue to work on the other cases.

**Comment by richmanrachel** [comment]
@gissoo - yes, text placement is fine!

**Comment by gissoo** [comment]
Note: in this issue we are not dealing with image URLs, I'll create a separate issue for that. 

@rlskoeser [this is what we agreed on for cases when only some images are available ](https://www.figma.com/file/anZFStv7zBaVWnFxr95nKt/Work-in-Progress-%2F-WIP?node-id=1562%3A40673).
- When only some images are available, for the ones that are missing the agreed language and capitalization is as follows, "Image not available in PGP"
- We'll display the shelfmark, and I've left the side info for now but informed Marina that we probably won't be able to display as you'd mentioned. 

[This is what we agreed on for when no images are available ](https://www.figma.com/file/anZFStv7zBaVWnFxr95nKt/Work-in-Progress-%2F-WIP?node-id=1562%3A41794) 
- we will not display the image panel and it will be in disabled mode.

**Comment by rlskoeser** [comment]
This looks great to me.
