### ISSUE TITLE
Design a way to paginate between images 

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/geniza#788]
- note: no pagination is necessary when the all items within one record type are displayed (for instance: all images)

**Comment by gissoo** [comment]
@rlskoeser Please take a look at the pagination styles on the transcription panel – Marina suggested that on mobile we display only one set of records on each page, unlike desktop where we display two. After much contemplation I decided to keep the pagination display the same on desktop and mobile. What this means from my pov is: on desktop "1/2" means you're viewing page 1 of 2 which contains two sets of records, and on mobile it's "1/4" which means you're viewing page 1 of 4 which contains one set of records. Let me know if this is disastrous – I'd like to avoid changing pagination formats between desktop and mobile. 

![Screen Shot 2022-04-28 at 1.25.45 PM.png](https://images.zenhubusercontent.com/5bf307a69d595b459ec91bb1/d394b586-48d3-4b68-be6f-f7ca70b0b403)

![Screen Shot 2022-04-28 at 1.25.14 PM.png](https://images.zenhubusercontent.com/5bf307a69d595b459ec91bb1/de969036-2484-4fcd-8c04-ca0bd03f3a59)

**Comment by rlskoeser** [comment]
@gissoo thanks for flagging this. I understand the logic and can see how this approach makes sense for the user.

It definitely makes the implementation more complicated. I'm not sure whether it's _disastrous_ exactly...  But it will require a different approach than typical responsive css. I can see a few ways we might approach it, although I'm not sure how well I like the ideas I'm coming up with now. (e.g., do we have redundant logic/pagination in the html that we disable/enable based on screen size? do we paginate entirely in javascript? neither one seems ideal.)

The starting point question for me about implementation is how much of this functionality can we reasonably implement (and should implement) without javascript and then how can we progressively improve that version. i.e., if you look at the page with javascript disabled, do you see an unpaginated version? the mobile version? 

I really like the idea of showing two pages at once on desktop, but I can see why that doesn't work on mobile. How much extra value does the two page layout give to the researchers? Is it worth the extra complexity to implement and design, or would it be better to keep it more consistent?

**Comment by rlskoeser** [comment]
(unrelated to the question you asked, but it's so exciting to see these designs and think about implementing them)

**Comment by richmanrachel** [comment]
@gissoo and @rlskoeser - I like this in theory, but am worried about it creating more problems:

1) Would we have to go through every single image and delete/remove the manifest of the verso image for all documents that just are on the recto, for example? We do not have the metadata delineating where most of our documents are on the fragment, so this would be a massive datawork problem that requires someone with decent paleographic skills to determine.

2) Is the transcription model already strong enough to highlight areas on the image, so that if the verso contains the address for document 1 on the recto, we keep the whole verso image but highlight the address?

3) Most documents really are on a single fragment, so not paginating will usually be okay. But @gissoo, have you tried a mockup of the Sa'adya bifolio or one of the multi-page docs to see if this will be okay at the extreme end?

**Comment by gissoo** [comment]
@rlskoeser @richmanrachel @mrustow documenting: 
1. Marina agreed with not paginating for now, 
2. Marina and Rebecca also agreed to the proposed format and placement for the source information/citation. 3. Marina stated the citation would need to have page and volume info (mostly book citation format). 
4. Marina and Rebecca also agreed with the truncated version of the drop down on mobile (won't probably need truncation on desktop) – this is for multi-authored cases
5. Marina agreed on displaying the record type (i.e. "Translation" or "Transcription" once on the panel at the top.) 
6. Marina agreed with the proposed display for the shelfmark and side information above each image (e.g. shelfmark recto/verso) – thanks to Rebecca for the proposed placement. 

[You can find all of the above in this Figma frame](https://www.figma.com/file/anZFStv7zBaVWnFxr95nKt/Work-in-Progress-%2F-WIP?node-id=1426%3A40328) (used State Document; DK 256 (alt:XXI) as an example here because it's multi-authored).
