### ISSUE TITLE
create an ansible deploy script for qa for the flask prototype

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#8]
Should be able to adapt pretty directly from the pemm ansible playbook

**Comment by kmcelwee** [comment]
See: https://github.com/Princeton-CDH/CDH_ansible/pull/34

**Comment by rlskoeser** [comment]
Completed and confirmed; was used to successfully deploy to qa.

**Comment by rlskoeser** [comment]
I think this shouldn't have been closed until the remaining problems with the ansible PR were addressed and it was merged.
