### ISSUE TITLE
As a front-end user, I want to see provenance information for images when available so that I know where images and content is coming from for various shelfmarks.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#801]
## testing notes
For JTS images that are managed/provided by PUL, the image permissions statement should now include language that makes it clear that the documents are provided by JTS, you should see the Public Domain Creative Commons license image, and you should see both the PUL and JTS logos.

I've updated _most_ (some?) of the figgy iiif manifests on the test site to pull in the revised language and license.

Here are some examples you can test with, but feel free to poke around others in the search:
- https://test-geniza.cdh.princeton.edu/en/documents/30780/
- https://test-geniza.cdh.princeton.edu/en/documents/11276/
- https://test-geniza.cdh.princeton.edu/en/documents/11199/

If you see a JTS record with "no known copyright" that means the manifest hasn't been updated yet; please ignore for the purposes of testing this change.

## dev notes
PUL manifests for JTS content have been updated with provenance metadata and a corrected license. We'll need to:
- [x] do an import + update of JTS manifests from Figgy to get the new versions (RSK may need to help with spreadsheet/command option; we should document in deploy notes)
- [x] add logic to image attribution/rights to display provenance metadata when available (maybe as a fallback to attribution? I don't think the CUDL provenance statement is particularly relevant for us to display)
- [x] add logic to handle creative commons licenses similarly to existing logic for rightsstatement.org 
- [x] add logic to display JTS logo for JTS content served by PUL
- [x] update styles as needed to handle provenance text + license image

**Comment by richmanrachel** [comment]
@rlskoeser - works! Closing :)
