### ISSUE TITLE
 As a front-end user, I want to see logos for museums and libraries providing image content, so I have a better sense of where the content is coming from.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#802]
## testing notes (QA)

- [x] On the public site (QA), confirm that the document detail pages (for documents with images) include logos of image providers under "Image Permissions Statement" beneath the transcription.

## dev notes
Revise image attribution & rights section to display logos from manifests (as we're required to do per IIIF spec!)

Don't duplicate logos — simply display the unique set of logos. (I don't know how much it matters that the logos link to specific shelfmarks — I think it's ok if it's not one to one)

**Comment by rlskoeser** [comment]
@mrustow @richmanrachel would you like us to display the JTS logo for JTS content served by PUL? The PUL logo is the one in the manifest, and based on my conversation with Esmé this isn't required per the MOU, but it isn't too much effort for us to do. Please let us know — and if so, please provide a link to the correct website or logo so we can make sure we get the correct one!

**Comment by richmanrachel** [comment]
Never knew that was CUDL's logo, but it works! Closing!
