### ISSUE TITLE
As a front-end user, I want a way to access the museum or library view of the fragment (when available), so I can see more context about the source.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#805]
## testing notes (QA)
- [x] Confirm that each fragment's shelfmark links to its view URL, if one exists for that fragment (e.g. pgpid 5472, the second shelfmark in pgpid 12409)

## dev notes
Suggest we add this to the image rights/attribution section — if a fragment has a `view_url` set, then use that to make the shelfmark into a link. Should probably set a `target="_blank"` on the link.

- [x] link shelfmark to fragment `url` if one exists
- [x] set `target="_blank"` on link
- [x] style link with underline

**Comment by richmanrachel** [comment]
CUDL links work and look great! Is this what's expected for ENA right now while we determine whether it should be PUL or JTS?
<img width="321" alt="image" src="https://user-images.githubusercontent.com/68028846/165369916-83843787-8166-44fb-a87a-3b0142a89674.png">
Fyi there is no link here to the image currently.

**Comment by rlskoeser** [comment]
@richmanrachel yes, I think that's what we expect for JTS content right now — Esmé added a provenance statement about them being owned by JTS, and we have a task to display that; we don't have view urls for JTS content in the db yet (should resolve to the DPUL site, not to figgy).

**Comment by rlskoeser** [comment]
@richmanrachel based on this information, does this issue pass testing? If not, please specify what changes you'd like to see.

**Comment by richmanrachel** [comment]
@rlskoeser - yes, thank you!
