### ISSUE TITLE
As a front-end user, I want to sort documents by input date so I can find the most recently added records or those that have been in PGP the longest. 

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#806]
## testing notes (qa)

- [x] In the public site document search (QA), sort by input date ascending and descending and confirm the results are as expected
- [x] Try the same with some filters/queries applied

## dev notes
- [x] add input date sort options to form
- [x] configure sort mapping so input date options sort properly on the full input date which is is already indexed as `input_date_dt`
- [x] add a unit test or two to confirm the logic works properly

**Comment by richmanrachel** [comment]
Beautiful! Closing :D
