### ISSUE TITLE
As a content editor, when I'm editing a source I want footnotes sorted by location so I can review them in the same order they appear in the source.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#810]
## testing notes
1. In admin, go to scholarship records -> sources and choose a source that has multiple footnotes with locations set.
2. Confirm that sources are now ordered by location.

## dev notes
- [x] implement a natural sort field
- [x] use new natural sort field for location
- [x] sort on new natural sort location field
- [x] remove `natsort` template tag and use in scholarship records template

**Comment by rlskoeser** [comment]
configured ordering on source footnote inline in d8f0929f

**Comment by richmanrachel** [comment]
@rlskoeser - it mostly works! I think the main issues are the data inconsistencies in how the locations are entered, but also there are some oddities like "109, 10, 110" [for reference, I'm looking at the entries for Gil's Pious Foundations: https://test-geniza.cdh.princeton.edu/admin/footnotes/source/38/change/?_changelist_filters=q%3Dgil ]

**Comment by richmanrachel** [comment]
Here is a screenshot from Gil's unsorted Kingdom of Ishmael, which show the type of data problems we have:
<img width="740" alt="image" src="https://user-images.githubusercontent.com/68028846/165391225-1cb02e5b-fe28-4364-a0ac-57890b98fc12.png">

But when I changed the number in the location box to make it more consistent, saving did cause it to reorder properly.

**Comment by richmanrachel** [comment]
Here for Kingdom of Ishmael vol. 2, the doc numbers are more consistent and producing good results:
<img width="727" alt="image" src="https://user-images.githubusercontent.com/68028846/165391623-0330f8cd-8b43-4496-b433-ff5db7f6da83.png">
@rlskoeser - So should this be a data problem that I close here and assign to RAs?

**Comment by rlskoeser** [comment]
@richmanrachel right now it's sorting the locations as strings and not numbers — which is why you're seeing the order "109, 10, 110". I see that there's a django naturalsort library — we could try using that. Ben used a natural sort when displaying footnotes on the scholarship records page, but if this library (or the approach) works, then we would have that logical sorting available everywhere.  Please let me know how important that is — do you want simple sort right away, or should we spend a little more time and implement natural sorting?

I think the other things you're seeing are a result of the data and you all need to decide how consistent you want to be in tracking footnotes — would make sense to me to be consistent within a single source, but IDK how much effort that is or how much value it gives you for existing contetn. Maybe you could set up as conventions to follow going forward.

**Comment by richmanrachel** [comment]
@rlskoeser - I agree conventions are a good idea. 

If implementing naturalsort takes less than 30 minutes, could we try it?

**Comment by rlskoeser** [comment]
@richmanrachel yes, I think it's worth trying to implement natural sort — it will be useful in a couple of places if we can get it working

**Comment by richmanrachel** [comment]
@rlskoeser - just got a server error while trying to update footnotes for Gil's Pious Foundations (which only has 145 footnotes) :(

**Comment by rlskoeser** [comment]
@richmanrachel based on the error in the log, I think the error may be related to the recent db migration we did on the staging db — it's complaining about a log entry key violation.

I think I'll need to refresh the data from production at some point, which I hope will clear out these problems.

**Comment by rlskoeser** [comment]
@richmanrachel please test other open issues and I'll plan to refresh the db next week

**Comment by richmanrachel** [comment]
Works! Closing!
