### ISSUE TITLE
As a frontend user, I want to be able to search by historic shelfmark so I can find documents by what they're called today.

### ISSUE THREAD

**Issue by richmanrachel** [Princeton-CDH/geniza#817]
## testing notes

Try searching by historic shelfmark in the public document search and see if you can find the records. (Note that it may have the same limitations we have with regular shelfmark). 

Here are some examples of current and old shelfmarks you can use for testing:
| current | old|
|----|-----|
| T-S Misc.35.50 | T-S Loan 50 |
| X893 Z8 v.3 no.2 | Fr. 627a |
| Yevr. III B 641 | Antonin B 641 |
| Yevr. III B 644 | Antonin B 644 |
| Yevr.-Arab. I 1700.11 | Firk. II NS 1700.10; Firk. II NS 1700.11 |
| Yevr.-Arab. II 1367 | Firk. II A 1367 |
| Yevr.-Arab. II 1446 | Yevr.-Arab. II 946 |
| Yevr.-Arab. II 1456 | Yevr.-Arab. II 1477 |
| p. Heid. Heb. 10 | p. Heid. Heb. 10r |
| p. Heid. Hebr. 12 | p. Heid. Arab. 912; p. Heid. 912 |

(We don't currently display historic shelfmarks on the public site and they are still hard to see in the admin, you have to go to the fragment edit page. We may need to remedy that for this to be properly helpful.)

**Is your feature request related to a problem? Please describe.**
Goitein and other authors frequently use outdated shelfmarks. We already have a Historic Shelfmark option on the backend, but making it visible and searchable on the frontend would help many users (especially Geniza newbies). 

**Describe the solution you'd like**
#271 may need to occur first, so that historic shelfmarks are available through document detail view. Then we need to make this a searchable and visible field from the frontend and admin site.

**Comment by kseniaryzhova** [comment]
@rlskoeser The search of the old shelfmark does display the correct new shelfmark in the first 1-2 results. However, it's not always clear that this is what you're looking for because it doesn't display the old shelfmark in the document detail page. I know we'll need a redesign if we do anything to the public page (and thus won't have time) but there will be lots of non-specialists who are confused about this.

**Comment by richmanrachel** [comment]
The search works, and I'm not sure we want to mess around with the public site at this point....

One workaround I could imagine is doing some sort of data mining where we put the old shelfmark into the document description? It was often there before.

**Comment by rlskoeser** [comment]
I strongly recommend not putting the old shelfmarks back into the descriptions, that causes more problems than it solves.

It might not be too much effort to add historic shelfmarks to the document search results and the document metadata using the existing field layout (basically extrapolating from the current design). You all would have to decide what priority/order makes sense. The one thing that would benefit from design input is how to display historic shelfmarks clearly if the documents is associated with multiple fragments.

How likely are non-specialists be to search on historic shelfmarks, though? Is it really that much of a problem?

**Comment by kseniaryzhova** [comment]
@rlskoeser I think it's especially a problem for non-specialists since Goitein is widely read and if you're not clued into the history of the collections, you're so easily using old shelfmarks to find documents (I experienced this personally). Do we have a guide for old shelfmarks on the site itself, publicly-available? Could be a good workaround while we figure out how to approach this. Either way, nothing we can do right now. Should I close this and make another issue for tracking purposes?

**Comment by rlskoeser** [comment]
Ah, that's very helpful context! And that makes a lot of sense — this would be very confusing, then.

I think you should decide how you want them displayed and plan to have Performant add historic shelfmarks to the search view and document details. Actually implementation should be pretty straightforward once decisions are made about how to display multiples.

There aren't all that many historic shelfmarks in the system right now, so I don't think a huge number of records are impacted by this.

If you want me to remove historic shelfmark from the search in the meantime to avoid potential confusion, I can comment it out and it can be re-enabled once the display is updated.

**Comment by kseniaryzhova** [comment]
@rlskoeser I think we should keep the search for now, and then we'll have a longer discussion about how to display it publicly with Performant. Closing!
