### ISSUE TITLE
Add a faded colored background/highlight to the tags to compensate for the padding around each tag

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/geniza#818]

**Comment by gissoo** [comment]
@rlskoeser [this is what we agreed on for light mode](https://www.figma.com/file/anZFStv7zBaVWnFxr95nKt/Work-in-Progress-%2F-WIP?node-id=1575%3A53042):

- the color of the box is 7BAC7B with 20% transparency 
- top and bottom margins are 4px and left and right margins are 8px

I will need to work more on the dark mode and run it by Marina.

**Comment by rlskoeser** [comment]
This looks great. I don't think we should plan implementation until we have both light & dark modes defined, though.
