### ISSUE TITLE
Document from a fragment in a newly added collection isn't behaving properly

### ISSUE THREAD

**Issue by mrustow** [Princeton-CDH/geniza#819]
I input a new collection, then a new fragment, then two documents on the fragment. The first time I searched for the shelfmark (P.CtYBR inv. 1705 qua) from the public site, I input 1705 and both documents came up, first and second in the results. The second time, no dice. I also noticed that I couldn't reach the public record from the admin record. See [screen recording](https://capture.dropbox.com/8Dd3zFLbndSNRnv8).

**Comment by kseniaryzhova** [comment]
The example is working now, and we haven't heard of other issues. Closing for now!
