### ISSUE TITLE
Design a footer for the site 

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/geniza#82]
[Here are the designs](https://www.figma.com/file/anZFStv7zBaVWnFxr95nKt/Work-in-Progress-%2F-WIP?node-id=190%3A8273) for the footer for light and dark mode on desktop and mobile – let me know what you think about the content that it contains and the way the content is structured. 

- I reached out to Deena to get a Geniza Lab logo file 
- I need to find the right PU logo 
- Let me know if there is anything that's missing that should be in the footer 
- Also, what should the license text be? Does what I have work? I intended it as a placeholder.

**Comment by richmanrachel** [comment]
@gissoo - Just so you know, the Hebrew text on the desktop version is upside down, whereas on mobile it's right side up. Text in multiple directions is certainly part of the Geniza collection, but I don't know which way you want it to go :)

**Comment by rlskoeser** [comment]
Footer contents looks fine to me; some of those pages may not exist for a while yet, but it's nice to have a structure that can handle adding them gracefully when we're ready. 

We said in the charter that site content would be CC-BY; there are other licenses for code and potentially data. I'm not sure what that means for license text in the footer.

**Comment by gissoo** [comment]
@rlskoeser thanks for writing! I just used their icon as we did in Startwords. [Here is a final version of the footer](https://www.figma.com/file/anZFStv7zBaVWnFxr95nKt/Work-in-Progress-%2F-WIP?node-id=190%3A8273)

@blms @mrustow @richmanrachel if you don't have any questions or points, we can close this issue

**Comment by richmanrachel** [comment]
@gissoo - Looks awesome!
