### ISSUE TITLE
sort automatically switches relevance whenever the search term is revised

### ISSUE THREAD

**Issue by richmanrachel** [Princeton-CDH/geniza#827]
## testing notes (qa)

- [x] In the public site search on QA, start typing a search term and confirm it switches to "relevance". Then, change the sort option to something else (not "random" or "relevance"), add a new search term, and confirm the sort remains on the option you chose.

---

**Describe the bug**
When I add a new search term while trying to remain within Shelfmark A-Z sort, the site reverts the search to sort by Relevance. 

## dev notes
-  only change sort option when sort is default (i.e., user has not changed sorting)

**Comment by blms** [comment]
I think this is actually one of the few times we can say "it's not a bug, it's a feature"! At least, it was planned that way. But perhaps we should revisit now that we have so many more sort options.

Here is the original issue collecting the discussions: https://github.com/Princeton-CDH/geniza/issues/550

**Comment by richmanrachel** [comment]
@blms - ahh, I see! That makes sense to me. 

Right now the auto-switch is just extra confusing since all the filters stick around. But I think your solution is on the right track.

**Comment by blms** [comment]
Right—maybe "filters applied" could be another condition that prevents the sort from auto-switching!

**Comment by richmanrachel** [comment]
I'm not sure I fully understand how that will work, but I trust you!

**Comment by rlskoeser** [comment]
@blms it works as we planned originally, but when we built it we didn't have so many sort options! I think maybe it should only change if you have the default sort selected. Also should probably only trigger if you go from no keyword text to some keyword text — not modified text, which I think it does now. I think it should not be aware of the filters, though.

**Comment by richmanrachel** [comment]
Fixed! Thank you :)
