### ISSUE TITLE
As a front end user, I want to see detailed information about the different historical calendars, so I can understand the meaning of "original dates" for documents.

### ISSUE THREAD

**Issue by blms** [Princeton-CDH/geniza#828]
We don't currently have information tooltips, so this might make more sense as a content page, but opening this issue to track either way.

> It occurs to me that it could be user-friendly to have a pop-up info bubble on the public site (are we doing those?) defining the various eras: 
> 
> CE: Common Era, derived from the Christian calendar and in common use today
> AH: *anno hegirae,* the year according to the Islamic calendar, calculated from 622 CE with a lunar year of 354 or 355 days
> Sel.: *anno graecorum,* or Seleucid Era; in Jewish documents, the Era of Contracts (מניין שטרות, minyan sheṭarot), calculated from 311 BCE

_Originally posted by @mrustow in https://github.com/Princeton-CDH/geniza/issues/779#issuecomment-1113458288_

> Anno mundi: the Jewish calendar, counted from the date of creation. 
> 
> Kharājī: the fiscal calendar. Either in sync with the hijrī year (AH) or up to several years behind it, depending on the year. The difference was due to delays in tax collection.

_Originally posted by @mrustow in https://github.com/Princeton-CDH/geniza/issues/779#issuecomment-1114060486_

**Comment by rlskoeser** [comment]
I think this should probably be an entry on the faq and we can link there for now

**Comment by richmanrachel** [comment]
Our temporary solution has put some dating information in both the FAQ and the Glossary. See: https://docs.google.com/document/d/1Tz7LhfM_jJfkQDfdqfxYXwBdDF4uvW4jd3JNmKRJahY/edit

**Comment by kseniaryzhova** [comment]
Temporary solution is ok, hoping to still build out Glossary. Closing!
