### ISSUE TITLE
Prepare annotation editor plugin for NPM publication

### ISSUE THREAD

**Issue by blms** [Princeton-CDH/geniza#833]
## dev notes
- [x] create new repo
- [x] import preliminary code
- [x] Repo organization
- [x] ESLint setup
- [x] Package.json
- [x] TypeScript conversion
- [x] Webpack setup
- [x] JSDoc documentation
- [x] Write readme
- [x] Jest setup
- [x] Write tests
- ~Publish to NPM~

---

- [x] bug: saving changed shape, then saving changed text, causes shape to revert
- ~chore: refactor events to delegation (see https://github.com/Princeton-CDH/annotorious-tahqiq/pull/3#discussion_r870654857)~

**Comment by rlskoeser** [comment]
@blms should we close this issue? I'm pretty sure the bug was resolved; I don't remember what the other item is but maybe it isn't important now.
