### ISSUE TITLE
Design styles and placement of the light/dark mode toggles so that the toggles can be displayed and used on all site pages

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/geniza#834]

**Comment by gissoo** [comment]
I initially looked at some visual examples from the fragments which Rebecca and Zohar had shared with me. I came up with the following proposals using the examples from the fragments. 
![Screen Shot 2022-07-26 at 4.46.05 PM.png](https://images.zenhubusercontent.com/5bf307a69d595b459ec91bb1/2d0b7a38-221f-4685-a24c-8982c5f82cb8)

Marina mentioned that she'd like the proposals to feel more hand-drawn – and mentioned she liked proposal no.2. I then revised proposal 2 and came up with 2.1 – everyone liked this, this design has been approved. 
![Screen Shot 2022-07-26 at 5.20.05 PM.png](https://images.zenhubusercontent.com/5bf307a69d595b459ec91bb1/6b77befd-282d-482c-8c4a-29aa4873ffd7)

![Screen Shot 2022-07-26 at 5.20.59 PM.png](https://images.zenhubusercontent.com/5bf307a69d595b459ec91bb1/0eba8e24-2cda-48ea-95e0-a7b83ee9a30c)

**Comment by gissoo** [comment]
@rlskoeser @blms Here are what I propose they look like on [desktop](https://www.figma.com/file/anZFStv7zBaVWnFxr95nKt/Work-in-Progress-%2F-WIP?node-id=2098%3A47371) and [mobile](https://www.figma.com/file/anZFStv7zBaVWnFxr95nKt/Work-in-Progress-%2F-WIP?node-id=2098%3A54059)

I'm proposing that:
- on desktop it's a sticky, and that it sits below the header 
- on mobile it's not a sticky and it sits in the header 
- once selected on desktop and mobile it would rotate so that its left side is the active side 
- on desktop it's 70px 
- on mobile it's 40px 
- for larger screens it would be great if the toggle's distance with the search form and the nav above it remains the same (doesn't get pushed to the right edge too much)
- the interaction is when selected once you get the light mode, and when selected again you get the dark mode. 
 

Please let me know if you have any thoughts or questions.

**Comment by blms** [comment]
@gissoo I love the design!

By "sticky" do you mean that it remains on screen when the user scrolls down, like [CSS "position: sticky"](https://developer.mozilla.org/en-US/docs/Web/CSS/position)? I'm wondering if that's needed for something the user will probably only interact with once during the browsing session—worried it might be distracting.

**Comment by blms** [comment]
@gissoo Thanks, these all sound great! Just dark mode is fine, but I don't see the upload. Did you put it on the [`develop` branch](https://github.com/Princeton-CDH/geniza/tree/develop)?

**Comment by gissoo** [comment]
@blms sorry for some reason it didn't attach the file when I dragged in the first time – just did, should be there now
