### ISSUE TITLE
On mobile, hamburger menu seems to overlap with the light/dark mode toggle.

### ISSUE THREAD

**Issue by mrustow** [Princeton-CDH/geniza#839]
## testing notes (QA)

- [x] On the public site on mobile (QA), confirm that the hamburger menu does not overlap with the light/dark mode toggle

---

![13075EB7-850F-4F18-9D64-E53D149EA439](https://user-images.githubusercontent.com/73319225/166741441-2ae2f49e-376b-4565-a084-f7b0f81d9417.png)

**Comment by blms** [comment]
@mrustow This should now be fixed on QA! Ready for testing.
