### ISSUE TITLE
As a content editor, I want Anno Mundi dates automatically converted to standard dates when possible, so that dates can be compared and used for filtering and sorting.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#854]
## testing notes
Test editing a document in the admin and set an original date and Anno Mundi calendar, with no value in the standard date. Use the "save and continue editing" button to save the record. The standard date should be populated for you based on the original date you entered.  You should also see a read-only human readable version of the date next to the standard date field.

Test a variety of examples:
- [x] year only
- [x] month and year
- [x] month, year, and day
- [x] "first decade of ..." or similar — currently unsupported; you should see a notice
- [x] if you put content in the standardized date directly yourself, it should stay there (i.e., conversion logic shouldn't override manual entry, even if they differ)

## dev notes
this implementation should handle only the basic cases, as already prototyped in #714 

- [x] refactor `Document` date logic into a mixin to make the code more manageable
- [x] add method to calculate standard date on `Document` save if calendar is Anno Mundi
- [x] display human-readable version of the standard date for easier checking/comparison between dates
- [x] warn if date can't be parsed / calculated

**Comment by richmanrachel** [comment]
@rlskoeser - it works! We're so excited
