### ISSUE TITLE
As a frontend user, I want document descriptions displayed with line breaks from the content editors so that I can more easily read longer or more structured descriptions.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#861]
## testing notes
Check that line breaks entered in the document description in the admin site are rendered on the public site.

Example suggested by Alan for testing: https://test-geniza.cdh.princeton.edu/en/documents/9248/

# dev notes
- set description whitespace style to either `pre-wrap` or `pre-line`

**Comment by richmanrachel** [comment]
@rlskoeser - love it!
