### ISSUE TITLE
Revise the design of the image attribution so that image and text(provenance) are displayed

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/geniza#867]

**Comment by gissoo** [comment]
@rlskoeser thanks for explaining this to me on Slack – [here is how I have revised the designs](https://www.figma.com/file/anZFStv7zBaVWnFxr95nKt/Work-in-Progress-%2F-WIP?node-id=1562%3A39643) – there are guides for spacing – I have reduced the line length to take half of the page on desktop for readability.

**Comment by rlskoeser** [comment]
This looks great to me. Could you provide style instructions or an example for a non-square logo? Do we keep the same height and let it go wider?
