### ISSUE TITLE
As a frontend user, I want to see dating information displayed on document details when available, so that I can find out the time frame of a document when it is known.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#875]
## testing notes (qa)

On the [QA public site](https://test-geniza.cdh.princeton.edu/):
- [x] Documents with inferred dates should show them on the document details page, e.g. [PGPID 38537](https://test-geniza.cdh.princeton.edu/en/documents/38537/)
- [x] Documents with both inferred and document dates should show both, e.g. [PGPID 2554](https://test-geniza.cdh.princeton.edu/en/documents/2554/)
- [x] Documents with inferred dates that do not have "display date" set should show "standard date" (CE date or range) instead, e.g. [PGPID 709](https://test-geniza.cdh.princeton.edu/en/documents/709/)

## dev notes
-  [x] display inferred date on document details when set

**Comment by blms** [comment]
@richmanrachel I'm reopening as this refers to the public site, and I don't believe inferred dates are visible there yet.

**Comment by kseniaryzhova** [comment]
@blms so everything displays as it should, it has just brought a lot of issues to my attention about how we enter the data.
