### ISSUE TITLE
As a frontend user I want to search on document date information so I can find records by calendar or historic date.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#882]
## testing notes

The text of the document date (both historic and converted), as displayed in search results and on the document details, are now included in the search fields. You should be able to get records by searches on date text (although often the date is repeated in description, which may make it a little harder to tell).

You can also do a field-specific search using the syntax `document_date:xxx` - e.g., search for a Seleucid year `document_date:"1450 seleucid"` or everything dated as being on a Thursday: `document_date:thursday`

- [x] try searching for date or calendar as keyword search
- [x] try searching for date or calendar with document_date:## syntax

-----
If we're not using the filter to include dates in other calendar types, can we make the full dates searchable (so you can put 4963 into the search to get the AM docs dated to that year)?

_Originally posted by @richmanrachel in https://github.com/Princeton-CDH/geniza/issues/865#issuecomment-1130185299_

## dev notes
index date field in solr and add to list of searchable fields

**Comment by kseniaryzhova** [comment]
@rlskoeser works for me! Both syntax and keyword search have the same number of results (and the results are the same) except in Seleucid - document_date: "1450 seleucid" gives me 5 exact matches while 1450 seleucid keyword search returns 1364 results (partial matches). For non-Seleucid dates, it seems the date field is matching.
