### ISSUE TITLE
As a content editor, I want Seleucid dates automatically converted to standard dates when possible, so that dates can be compared and used for filtering and sorting

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#886]
## Testing notes (QA)

On the [QA admin site](https://test-geniza.cdh.princeton.edu/admin/):

- [x] Enter a Seleucid date (not inferred) on a document, and save. The automatic conversion should produce the correct CE date result.
- [x] Check a few existing Seleucid date records that have been updated by navigating to [Log Entries](https://test-geniza.cdh.princeton.edu/admin/admin/logentry/) and clicking on recent "Recalculated standard document date" entries.

---

Adapt existing calendar conversion for Anno Mundi and Hijri; Seleucid should be calculated as a year offset from Anno Mundi calendar. (AM - 3449)

Update report script and check existing Seleucid dates against newly converted dates.

Documentation on Seleucid calendar from Marina and Ksenia:
> Seleucid calendar (Sel. or SE; also Anno Graecorum or AG): Though this calendar is now obsolete in Jewish practice, for the numbering of years, it is the most common calendar found in geniza documents. It is used only for years, and calculated from Seleucus I Nicator’s reconquest of Mesopotamia in 312–11 BCE. There were variants of the Seleucid era used in the Middle Ages. The Seleucid era in Jewish documents was deemed to begin on 1 Tishri 312 BCE. In practice, to convert a Seleucid date to CE, if the day falls before 1 Tishri, subtract 311 from the Seleucid year; if after, subtract 312. 
Examples:
29 Elul 1311 Sel. = 29 Elul 1000 CE = 1 September 1000 CE
1 Tishri 1312 Sel. = 1 Tishri 1000 CE = 2 September 1000 CE

Calendar converter that includes Seleucid logic: https://www.muqawwim.com/

# dev notes
- [x] add support for seleucid calendar in dates module
- [x] include in date reporting script
- [x] generate report of seleucid dates in the db compared with new converted dates; flag discrepancies
- [x] share report for review to check conversion logic
- [ ] run update script on all existing dates

**Comment by rlskoeser** [comment]
@mrustow how do we account for leap years when calculating Seleucid dates? does it follow the same pattern based on the offset from Anno Mundi ?

**Comment by mrustow** [comment]
Right: the months are the regular Jewish months, so no need to account for leap-years; the offset remains the same. Conveniently, the New Year falls on the same date in both (1 Tishrei AM/1 Tishrin Sel.)

**Comment by kseniaryzhova** [comment]
@blms checked a few of the entries too - looks good, closing!
