### ISSUE TITLE
As a user I want to see all images and first available transcription for a document, so that I can see and read the content.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#889]
## testing notes
- [x] confirm all images available are displayed
- [x] confirm content from first transcription is displayed (note: transcription sync script has been updated to roughly chunk content into pages/images, but it is not completely accurate)

## dev notes
- [x] Show all images (no pagination for now)
- [x] Show image + transcription panels by default ; transcription should be roughly aligned with images; show first only, for now
- [x] implement spacing and layout per designs
- [x] adapt preliminary srcset image sizes as needed for the design
- [x] move / adapt image attribution styling from previous iiif viewer

**Comment by gissoo** [comment]
@rlskoeser @blms [here are the designs for this issue ](https://www.figma.com/file/anZFStv7zBaVWnFxr95nKt/Work-in-Progress-%2F-WIP?node-id=1384%3A35645)

**Comment by richmanrachel** [comment]
@rlskoeser - looks amazing! Closing!
