### ISSUE TITLE
As a user I want to see page side and shelfmark information above each image so that I know what part of the document I’m viewing.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#890]
## testing notes
In the image panel of the new image+transcription viewer, above each image you should see shelfmark + the label from the manifest (usually something like recto/verso, 1/2, 1r/1v)

**Comment by gissoo** [comment]
@rlskoeser @blms y[ou can refer to the guides on this frame for this issue](https://www.figma.com/file/anZFStv7zBaVWnFxr95nKt/Work-in-Progress-%2F-WIP?node-id=1384%3A35645) – the same spacing can work for desktop and mobile

**Comment by richmanrachel** [comment]
@rlskoeser - beautiful, closing!
