### ISSUE TITLE
As a user I want to click or tap on image controls to turn on deep zoom so I can inspect the image in more detail.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#891]
## testing notes (round 2)

Confirm the following on mobile:
- [x] When zooming, the toggle remains visible (https://github.com/Princeton-CDH/geniza/issues/891#issuecomment-1181795872)
- [x] Zoom container does not fill whole browser screen (https://github.com/Princeton-CDH/geniza/issues/891#issuecomment-1181934672)

## testing notes
Look at the image+transcription viewer for documents that have images available. 
- [x] images should be static and not zoomable by default
- [x] on desktop, interacting with the slider above the image will enable deep zoom and make the image zoomable and interactive
- [x] on desktop after zoom is enabled, sliding the slider all the way to the left will turn zoom off again
- [x] on mobile, zoom is enabled and disabled by a toggle. Once enabled, can use gestures to zoom and rotate. Once disabled, can scroll through the page normally.

## dev notes
Images are not zoomable by default; tap to zoom within existing container; x to turn off  zoom mode
On desktop, trigger via +/- or something outside image to activate
- use stimulus to load/activate OSD; so we'd probably want a data prop on the image container with the url for OSD

**Comment by rlskoeser** [comment]
@blms when you revise the zoom functionality, please add the following:
- image should fade out the first time that open seadragon loads (since there's a slight delay with OSD coming in; hoping this will make it less jarring)
- when deep zoom is disabled, reset the image to original position so that turning it on again will match the static image

**Comment by gissoo** [comment]
@blms here are the designs for this issue: 
1. [zoom toggle on mobile](https://www.figma.com/file/anZFStv7zBaVWnFxr95nKt/Work-in-Progress-%2F-WIP?node-id=1863%3A46499)
2.[ image rotation on desktop](https://www.figma.com/file/anZFStv7zBaVWnFxr95nKt/Work-in-Progress-%2F-WIP?node-id=1863%3A62435)

let me know if you need anything else.

**Comment by richmanrachel** [comment]
Okay, mobile zoom works too! The mobile rotate is a bit too sensitive though - when trying to do normal zoom motions, it rotates the document significantly
![IMG_1468](https://user-images.githubusercontent.com/68028846/178302714-a05c9e5d-d03c-40ec-aa32-366ee4ef01e9.PNG)

**Comment by richmanrachel** [comment]
@rlskoeser - please advise whether this issue should be closed or needs more attention. Thanks!

**Comment by richmanrachel** [comment]
And I assume rotation features will be available on desktop soon?

**Comment by richmanrachel** [comment]
@rlskoeser - Great, thanks! I'll change this to Tested Needs Attention while you look at the white-out situation. Perhaps @mrustow needs to test on mobile since she's the primary user?

**Comment by mrustow** [comment]
Tested on the "public" test site. After I zoomed, the toggle disappeared and I was stuck in a zoom trap.![image](https://user-images.githubusercontent.com/73319225/178507333-2e456959-0c86-4a25-9429-48e20d82d62f.png)![image](https://user-images.githubusercontent.com/73319225/178507568-e4f6b351-5746-480b-a5c4-44cf578bf11b.png)

**Comment by rlskoeser** [comment]
@mrustow toggling off zoom does reset, but I don't know if that's the right solution for what you're requesting. Gissoo was trying to keep the buttons minimal, but are there cases where you would want to reset and then continue zooming? Is it useful enough that you'd want another button for it?

@blms can you duplicate the disappearing buttons? I was testing with my phone (android), and it didn't happen on Firefox but when I tried on Chrome and rotated, I think the screen must have scrolled down some — looks like the zoom container filled my whole browser screen, and then you're pretty much trapped..

**Comment by blms** [comment]
@rlskoeser I can replicate the screen scrolling down to make the zoom container fill the whole screen, but only on desktop in responsive design mode. That would be the bug I was talking about here: https://github.com/Princeton-CDH/geniza/pull/888#issuecomment-1177966394
> Turns out that whole weird scroll trap handler thing for mobile wasn't needed. It only applies to mouse events, which would not be encountered on a mobile device. My browser was triggering it when using responsive design mode, but that's not a real-world scenario. I tested it without that on my real phone and didn't encounter the issue, so I've removed that code.

I can't replicate the disappearing buttons, but I did encounter that in desktop at full screen, and it's why I ended up implementing this [scrollTo0](https://github.com/Princeton-CDH/geniza/blob/a10e037255c3bd474502222d8982df5b11b43902/sitemedia/js/controllers/iiif_controller.js#L200) function. I think OSD tries to scroll whatever its container is to the top of OSD when you interact with it, which is a problem since we have controls above it that should not be scrolled out of view. Looks like we'll need to implement something similar for mobile—just wish I had a device that could test it properly!

**Comment by rlskoeser** [comment]
@richmanrachel or @mrustow please retest on mobile to check if our revisions address the zoom trap problem and this is acceptable now.

We can consider adding a separate reset button in a future revision, but let's hold off on doing it now.
