### ISSUE TITLE
As a user I want content panel toggles to be disabled when a record type for a document is not available, so that I know what content is available. 

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#892]
## testing notes
- [x] if document has no image or transcription, image+transcription panel should not display at all (no toggle buttons)
- [x] if document has image but no transcription, transcription toggle should be disabled
- [x] if document has transcription but no image, image toggle should be disabled

## dev notes
- [x] set as disabled in template if there is no content available
- [x] implement disabled styles for toggle

**Comment by gissoo** [comment]
@rlskoeser @blms you can see [disabled toggles variants here for desktop and mobile](https://www.figma.com/file/anZFStv7zBaVWnFxr95nKt/Work-in-Progress-%2F-WIP?node-id=1426%3A40294)
