### ISSUE TITLE
search fields jump when an error message displays

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#894]
Just noticing some things here for usability / potentially problematic:

- whenever there is an alert/invalid message the fields jump and I'm selecting the "has image" filter by mistake. 
 

 ![Screen Shot 2022-05-24 at 10 48 59 AM](https://user-images.githubusercontent.com/44615389/170065033-956b1990-f5d8-4995-b9c7-892417e3b1d2.png)

_Originally posted by @gissoo in https://github.com/Princeton-CDH/geniza/issues/865#issuecomment-1136035890_

**Comment by kseniaryzhova** [comment]
@rlskoeser this seems fixed on our end - both @richmanrachel and I tested (Mac/PC) and it didn't bounce anything around. (We input 300 into the document date and it just told us date must at least be 828 but nothing jumped or shifted) Closing!
