### ISSUE TITLE
As a user I want to switch between different transcriptions when there are multiple, so that I can read all available versions.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#899]
## testing notes
Test the image+transcription viewer display with some documents that have transcriptions.
- [x] documents with a single transcription should have a label above the transcription panel indicating the editor; it should not be interactive
- [x] for documents with more than one transcription, the label should be interactive and allow you to switch between transcriptions. PGPID 9121 is a good example. (FYI transcription sync appears to be not updating some multi-edition records; will need to address)

## dev notes
- [x] investigate options for placing multiple transcriptions in the html
- [x] Add a dropdown menu for switching between transcriptions
- [x] Displaying a short version of the editor information in the drop down to identify the source of the current translation
- [x] transition should fade out one / fade in other (no overlap)

**Comment by rlskoeser** [comment]
ok @blms finally had time to investigate this a bit and think about approach.

I propose that we use markup similar to a css-only image carousel like this one: https://css-tricks.com/css-only-carousel/

It will use flex + overflow to control placement; each nested div would be full-width of the panel width. Instead of making it scrollable, we make overflow hidden and then use javascript to manage the scrolling (which I think should not be too difficult — do you agree?). This was the only solution I've come up with that automatically accounts for the full height of the longest transcription. The main drawback is I think we'll need to add another layer of nested divs to contain all the transcriptions, but that doesn't seem too terrible.  I'm open to other solutions if you have ideas. 

I was testing with PGPIDs 2179 and 4721, however I had some trouble getting all the footnotes to update with the new chunked content format. If this is a problem for you, LMK. I did start adding an option to the sync tei script to take an optional list of filenames, but that didn't fully resolve the problem. My quick-fix workaround was to make the content editable in admin and fix it myself, but if it's a problem for you too I'll probably have to deal with it before we can release the new transcription panel.

I don't think I did enough to warrant checking in and starting a branch, but in case it's useful here's the preliminary template code I added while I was experimenting with how to implement:

```jinja
<div class="transcription">
      {% if forloop.first %}
          {# do we always display even if only one, as a label? #}
          {% if document.digital_editions.count > 1 %}
              <ul>
                  {% for ed in document.digital_editions %}
                      <li data-edition="ed {{ ed.pk }}">Editor: {{ ed.source.all_authors }}</li>
                  {% endfor %}
              </ul>
          {% endif %}
      <h3>Transcription</h3>
      {% endif %}

      <div class="wrap">
      {# display transcription in chunks by index #}
      {% for edition in document.digital_editions.all %}
          <div class="ed{{ edition.pk }}">
              {{ edition.content.html|index:forloop.parentloop.counter0|h1_to_h3|safe }}
          </div>
      {% endfor %}
      </div>
  </div>
  ```

**Comment by richmanrachel** [comment]
@rlskoeser - this looks amazing and works perfectly! 

The only minor issue I found is that for docs like 9121 where the Gil edition is longer than Frenkel's the container stays at the Gil size for the whole thing, so that you have to scroll quite a bit for Frenkel to get from recto to verso. But I don't think this is a blocker - closing!

**Comment by rlskoeser** [comment]
@richmanrachel yes, we noticd the discrepancy between the edition lengths too — but usually they'll be more comparable in length, right? In this case it seemed like a description is included in the TEI that is causing the disparity in length.

**Comment by richmanrachel** [comment]
@rlskoeser - great. I'm good with this!
