### ISSUE TITLE
As a user, I want to search on text with or without accents so that I can easily find variants of words with accents and diacritics in the data.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#9]
- [x] edit schema to add unicode folding to the fields where we want it (maybe just add to existing text field) 
- [x] change indexing/search config to use the new field if necessary (if new field name/type)
- [x] test to confirm & document required steps for the update to take effect (is copying files + restart + reindex sufficient?)

**Comment by rlskoeser** [comment]
You should now be able to search with or without accents!

Please test by searching for words with and without accents — no matter which version you put into the input, your results should include results where that term matches with and without accents. Particularly helpful if you can test on terms or names that you know occur in the data with accents or diacritics in some cases and without them in others.

**Comment by sluescher** [comment]
[Mikhail](https://test-geniza.cdh.princeton.edu/?keywords=Mikhail) is a good test name. Shows up as Mikhaʾil, Mikhāʾīl, Mīkhāʾīl. So works.

Which are the diacritics? And if I do add diacritics, do only results with it show? If I search for Yeshu‘a, for example, I get [56 results](https://test-geniza.cdh.princeton.edu/?keywords=Yeshu%E2%80%98a). If I search for Yeshua, I get 207 results and Yeshuʿa shows up, which is a different symbol (' vs ʿ). We might want to unify this.

Side note, when I searched for [Ḥasan](https://test-geniza.cdh.princeton.edu/?keywords=%E1%B8%A4asan), one result wanted to run from the page. 
<img width="1374" alt="Screen Shot 2020-11-04 at 4 03 51 PM" src="https://user-images.githubusercontent.com/30683720/98168340-70c97a00-1eb8-11eb-8954-c4f6049a9132.png">

**Comment by rlskoeser** [comment]
For characters that are normalized, searching on e.g. Ḥalfon and Halfon should give you exactly the same results.

The Solr filter we're using is using unicode normalization — here's the filter https://lucene.apache.org/solr/guide/6_6/filter-descriptions.html#FilterDescriptions-ICUFoldingFilter and here's the technical report that the normalization is based on http://www.unicode.org/reports/tr30/tr30-4.html

Based on the behavior you describe for Yeshua / Yeshu‘a / Yeshuʿa, it might be handling one of those symbols but not the other — which does suggest that it would be good to make them more consistent.

I think I did notice the long transcription at one point... I have it set to preserve whitespace right now.

**Comment by thatbudakguy** [comment]
digging into the Yeshua / Yeshu‘a / Yeshuʿa issue:

- Yeshu‘a uses `‘` [`U+2018 : LEFT SINGLE QUOTATION MARK`](https://codepoints.net/U+2018), which is in the "General Punctuation" block. I didn't see it in [the normalization table](https://www.unicode.org/charts/normalization/chart_Punctuation-Other.html) for that block.
- Yeshuʿa uses `ʿ` [`U+02BF : MODIFIER LETTER LEFT HALF RING`](https://codepoints.net/U+02BF), which is in the "Spacing Modifier Letters" block. I didn't see it in [the normalization table](https://www.unicode.org/charts/normalization/chart_Letter-Modifier.html) for that block, but in [the latin normalization table](https://www.unicode.org/charts/normalization/chart_Latin.html) you can find its sibling [`U+02BE : MODIFIER LETTER RIGHT HALF RING`](https://codepoints.net/U+02BE) as something that other letters like `ẚ` normalize _to_ (`a` + `ʿ`), so maybe reasonable to expect it wouldn't get changed either?

**Comment by rlskoeser** [comment]
Thank you @thatbudakguy for investigating! Based on this, I would guess that punctuation is treated differently than modifier characters for normalization.

**Comment by thatbudakguy** [comment]
the unicode github org now has [this (relatively new-looking?) site](https://unicode-org.github.io/icu/userguide/) where you can read about what's available in the big ICU package, which I think gets installed alongside solr to power things like normalization/folding.

i did see that you can apply arbitrary "transforms" in addition to normalization using [solr's `ICUTransformFilter`](https://lucene.apache.org/solr/guide/8_3/filter-descriptions.html#icu-transform-filter); i think by just specifying them by name. going off of [this list](https://unicode-org.github.io/icu/userguide/transforms/general/#icu-transliterators), the `→Latin-ASCII` one looks promising for playing around with:
> Converts non-ASCII-range punctuation, symbols, and Latin letters in an approximate ASCII-range equivalent. For example: « → ‘«’, © → ‘(C)’, Æ → AE. Can be combined with Any-Latin to produce a transform that will convert as much as possible to an ASCII-range representation: “Any-Latin; Latin-ASCII”.

there's also all sorts of other transliteration stuff that might let us romanize hebrew or arabic in a consistent way, if we needed that, and I think they're designed be reversible.

**Comment by sluescher** [comment]
I am reading this to mean that we should unify the way we write these names and words transcribed from Hebrew and Arabic in order for them to appear in such searches?

I have done a number of searches with words with (actual) diacritics and without and they return both matches with and without diacritics.

**Comment by rlskoeser** [comment]
We can do transforms in the search if there are things the existing filter doesn't handle, but either way it is better if things can be made more consistent.

Nick's comment reminded me of something I'd wondered about briefly but not pursued — would support for transliteration search be useful in future?  

Are you comfortable signing off on this for current functionality? Is there anything we should document or add to the list of questions raised by the prototype? (transliteration search support, maybe?)

**Comment by sluescher** [comment]
What do you mean with support for transliteration search?

Other than that, yes, I am happy to sign off. No questions to document related to the prototype (more re: cleaning data).

**Comment by rlskoeser** [comment]
> What do you mean with support for transliteration search?

I presume there is a standard transliteration / romanization for Hebrew and Arabic. Do we imagine people would ever want to search based on transliteration instead of the original Hebrew or Arabic text?

**Comment by thatbudakguy** [comment]
wouldn't this apply to all person/place names? so "fustat" should return results for the actual place name written in judaeo-arabic, not just "fustat" in roman script

**Comment by sluescher** [comment]
oh. So basically having a transliteration script that would not only search in whatever script we enter, but also in its other form?

That would be a question to document. The issue would probably be that from Hebrew to Arabic script we have some letters that are the same in Hebrew but different in Arabic (כ could be خ or ك), so I am not sure how easy that would be. Though, I guess you could search for both? 

Let's discuss it! (happy to close otherwise)

**Comment by thatbudakguy** [comment]
if we do this, I think it'd be simplest to basically create a field that transliterates the transcriptions into roman script. so, "fustat" will match against the "fustat" that is generated in that field from the transcription. 

doing conversion to or between hebrew and arabic seems more complicated; perhaps we want to respect the script the user enters in those cases and not try to transliterate. so, searches including "כ" will only match "כ", not "خ" or "ك".

**Comment by sluescher** [comment]
We would actually need a dictionary of Arabic and Hebrew terms for it to work. Arabic and Hebrew script do not show vowels except if they're long. فسطاط would be transliterated 'Fstāt' if we go by the letters that are there. The script would have to know to put an 'u' between 'F' and 's'. Muhammad is محمد which going by the letters is Mhmd.

**Comment by rlskoeser** [comment]
@thatbudakguy I agree we would want to generate the transliteration fields, but if at all possible we'd want to highlight the corresponding word in the original (maybe possible with solr filters and copy keywords? IDK). I agree we should probably only transliterate in one direction.

Okk, the more you two discuss it, the more I think this sounds like it is out of scope! We can keep in mind as a future possibility, but it's not clear to me the amount of work it would require is worth it for the value it would add.

**Comment by thatbudakguy** [comment]
maybe more appropriate to transliterate at query time, then - so "fustat" that you typed would be converted to فسطاط and then match the correct location in a transcription (but would also need to match literal "fustat" in item descriptions). definitely seems complicated enough to postpone, since I didn't see any readily available tools to do the transliteration when I looked closer at the unicode site.
