### ISSUE TITLE
As a user when viewing a document I want to see if there are any related documents so that I can easily discover other documents on the same shelfmarks. 

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/geniza#903]
## testing notes
- [x] document details should now have a "related documents" tab instead of "external links"
- [x] related documents count should be 0 and tab should be disabled if there are no related documents
- [x] related documents tab should display count and list documents for those records that do have them (a few you can test with: 5435, 1484, 23194)
- [x] should not display the current document in the list of related documents
- [x] should no longer display the provisional "other documents on these shelfmarks" section on the main detail page that I added quickly when we needed this functionality

---
[Here are the designs on figma](https://www.figma.com/file/anZFStv7zBaVWnFxr95nKt/Work-in-Progress-%2F-WIP?node-id=1562%3A44642)

**Comment by rlskoeser** [comment]
@richmanrachel great — thanks, I was thinking the same thing. Easy enough to adjust the label or add headings if/when we figure out what we need, and better from my perspective to treat that as a refinement.
