### ISSUE TITLE
Still not able to update large sources without error message (though it worked in the end)

### ISSUE THREAD

**Issue by richmanrachel** [Princeton-CDH/geniza#905]
**Describe the bug**
@rlskoeser - not entirely sure we need to deal with this as a bug since it ended up working, but wanted to record it. Similar to what we were dealing with in #733 regarding changing sources. When I tried to update the volume name of one of Goitein's unpublished sources, it was very slow then I got a 405 error ("not allowed"). This is slightly different than the 400 errors we were getting before... But when I hit the back button, the source actually did save with the proper info!

**To reproduce**
1. Go to the admin site, sources, unpublished.
2. Click on S. D. Goitein, index cards. (T-S 13)
3. Scroll down to Volume. Update per MR's instructions to T-S 13J
4. Click save, wait
5. See error
<img width="1004" alt="image" src="https://user-images.githubusercontent.com/68028846/172253966-7ec52a8c-50e6-47b9-99de-0f1a0d998f65.png">

**Device information**
 - Device: MacBook Air
 - OS and version: macOS 12.0.1
 - Browser and version: Chrome 102
 - Site version 4.4.1

**Comment by kseniaryzhova** [comment]
@rlskoeser we tested again and it's still slow but it does actually update. Since this will not be a feature we frequently use, and only Super Users will ever have to rename sources, then it should be fine to leave as is. Closing!
