### ISSUE TITLE
server error for documents associated with Heidelberg IIIF (PGPIDs 34016, 34017, 34018 so far)

### ISSUE THREAD

**Issue by alanelbaum** [Princeton-CDH/geniza#906]
## testing notes

https://test-geniza.cdh.princeton.edu/en/documents/34016/
https://test-geniza.cdh.princeton.edu/en/documents/34017/
https://test-geniza.cdh.princeton.edu/en/documents/34018/

no need to test everything on all three, should be sufficient to confirm on one or two

- [x] public page displays properly without 500 error
- [x] admin edit page displays properly without 500 error
- [x] image thumbnails display properly in the admin "related fragments section"
- [x] image permissions in the image viewer displays "Heidelberg University Library" and a creative commons / public domain 

--- 

There's a server error when trying to access the document pages for these documents in both the admin site and the public site.

> server error for PGPIDs 34016, 34017, 34018 (but no other documents so far)

Thank you for investigating!

**Comment by richmanrachel** [comment]
@rlskoeser - bug fixed! @alanelbaum - wow, these are such pretty documents!
