### ISSUE TITLE
On the admin site, I want the tag list view to include counts for how many times its used, in order to understand the scope of tags and to help clean them later.

### ISSUE THREAD

**Issue by richmanrachel** [Princeton-CDH/geniza#909]
## testing notes
In django admin, go to the list of tags:
- [x] confirm you see a count for each tag
- [x] confirm you can sort by count

**Is your feature request related to a problem? Please describe.**
In #506 we asked for a tag merge solution. But before we merge tags, it would be helpful to understand the spread, scope, and overlap of existing tags.

**Describe the solution you'd like**
Similar to how the language+script list view is, it would be great to add a column to the tag list view with numbers of how often the tag is used.

## dev notes

Should be similar to implementation with `LanguageScriptAdmin` and queryset annotated with `Count`.  

Possibly additional complication that we're using default taggit admin view — will likely have to extend the default taggit admin model object, unregister their version, and register the customized version. It seems unlikely a custom admin model queryset will impact the autocomplete keyword lookup speed, but should be tested.

**Comment by richmanrachel** [comment]
@rlskoeser - this is great! I think we can close this issue now, then can we get a CSV download of just the categories that show up on this tag list view/would it be easy to implement that as a command for this page in general?

**Comment by rlskoeser** [comment]
@richmanrachel what's the use case for a CSV export of tags?

**Comment by richmanrachel** [comment]
@rlskoeser - so that we can re-sort by name, for example, to determine which tags need to be merged. And to identify which of the lesser used tags should be deleted.

**Comment by rlskoeser** [comment]
@richmanrachel you can sort tags by name in the admin site, which is a better place to work with them and do cleanup.

**Comment by richmanrachel** [comment]
@rlskoeser - oh, fantastic! you're right. No problem then :)
