### ISSUE TITLE
Design desktop wireframes of document detail page to communicate the content structure, page layout, and content variations to the project team

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/geniza#91]
_This issue tracks design work through the [CDH design review workflow](https://princeton-cdh.github.io/docs/workflows/#workflow-5)._

Here is a link to the [desktop wireframes on Figma ](https://www.figma.com/file/AG0WY75iWI9oDKFtxen9vD/Princeton-Geniza-Dev?node-id=624%3A11607)

**Description:**

The designs are for the following pages (the revised sitemap is on this figma page for reference):

- document details
- external sources
- scholarship records

also covering variations with:
- no image / one image / more than one image
- no transcription / transcription for one image / transcription for more than one image
- no description
- no external resources
- no scholarship records

Updates: (most of the decisions here need usability testing)
- For this revision I have decided to include the transcriptions visually accessible by default (no clicks) – will be doing usability testing to confirm decisions such as these and the order of info on the page. 

(updates below are same as the ones on #88)
- I have chosen to go with the horizontal nav
- I have also decided to not include "fragments" and "shelf read" in the main nav of this section, I think it makes sense that we have links to the fragment section/page but that it doesn't come next to the other items on the nav of this section
- Also, per RSK's advice I have taken out fragments and shelf read from this issue (I explored them and have some proposals but I also think they should have their own issue, and I have also updated the sitemap per RSK's comments + made fragments and shelf read to be potentially out of scope)
- I have decided to include the "editor" info on the document detail page at least for now till we know more because I think if we include it in the search results it needs to be shown on the landing page of a document
- I have decided to include only the shelfmark, doc type and dates, and the editor info to act as points of reference on the scholarship records and external sources (to know what document the info on these pages is about following Nick's comments on it) – but I think it should be visually less bold here
- the UI for suggesting or editing descriptions and transcriptions are not covered here because it was not part of the goal for the preliminary doc detail view, if you need it please let me know. 
- I have made the "viz" on the scholarship record as simple as possible for now, I'll continue to explore data viz for future revisions. 

specific designs aspects covered in this issue:
- [ ] content structure
- [ ] grid
- [ ] page layout
- [ ] menu/side bar position on page 
- [ ] image option menu position on page
- [ ] image option menu navigation
- [ ] page layout when any field is missing, e.g. images 

**How the proposal/idea can fail:** 
1. if the order and position of content on doc detail page doesn't make sense to users – especially the image and transcription the page layout may need to go through a change that's not subtle.

Same points as on #88
2. Depending on how the content will look like on Scholarship Records, External Resources may not make sense on its own – because this page is only about informing the user about what libraries/institutions hold info about this particular document – it's a bit more general than scholarship records (and I want to avoid nesting them) – but if it can be incorporated as part of Scholarship Records naturally with its content then we may not need that page. 
3. I propose that we navigate through images and transcriptions together – selecting to view image 2 will also show the user the transcription for image 2 – this idea is the most preferable usability-wise but it might fail if we can't support it 

**Questions:** 
1. Does the idea and/or the design make sense to you? If not, please say why
2. **Within the context of this issue**, is there anything that you expected to see and is missing? 
3. Can we do this?: for the user to select a line of text /area of text on the image (that is already outlined) which would visually focus/highlight the piece of transcription that corresponds to it?

Note: 
1. Because this issue and the issue for desktop got a little messy with our conversations on wireframing/fidelity and doing mobile first and uncertainties with how many pages/sections are included in "doc detail view" it's being divided in a messy way this time, the work in each issue will be more structured and appropriately scaled in the future.
2. Since you're now both editors on Figma it should be easier to view the labels I have written for each frame (which should further help with understanding what each page is.

**Comment by thatbudakguy** [comment]
not a ton to add here that isn't covered on #88. I like the way the image is centered if there's no transcription, but side-by-side when there is one. my only thought on seeing the larger transcription viewer is that it would make sense for me to have the little "fragment browser" thing (the pagination and "view entire fragment") closer to the actual viewer, rather than up with the document details. it might be made somewhat redundant though, because the viewer will likely have its own pagination and version of those controls (unless we tell it not to). lmk if this doesn't make sense; it's a little hard to explain without having a IIIF viewer to demonstrate.

another thing to put on your radar (maybe it already is) is to think about the behavior between breakpoints. my assumption when seeing a 10-column grid like this is that the grid scales with the viewport so that there are always 10 columns. that means that the column widths themselves change, so the width of items on the page also changes. when we do that, we generally want to also set a max width so that content doesn't get stretched too far out on huge screens. just something to think about.

**Comment by rlskoeser** [comment]
I like these new desktop designs a lot. Thank you for including examples of all the different variations of missing and different length data!

The only thing that occurs to me as potentially odd is the document with no image and transcriptions for more than one page — it makes sense that the pagination and display should work the same as for documents with images, it just struck me that it would be nice to support using `ctrl-f` on the page (somehow this is more visible on the version without images, although I think it would apply to any multipage content). But IDK how that will work within transcriptions in the image viewer anyway, so we probably shouldn't worry about it right now!

**Comment by gissoo** [comment]
Thank you both for writing. 

I have applied everything here from your comments on #88. 

@thatbudakguy I think I understand what you mean about the little fragment images (not sure if those should be clickable, have been thinking of them more as display) – I think I would still rather them to be where they are because it's what the users first see when navigating to this page and being exposed early on about the fact that there is a bigger picture view/structure involved (i.e. Fragments) is my goal here. 

Also regarding the grid, thank you for bringing it up!! I'm actually thinking of using the updated auto layout feature on Figma for the components to communicate these with you. Can't wait to try it for this project!! It has be super helpful!! :) 

@rlskoeser I'm not sure I understand everything you said (about the point on ctrl-f) but if I understand partially correctly maybe the pagination is less visible on the pages with images because the arrows extend too wide? I can align them with the narrower parts of the page at the top so they would take only two columns. (just like what they look like when there is only a transcription)

**Comment by gissoo** [comment]
@richmanrachel @mrustow This issue is ready for you to review – This is mostly covering the same aspects that the mobile and tablet issue cover, except that on desktop the alignment of content is a bit different since it's a different space. (Note that I will need to conduct usability testing on some of the designs decisions). Again, please ignore all the descriptions above. I'll provide all the updated context here:
[Here are the designs on Figma](https://www.figma.com/file/HpGBOZi9lO8B3nCAx3d4Fj/Princeton-Geniza-Project-team?node-id=572%3A2204)

**If you answered the questions below in the other issue (#88) then ignore them here.**

1. The designs are for mobile and tablet covering: document details, external sources, and scholarship records (the revised sitemap is on this figma page as reference), also covering the designs for a variety of conditions, for when there is:
- no image / one image / more than one image
- no transcription / transcription for one image / transcription for more than one image
- no description
- no external resources
- no scholarship records

2. "External Sources" came up during the ux research phase, as a place where there is a list of the institutions that have the document in their database like FGP or CUDL – RSK has mentioned that we may not have this in the database. Is this possible to do? Or can it be incorporated into the "Scholarship Records" page as one of the sources? Or is it on a different level? 

3. Thinking of including a data visualization (that's simple to understand) on the "Scholarship Records" page, but for now I've listed the total number of record types at the top of the pageas a placeholder. 

4. We have taken the page on fragments and shelf read out of this issue and as potentially out of scope for now. 

5. What should the language be with suggesting a new transcription vs. an edit to an existing transcription? Does having two buttons make sense? 

Please let me know your thoughts and if you have questions  – my goal is to revise and close this issue this week. 
Note: these are wireframes, just covering the following aspects of the designs: 
- [ ] content structure
- [ ] grid
- [ ] page layout
- [ ] menu/side bar position on page 
- [ ] image option menu position on page
- [ ] image option menu navigation
- [ ] page layout when any field is missing, e.g. images

**Comment by richmanrachel** [comment]
For Document Details: 
- Why would the desktop version have a transcription that extends beyond one page? Can't we just scroll to see more? 
- I don't love that the top part is centered, but then below it it becomes right and left adjusted. Can we keep the two column feeling throughout, maybe with only the description centered (or right adjusted but allowed to extend across)?

Scholarship Records and External Sources look good to me! 

@gissoo  - is this what you need from me? Or am I supposed to be doing something with your checkboxes?

**Comment by gissoo** [comment]
> For Document Details:
> 
>     * Why would the desktop version have a transcription that extends beyond one page? Can't we just scroll to see more?
> 

- This is something that I would like to test – it's helpful that you're asking about this – I would like to test with the longest transcription that exists for a document. The concept I'm proposing (to conduct usability test) is mapping a transcription with its image, even if we don't have the image and there is still a transcription. Is your question about scrolling through transcriptions with regards to all the designs for multi-image documents or just the ones with no images? 
- Do you need any indicators to tell you that a specific portion of a transcript belongs to e.g. image 1 vs. image 2? If yes, what do you imagine that indicator to be in the case of a scroll?

>     * I don't love that the top part is centered, but then below it it becomes right and left adjusted. Can we keep the two column feeling throughout, maybe with only the description centered (or right adjusted but allowed to extend across)?
> 

- I would strongly suggest that we don't widen the top portion, because it decreases readability – it would be harder to read the two columns on top when we increase the spacing between then but more importantly the description will become hard to read. The recommended range for number of characters per line is 50-60. If I make it wider than this it would exceed 90 characters per line, which is not great especially on larger screens. 
-  What do you think about the image and the transcription being side-by-side? Do you find it helpful? 
- What do you think about being able to see the transcription by default on this page? Is it what you expected? 
 
> 
> Scholarship Records and External Sources look good to me!
> 
> @gissoo - is this what you need from me? Or am I supposed to be doing something with your checkboxes?
> 

- This is exactly what I need from you. If there are any more thoughts that you have regarding any items in the list of checkboxes please share them with me. We will check them off when Marina has also reviewed the designs, and when we agree on the designs and when you or Marina are closing the issue. Thank you, @richmanrachel!

**Comment by richmanrachel** [comment]
@gissoo 
- So we're reading this correctly, does the gray line help indicate what's on the screen prior to scrolling down?

I think everything looks good!

**Comment by richmanrachel** [comment]
@gissoo - I guess the only questions we have are about navigation, because since we don't see the sidebar or what's on top, we don't really know how to answer your queries about them. 

And what do you mean by "grid?"

**Comment by gissoo** [comment]
> @gissoo
> 
>     * So we're reading this correctly, does the gray line help indicate what's on the screen prior to scrolling down?
> 

- let's discuss this, not sure I know what you mean, will screen share during the meeting. 

> I think everything looks good!
>

**Comment by gissoo** [comment]
> @gissoo - I guess the only questions we have are about navigation, because since we don't see the sidebar or what's on top, we don't really know how to answer your queries about them.
> 

- great, let's discuss at the meeting – the sidebar/menu is what you see as "Document Details", "Scholarship Records", and "External Sources" at the top – since this is a wireframe it needs to not be styled on purpose so it looks very raw right now, but that will look more like a bar when I style it. 

> And what do you mean by "grid?"
>

- grid is just the red columns you might have seen on some of the screens – it determines how the wide or narrow the content could be laid out (related to how we were discussing the width of the content above transcription and image and the character limit per line that I mentioned to you for readability)

**Comment by gissoo** [comment]
Conclusion – the project team is clear about the designs and the responses above – This issue is ready to be closed.
Note: GD will have review meetings with Rachel and Marina for the next couple of design issues to walk them through the designs, and to make them comfortable with Figma and reading designs.
