### ISSUE TITLE
As a content editor, I want transcription content linked to a scholarship record so that it is clearly documented who authored the transcription and where it came from.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#913]
## testing notes

- [x] on public document detail page, if logged in as a content editor and there is an existing transcription, you should see a link to "edit X's transcription"
- [x] clicking the link should take you to the transcription editor for that transcription
- [x] test a document with more than one existing transcription: the transcription content should be separated correctly by source (i.e., when you open the editor you should only be editing one transcription at a time and it should be the correct one)

## dev notes

general approach: transcriptions for different sources will be edited on different urls; we'll store the uri for the scholarship record (source) as a custom field on the annotation so that we can find them again

- differentiate editing existing transcriptions and adding new ones:
  - [x] revise transcription editor url to take a source id to)
  - [x] revise admin links from document details; we'll need separate links for  "edit x's transcription" and "add a new transcription"
- link annotations to sources:
  - [x] implement a URI method on `Source`; use the `ANNOTATION_MANIFEST_BASE_URL` configuration rather than current site absolute url; numeric db id is fine
  - [x] pass source uri as an optional config to tahqiq
  - [x] on save, set source uri as `dc:source` on the annotation (annotation top level)
  - [x] implement a search option in the annotation search view to find annotations by uri _and_ source
  - [x] on load, filter annotations by source uri to get only the annotations for the current source

see also #1002

**Comment by rlskoeser** [comment]
@blms let's use `dc:source` for the scholarship record URI — I just looked at extensions, that's already one of the namespaces that's included in the annotation json context.

**Comment by kseniaryzhova** [comment]
@rlskoeser Every time I click to edit a transcription from the public site, it takes me to the bottom of the page so I have to scroll all the way up to see the actual transcription. PC, Microsoft Edge, Adblocker. Everything else works though!

**Comment by rlskoeser** [comment]
@kseniaryzhova oh yes! I noticed this and mention it to @blms but I don't remember if we're tracking it anywhere yet — the zoom image autoscroll functionality we wanted on the public site needs to be turned off when we're in transcription edit mode since we load all images in deep zoom mode by default for editing.

**Comment by blms** [comment]
Tracked here! https://github.com/Princeton-CDH/geniza/issues/1037

**Comment by rlskoeser** [comment]
did not mean to reopen this!
