### ISSUE TITLE
As a content editor I want to add or edit labels for blocks of transcription text so that I can indicate new sections or different kinds of texts.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#915]
## testing notes (qa)

After testing https://github.com/Princeton-CDH/geniza/issues/911, confirm:
- [x] You can add/edit a label in a separate text box from the annotation body
- [x] Labels persist after saving, and are properly deleted along with a deleted annotation
- [x] labels are optional

## dev notes
- [x] determine how/where to store labels in the annotation object (tag or special metadata)
- [x] store label on the annotation text (annotation.resource.label)
- [x] update tahqiq to add optional field for editing/adding labels
- [x] populate label with existing value when present
- [x] ensure storage plugin persists label when converting between v2 / v3 annotations

**Comment by richmanrachel** [comment]
Works! Closing :)
