### ISSUE TITLE
As a content admin I would like to see counts and/or be able to export user log entries so that I can quantify how much work a content editor has contributed to the database. 

### ISSUE THREAD

**Issue by richmanrachel** [Princeton-CDH/geniza#918]
## testing notes
test log entry csv export — should be available from the [log entry admin list](https://test-geniza.cdh.princeton.edu/admin/admin/logentry/) on the test site, and should work like the other csv exports:
- [x] download all
- [x] select and download for a subset
- [x] CSV should include dates, usernames, information about what kind of record was changed (content type), information about what was changed, and indication of what action was taken (addition, change, deletion)

----

**Is your feature request related to a problem? Please describe.**

@rlskoeser - this is not a priority item, but I have been thinking about it for a while, so it would be helpful to know how difficult/easy this is to execute.

Just as we asked for a copy of all of Alan's log entries, it would be helpful as a Project Manager to do this for all the RAs. Every quarter when I prepare for a Geniza Lab meeting, I try to quantify what work has been done since our last meeting in order to praise and highlight the work the team has done.

Right now I have to go manually by each username and month and add all the numbers together. It would be nice if I could choose a full time frame for all users and export the data to sort by user.

**Describe the solution you'd like**
Have a "export selected user logs to CSV" action

**Describe alternatives you've considered**
I'm open to other options!

**Comment by kseniaryzhova** [comment]
@rlskoeser works for me, closing!
