### ISSUE TITLE
Design a toggle that activates and deactivates image zoom on mobile so that images are not zoomable and scroll traps by default 

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/geniza#920]
@rlskoeser @blms please take a look at this and let me know your thoughts – I reduced my proposals to two – [proposal 1](https://www.figma.com/file/anZFStv7zBaVWnFxr95nKt/Work-in-Progress-%2F-WIP?node-id=1863%3A46498) and [proposal 2](https://www.figma.com/file/anZFStv7zBaVWnFxr95nKt/Work-in-Progress-%2F-WIP?node-id=1863%3A46499)  – you can also view explanations in the links. 

- I've shown three toggle designs – now that we've chosen the round design for the slider I'd also prefer the round version for this one
- The expected gesture to activate/deactivate the toggle is tap. 
- Design of the toggles doesn't change in the two proposals, it's mainly the interactions around it that change, which I think would be important to consider now.

**Comment by rlskoeser** [comment]
We discussed on slack but I forgot to document here! I like proposal 2 better — zoom slightly when zoom is enabled, no help prompts about how to interact with the image.

I would like to implement without the scrolling tip first and test if it causes confusion.

**Comment by blms** [comment]
I agree, I prefer proposal 2. 

In our Slack discussion, we talked about the possibility of doing a full screen view with an X to close it on mobile, instead of a toggle switch:

> @blms:  It’s just the difference between hitting a toggle to disable deep zoom, vs an X to close the full screen, right?

> @gissoo: [Marina] said it’s fine as is right now – and really liked being able to access the text easily 

> @gissoo: but currently many images take the full height of the screen anyway – is it really that different?

> @gissoo: that’s why I was bringing up the fact that the difference between the two really are the X vs the toggle – seems pretty much the same amount of effort to see content below the image

> @rlskoeser: we talked about having a dedicated fullscreen view later on that would not be mvp

Re-reading, it sounds like we decided this should eventually be the case, but is not MVP. Does that sound right—and for now I'll just implement the toggle and we can close?

**Comment by rlskoeser** [comment]
@blms correct — let's make full-screen not MVP and just implement the simple case with the toggle.

**Comment by gissoo** [comment]
@blms we also won't worry about any text hints for now for this issue.
