### ISSUE TITLE
Design a control for image rotation so that users can rotate images on desktop 

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/geniza#922]
@rlskoeser @blms [Here is the proposal for the image rotation. ](https://www.figma.com/file/anZFStv7zBaVWnFxr95nKt/Work-in-Progress-%2F-WIP?node-id=1863%3A62422)There are three styles. Please let me know what you think.

**Comment by rlskoeser** [comment]
@gissoo I don't know how much control we have over the styles yet. 

These kind of look like eyeballs to me? does that matter? 

I don't have a strong preference among these.
