### ISSUE TITLE
Design transcription panel "not available" button so that it is more distinguishable from "not open".

### ISSUE THREAD

**Issue by richmanrachel** [Princeton-CDH/geniza#925]
_This issue tracks design work through the [CDH design review workflow](https://princeton-cdh.github.io/docs/workflows/#workflow-5)._

@gissoo - Continuing the work from #893, I think it would be helpful for the design to be slightly more distinct between "unavailable" and "not currently open" on the transcription panel. Right now it's only a soft shade of gray/lack of boldness, and I fear that some users may get frustrated not noticing the difference (ex. here where translation is not available):
![image](https://user-images.githubusercontent.com/68028846/173614515-834a95f9-984a-457e-b597-a59cc479e67a.png)

Could we add crosshatching or some other distinct visual marker to make it clearer?

Thanks!

**Comment by rlskoeser** [comment]
I discussed with @gissoo — we think the distinction between these two states is clear enough, and Marina approved these designs. We're not going to spend designer and developer time on revisiting the deactivated toggle styles at this point.
