### ISSUE TITLE
As a content editor, I want a faster document search in the admin site, so that matches on long combinations of joins do not crash the site.

### ISSUE THREAD

**Issue by richmanrachel** [Princeton-CDH/geniza#93]
## testing notes
Login to django admin and go to the document list view. All tests should be done with search on this page.
- confirm that you can search on each of these fields:
   - [x] type
   - [x] shelfmark
   - [x] tag 
   - [x] description
   - [x] notes
   - [x] needs review
   - [x] pgpid 
- [x] test some of the problematic searches that were timing out before
- confirm that making changes in the database updates the search (there may be a slight delay in some cases before the changes are visible in search results)
   - [x] make a change to one of the document fields and confirm you can search on it (e.g., add test text to the description)
   - [x] make a change to a related fragment (e.g. edit the shelfmark)
   - [x] rename a document type and then search for the new name
   - [x] rename a tag that has documents associated and then search for documents by the revised tag

Because this search is powered by solr, it does support advanced search syntax (wild cards, exact phrase, etc) but I'm not sure how much you want to rely on that since it's not available in the other admin searches.

## dev notes
- [x] add parasolr to requirements, installed apps
- [x] update `Document` to extend `Indexable` and implement `index_data` method (not exhaustive; equivalent to current admin search fields)
- [x] add signals to reindex `Document` on save / related object save
- [x] implement `get_search_results` on `DocumentAdmin` using Solr; refer to [mep example](https://github.com/Princeton-CDH/mep-django/blob/main/mep/books/admin.py#L124-L145)

**Comment by richmanrachel** [comment]
@rlskoeser - Most of the searches work but with a couple major (and important) exceptions:
- Search does not work for shelfmarks (and therefore I couldn't test the ones previously giving me trouble).
- A new note that I added on the site was searchable, but existing notes from the spreadsheet were not. 
- When we edited a shelfmark, the shelfmark changed but did not show up as a search result.
- New tag name did not show up in search.

**Comment by rlskoeser** [comment]
@richmanrachel thanks for the great testing notes, will look into the things that are not working.

One clarification question, when you say existing notes from the spreadsheet are not searchable, which notes do you mean? We're not currently importing technical notes or notes 2 (still waiting on a decision from Marina about where they should go or if they need to be imported at all).

**Comment by richmanrachel** [comment]
@rlskoeser - I think we forgot that detail, so no worries then!

**Comment by rlskoeser** [comment]
@richmanrachel the shelfmark and tag fields were configured incorrectly before! Please try again.

A couple notes: 
- if you're searching by shelfmark, you may get more matches than you expect — the search is configured to match all parts of the query, but it will match in any of the fields included in the search (e.g., numeric portion of the shelfmark could match against pgpid, and if the other portion of the shelfmark is included anywhere in the description you'd find that record). If you want to find a document by exact shelfmark, try putting quotes around the shelfmark.
- If you're searching for a join, don't include the `+` in your search.

**Comment by richmanrachel** [comment]
@rlskoeser - the shelfmark search works! and works much better for the ones previously causing issues. Thanks!

However, I can't get these two to work:
- make a change to a related fragment (e.g. edit the shelfmark)
- rename a tag and then search for associated documents by the revised tag

The shelfmark I changed for testing is ENA 1867.20TEST, and the renamed tag is 13th c test.

**Comment by rlskoeser** [comment]
@richmanrachel so glad to hear this is working well for the shelfmarks that were causing problems before.

regarding the things that aren't working:

- Searching for "ENA 1867.20TEST" is working now. How long did you wait after renaming it before you tried searching for it? 
- I can't find a tag named "13th c test"; I see one named "13th century test" but it doesn't seem to have any documents associated. Would you try renaming a tag with a few documents associated? (I see now I didn't specify that in my instructions, sorry!)

**Comment by richmanrachel** [comment]
It's still not showing up for me on document or fragment search:
![image](https://user-images.githubusercontent.com/68028846/119191064-2c648c80-ba4c-11eb-9e18-3ad396beee01.png)
![image](https://user-images.githubusercontent.com/68028846/119191101-371f2180-ba4c-11eb-8ede-31f34531d677.png)

**Comment by richmanrachel** [comment]
Changing the tag did work immediately :)

**Comment by richmanrachel** [comment]
Tested new fragment, success! Happy Friday!
