### ISSUE TITLE
As a content editor working in the admin interface, I want a warning/error if I try to save a new document without a shelfmark.

### ISSUE THREAD

**Issue by richmanrachel** [Princeton-CDH/geniza#935]
## testing notes

On the [QA site](https://test-geniza.cdh.princeton.edu/admin/), try to create a document without attaching any fragments. It should display an error when you try to save it.

---

Background: Yusuf thought he was running into a bug when he was adding new documents and they were attached to "related documents" on the front end. But the issue is that he was using the shelfmark override to input the shelfmark, rather than using the "related fragments" field to properly connect the fragments field in the relational database. While investigating, Rachel discovered that other users had made the same mistake, resulting in 14 documents that were technically fragment-less. 

Proposal: Some kind of error message or genuine error that prevents saving a new document entry without a related fragment. RR doesn't have a strong preference for how this is done, but we do want the user to be made aware so that we don't have any fragment-less documents.

**Comment by kseniaryzhova** [comment]
@blms I wasn't able to even click create document - sent me a server error message: 
![image](https://user-images.githubusercontent.com/105385128/212405564-06ee3fe8-3315-450b-8aa5-12ca7607a1cc.png)

**Comment by kseniaryzhova** [comment]
@blms works now! Closing, thank you!
