### ISSUE TITLE
As a desktop user, I want to click to rotate the deep zoom image of a fragment so that I can view it in alternate orientations.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#937]
## testing notes

This is a provisional rotation solution for mvp of the new viewer so we can get it out sooner, so it just needs to be good enough for now.  Gissoo intended it for desktop only, but I asked Ben to make it available on mobile so you can compare the functionality with the buttons vs touch rotation and let us know what you prefer.

Please try out the rotation on the test site to confirm:
- [x] rotation buttons are disabled until deep zoom is activated
- [x] rotation buttons worked as expected once you activate deep zoom

## dev notes
Simple version of rotation for mvp version of image+transcription viewer.

- [x] add appropriate phosphor icons for rotation; place them roughly where the designed angle rotation will go (hopefully there's space).
- [x] bind rotation icons to OpenSeaDragon controls for rotate left and rotate right in OSD config
- [x] remove OSD image preloading

**Comment by richmanrachel** [comment]
@rlskoeser - works perfectly! I think I still want Marina to weigh in re: mobile, but this is good to close!
