### ISSUE TITLE
As a content editor, I want to be able to search for tags with or without diacritics and get the same results.

### ISSUE THREAD

**Issue by mrustow** [Princeton-CDH/geniza#943]
## testing notes

- [x] Try the below search and confirm it works as expected
- [x] try adding a new tag with diacritics — tag should be saved with the diacritics removed
- [x] confirm existing tags have had diacritics removed
- [x] confirm tag variants with and without diacritics have been merged correctly 

## deploy notes

- [ ] solr reindex

---

On the admin interface > taggit, I typed hujra (no dot under the H) into the search bar and received this result:
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/73319225/178540505-ac18a681-3d3a-467b-ab31-872eaacb5e5c.png">

However, I knew that #ḥujra is associated with 4 documents. So then I searched for ḥujra and received this result:
<img width="1443" alt="image" src="https://user-images.githubusercontent.com/73319225/178540775-8976e188-818a-4fe4-b41f-c126e12019cd.png">

Lots of our tags don't use proper diacritics, so it would be better for us to be diacritic-agnostic.

Which we do seem to be already in the document view in the admin interface, and in searching the public site. 

Thanks! 🥇

**Comment by rlskoeser** [comment]
@richmanrachel is it ok for tags to not allow diacritics? wondering if we can tackle this in tandem with #499 — collapse tags that are the same except for diacritics, and then add logic so that in future diacritics are ignored when creating tags.

**Comment by richmanrachel** [comment]
@rlskoeser - yes! Especially since Marina already requested this, I'm happy with this solution

**Comment by richmanrachel** [comment]
This didn't quite work either. The slug correctly took out diacritics, but the search doesn't include the slugs I guess? no results for mualim but returning correct result with diacritics:
<img width="451" alt="image" src="https://user-images.githubusercontent.com/68028846/184223530-c742c07c-b0eb-4ff4-92f7-f0f08dfa59ce.png">

**Comment by blms** [comment]
Ah—this is a problem with the "add tag" functionality in the Tags section of the admin, rather than adding a tag to a document. Looks like our diacritic-stripping code is not run when you create a tag separately!

**Comment by richmanrachel** [comment]
I didn't read through all the tags to ensure that all of the diacritics were properly dealt with, but I did look over about 400. The only potential error I saw was this one:
<img width="417" alt="image" src="https://user-images.githubusercontent.com/68028846/184896889-8c5d8ad3-febd-4363-a61e-b0460891e625.png">

But if I only found 1/400 with errors, I think that's still enough to close as this gets us to a much easier place for tag cleanup. Do you agree, @rlskoeser ?

**Comment by rlskoeser** [comment]
@richmanrachel I agree with you — the near-duplicates I saw were variations like plural/singular, and I think those are ones that I think would be better to handle manually when we get the tag merge function implemented. Thanks for reviewing so carefully.

**Comment by richmanrachel** [comment]
@rlskoeser - perfect, closing now!
