### ISSUE TITLE
admin footnote download results in an empty csv file (headers only)

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#946]
**Describe the bug**
Attempted to download csv file for footnote data and got an empty csv that included the headers but no content. Happened whether I tried to download all using the button or selected a set and download jest a portion

**To reproduce**
1. Log in to admin
2. Navigate to scholarship records > footnotes
3. Click "download all as csv" OR select some records and choose action "export selected records to CSV" and hit go
4. Downloaded file contains headers but no content

**Expected behavior**
Downloaded file should include information for all or selected footnotes

**Comment by richmanrachel** [comment]
@rlskoeser - by "content" do you mean any content or what belongs under the "content" header? here's what the sample I just downloaded looks like:
<img width="836" alt="image" src="https://user-images.githubusercontent.com/68028846/179064973-80708aa9-8ce3-496c-99a6-07590b893fed.png">

**Comment by rlskoeser** [comment]
@richmanrachel whoops, sorry for being unclear — I mean any rows other than the header row. In production I only got the header row and nothing else. This looks reasonable to me!

**Comment by richmanrachel** [comment]
@rlskoeser - great! Closing :)
