### ISSUE TITLE
As a content editor, I want to view and edit transcription edit synced from TEI so that I can correct or remove incorrectly synced content when necessary.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#950]
## testing notes
In django admin, go to scholarship records > footnotes, filter to footnotes with digitized transcription, and then edit.

You should see an editable field for `content` now, which contains the JSON structured data generated by the `sync_transcriptions` script. In most cases we shouldn't be editing this directly, but when the sync is broken or not updating, it may be a useful stopgap.

Try editing this record, which has only "see [shelfmark]" content: https://test-geniza.cdh.princeton.edu/admin/footnotes/footnote/5420/change/

(That footnote is marked as a transcription and not edition, so it isn't showing up on the public site — but if you want to see how this impacts the public display, you can mark it as edition, save it, look at pgpid 5383, remove the transcription content, and then refresh 5383 and you should see the difference.)

test cases:
- [x] confirm you can remove unwanted transcription content (like the "see also" record above)
- [x] try saving with invalid JSON structure (you could just remove part of it, or replace the content with text) — you should get an error and not be allowed to save

## dev notes
make `content` jsonfield editable in admin

**Comment by richmanrachel** [comment]
@rlskoeser - This was really helpful! I was able to resave without the JSON and it made the frontend cleaner. I think we should just issue a clear message to the General PGP channel when it goes into production
