### ISSUE TITLE
As a content editor, I want to filter the document list view to include translation (Y/N) in order to find translations

### ISSUE THREAD

**Issue by kseniaryzhova** [Princeton-CDH/geniza#952]
## Testing notes (QA)

On the [QA admin site](https://test-geniza.cdh.princeton.edu/admin):
- [x] After adding some translations, in Documents, there should be "has translation" "yes/no" links, which should filter on the presence of digital translation content.

---

We want the translation filter to mirror the transcription filter. 
**Fields**
By Translation
- All
- Has translation
- No translation

**List Fields**
Same as above 

**Edit Fields**
N/A

**Search Fields**
N/A

**Default sort**
All

**Filters**
See above

**Date Hierarchy (optional)**
N/A

**List Fields (optional)**
N/A

**Field translation (optional)**
Up to CDH discretion

**Related models**
Parallel to transcription filter

**Additional context**
Adding this in order to make the admin and public csv download better.

- Ensure that the admin site "has translation" filter applies to digital translations only

**Comment by blms** [comment]
@kseniaryzhova Yes that would be a separate one!
