### ISSUE TITLE
As a content editor, I want the admin csv download to include transcription (Y/N) and translation (Y/N) so that I can filter documents to this with or without transcription or translation.

### ISSUE THREAD

**Issue by kseniaryzhova** [Princeton-CDH/geniza#953]
**Is your feature request related to a problem? Please describe.**
Building off of issues #951 and #952, we want the admin csv download to mirror the document list view options on the admin site.

**Describe the solution you'd like**
See above - add transcription (Y/N) and translation (Y/N) to the admin csv download. This EXCLUDES bibliographic information for the transcriptions and translations in order to keep the download manageable. 

**Describe alternatives you've considered**
N/A

**Comment by quadrismegistus** [comment]
I'm working on this now

**Comment by kseniaryzhova** [comment]
@rlskoeser confirm that I see separate columns for has translation and has transcription in the csv download, and that they are marked Y/N. Closing, thank you!
