### ISSUE TITLE
As a content editor, when I select a fragment “side” in the document edit form I want an indicator of which fragment images will be displayed so that I can confirm I’m selecting the correct side or sides.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#955]
## testing notes (qa)

In the admin edit form for a document, in the "related fragments" section, change the selected "Side" for a fragment connected to the document. Save your changes on the document, and scroll back down to the fragments section. There:
- [x]  Confirm that the selected side or sides are clearly highlighted in the image thumbnails

## dev notes
Side information is stored in `TextBlock.side` and can currently be recto, verso, or both.

- [x] revise the `Fragment.iiif_thumbnails` method used in the textblock inline display to add a class for selected image based on side. (For now assume recto / verso matches iiif image order). 
- [x] add admin css to add an indicator to thumbnails based on the selected sides (e.g. colored outline or similar)

**Comment by rlskoeser** [comment]
@mrustow or @richmanrachel how do you use (or want to use) the `side` field (recto, verso, recto & verso) wen a fragment has more than two images? Do you need a way to select a subset of images as being part of the document when there are more than two images? 

Here are a few shelfmarks with more than two images in case it's helpful to look at examples (let me know if you want the whole list):
- T-S Ar.54.46
- Or.1081 J56
- T-S 10J7.6
- T-S 8J17.18

In my local development data (which is probably slightly out of sync) I found 293 IIIF manifests with more than two associated canvases out of 15,455 total cached manifests.

**Comment by rlskoeser** [comment]
@richmanrachel are these cases where you'd want to make a custom iiif manifest, like Alan and I discussed on #701 ? Or is this a case where the manifest is fine but you want to select which images from it are relevant?

We'll need to discuss how to support selecting images in cases that are not simple recto/verso, I'm not sure how to approach it.

**Comment by richmanrachel** [comment]
@rlskoeser - I don't think I can make a decision about this without further discussion. Is this a blocker for what you're trying to get out today? Or can we discuss it next week?

**Comment by rlskoeser** [comment]
@richmanrachel Not a blocker, and agreed we should discuss. We'll work on the implementation for the simple cases for now, which will hopefully give us all more context for thinking about the other cases.

**Comment by richmanrachel** [comment]
Works!
