### ISSUE TITLE
As a user, when I search for a document that is only on one side of a fragment, I want to see the relevant image first so that I can preview the document more accurately.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#956]
## testing notes (qa)

After setting a "side" for a fragment on a document in #955, search for that same document in the public site search (can search like `pgpid:###`). 
- [x] Confirm that in the search results page, only the thumbnail for the selected side shows up.

## dev notes
In `Document.index_data` when indexing iiif images in Solr, only include images that are part of the current document based on recto/verso side information; if `side` is unset, don't filter images. Looks like it would be easiest to implement as an optional param to the `Document.iiif_images` method.

**Comment by richmanrachel** [comment]
Beautiful, closing!
