### ISSUE TITLE
As a user viewing document details I want to see which images are not part of the document so that I understand which parts of the fragment are used for the current document.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#957]
## testing notes (QA)

For [several documents](https://github.com/Princeton-CDH/geniza/issues/957#issuecomment-1218446947) containing images that are not selected (in the admin, i.e. designated as being part of the document), check the document details page image viewer and confirm:
- [x] it is clear which images are and are not part of the document
- [x] if applicable, link or links appear under the excluded images to documents that _do_ include them

## dev notes

design work for this feature was tracked on https://github.com/princeton-cdh/geniza/issues/884 ([here is the design](https://www.figma.com/file/anZFStv7zBaVWnFxr95nKt/Work-in-Progress-%2F-WIP?node-id=1565%3A53416))

summary of decisions:
- images that aren't part of the current document are displayed with white box with 60% transparency on top of the image
- these images are _not_ zoomable
- we still display shelfmark and side information as for other images
- we should not display transcription content adjacent to non-document images
- if there is a document on that image, we link to it in place of transcription; Figma design says "view document details", but we will use document title (type + shelfmark). Note that there could be multiple documents. [let's make this a separate issue]

implementation:
- [x] add an included/not included indicator to information returned by `Document.iiif_images` (similar to the admin version in #955 )
- [x] add an appropriate class name or other to non-document images in `document_transcription.html`
- [x] add styles for non-document images
- [x] omit zoom behavior for non-document images
- [x] when displaying transcription content in `document_transcription.html`, skip non-document images (not sure how to do this in current forloop structure; if it's complicated let's discuss)

implementation updates after design revision and transcription format decision:
- [x] update non-document image display and links to match revised designs as documented in https://github.com/Princeton-CDH/geniza/issues/997#issuecomment-1209723393
- [x] revise sync transcript to return html in a dict of lists keyed on canvas uri; skip non-document images
- [x] in document transcription template, display transcription html by canvas uri instead of index using `dict_item`

**Comment by rlskoeser** [comment]
@gissoo what should happen to the links to other documents when only the transcription panel is showing? Do they go away?

**Comment by gissoo** [comment]
@rlskoeser it's fine if the links to other documents stay in the format you've mentioned "document title (type + shelfmark)"

**Comment by rlskoeser** [comment]
Revised estimate from 2 pts to 3 since we had to add logic to associate html chunks with canvases skipping non-document images.

**Comment by rlskoeser** [comment]
For convenience, to help with testing this, here are a handful of records that have non-document images specified:

T-S Ar.5.1 (PGPID 1264)
T-S 8J7.23 (PGPID 5505)
CUL Add.3417 (PGPID 3970)
ENA 2728.5 (PGPID 2652)
T-S 8J4.2 (PGPID 2120)
CUL Or.1080 J138 (PGPID 3980)
ENA NS 18.24 (PGPID 813)
T-S 10J28.11 (PGPID 2986)
T-S 12.320 (PGPID 5522)
Moss. VII,17 (PGPID 9141)
T-S 13J26.24 (PGPID 1082)
T-S 16.172 (PGPID 3432)
T-S 16.56 (PGPID 4088)
T-S 8J37.2 (PGPID 4581)
T-S K15.94 (PGPID 4635)


Found with this queryset filter:
```python
Document.objects.exclude(textblock__selected_images=]) \
   .filter(fragments__manifest__isnull=False) \
   .filter(footnotes__content__has_key='html')
```

**Comment by richmanrachel** [comment]
@rlskoeser - It looks good, but I ran into a problem when I noticed that one of the images was improperly marked. When I changed it to a new image, the transcription disappeared (PGPID 2120)

**Comment by rlskoeser** [comment]
@richmanrachel interesting! that makes sense with the current implementation — it should show up  properly once the sync transcription script runs again. Do you want me to run it now to confirm?

**Comment by richmanrachel** [comment]
@rlskoeser - yes, that seems like a wise idea! Thank you!

**Comment by richmanrachel** [comment]
1082 is another example of the wrong side being tagged (because of disagreement between library and editor) - flagging for myself

**Comment by rlskoeser** [comment]
@richmanrachel sync transcriptions script re-run complete

**Comment by richmanrachel** [comment]
@rlskoeser - it worked! Closing :)

**Comment by blms** [comment]
Closing per above comment!
