### ISSUE TITLE
As a user looking at images for a single document, I want easy access to documents on images from the same fragment that are not part of the current document.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#958]
## dev notes

This is a follow up / refinement to #957 

If a document has images that are not part of it, which have other documents, we should link to them in the space where we would normally display the transcription.   `Document.related_documents` which we use for the Related Documents tab should find the correct records; maybe call it in the view if a document includes non-document images, and then filter documents for display based on the iiif url indexed in Solr index data based on side information.

**Comment by richmanrachel** [comment]
Something I noticed in the backend as I was testing #957 but is even more evident on the frontend is how the intro text still stays with the first image, regardless of whether that image is part of the document:
<img width="1051" alt="image" src="https://user-images.githubusercontent.com/68028846/185242883-579174f0-4091-4b73-be93-79a05868f24d.png">

**Comment by richmanrachel** [comment]
But this feature is working as expected, so I'll close here!

**Comment by rlskoeser** [comment]
> Something I noticed in the backend as I was testing #957 but is even more evident on the frontend is how the intro text still stays with the first image, regardless of whether that image is part of the document

Yes... I guess when we give you the image order override feature, then you can re-order so the non-document image isn't first?

**Comment by richmanrachel** [comment]
@rlskoeser - hmmm... yes, that's probably a good idea. Now that we're replacing recto/verso with ordering it hopefully won't screw things up?

**Comment by rlskoeser** [comment]
@richmanrachel I think that it will work and not cause new problems. :-) Can you make a note somewhere so we can keep this in mind as a test case to try when we test the ordering feature and the transcription editor work?

**Comment by richmanrachel** [comment]
@rlskoeser - yes, will do. Thanks!
