### ISSUE TITLE
As a user, I want the full citation for a transcription in context so I know who authored it and where it came from.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#959]
## testing notes (qa)

- [x] Check the transcriptions for a few different kinds of documents—example PGPIDs could be: 606, 9121, 2691, 4508, 3254—and confirm that the citation in gray text provides the necessary information, including when switching between multiple transcriptions.

## known revisions needed

- [x] switching back to Gil edition on [pgpid 606](https://test-geniza.cdh.princeton.edu/en/documents/606/), Goitein on [pgpid 9121](https://test-geniza.cdh.princeton.edu/en/documents/9121/) loses some info (related to links?)

## dev notes

Transcription citation should be displayed in gray at the top of the transcription panel.

This was already implemented in an earlier phase even though it was not mvp, but I'm not sure it was tested directly and I noticed in passing some citations that didn't look correct. Let's check the dev implementation and be sure we're using the correct citation and then test it with all source variations.

**Comment by blms** [comment]
We are indeed using the same short citation format that is used in the metadata section. A few things I noticed:

1. That citation format doesn't seem to italicize book titles—I recall vaguely that it was intended to be plaintext, but should it be?
2. Should the citation format include "[digital geniza document edition]"? Right now we're only including that on the long format, but in the designs it appears next to the transcriptions.
3. I noticed sometimes the spacing is different depending on whether or not there is a heading. It interacts strangely with the `min-height` we set on the citation. I think that's more of a problem with the transcription styling than the citation styling, though. See below:
   <details>
   <summary>Spacing differences</summary>
   
   <img width="698" alt="Screen Shot 2022-07-25 at 2 18 49 PM" src="https://user-images.githubusercontent.com/7234006/180846719-435317d1-a77b-4bda-b9c8-b729e4bb606f.png">
   <img width="677" alt="Screen Shot 2022-07-25 at 2 18 53 PM" src="https://user-images.githubusercontent.com/7234006/180846726-91d427f0-f4f1-459f-bcdf-65470802e7ee.png">
   <img width="684" alt="Screen Shot 2022-07-25 at 2 18 57 PM" src="https://user-images.githubusercontent.com/7234006/180846728-c1b2a568-dbf1-497d-a304-ee0b11037452.png">
   
   </details>
4. Unrelated, but I found during this testing that the transcription switcher doesn't work at all for documents with no images, so time to fix that!

**Comment by rlskoeser** [comment]
@blms I think we should use the formatted citation. Maybe it's easier (except for layout/spacing) if we use the formatted version — the `formatted_display` method. We've discussed including the citation in the copy/paste version of the transcription text, and in that case researchers would definitely want the full citation — and what they copy should probably match what we display. Ergo, full citation with formatting please.


I think the min-height really only comes into play with documents that have more than one transcription. Maybe that helps us somehow with how we approach it?

**Comment by richmanrachel** [comment]
Love it! Closing :)

**Comment by blms** [comment]
Reopening due to the issue I found with links, marking as tested needs attention too

**Comment by rlskoeser** [comment]
tested switching between editions on pgpid 606 and pgpid 9121, I think it's behaving as expected; links are preserved and display properly after switching
