### ISSUE TITLE
As a content editor, I want to create and edit scholarship records so that I can keep track of relevant scholarship on documentary geniza fragments.

### ISSUE THREAD

**Issue by richmanrachel** [Princeton-CDH/geniza#96]
## Testing Notes
In the **footnotes** section in the admin, as a **Content Admin**:
- [x] Check that the provided list of **Source types** have been created
- [x] Add a new **Creator**
- [x] Add a new **Source Language**
- [x] Add a new **Source**. Confirm that the admin list display and edit fields are appropriate.
- [x] Enter values for the multiple languages in a Source. Confirm that it works as expected.
- [x] Confirm that you can add multiple authors to a Source and order them (drag using the gray bars on the left of the creator row after saving)
- [x] Add a new **Source type**. Confirm that the admin display is appropriate.
- [x] In the Source list, confirm you can sort by author and that it sorts by first author when there are multiple

As a **Content Editor**:
- [x] confirm you can view all of the source records (creator, language, type, source)
- [x] confirm you can add and edit creators, source types, source languages, sources
- [x] confirm you cannot delete any of the above

---

**Fields**
Provide a list of the fields to be included on this model. 

- Sourcetype (book, article, unpublished, dissertation, web/blog?)
- Author(Last name, First name)
- Title
- Date
- Edition Number (i.e. Gil #45)
- Volume
- Page range
- Edition/Translation/Discussion tickbox (mandatory to input at least one value, but allow all three)
- Language of the source

**List Fields**
Which fields should be included on the django admin list view?

- Author
- Title
- Date (year only)
- Edition Nr.
- Edition/Translation/Discussion (boolean)

**Edit Fields**
Which fields should be editable via django admin view? Please list them in the order you want them to appear. Indicate which fields are optional, and any fields that should be displayed but not editable.

- Sourcetype (book, article, unpublished, dissertation, web/blog?)
- Author
- Title
- Date (Month optional, Year optional)
- Edition Number (i.e. Gil #45) (optional)
- Volume (optional)
- Page range (optional)
- Edition/Translation/Discussion tickbox? (at least 1)
- Language of the source (at least one)

**Search Fields**
Which fields should be searchable in the django admin list view?

- Author
- Title
- Date (Year)

**Default sort**
Which field should be used for initial sorting?

- Author (Last name)

**Filters**
Which fields should be used for list filters?

- Edition
- Translation
- Discussion

**List Fields (optional)**
Which fields (if any) should be editable on the django admin list view?

- Sourcetype (book, article, unpublished, dissertation, web/blog?)
- Author
- Title
- Date (month and year, both optional)
- Edition Nr. (optional)
- Volume (optional)
- Page range (optional)
- Edition/Translation/Discussion tickbox? (at least 1)
- Language of the source

**Field translation (optional)**
Which fields (if any) do you want to provide in multiple languages?

- Author name
- Title

**Related models**
List any directly related models (database tables) that would be helpful to edit when on the same page when editing this one.

- Documents
- 
-----

## dev notes
This implementation can be adapted from the footnotes app we've used in other projects; most recent version and most extensively used is in mep-django: https://github.com/Princeton-CDH/mep-django/tree/main/mep/footnotes

We also agreed in a meeting that authors would be tracked as people, so let's go ahead and stub out a people app with a person model for this.

- [x] people app
   - [x] stub person record with last name, first name
   - [x] setup model translation for person name fields
   - [x] configure django admin for person 
- [x] footnotes app
   - [x] source type model
   - [x] source model
   - [x] setup model translation for title
   - [x] write a data migration to preload the provided list of source types
   - [x] write a data migration to give content editors and content admins permissions on the new models (will be similar to other migrations in the `common` app)
   - [x] configure django admin for source type
   - [x] configure django admin for source

**Comment by rlskoeser** [comment]
@richmanrachel I'm working on implementation notes for this and have some questions:
- I don't see date in the list of fields, but presumably we'd need one to generate a citation. Can you add this and let us know what you want to to track? (publication date, maybe, but then what about unpublished work? do you need full dates, or is year enough?)
- Any thoughts on what we should call the scholarship record model/table/entity? In previous implementations, this was called bibliography. Is that fine, or is there something else that would be better? Source, citation, reference?  (I'd prefer to keep it somewhat general, since we may want to use footnotes for information beyond scholarship records)
- What name or label can we use for the Edition/Translation/Discussion choice field?  (content? mode? relationship to text?)
- For language, can we use the existing Language+Script model? 

I think we may want to split this into two stories, one for editing and managing scholarship records and one for the actual footnotes linking scholarship records to documents. (I'm worried about size/complexity if we don't split it).

**Comment by richmanrachel** [comment]
@rlskoeser - sorry for doing this on the weekend, but didn't want to lose track of this before the craziness of the week.

> I don't see date in the list of fields, but presumably we'd need one to generate a citation. Can you add this and let us know what you want to to track? (publication date, maybe, but then what about unpublished work? do you need full dates, or is year enough?)
- Good call. Yes, we definitely want the date of publication. Perhaps just years and it can be an optional fill in, since we won't know for all of the unpublished work. 
- Is there a way to link to Zotero or something, so that it's easy to export bibliographic entries? I wonder if there's a way we can harness existing library bibliography sources to input this information into the database as well?

> Any thoughts on what we should call the scholarship record model/table/entity? In previous implementations, this was called bibliography. Is that fine, or is there something else that would be better? Source, citation, reference? (I'd prefer to keep it somewhat general, since we may want to use footnotes for information beyond scholarship records)
- "Bibliography" works for me.

> What name or label can we use for the Edition/Translation/Discussion choice field? (content? mode? relationship to text?)
- I like "relationship to document" - @mrustow, does that work for you?
 
> For language, can we use the existing Language+Script model?
- The scholarship language records should be much simpler. English and Hebrew will cover nearly everything, though I do want to make it possible for Arabic and other languages to be listed. Maybe we can just use the display name list from the current model?

**Comment by rlskoeser** [comment]
@mrustow @richmanrachel should have clarified sooner, do you need more than one language for a scholarly source? We have it allowing multiple right now, but I wonder if that's necessary. Aren't scholarly works usually written in one language primarily?

**Comment by richmanrachel** [comment]
Everything works well with one hickup: content editor couldn't initially re-order authors before saving. If we didn't have to take this extra step, that would be ideal.

**Comment by rlskoeser** [comment]
The save + drag to reorder is a limitation of the library we're using (as far as I can tell). But if you're adding them initially, can you just add them in the preferred order? Does the order stick if you do that?

**Comment by richmanrachel** [comment]
@rlskoeser - sorry I lost track of this. Yes, the order sticks, so I'll close this now!
