### ISSUE TITLE
As a transcription editor, I should see an error if I try to update an annotation with out of date content so that I don't overwrite someone else's changes.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#965]
## testing notes (QA)

On the QA site:
- [x] Edit a transcription or translation. Open the same one for editing in two different windows, in order to mimic two people working on the same transcription simultaneously.
  - [ ] If someone else is available to test actually editing simultaneously, that would be an even better test!
- [x] Scroll down to ensure the transcription is fully loaded in both windows.
- [x] Edit a block of text and save it in one of the windows. The second window should _not_ reflect this change.
- [x] Start editing the block of text in the second window, and then save it. You should receive an error that someone else edited the text and you must refresh to get the updated text.
- [x] Try deleting the block of text in the second window. You should get a similar error message.
- [x] Try refreshing the page in the second window. You should now see the updates that you made in the first window, and be able to save/delete freely.

---

Documenting this because I'm putting off implementing E-tags in the new annotation server code and we don't support it in tahqiq yet anyway. We can probably work around it with workflow / assignments, but it would be good to implement in the longer term.

## dev notes
- [x] add etag logic to annotation detail view; adapt solr last modified mixin to make a more generic version that will let us make use of django's existing conditional response behavior
- [x] update tahqiq to store and update etag when requesting annotations, and include etag in the request header when making changes (post, delete)
- [x] add warning/error display to transcription editor to report problems with saving or deleting records

**Comment by kseniaryzhova** [comment]
@rlskoeser would you like to pass this off to Ben?

**Comment by rlskoeser** [comment]
@kseniaryzhova we could discuss — I'm not sure how much of a priority this needs to be; you may be able to address with workflow. You might also want to get an estimate from Ben to help decide.

**Comment by kseniaryzhova** [comment]
@blms Any thoughts? How long would this take? And how fatal would an override be? We don't often work on the same document, at least not on the transcription/translation, which is usually entered in one go, copied over from Google Docs.

**Comment by blms** [comment]
@kseniaryzhova I would probably estimate somewhere in the ballpark of 15-20 hours for this. I would consider it low priority if it's not likely to be encountered. The potential error is if someone is working on a transcription/translation and it's edited by someone else in the meantime. If they click save, the other person's edits will be overwritten. Though, the overwritten edits should still be accessible via the automated backups to [the github repo](https://github.com/princetongenizalab/pgp-text).

**Comment by kseniaryzhova** [comment]
@blms works as it should! I may coordinate testing with one of the other PMs or Marina, to check it on two different devices. But closing!
