### ISSUE TITLE
Dark mode does not support wide displays

### ISSUE THREAD

**Issue by blms** [Princeton-CDH/geniza#967]
When increasing the window size past a certain point, the background of the header breaks in dark mode:
![image](https://user-images.githubusercontent.com/7234006/180252810-491af534-bbda-4471-b839-5bd9b258e730.png)

There is also a small bug with the drop shadow:
![image](https://user-images.githubusercontent.com/7234006/180253097-1acc1a90-0423-4b60-9415-ac6d3042da82.png)

**Comment by rlskoeser** [comment]
confirmed fixed on staging site
