### ISSUE TITLE
As a desktop user, I want an angle control to rotate the deep zoom image of a fragment, so that I can control the rotation more finely than 90º increments.

### ISSUE THREAD

**Issue by blms** [Princeton-CDH/geniza#978]
## testing notes (qa — round two)

On documents with images on the QA site, try rotating images with the new rotation control
- [x] confirm it snaps to 0 degrees when you get near 0 (+/- 5 degrees), and this works as expected

## testing notes (qa)

- [x] On some documents with images, on desktop QA site, try rotating images with the new rotation control and confirm it works as expected / write any feedback

## known issues

- center of rotation seems off?

---

Extension of #937 that uses [andrejewski/angle-input](https://github.com/andrejewski/angle-input) and this [design](https://www.figma.com/file/anZFStv7zBaVWnFxr95nKt/Work-in-Progress-%2F-WIP?node-id=1863%3A62435)

**Comment by richmanrachel** [comment]
@blms - overall I really like it! The only thing that might be convenient is some sort of button to snap it back to "normal" (but I was able to reload the page to get that functionality)

**Comment by richmanrachel** [comment]
@blms and @rlskoeser - such an improvement, thank you!
