### ISSUE TITLE
As a global admin, I want display name included in the one-time import of languages and scripts, so that I can start using display names while the import is still being developed and tested.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#98]
## Testing notes
- [x] Ensure that the display names from the ontology spreadsheet appear appropriately in the LanguageScript admin interface

## dev notes
Update `import_collections` to include the new display name when creating Language+Script records.

**Comment by kmcelwee** [comment]
@richmanrachel It looks like the ontology spreadsheet maps Judaeo-Romance and Arabo-Romance to just "Romance". We have a coded rule that display names be unique. Could the display name be Judaeo-Romance and Arabo-Romance like we do for Judaeo-French, Judaeo-Italian, etc? Or is it important to have both of these displayed as simply "Romance"?

**Comment by richmanrachel** [comment]
@kmcelwee, I think I need to bring @mrustow into this. My guess is that we can go with Judeao- and Arabo-Romance, but I want a more expert opinion.

**Comment by mrustow** [comment]
Fine with me. Thanks for asking.

On Mar 15, 2021, at 10:47 AM, richmanrachel ***@***.******@***.***>> wrote:



@kmcelwee<https://github.com/kmcelwee>, I think I need to bring @mrustow<https://github.com/mrustow> into this. My guess is that we can go with Judeao- and Arabo-Romance, but I want a more expert opinion.

**Comment by kmcelwee** [comment]
We should probably hold off testing until #106 is addressed by the dev team.

**Comment by richmanrachel** [comment]
@rlskoeser - the display names appear correctly, however, as @kmcelwee flagged at some point, there is an issue with matching the documents to the correct forms of the language when "Arabic" (or Syriac or Turkish) has multiple scripts associated.

We definitely should have 2000+ "Arabic" documents, not "Garshuni" ones...

**Comment by rlskoeser** [comment]
@richmanrachel yes — I had noted that the document-language mapping was preliminary and requested a definitive mapping of languages as listed in the metadata spreadsheet to the new language+script ontology, but maybe we lost track of that. Do the display labels in the spreadsheet correspond to the names used in the metadata spreadsheet?

Since we've already closed on the document import with the preliminary language mapping in #66, let's track this work on the new issue Kevin created, #106. Correcting it shouldn't hold up accepting this issue, since it's only about importing the display names.

**Comment by richmanrachel** [comment]
@rlskoeser - okay great. Yes, the labels correspond correctly. 

The one odd thing is that Romance is the only language that doesn't have a display name. It can just be called "Romance." I updated it in the new site (and that worked!) but would you like me to add that to the spreadsheet as well?

**Comment by rlskoeser** [comment]
@richmanrachel yes, please go ahead and add it to the spreadsheet if you'd like it to have a display name. (I wondered about that!)

**Comment by richmanrachel** [comment]
Done! Closing now.
