### ISSUE TITLE
Implement the light/dark mode toggle so that users can use the site in the UI mode they prefer. 

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/geniza#989]
## testing notes (qa)

Confirm the light/dark mode toggle matches the designs at:
- [x] Mobile (<900px)
- [x] Tablet (900px-1200px)
- [x] Desktop (1200px+)

---

This issue is based on the designs handed off in issue #834

## dev notes 
[desktop](https://www.figma.com/file/anZFStv7zBaVWnFxr95nKt/Work-in-Progress-%2F-WIP?node-id=2098%3A47371)
- on desktop it's a sticky, and that it sits below the header
- on mobile it's not a sticky and it sits in the header
- the transition is: once selected it would rotate 180 degrees such that the left half of the circle is the active mode (on desktop and mobile)
- on desktop it's 70px
- on mobile it's 40px
- for larger screens it would be great if the toggle's distance with the search form and the nav above it remains the same (doesn't get pushed to the right edge too much)
- the interaction is once selected you get the light mode, and once selected again you get the dark mode
- I've fixed the mobile version and [here is my final proposal on mobile light mode](https://www.figma.com/file/anZFStv7zBaVWnFxr95nKt/Work-in-Progress-%2F-WIP?node-id=2098%3A54059) and [mobile dark mode](https://www.figma.com/file/anZFStv7zBaVWnFxr95nKt/Work-in-Progress-%2F-WIP?node-id=2098%3A53568)
- note that the toggle is placed 16px to the left of the burger menu. I think the language toggles can be placed to the left of this toggle on mobile (we'll know more soon, but I expect this proposal will work in the future as well)
- note that the toggle is horizontally centered with the burger menu

**Comment by blms** [comment]
@gissoo Two questions on this:

1. On desktop, for screens between 900px and about 1130px, what should happen with the light/dark mode toggle? Right now, it will either cover up or be hidden behind the search box/button, depending on z-index.
   <img width="898" alt="Screen Shot 2022-07-28 at 5 05 42 PM" src="https://user-images.githubusercontent.com/7234006/181775328-eca0a6a2-b930-4282-824a-0f39e301cc41.png">
   I know we're not specifically designing for screens of those sizes, but I think the controls should still all be clickable at that size.
2. Also on desktop, right now with `position: sticky` it's going to cover up some of the transcriptions, because the ITT viewer is wider than the normal page content. How should we handle this? Should we not show the toggle on this page?
   <img width="1562" alt="Screen Shot 2022-07-29 at 9 49 59 AM" src="https://user-images.githubusercontent.com/7234006/181775714-f885207d-194f-4ec2-a0be-8f1b5c2863b3.png">

**Comment by gissoo** [comment]
> @gissoo Three questions on this:
> 
>     1. On desktop, for screens between 900px and about 1130px, what should happen with the light/dark mode toggle? Right now, it will either cover up or be hidden behind the search box/button, depending on z-index.
> 

- Thank you for these, Ben. It would be great if we place it on the menu, no change in its x axes but only on its y axes so that it's vertically centered with the menu items – went back and forth a lot about this since I know this is still on desktop, but it would be better than having it take any space below the menu. 

>        <img alt="Screen Shot 2022-07-28 at 5 05 42 PM" width="898" src="https://user-images.githubusercontent.com/7234006/181775328-eca0a6a2-b930-4282-824a-0f39e301cc41.png">
>        I know we're not specifically designing for screens of those sizes, but I think the controls should still all be clickable at that size.
> 
>     2. Also on desktop, right now with `position: sticky` it's going to cover up some of the transcriptions, because the ITT viewer is wider than the normal page content. How should we handle this? Should we not show the toggle on this page?
>        <img alt="Screen Shot 2022-07-29 at 9 49 59 AM" width="1562" src="https://user-images.githubusercontent.com/7234006/181775714-f885207d-194f-4ec2-a0be-8f1b5c2863b3.png">
> 

- Would it possible to have it stop above the transcription panel? By the description really. That would be the best solution at the moment. Let me know if that's not feasible. 

>     3. How much space should be between the top of the screen and the toggle when scrolling past where it "sticks"? Here's a video of how it works now to illustrate what I mean:
> 
> 
> Screen.Recording.2022-07-29.at.9.57.54.AM.mov
>

- could it remain the same as it is by default before scrolling? (approximately 209px according to the designs? / like how you have it in the beginning) – let me know if that's feasible.

**Comment by blms** [comment]
> Thank you for these, Ben. It would be great if we place it on the menu, no change in its x axes but only on its y axes so that it's vertically centered with the menu items – went back and forth a lot about this since I know this is still on desktop, but it would be better than having it take any space below the menu.

OK, so is the decision that it should just be in the menu and not scroll down with the user while the user scrolls?

> Would it possible to have it stop above the transcription panel? By the description really. That would be the best solution at the moment. Let me know if that's not feasible.

I don't think that's feasible with CSS unfortunately. It doesn't let you define start and stop points, it only lets you say whether or not it should scroll with the user, and what "container" it lives in. I could potentially see putting a big transparent container on top of the whole page with just the light/dark toggle in it, though it's not semantically good HTML. @rlskoeser let me know if you have thoughts on how to achieve something like that.

> could it remain the same as it is by default before scrolling? (approximately 209px according to the designs? / like how you have it in the beginning) – let me know if that's feasible.

That's definitely feasible, though still runs into the two issues above colliding with other items if we keep it on screen at all when scrolling.

**Comment by gissoo** [comment]
> > Thank you for these, Ben. It would be great if we place it on the menu, no change in its x axes but only on its y axes so that it's vertically centered with the menu items – went back and forth a lot about this since I know this is still on desktop, but it would be better than having it take any space below the menu.
> 
> Thanks @gissoo—so is the decision that it should just be in the menu and not scroll down with the user while the user scrolls?
> 

- @blms correct, for screen sizes ~900-1130px (more consistent with the mobile decision on these screens due to lack of horizontal space) 

> > Would it possible to have it stop above the transcription panel? By the description really. That would be the best solution at the moment. Let me know if that's not feasible.
> 
> I don't think that's feasible with CSS unfortunately. It doesn't let you define start and stop points, it only lets you say whether or not it should scroll with the user, and what "container" it lives in. I could potentially see putting a big transparent container on top of the whole page with just the light/dark toggle in it, though it's not semantically good HTML. @rlskoeser let me know if you have thoughts on how to achieve something like that.
> 

- yes, I'll look for Rebecca's comment and think of a solution then – I'm also aware hiding it on top can easily become problematic and not an appropriate way of handling this issue, probably wouldn't want to do it. 
 
> > could it remain the same as it is by default before scrolling? (approximately 209px according to the designs? / like how you have it in the beginning) – let me know if that's feasible.
> 
> That's definitely feasible, though still runs into the two issues above colliding with other items if we keep it on screen at all when scrolling.
>

- your screen recording appears to be from a desktop size that is larger than 1130px – I'm proposing that amount of spacing and sticky property for larger screens so I don't think my answers will affect the issues above.

**Comment by rlskoeser** [comment]
I like the sticky behavior where there's enough space in the margins.

@blms could we just adjust z-indexes so that the light/dark toggle will disappear behind the image+transcription panel when you scroll down far enough?

**Comment by gissoo** [comment]
@blms thank you!! This looks great! I hope I can get to the language toggles soon so the tablet view will be better. 

- can we just hide the toggle even below the transcription panel? it looks weird. 
![Screen Shot 2022-08-03 at 4 48 52 PM](https://user-images.githubusercontent.com/44615389/182708830-847aa7b1-a6f7-4bde-a694-1334d2343e99.png)

- can we make the toggle rotate clockwise when switching from light-dark mode? :D ...it will feel a bit more comfortable that way (if possible).

**Comment by blms** [comment]
@gissoo Thanks for testing!

> can we just hide the toggle even below the transcription panel? it looks weird.

Yes! I'll just expand the permalink section to cover that whole area and raise its z-index above the toggle.

> can we make the toggle rotate clockwise when switching from light-dark mode? :D ...it will feel a bit more comfortable that way (if possible).

Sure—do you mean it should be clockwise for toggling in both directions, or just that I should switch which is CW and which is CCW?

**Comment by rlskoeser** [comment]
closing based on https://github.com/Princeton-CDH/geniza/pull/1009#issuecomment-1212549134
