### ISSUE TITLE
refine logic for identifying transcription chunks that indicate new image

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#995]
## dev notes
- [x] add the Hebrew label for page two (ע“ב) ; can test with https://geniza.princeton.edu/en/documents/3573/ 
- [x] check if label starts with ENA or Moss.; test with https://geniza.princeton.edu/en/documents/1546/

**Comment by richmanrachel** [comment]
Hebrew label for "margins" should NOT indicate new page (but noting for convenience here): שוליים

**Comment by rlskoeser** [comment]
@richmanrachel I looked at PGPID 3573 and noticed that ע“ב didn't look like it was tagged as a label. I checked the TEI to confirm, and then did a quick search and I found 66 xml documents total where this text is tagged as a line instead of a label, i.e.:
`<l n="">ע"ב</l>`

Is it appropriate to convert all of these to `<label>` tags ?

**Comment by richmanrachel** [comment]
@rlskoeser - yes, please convert those to labels! This will be a huge help :)

**Comment by richmanrachel** [comment]
@rlskoeser - it doesn't seem to be working :( https://test-geniza.cdh.princeton.edu/en/documents/3573/

**Comment by rlskoeser** [comment]
@richmanrachel oh no! I thought it worked properly when I ran it locally, once I changed the lines to labels; will have to investigate

**Comment by richmanrachel** [comment]
@rlskoeser - Bummer! But the 1546 labels with ENA, etc, are working :)

**Comment by rlskoeser** [comment]
@richmanrachel it's a smart quotes / straight quotes problem! The original version you gave me used a smart quote, and that's what I'm checking for in my code, but when I did my search and replace I must have converted to straight quotes. Which one do you want in the transcription label?

**Comment by richmanrachel** [comment]
@rlskoeser - oy vey, the smart quotes strike again! The instructions on PPA only showed how to override them on iPhones, not Macs, and so I didn't go deeper... 

You might need the transcription label to have both versions, so we don't run into this problem - is that possible?

**Comment by rlskoeser** [comment]
@richmanrachel yes, I'll revise so it works with both variants

**Comment by richmanrachel** [comment]
@rlskoeser - fixed! Thank you!
